### ISSUE TITLE
Use Active Sky route weather

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#10]
Use Active Sky route weather file if route is loaded which gives slightly different metars compared to the wx snapshot.

**Comment by albar965** [comment]
Postponed to next release. #74 gives enough information for now.

**Comment by albar965** [comment]
Moved back to 1.2 since flight simulator weather for the destination is not too useful for ASN and AS16 users.

**Comment by albar965** [comment]
Flight plan weather from Active Sky now shown in weather tab. This should give a precise indication of destination and departure weather for Active Sky users.

**Comment by PaulFWatts** [comment]
Tested on Windows
