### ISSUE TITLE
Flight Plan / Search tab problem

### ISSUE THREAD

**Issue by CgZ1177** [albar965/littlenavmap#1000]
Each time LittleNM window is minimized and reopened, Flight Plan / Search tabs alternatively selects and shows.

2.8.8 x64 Windows10

**Comment by albar965** [comment]
Can you show a screenshot? 
Is the search tab floating or docked?
What OS?

**Comment by CgZ1177** [comment]
Windows10 x64
https://user-images.githubusercontent.com/126181051/221036291-edd47077-e11b-461b-8f12-399e441d5906.mp4

**Comment by CgZ1177** [comment]
![imagen](https://user-images.githubusercontent.com/126181051/221036707-8b425803-dff8-470a-af66-003a6d848372.png)

**Comment by albar965** [comment]
Thank you a lot for the video. I can reproduce this here even on Linux. Something weird is going on there.

**Comment by albar965** [comment]
Congratulations for issue number 1000, BTW. :fireworks: :smile:

**Comment by CgZ1177** [comment]
Thanks to YOU for this amazing software!

This has been happening to me for a long time. Always thought it was something I touched but... I've been playing many times with the options and settings without finding the solution.

**Comment by CgZ1177** [comment]
Bravo!
