### ISSUE TITLE
MSFS - airways not used when creating a flight plan

### ISSUE THREAD

**Issue by ChrisXPP** [albar965/littlenavmap#1001]
Hi!

When I try to create a flight plan with (low) airways for MSFS (version 1.30.12) with stock nav data (i. e. Navblue only, option "do not use Navigraph database" is ticked) the route doesn't include any airways, just direct legs between the enroute waypoints:

![route_calculation](https://user-images.githubusercontent.com/74152765/221401729-cde255ca-9084-4336-a0fb-3438a627e24a.jpg)

![route_w_o_navigraph](https://user-images.githubusercontent.com/74152765/221401732-2e0e4e3a-9ac7-4ae1-8116-d647333818a4.jpg)

As soon as I tick the option to use the Navigraph database for airways and procedures the parsed route looks like this:

![route_w_navigraph](https://user-images.githubusercontent.com/74152765/221401876-5344a21f-e38d-4ddd-99e3-3290444f59d9.jpg)

As a crosscheck I tried the same with the XP12 database, and here in both cases the route includes airways.

**Comment by albar965** [comment]
Thanks. I have to check what's going on there. Seems that not all airways are affected.
The FSX, P3D and MSFS airway data is a bit messy and I had to create a few workarounds to get this into a usable structure.

**Comment by albar965** [comment]
Do you have the Navigraph navdata update installed in MSFS by any chance?

**Comment by ChrisXPP** [comment]
No, just stock nav data (Navblue) which was updated last week on 23rd February.

**Comment by albar965** [comment]
Ok. Thanks.

**Comment by albar965** [comment]
Fixed with albar965/atools@d29060e020c24a9acdc215fc51ae0c458caa74b7
