### ISSUE TITLE
Wind arrow is upside down

### ISSUE THREAD

**Issue by jpr5551** [albar965/littlenavmap#1002]
![Wind arrow issue](https://user-images.githubusercontent.com/126686000/222157215-a6a0ae66-886d-4adf-b450-727014bc1ff1.jpg)

**Comment by jpr5551** [comment]
Ohh!! I'm sorry.

**Comment by albar965** [comment]
No problem. It can be confusing at times. :upside_down_face:  For arrows the general consensus is to point into the direction the wind is blowing. For the wind barbs there are even official rules how they have to point (from wind).

**Comment by jpr5551** [comment]
Yes, I read about it.
Thanks for yout time.
Excuse me again.
