### ISSUE TITLE
scenery library loading with errors

### ISSUE THREAD

**Issue by at197855** [albar965/littlenavmap#1005]
Please let me know how to fix this issue. This is the error message I receive when loading the scenery database into little nav map:
Found 5 notes in 5 scenery entries when loading the scenery database

Some files or scenery directories could not be read properly due to encrypted airport data.

Scenery Title: OneStore
Encrypted add-on "asobo-airport-eham-amsterdam" found. Add-on might not show up correctly.

Scenery Title: OneStore
Encrypted add-on "asobo-airport-fact-cape-town" found. Add-on might not show up correctly.

Scenery Title: OneStore
Encrypted add-on "asobo-airport-heca-cairo" found. Add-on might not show up correctly.

Scenery Title: OneStore
Encrypted add-on "asobo-airport-kord-chicago-ohare" found. Add-on might not show up correctly.

Scenery Title: OneStore
Encrypted add-on "asobo-airport-lemd-adolfo-suarez" found. Add-on might not show up correctly.

Latest version of littlenavmap 3/4/2023. windows 11. MSFS, Thank you!

**Comment by albar965** [comment]
You cannot fix this. 
This is not an error but, as the header in the message indicates, only a hint that payware airports from MSFS might look different in LNM due to digital restriction management (DRM).

See here: https://albar965.github.io/littlenavmap-faq.html#no-airport-msfs

**Comment by at197855** [comment]
Thank you for your response. While I understand your reply I want to let
you know that these are not add-on airports. They came with msfs deluxe
edition (40th anniversary). Please let me know if there is anything else I
can do or if you have any solutions now knowing they are not add-on
airports. Thank you again. I appreciate all of the work you are putting
into littlenavmap and as a new user I'm learning a lot and enjoying all of
it's wonderful tools.

**Comment by albar965** [comment]
Nevertheless they are encrypted. Sorry, but there is no solution. There is no legal way to break the DRM and read these files.

The limitations are not too big. You can still use the stock airport shown in Little Navmap for flight planning but keep in mind that parking, taxiways or aprons might probably look different in the simulator.

You can manually place a userpoint of type`Addon` on top of the airports if you'd like to mark them. Erase all texts from the userpoint to avoid overlap with the airport.
