### ISSUE TITLE
Initial climb on SIDs

### ISSUE THREAD

**Issue by jessy0506** [albar965/littlenavmap#1007]
Add the initial climb altitudes to the SIDs information page.

**Comment by albar965** [comment]
Sorry, I don't understand. Can you explain better. Maybe a screenshot with explanations?

**Comment by jessy0506** [comment]
Sure.

Airports with a SID often have a pre-determined altitude that pilots can climb to after take-off, the so called "initial altitude" or "initial climb altitude" or "top altitude". See the screenshot of the KUDAD2N SID out of EHAM airport. You will see above the routing it says "initial climb FL060"
![fjgdfisjg93](https://user-images.githubusercontent.com/120395294/223737785-6cb50929-3582-481a-97af-ffba1620ebbd.PNG)

I thought this could be useful information to contribute to the SIDs page on littlenavmap!

**Comment by albar965** [comment]
Thank you for the clarification.

Unfortunately the data is not available in the Navigraph, X-Plane or MSFS databases. Sorry.
