### ISSUE TITLE
ILS Course Width in Navigraph database

### ISSUE THREAD

**Issue by srcejon** [albar965/littlenavmap#1011]
It appears that the Navigraph database (2302 AIRAC) for LittleNavMap has a loc_width field (for ILS Course Width), but no data in it, and so the ILS course width in LittleNavMap is always just the default of 4 degrees.

I thought this was a Navigraph issue, so reported the problem [here](here: https://forum.navigraph.com/t/ils-course-width-in-little-navmap/11530) - however, the reply seems to suggest that the reader to convert Navigraph's DFD to the LittleNavMap database was written by you. 

If so, would it be possible to update the reader to include loc_width? It should be available in the DFD format in tbl_localizers_glideslopes.llz_width.

Thanks.

**Comment by albar965** [comment]
Change is implemented but I'll send the compiler later to Navigraph since it needs more testing regarding other changes.

**Comment by srcejon** [comment]
Thanks!
