### ISSUE TITLE
Unit measures on search panel with italian translation

### ISSUE THREAD

**Issue by Albigheros** [albar965/littlenavmap#1012]
Thanks for your amazing work!
Sorry for my english, i'm trying to explain at my best,
I found three little errors in the italian translation on the search panel:

1. in min runway lenght the um shown is %sists% (should be ft)
2. in max runway lenght the um shown is NM (should be ft)
3. in min distance from center of search the um shown is ft (should be NM)

They are only visualization problems, the results of search are always correct!

![Screenshot 2023-03-19 110333](https://user-images.githubusercontent.com/128284355/226168477-9c92fe70-3f45-41ff-b2c6-1416b0baeda4.png)

I run Version 2.8.9 64-bit (revisione e925159c) on Windows 11 64 bit
My flight simulator is MSFS 1.30.12.0

**Comment by albar965** [comment]
Thank for the report and the screenshot. I can fix this right away for 2.8.10.
