### ISSUE TITLE
Force departure or destination airport in Random Flight

### ISSUE THREAD

**Issue by Albigheros** [albar965/littlenavmap#1013]
For the Random Flight function could be interesting add the possibility to force the Departure or Destination Airport.

I run Version 2.8.9 64-bit (revisione https://github.com/albar965/littlenavmap/commit/e925159c0601685e64c713a2dfbbba2c724ec31c) on Windows 11 64 bit
My flight simulator is MSFS 1.30.12.0

**Comment by albar965** [comment]
Makes sense. Will keep this in mind for a future version.

**Comment by albar965** [comment]
![image](https://github.com/albar965/littlenavmap/assets/15254956/6ae1daac-43d6-4e0c-bace-a5f206163a28)
![image](https://github.com/albar965/littlenavmap/assets/15254956/a4a2e289-73bc-4549-beff-0a8fca91f9b1)
