### ISSUE TITLE
Add Linux installation requirements to readme

### ISSUE THREAD

**Issue by RedFraction** [albar965/littlenavmap#1014]
Add Linux installation requirements to readme. Like for Ubuntu it's `sudo apt install qt5dxcb-plugin`

**Comment by albar965** [comment]
The plugin `libqxcb.so` comes with LNM in the archive folder `lib/platforms` and is loaded from there. 
`qt5dxcb-plugin` is not even installed on my development platform (Kubuntu).

Do you use the Deepin Desktop Environment by any chance?

Further candidates are more `sudo apt install libxcb-xinerama0 libxcb-icccm4` too.

**Comment by albar965** [comment]
Added to [FAQ - Little Navmap does not start on Linux](https://albar965.github.io/littlenavmap-faq.html#linux-start).
This is referenced from the readme and user manual for issues.
