### ISSUE TITLE
navdata.sqlite is missing runways that appear in Navigraph and MSFS

### ISSUE THREAD

**Issue by cogwheel** [albar965/littlenavmap#1019]
* OS: `Windows 11 64 bit`
* Flight simulator: `MSFS 1.31.22`
* AIRAC cycle and navdata source: `Navigraph Cycle 2303 rev.1`

NZFX (antarctica) has runway 33/15. I can make flight plans in simbrief and in the G5000 in-game, the runway appears in the world, and has multiple arrival/approach procedures.

When I run navdatareader, the resulting navdata.sqlite has NZFX airport, but it does not contain any runways. The num_runways is 0, and the runways table doesn't have any entries for NZFX.

This is reflected in Little Navmap. With MSFS scenery and navigraph procedures, there is no runway displayed. If I switch to Navigraph for scenery, then the runway appears.

**Comment by albar965** [comment]
NZFX is only contained in the Navigraph database and not in MSFS stock scenery (X-Plane has it). Navdatareader reads only what is in the MSFS scenery library and therefore cannot find the airport. 

You use an airport add-on if you can see it in the MSFS scenery. Maybe an error in the add-on if runways are missing. Do you have a link to the used add-ons?

LNM ignores the Navigraph updates in MSFS since there is also the Navigraph navdatabase update for LNM. Another reason is the nightmarish complexity in the scenery library to update navdata. 

Alex

**Comment by cogwheel** [comment]
> NZFX is only contained in the Navigraph database and not in MSFS stock scenery (X-Plane has it). Navdatareader reads only what is in the MSFS scenery library and therefore cannot find the airport.

But it does find the airport. It just doesn't assign any runways.

```sqlite> select * from airport where ident = "NZFX";
airport_id,file_id,ident,icao,iata,faa,local,name,city,state,country,region,flatten,type,fuel_flags,has_avgas,has_jetfuel,has_tower_object,tower_frequency,atis_frequency,awos_frequency,asos_frequency,unicom_frequency,is_closed,is_military,is_addon,num_com,num_parking_gate,num_parking_ga_ramp,num_parking_cargo,num_parking_mil_cargo,num_parking_mil_combat,num_approach,num_runway_hard,num_runway_soft,num_runway_water,num_runway_light,num_runway_end_closed,num_runway_end_vasi,num_runway_end_als,num_runway_end_ils,num_apron,num_taxi_path,num_helipad,num_jetway,num_starts,longest_runway_length,longest_runway_width,longest_runway_heading,longest_runway_surface,num_runways,largest_parking_ramp,largest_parking_gate,rating,is_3d,scenery_local_path,bgl_filename,left_lonx,top_laty,right_lonx,bottom_laty,mag_var,tower_altitude,tower_lonx,tower_laty,transition_altitude,transition_level,altitude,lonx,laty
119817,5086,NZFX,,,,,,,,,,,,0,0,0,0,126200,,,,122800,0,0,0,6,0,0,0,0,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,UNKNOWN,0,,,0,0,"D:\Games\Microsoft Flight Simulator\Packages\Community\navigraph-navdata",NAX92590.bgl,166.749572753906,-77.9569396972656,166.749572753906,-77.9569396972656,142.181976318359,,,,,,38,166.749572753906,-77.9569396972656
```

I don't have any scenery addons, just the navigraph data. When I fly to the location, MSFS shows a runway even though it's not in the base scenery:

<img width="636" alt="Screenshot 2023-04-15 202227" src="https://user-images.githubusercontent.com/2105215/232504598-9f0c6a67-60d7-4a9d-aa72-9d4555be0418.png">

**Comment by albar965** [comment]
I see. Navigraph adds the airport somehow and LNM "thinks" it is a procedure update.
Need to debug into this.

**Comment by albar965** [comment]
Fixed. Now reading all airports from update. These are not marked as add-on.
