### ISSUE TITLE
Current perfomance not work (2.8.10)

### ISSUE THREAD

**Issue by fhprietor** [albar965/littlenavmap#1024]
The current perfomance only show the total and taxi fuel consumed. But the Average perfomance Climb/Cruise/Descent always in ZERO.
<img width="139" alt="Captura de pantalla 2023-05-02 230823" src="https://user-images.githubusercontent.com/52725986/235831312-cf053a85-9208-4356-b471-aacff95f478f.png">

**Comment by albar965** [comment]
What aircraft is this?

Most likely this: [FAQ - I get fuel flow indications that do not match the values in Little Navmap](https://albar965.github.io/littlenavmap-faq.html#wrong-fuel-indication).

**Comment by albar965** [comment]
And do you see any speed and fuel flow numbers in the aircraft progress tab?

**Comment by albar965** [comment]
No feedback. Closing.
