### ISSUE TITLE
Feature Request : logbook query to shows hours by aircraft

### ISSUE THREAD

**Issue by joeaudette** [albar965/littlenavmap#1026]
I would like to see a new logbook query to show me how many hours I have in each aircraft.
I was able to write a query for it using external sqlite gui, but wish it could be built in.

SELECT
aircraft_name,
aircraft_type,
SUM(hours_flown) as total_hours
FROM
(
select
logbook_id,
aircraft_name,
aircraft_type,
CAST ((julianday(destination_time) - julianday(departure_time)) * 24 AS REAL) AS hours_flown
from logbook
WHERE 
departure_time IS NOT NULL
AND destination_time IS NOT NULL
)
GROUP BY
aircraft_name,
aircraft_type
ORDER BY total_hours DESC
;

**Comment by albar965** [comment]
Makes sense since the other queries cannot be sorted by traveling time.
Thanks a lot for the query. :+1:

**Comment by albar965** [comment]
Fixed (and much more) with 5dcb3ba3b69ff76b8c78a64e3b2a3eacafac8358

**Comment by joeaudette** [comment]
I wish I had thought of it sooner, but it is trivial to also include count of flights per aircraft in the same query.

SELECT aircraft_name, aircraft_type, SUM(hours_flown) as total_hours, COUNT(*) AS total_flights
FROM (select logbook_id, aircraft_name, aircraft_type,
CAST ((julianday(destination_time) - julianday(departure_time)) * 24 AS REAL) AS hours_flown
from logbook
WHERE departure_time IS NOT NULL AND destination_time IS NOT NULL)
GROUP BY
aircraft_name,
aircraft_type
ORDER BY total_hours DESC
;

**Comment by albar965** [comment]
No problem. Still fixing small bugs here and there anyway. :slightly_smiling_face:

**Comment by joeaudette** [comment]
I promise, this is the last one, but this occurred to me tonight and seems very nice to have, last_flight and first_flight per aircraft.
Note it requires adding departure_time to the sub query in main from clause.


SELECT aircraft_name, aircraft_type, SUM(hours_flown) as total_hours, COUNT(*) AS total_flights, MAX(departure_time) AS last_flight, MIN(departure_time) AS first_flight
FROM (select logbook_id, aircraft_name, aircraft_type, departure_time,
CAST ((julianday(destination_time) - julianday(departure_time)) * 24 AS REAL) AS hours_flown
from logbook
WHERE departure_time IS NOT NULL AND destination_time IS NOT NULL)
GROUP BY
aircraft_name,
aircraft_type
ORDER BY total_hours DESC
;

**Comment by joeaudette** [comment]
maybe avg_flt_hours is also interesting..

SELECT aircraft_name, aircraft_type, SUM(hours_flown) as total_hours, COUNT(*) AS total_flights, AVG(hours_flown) as avg_flt_hours, MAX(departure_time) AS last_flight, MIN(departure_time) AS first_flight
FROM (select logbook_id, aircraft_name, aircraft_type, departure_time,
CAST ((julianday(destination_time) - julianday(departure_time)) * 24 AS REAL) AS hours_flown
from logbook
WHERE departure_time IS NOT NULL AND destination_time IS NOT NULL)
GROUP BY
aircraft_name,
aircraft_type
ORDER BY total_hours DESC
;

**Comment by joeaudette** [comment]
total_distance and avg_distance are also easy to include

SELECT aircraft_name, aircraft_type, 
COUNT(*) AS total_flights, 
SUM(hours_flown) as total_hours, 
AVG(hours_flown) as avg_hours,
SUM(distance_flown) AS total_distance, 
AVG(distance_flown) AS avg_distance, 
MAX(departure_time) AS last_flight, 
MIN(departure_time) AS first_flight
FROM (select logbook_id, aircraft_name, aircraft_type, departure_time, ifnull(distance_flown,0) AS distance_flown,
CAST ((julianday(destination_time) - julianday(departure_time)) * 24 AS REAL) AS hours_flown
from logbook
WHERE departure_time IS NOT NULL AND destination_time IS NOT NULL)
GROUP BY
aircraft_name,
aircraft_type
ORDER BY total_hours DESC
;

**Comment by albar965** [comment]
Good I made the stats code more flexible. :slightly_smiling_face: 
I can add these too. No problem. Still reorganizing code and fixing bugs.
