### ISSUE TITLE
[2.8.11] give possibility to define flight rules when creating a flight plan

### ISSUE THREAD

**Issue by ChrisXPP** [albar965/littlenavmap#1035]
Hi @albar965 ,

whenever I create a flight plan from scratch via the route description window the flight rules (and the cruise altitude) switch to VFR. Of course it's possible to change this setting afterwards, but still a bit "inconvenient"... ;-)
May I suggest to include a drop-down menu (or something like that) in the route description window where you can define the preferred flight rules (IFR or VFR)... ? :-)

Using the latest version 2.8.11

**Comment by albar965** [comment]
Actually I removed this button versions ago since I found two settings confusing. This change happened with feaeca1f9efd4c2e8a7a500b6f761ad365004eb4 . I'll see if it makes sense to put it back for `Create Plan...`.

**Comment by albar965** [comment]
Done with 33a61ca0939e147a8f57a7e5879da3726a4dd9ba
