### ISSUE TITLE
Repetitively getting "Cannot access weather files." in spite of mentioning path in Weather file location

### ISSUE THREAD

**Issue by devleaks** [albar965/littlenavmap#1036]
Mac where X-Plane 12 runs:
Mac Mini M1 (2020), MacOS (Ventura) 13.4
X-Plane 12.05.r1, one set of old Custom Data (Aerosoft, 08-2022)
Little Xpconnect 1.0.38
(everything used under Rosetta)
Little Navconnect 2.8.6

Mac where I use Little Navmap 2.8.11:
iMac (27-inch, Late 2013), MacOS (Catalina) 10.15.7
Little Navmap 2.8.11

I use little navmap on a remote computer. When I start it, I always get "Cannot access weather files." Even after selecting the proper Real weather folder in X-Plane 12 (full of recently acquired files) in the Weather file preferences, I get this error message.
I understand that when not using Real weather, there is no file in the folder, and I would then expect LNM to tell that it "Cannot access weather files.".
Many thanks in advance for your help.

[lnm-log.zip](https://github.com/albar965/littlenavmap/files/11798659/lnm-log.zip)

**Comment by albar965** [comment]
Thanks for the detailed information. I'll check what's going on there.

**Comment by albar965** [comment]
Hopefully fixed with b196c8f81c71aff6c86ef2c89c7a290a75a3983a

**Comment by albar965** [comment]
https://albar965.github.io/release/2023/07/07/littlenavmap-2.8.12.rc1-released.html

**Comment by albar965** [comment]
> I confirm, tested and fixed.

Thanks a lot for the confirmation!
