### ISSUE TITLE
New Info for: Custom waypoints don't load in MSFS 2020 #922

### ISSUE THREAD

**Issue by eaides** [albar965/littlenavmap#1038]
The problem of the "north pole" for user points exported from little nav map to msfs2020 seam to occur only when you have navigraph DB installed. The owner of navigraph is investigating the problem

Meanwhile, the issue is generated by the lack of the following nodes in the XML (the pln) generated:

Inside any <ATCWaypoint id="WP1"> (WP2, WP3, etc) a subnode <ICAO> is loosen.

Actual pln section (produce the issue)

`<ATCWaypoint id="WP1">
            <ATCWaypointType>User</ATCWaypointType>
            <WorldPosition>S34° 10' 16.88",W58° 58' 47.68",+003500.00</WorldPosition>
        </ATCWaypoint>`
        
The node with the subnode, that loads OK into the simulator
`<ATCWaypoint id="WP1">
            <ATCWaypointType>User</ATCWaypointType>
            <WorldPosition>S34° 10' 16.88",W58° 58' 47.68",+003500.00</WorldPosition>
        <ICAO>
            <ICAOIdent>WP1</ICAOIdent>
          </ICAO>
     </ATCWaypoint>
`

Can be added for all nodes, the "required" subnodes

**Comment by albar965** [comment]
Terrific. :+1:  
I'd be more than happy if this simple change really fixes it.
Thank you a lot for the information!
I'll add this to the next 2.8.12 release candidate.

**Comment by eaides** [comment]
thanks a lot, expected to check it when ready.

**Comment by albar965** [comment]
Confirmed working here with Navigraph MSFS navdata update.

Strange thing is that even MSFS does not add the ICAO element when saving. :confused: :shrug:

**Comment by albar965** [comment]
https://albar965.github.io/release/2023/07/07/littlenavmap-2.8.12.rc1-released.html
