### ISSUE TITLE
Airport in wrong location

### ISSUE THREAD

**Issue by Pylotjon** [albar965/littlenavmap#1043]
LIQY Airport (Aliscarlino Italy) is shown in the wrong location on the map. It should be at:

Location	42.911700° 10.816400°
Runways	1
Magnetic Variation	3.368° E

Instead, its way at the south end of Italy at:
40 25'56.19"
17 56'  53.23"

I checked both Navigraph and Skyvector to confirm. The airport location you have it at now does not actually have an airport located there...
LNM Location:
![image](https://github.com/albar965/littlenavmap/assets/139922237/f01f34b3-b357-4686-aaca-424a91523d62)

It should be here:

![image](https://github.com/albar965/littlenavmap/assets/139922237/081e345a-328d-4f92-8f8b-9ca13c05075d)

Hope this helps! If you need additional info let me know!

**Comment by albar965** [comment]
This is most likely a MSFS issue. LNM cannot make up coordinates. I see the airport in the wrong location too and its only a part of `.../fs-base-genericairports/scenery/0602/APX52170.bgl` looking at information -> airport -> overview in section Data Source. So, it's not overridden by an add-on.

What do you see in data source?
![grafik](https://github.com/albar965/littlenavmap/assets/15254956/5fabe762-8006-48e1-95f1-d90213e5d8ff)

The OpenStreetMap shows an airport at this place but no ID, though:
![grafik](https://github.com/albar965/littlenavmap/assets/15254956/3d6372fd-7f28-4197-938f-fbd8c5bc39e3)

**Comment by Pylotjon** [comment]
ah, ok-I didnt check MSFS- I'll see if its there and if so leave on the MSFS forums- thanks!

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by Pylotjon** [comment]
Just checked and yes, its incorrect in MSFS...

------- Original Message -------

**Comment by albar965** [comment]
Thanks for the confirmation. I suppose I can close this now.

**Comment by Pylotjon** [comment]
Yessir! thanks!

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
