### ISSUE TITLE
QUESTION: Is it possible to connect LittleNavMap on linux with MSFS on Windows ? 

### ISSUE THREAD

**Issue by gsegit** [albar965/littlenavmap#1045]
Hi there ;D
At first, your programm ist very awesome ;D Very big thanks for your work ;D

I have a small question, I have Littlenavmap under Linux Mint on a small minipc. And MSFS under Windows on a large PC. Now my question is, can I start the LNM under linux and connect it to the MSFS under Windows ?  

Tschöö
Gerriet | Greetings from Germany ;D

**Comment by albar965** [comment]
Hi Gerriet,

sure. Run the 64-bit Little Navconnect for Windows on the MSFS computer and connect to Navconnect from Linux.
You can mix all OS/bits when connecting LNM to Navconnect.

See here about details for remote connections: https://www.littlenavmap.org/manuals/littlenavmap/release/latest/en/NETWORK.html 

Grüße aus dem Taunus :slightly_smiling_face: 

Alex

**Comment by albar965** [comment]
Answered.
