### ISSUE TITLE
Navigraph Airspace - Option to Hide Multiple Code Z - 

### ISSUE THREAD

**Issue by corkmaster** [albar965/littlenavmap#1047]
Navigraph airspace files come with areas marked with **Multiple code: Z** 

![image](https://github.com/albar965/littlenavmap/assets/119861228/100b6476-5288-4a6d-82e3-7d6230874e6b)

The problem is the airspace boundary/vertical limits it represents aren't "real". The request is for an option to filter these out somehow. 

For example, in the image the Z code shape just shows the _entire_ London TMA and says 2,500ft-19,500ft. In effect it is the entire horizontal extent, and the maximum vertical extent of the TMA. In reality the airspace steps up. When you hover or click to investigate the real height (in the example 4,500ft for TMA 11) you always get the additional spurious Code Z shown too. 

**Note**: I haven't checked if these exist globally, or if in all cases the Z code is a dummy airspace feature everywhere, but I'd bet it was based on how it behaves in the UK. I also found some discussion here which relates to these Z airspace designators in US Class B which also seems to confirm they are used for some other purpose than showing airspace boundaries on a map. https://www.avsim.com/forums/topic/632850-information-airspaces/

**Comment by albar965** [comment]
Thank you for the information. This looks like a case where the airspaces can be filtered out per default.
The `Z` is probably an ARINC specialty.
