### ISSUE TITLE
Export ICAO raw format

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#1049]
I've noticed there is a lack of ICAO raw format in import/export tools.
This format is using widely in the real world - for example on Eurocontrol fpl checking tools.
It could be great if would be possible import/export flight plans in this format.

Exactly this is ATS message format, example flight plan from EGLL to CYQX:

```
---
FPL-ACA101-IS
–B773/H-CHOV/C
–EGLL1400
–N0450F310 L9 UL9 STU285036/M082F310 UL9 LIMRI 52N020W 52N030W 50N040W 49N050W
–CYQX0455 CYYR
–EET/EISN0026 EGGX0111 020W0136 CYQX0228 040W0330 050W0415 SEL/FJEL)
---
```

**Comment by PaulWalkerUK** [comment]
Duplicate of #824?

**Comment by albar965** [comment]
> Duplicate of #824?

Right. Thanks!
