### ISSUE TITLE
Airport missing runways for kbwi

### ISSUE THREAD

**Issue by johnfrypa** [albar965/littlenavmap#1050]
![lnvkbwi](https://github.com/albar965/littlenavmap/assets/8397668/f4d26206-0b92-44a9-8213-7bb337d51866)

**Comment by albar965** [comment]
What simulator?
What LNM version?
Add-on or stock airport?
What runways are missing?

**Comment by johnfrypa** [comment]
Runway 15R abd 33LX plane 12LNM version 2.8.12Default airport

Sent from Yahoo Mail on Android 
 
  On Wed, Aug 23, 2023 at 10:12 AM, Alexander ***@***.***> wrote:   


What simulator?
What LNM version?
Add-on or stock airport?
What runways are missing?

**Comment by albar965** [comment]
Thanks for the information but I don't see the issue. All runways from `.../X-Plane 12/Global Scenery/Global Airports/Earth nav data/apt.dat` are shown:
![image](https://github.com/albar965/littlenavmap/assets/15254956/b275083a-9e2e-4f30-8034-7cf1d4f27a7f)

Check the data source section in the airport overview tab if there is an add-on overriding.

**Comment by albar965** [comment]
I suspect you look at the demo navdata from Navigraph which is cycle 1801.
First check if the scenery library was loaded from XP12. You see a red status bar message if not.

A screenshot of the full LNM window including title bar and status bar might help.

**Comment by albar965** [comment]
Even the 1801 cycle has all runways. Looks like an add-on issue to me. Screenshot?

Here is more information about wrong scenery: https://albar965.github.io/littlenavmap-faq.html#airport-wrong

**Comment by johnfrypa** [comment]
On Thursday, August 24, 2023 at 10:55:28 AM EDT, Alexander Barthel ***@***.***> wrote:  
 
 


Even the 1801 cycle has all runways. Looks like an add-on issue to me. Screenshot?

Here is more information about wrong scenery: https://albar965.github.io/littlenavmap-faq.html#airport-wrong

**Comment by albar965** [comment]
I don't see a screenshot. Please log into Github and answer on the web interface instead of the emails.

**Comment by johnfrypa** [comment]
![LNM](https://github.com/albar965/littlenavmap/assets/8397668/20ec744f-27c4-4f56-98c9-6458005c3a8c)

Screen shor

**Comment by albar965** [comment]
Thanks for the screenshot. This clears it a bit up but you still did not tell me if this is an add-on airport and which one.

To me this looks like an add-on airport (ident is italic underlined in flight plan table) which obviously contains an error. I'd rather contact the add-on author or fix this myself in WED. Clearly not a LNM issue.

**Comment by johnfrypa** [comment]
I have no airport add-on for X PLANE 12

**Comment by johnfrypa** [comment]
![KBWIXP12](https://github.com/albar965/littlenavmap/assets/8397668/efd70199-1d92-4fc0-b7a5-64253373b0bf)
This is a search of KWBI

**Comment by albar965** [comment]
CIFP files contain procedures but not runways.
This is not the stock airport. In plain XP12 it is `Bwi Marshall (KBWI)`.

Please post a screenshot or content of `Data Source` section in tab `Airport` -> `Overview`. 
Like this:
![image](https://github.com/albar965/littlenavmap/assets/15254956/4c09249b-9f8e-4fbf-bdd6-afba06a0a355)

**Comment by johnfrypa** [comment]
![KBWI OVERVIEW](https://github.com/albar965/littlenavmap/assets/8397668/81586609-c2cf-4666-ba8a-764e2d17badc)

**Comment by johnfrypa** [comment]
Sorry I was a little confused flying both simulators. Guess this is MSFX

**Comment by albar965** [comment]
Switch to the right sim for X-Plane 12 in the menu `Scenery Library`.

**Comment by albar965** [comment]
Yep. The runway is missing in MSFS but not in X-Plane. :upside_down_face:

**Comment by albar965** [comment]
That's why I asked for a screenshot including window title bar. This includes the selected simulator: [6.14. Window Title](https://www.littlenavmap.org/manuals/littlenavmap/release/latest/en/INTRO.html#window-title)😉

**Comment by johnfrypa** [comment]
👍

Sent from Yahoo Mail on Android 
 
  On Thu, Aug 24, 2023 at 5:19 PM, Alexander ***@***.***> wrote:   


That's why I asked for a screenshot including window title bar. This includes the selected simulator: 6.14. Window Title😉

**Comment by albar965** [comment]
I'm closing since it seems to be fixed. Happy flying! :slightly_smiling_face:

**Comment by johnfrypa** [comment]
Ok Thanks for all you do

Sent from Yahoo Mail on Android 
 
  On Fri, Aug 25, 2023 at 5:38 AM, Alexander ***@***.***> wrote:   


I'm closing since it seems to be fixed. Happy flying! 🙂
