### ISSUE TITLE
The map load very slowly by open the program

### ISSUE THREAD

**Issue by gsegit** [albar965/littlenavmap#1051]
Hi there ;D
When I open the program, the map is loaded very slowly. The simulator is not connected, I have also switched off some things to test whether it then loads faster, but this is not the case. Web server is off, Navi files are local. 
All under Windows 10 and current version. 
At the moment I don't know what the problem could be.

Greetings
Gerriet

**Comment by albar965** [comment]
Hi Gerriet,

some things to try:

1. Put the LNM installation folder and `C:\Users\YOURUSERNAME\AppData\Roaming\ABarthel` on the anti-virus exclusion list.
2. Disable distance search in all search tabs if enabled there or disable `Restore search parameters` in options on page `Startup and Updates`.
3. Disable unneeded weather downloads in menu `Weather` and in options on tab `Weather`.
4. Disable `Download oceanic tracks` in menu `Flight Plan`.
5. Put map details back to default in menu `Map` -> `Default map detail`.

You can send me the log file if all else fails: https://albar965.github.io/contact.html 

Alex

**Comment by gsegit** [comment]
Good morning ;D
you will lought me out, but I have no anti-virus, the another things would I make try and I hope the fixed it ;D

Have a nice Day ;D

**Comment by albar965** [comment]
> Good morning ;D you will lought me out, but I have no anti-virus, the another things would I make try and I hope the fixed it ;D Edit: I have found the problem, that was the maptheme, there was on opentoomap. Have now set on openstreetmap and very faster ;D

I neither run anti-virus since I'm developing on Linux :upside_down_face:. On the Windows flying computer I use MS Defender but all sim and LNM folders are excluded from scanning. And this *does* speed up things.

The OTM is a nice map theme but the server is very slow at times. 

Happy flying!

Alex
