### ISSUE TITLE
GPX export does not have correct altitudes in rtept - ele Element

### ISSUE THREAD

**Issue by bm98** [albar965/littlenavmap#1053]
Issue found with LNM V 2.8.12 64-bit rev af004428  Win10 64bit 

When exporting a GPX (Garmin Exchange Format) with MultiExport
The Route <rte> - <rtept> - <ele> Items do not carry the correct altitude except for the Airports
all others seem to have the Cruise Alt 

the Track seems to report <ele> with a profile but I cannot derive the unit from the numbers...

See attached files:
 LNMPlan
 GPX  export
 HTML export which is correct as far as I can see

[IFR Galeao-Antonio C Jobim Intl (SBGL) to Congonhas Intl (SBSP).zip](https://github.com/albar965/littlenavmap/files/12694139/IFR.Galeao-Antonio.C.Jobim.Intl.SBGL.to.Congonhas.Intl.SBSP.zip)

It would be helpful to have the correct altitudes reported in the GPX export 
Thank you :)

**Comment by albar965** [comment]
Thank you for the files and the description! :+1: 

I can confirm this. The track has the correct flown altitude (elements "ele") but the route does not. The units are always meters according to [Wikipedia - GPS Exchange Format - Units](https://en.wikipedia.org/wiki/GPS_Exchange_Format#Units).

I'll change the route to contain the altitudes from the calculated profile but will keep the actually flown altitude in the track. Hope this makes sense.

Alex

**Comment by bm98** [comment]
Thank you - I am looking mostly for the route (used as Plan) 
leaving the track as flown profile makes perfectly sense..
and thanks for confirming meters.
I don't remember having flown this route with LNM so that examples track with dates of 1970 may be artificial?
Trk seems not related to the route in the example (lat, lons don't match at all)
But I might have messed up here - don't know.

**Comment by albar965** [comment]
> I don't remember having flown this route with LNM so that examples track with dates of 1970 may be artificial?

The time is simulator UTC. Means it is whatever time you've set in the sim. Exporting here gives me the correct sim time and not epoch.

> Trk seems not related to the route in the example (lat, lons don't match at all)

You have to clear the track before flying (`File` -> `Reset all for new flight`). Otherwise you'll get a track from the previous flight(s).

A logbook entry also gets a track assigned which starts at takeoff and ends at touchdown. You can save this from the logbook table context menu `Files` ... This one does not contain previous flights.

Alex
