### ISSUE TITLE
Text "Arrive via" in Flight Plan has an unnecessary space to the left

### ISSUE THREAD

**Issue by hildebrandofc** [albar965/littlenavmap#1054]
It is a very minor bug, but noticeable, anyway.

When I print a flight plan or export it to HTML, I can see a space before the line that says " Arrive via .....". This space creates a misalignment with the rest of the paragraph.

![Misalignment in the --Arrive via-- text](https://github.com/albar965/littlenavmap/assets/113305258/482db7e6-1477-440d-b85b-992c63496231)

**Comment by albar965** [comment]
Thanks. Will fix. Let me know if you find more typos.

**Comment by albar965** [comment]
Fixed plus a bit more.
