### ISSUE TITLE
Errorneous filtering of airports that have procedures available 

### ISSUE THREAD

**Issue by ChrisXPP** [albar965/littlenavmap#1055]
Hi @albar965 ,

I recently found an issue with filtering airports that have procedures available (according to latest AIRAC cycle 2309):

Showing airports with & without available procdures:
![no_procedure_selected](https://github.com/albar965/littlenavmap/assets/74152765/a6558b5f-760a-44c4-b882-3c81f327d1ed)

Filter "no procedure" de-activated:
![procedure_selected](https://github.com/albar965/littlenavmap/assets/74152765/5f96715d-d207-4e58-8e3d-71961e3ff359)

Just as example one airport that was filtered out despite having procedures available (EKSN):
![example_EKSN](https://github.com/albar965/littlenavmap/assets/74152765/0670410d-423a-4952-bb68-9b979a3c91aa)

After a quick (and random) lookup I found many more of such examples: EDFQ, EDGS, EDME...

I currently use MSFS2020 on Win 11 (64 bit), stock scenery & Navigraph datasets.

PS: Could this be related to the Navigraph datasets (I mean the filter applies to "stock" navdata only, and I know e. g. EKSN has no procedures in the stock sim, as well)?

Many thanks for your help in advance!

**Comment by albar965** [comment]
Thank you for the detailed report, Christoph. :+1: 
I see this too here.
I'm going to fix this for the map airport filter. 

The airport search has a similar problem but I still have no idea how to fix this.

Alex
