### ISSUE TITLE
Stadia Stamen Terrain isssue

### ISSUE THREAD

**Issue by Marci353** [albar965/littlenavmap#1056]
Hi Alex,

can you help me (with a tutorial or something) with Stadia Stamen Terrain? Lately they provide a grey box at low zoom level.

I tried to sign up to them but looks very difficult.

Thank you,
Karl.

**Comment by Marci353** [comment]
Sorry, I forgot:

X-Plane 12 with Win10 on a PC.

**Comment by Marci353** [comment]
Meanwhile I succeed to get my API key from Stadia, which I entered under Tools/Options/Map Display Keys.

But LittleNavmap still shows this:
![1](https://github.com/albar965/littlenavmap/assets/102797982/263a708b-a331-4503-98d1-199248437a8a)

**Comment by albar965** [comment]
See here in the Avsim forum for the solution:
https://www.avsim.com/forums/topic/627225-new-maps-for-lnm-update-4/page/13/?tab=comments#comment-5016622

You can download the new theme file right here: https://www.littlenavmap.org/downloads/Map%20Themes/Stadia%20StamenTerrain.zip

This new theme uses another cache folder which does not overlap with the discontinued theme.

Alex

**Comment by Marci353** [comment]
Hi Alex,

I did exactly that. From LNM side everything perfect. But the grey boxes are there.

Is it possible that the issue comes from Stadia side?

**Comment by Marci353** [comment]
Could you check in your PC the area of Porto (Portugal)?

Because after requesting a new API key LNM looks working everywhere, but not at Porto.

Thank you

**Comment by albar965** [comment]
No problems in Portugal.
Go to LNM main menu `Tools` -> `Files and directories` -> `Show map cache`.
Close LNM and delete the `stadiastamenterrain` and `stamenterrain` folders to clear the cache.

**Comment by Marci353** [comment]
Thank you Alex!

That was it!

Perfect now!

**Comment by albar965** [comment]
Good to hear. :upside_down_face: 
I think I  can close this. The new stamen theme will be included with the next LNM version (0ec1b3f4a9ae298fc3640500059cd734d8eef5cd).

Alex
