### ISSUE TITLE
Log entry sorting by time.

### ISSUE THREAD

**Issue by anonymous555** [albar965/littlenavmap#1057]
Looks like log entries are sorted by day, not time.  So if there are multiple flights in the same day, they can show up in the wrong time order.

**Comment by albar965** [comment]
Thanks. I'll check.

**Comment by anonymous555** [comment]
Here's a screenshot 
![image](https://github.com/albar965/littlenavmap/assets/8370128/1526d088-2239-4609-bba6-e4841de08b1a)

The latest flight is from KAEX to KHDC, but you can see PAFA, an earlier flight, listed first

**Comment by albar965** [comment]
I cannot see the time in your screenshot.

Maybe it helps if you send me your logbook database per email. This is
`C:\Users\YOURUSERNAME\AppData\Roaming\ABarthel\little_navmap_db\little_navmap_logbook.sqlite` on Windows.

https://albar965.github.io/contact.html 

Alex

**Comment by anonymous555** [comment]
[little_navmap_logbook.zip](https://github.com/albar965/littlenavmap/files/13064263/little_navmap_logbook.zip)

Ok here's the log sql.

**Comment by albar965** [comment]
Thanks a lot for the file. Give me a few days to look into this.

**Comment by albar965** [comment]
Sorry, I cannot reproduce this. I changed all to English/US locale and checked a lot of flights which happened the same day and they are correctly sorted:
![image](https://github.com/albar965/littlenavmap/assets/15254956/81d3fe2b-df62-4e82-b46c-142828c2f9ad)
