### ISSUE TITLE
"Correct scenery mode" after loading scenery library, option to disable dialog and keep my option

### ISSUE THREAD

**Issue by marbleflower** [albar965/littlenavmap#1058]
One of the main reasons I prefer using Little NavMap over other similar programs is that it pulls data directly from the sim. Therefore, whatever airport, procedures, navaids, and data are available are shown exactly as it is in the simulator's world and not on a separate database. This problem started appearing after I started using Navigraph navdata as it was needed to add procedures for airports missing in the default global scenery. When updating the scenery library¸ I am prompted to "correct" the scenery mode to use Navigraph's data for Little NavMap, which I find to often be inconsistent with what is actually available in the sim. I already blocked the default navdata from loading in the scenery library so I don't have issues with conflicts. However there is no way to dismiss this dialog without allowing the Navigraph database to be loaded every time, and selecting the box and clicking "No" doesn't work either. I request an update to dismiss the dialog with "Do not show this dialog again and remember my choice" since we already have the option to change the scenery mode automatically under "Select Automatically" for those who want to use the Navigraph data.

![Screenshot (3035)](https://github.com/albar965/littlenavmap/assets/39548530/e1adc06f-8771-40e0-a69c-68caf9d2b312)

**Comment by albar965** [comment]
I don't know what you mean by " inconsistent with what is actually available in the sim". Any examples?

But if you do not like the default selection simply correct it after loading. In almost all cases the default selection is the right one.

And I'd strongly not recommend to disable the default scenery library or parts of it. This will case a mess after loading since add-ons often update default scenery.

**Comment by marbleflower** [comment]
Airports with recently opened runways (for example VHHH) are completely missing procedures for the new runways with the built in Navigraph data set.

Certain airports made by third-party scenery developers have procedures and ILS localizers that are broken, completely off, or missing as well.

This dialog did not start appearing for me until a few updates ago. The option to dismiss the dialog appeared later if I remember correctly, but without the option to keep the scenery mode.

**Comment by marbleflower** [comment]
Alright, that makes sense, thank you for your time and thanks for all the work you do for Little NavMap 👍

**Comment by albar965** [comment]
Ok. Let me know if you find issues where LNM differs from MSFS. Can happen with the incredibly complex scenery structure.
I think this can be closed.
