### ISSUE TITLE
Taxiway display

### ISSUE THREAD

**Issue by Marci353** [albar965/littlenavmap#1059]
Hi Alex,

I would like to ask you about displaying taxiways.

I am on XP12, and in LNM use Stadia StamenTerrain. I attach two pictures. On the first you see an airport IF the taxiways are transparent (by WED-editor), on the second IF a taxiway is asphalt for ex.

For some reason I need that taxiways are transparent at some airports. But in this case the background in LNM will be transparent too.

Is there any way to make the background color in LNM independent from the XP12 apt.dat datas? I mean dark even if in XP it is transparent?

Thx, Karl.

![1](https://github.com/albar965/littlenavmap/assets/102797982/2bcef644-cfde-4948-8dc5-70c6e63e5e17)
![2](https://github.com/albar965/littlenavmap/assets/102797982/097ef9b2-0ebb-4d81-bf2f-be421f31b453)

**Comment by albar965** [comment]
Makes sense. This appears too often in XP. I think it is better to use a solid color. Maybe a lighter version of Asphalt.

**Comment by Marci353** [comment]
Sorry, maybe I dont really undesrstand you.

Do you mean that you will make changes in LNM to avoid this?

**Comment by albar965** [comment]
Now I think I don't understand. You'd like to have all taxiways transparent?

You can change airport display in options:
![grafik](https://github.com/albar965/littlenavmap/assets/15254956/21c76519-a675-4f50-9a98-d697401395d9)
Maybe this helps.

**Comment by Marci353** [comment]
No, absolutely not.What I would like: even if my taxiway is transparent (for a certain reason), LNM should show it as dark, to be able to see it,  independently if it is transparent in the apt dat or not.--Sent from my Android phone.On 2023. 10. 27., 16:06 Alexander Barthel ***@***.***> wrote:

   
  Now I think I don't understand. You'd like to have all taxiways transparent? 
  You can change airport display in options:  Maybe this helps.

**Comment by albar965** [comment]
> No, absolutely not.What I would like: even if my taxiway is transparent (for a certain reason), LNM should show it as dark, to be able to see it, independently if it is transparent in the apt dat or not.

Then we agree. :+1: 

This is what I suggest too. :upside_down_face: : Never show transparent aprons or taxiways as transparent.

The transparent is an attribute in the airport features. Airport designers use it to put a photo-realistic background below aprons or other. Makes no sense to show this in LNM.

**Comment by Marci353** [comment]
Not always.In my case at a certain airport I dont have taxyways, only draped polygons instead.So I took the default taxiways, but because it is only approximately following the draped polygons, I made it transparent.The result you can see above.I ask you only for the possibility of a tick box, where user can decide wether he wants transparent taxiways to be shown, or not.--Sent from my Android phone.On 2023. 10. 27., 16:24 Alexander Barthel ***@***.***> wrote:

   
   
   No, absolutely not.What I would like: even if my taxiway is transparent (for a certain reason), LNM should show it as dark, to be able to see it, independently if it is transparent in the apt dat or not. 
   
  Then we agree. 👍 
  This is what I suggest too. 🙃 : Never show transparent aprons or taxiways as transparent. 
  The transparent is an attribute in the airport features. Airport designers use it to put a photo-realistic background below aprons or other. Makes no sense to show this in LNM.

**Comment by Marci353** [comment]
Sorry Alex,but X-Plane does. I am an airport designer.It is easy to make difference between taxiways and draped polygons, that is why LNM doesnt show them - even when they actually act as taxiways.They have a diff. code number in apt.dat of every airport.And LNM knows too if a taxiway us asphalt, or transparent, so it shoul be able to detect taxiways.--Sent from my Android phone.On 2023. 10. 27., 16:36 Alexander Barthel ***@***.***> wrote:

   
  X-Plane does not make a difference between taxiways an apron polygons unlike FSX or MSFS . It's all one big surface polygon. No way for LNM to detect a difference. The yellow center lines are paths which are also not related to the polygons.

**Comment by Marci353** [comment]
And one another thing: the centerlines are another category (Lines or Markings), which are always above terrain (ortho, polygons, taxiways, etc.)--Sent from my Android phone.On 2023. 10. 27., 16:36 Alexander Barthel ***@***.***> wrote:

   
  X-Plane does not make a difference between taxiways an apron polygons unlike FSX or MSFS . It's all one big surface polygon. No way for LNM to detect a difference. The yellow center lines are paths which are also not related to the polygons.

**Comment by albar965** [comment]
There is only record type `110` in apt.dat

**Comment by albar965** [comment]
LNM does not read centerlines.

**Comment by Marci353** [comment]
Yes, in this way you are right, You can determine the draped polygon coordinates by the boundary nodes, true. And I see it is not possible to differentiate taxiways from draped polygons.

Well, then remains my originally ask: would it be possible to place a tickbox in LNM where the user can decide if he wants to see the taxiways even if they are transparent, too?

**Comment by albar965** [comment]
> You can determine the draped polygon coordinates by the boundary nodes, true.

Unfortunately too much effort (also regarding CPU cycles). :man_shrugging: 

> Well, then remains my originally ask: would it be possible to place a tickbox in LNM where the user can decide if he wants to see the taxiways even if they are transparent, too?

Not sure if I want to make this configurable. But the transparency can go for sure.

**Comment by Marci353** [comment]
OK. Thank you anyway.

**Comment by Marci353** [comment]
I know it is my fault but I cant figure it out, why some airport have this pink symbol, meanwhile the majority have blue.
![1](https://github.com/albar965/littlenavmap/assets/102797982/6b142e60-fde2-49dd-91d3-e8e1ccde4239)

**Comment by albar965** [comment]
> I know it is my fault but I cant figure it out, why some airport have this pink symbol, meanwhile the majority have blue.

See [LNM User Manual - Legend](https://www.littlenavmap.org/manuals/littlenavmap/release/latest/en/LEGEND.html#airports).

Indicates airport with or without tower. Detected by presence of tower frequency. 
Depending on simulator this might be a bit unreliable.

**Comment by Marci353** [comment]
Thank you!--Sent from my Android phone.On 2023. 10. 29., 11:27 Alexander Barthel ***@***.***> wrote:

   
   
   I know it is my fault but I cant figure it out, why some airport have this pink symbol, meanwhile the majority have blue. 
   
  See LNM User Manual - Legend. 
  Indicates airport with or without tower. Detected by presence of tower frequency. Depending on simulator this might be a bit unreliable.

**Comment by Marci353** [comment]
Hi Alex,

"Empty airports shown in gray. No taxiways, no parking spots and no aprons."

Can you explain why EDDF is grey? Has taxiways, gates, etc.
![1](https://github.com/albar965/littlenavmap/assets/102797982/df8a1f33-2db9-4a66-b6a1-58dfd4b3161d)

**Comment by albar965** [comment]
> Can you explain why EDDF is grey? Has taxiways, gates, etc.

Due to a bug in X-Plane 12 large airports have the 3D flag is missing and LNM `Options` -> `Map` -> `Empty Airports` -> `Consider all airports not 3D as empty` is checked. This also applies to add-ons wrongly labeled as 2D.

**Comment by albar965** [comment]
Transparent surfaces are now shown light gray. Colors and transparency can be changed in `little_navmap_mapstyle.ini` now.

**Comment by Marci353** [comment]
Wonderful, thank you!--Sent from my Android phone.On 2023. 11. 08., 16:56 Alexander Barthel ***@***.***> wrote:

   
  Transparent surfaces are now shown light gray. Colors and transparency can be changed in little_navmap_mapstyle.ini now.

**Comment by Marci353** [comment]
Sorry, will it be in a future version available? Right now I dont find it.

**Comment by albar965** [comment]
Of course a future version. 

You can either fetch the sources and compile it yourself (you better be a developer then) or wait for the next alpha or beta release.
