### ISSUE TITLE
Trouble following reloading litlleNavMap

### ISSUE THREAD

**Issue by NCMarshall** [albar965/littlenavmap#1061]
Following a catastrophic meltdown with X-Plane 12 I reinstalled the application and found that I could not load my plane onto the map and nothing happened when I used the Tools bar to click on load simulation plane despite clicking on connect.
I uninstalled LNM and reinstalled it. Followed the instructions and added the program to X-plane plugins. 
Cannot make the LNM recognise that x-plane is running or load the plane.
Am I missing something. Is there something I have failed to do?

All help gratefully accepted.

NM

**Comment by albar965** [comment]
Please delete the issue text next time after reading and providing all needed information.

What OS do you run? 
Can you see Xpconnect in the X-Plane plugins menu?

**Comment by NCMarshall** [comment]
Apologies - for not deleting.
Mac OS 14.1.1 on a Mac Studio M2 Ultra 
When I click on X-Plane plugins I see the following:
Commands.txt
DataRefs.txt
LittleNavmap-macOS-2
PluginAdmin
SAM
XPLM_64.dll
XPLM_64.so
XPLM.framework
XPWidgets_64.dll
XPWidgets_64.so
XPWidgets.framework

Within LittleNavnap-macOS-2:
 3 CHANGELOG txt files
LICENSE,txt
Little Navconnect
Little Navmap
Little Xpconnect arm64
Little Xpconnect x486
3  README txt files 
2 revision-LittleNavmap txt files

Hope this makes sense,

NM

**Comment by NCMarshall** [comment]
Fantastic

Thank you - NM

**Comment by albar965** [comment]
Perfect. :+1: Happy flying! :upside_down_face:
