### ISSUE TITLE
Performance Drop Issue with Little Nav Map While Flying in MSFS

### ISSUE THREAD

**Issue by dunham94** [albar965/littlenavmap#1062]
I would like to talk about a PERFORMANCE issue that occurs in my Little Nav Map while I'm flying. I like to see where I am ascending and descending through the top of descent and climb graphics. When I click and drag the mouse on the map to see where I am flying, I notice a drop in FPS to around 5 to 3 FPS, even though I have a Ryzen 7 2700x with a 1070ti and also run MSFS. I don't know why this FPS drop is happening, as I should be able to run both normally. In other words, I am experiencing a performance issue when clicking and dragging the mouse on the map during the flight, showing the aircraft in real-time on the map.

==> While testing the PERFORMANCE issue, I realize that the number of 'details on the map,' such as Fixes, ILS, and AIRPORTS, is interfering with the performance. Therefore, if I reduce it, the FPS increases. However, if I reduce even 'one point,' I can't see the Fixes I want to fly to and the ILS I need for landing. So, I believe the issue lies in the program's performance.

**Comment by albar965** [comment]
Just to clarify: You see a drop in MSFS FPS while clicking and dragging in LNM? 
Do you use a add-on to show the map inside MSFS or do you use LNM on a second monitor or same screen?

I'd rather say that this is normal if the MSFS window is not active. You should not see any performance drop while LNM is running aside (second monitor or other ways). But clicking around will turn the MSFS window inactive and this can have all kind of consequences (stutter, lower FPS, etc.).

For add-ons showing the map inside MSFS I cannot help. You'd rather contact their developer.

**Comment by dunham94** [comment]
While testing the PERFORMANCE issue, I realize that the number of 'details on the map,' such as Fixes, ILS, and AIRPORTS, is interfering with the performance. Therefore, if I reduce it, the FPS increases. However, if I reduce even 'one point,' I can't see the Fixes I want to fly to and the ILS I need for landing. So, I believe the issue lies in the program's performance.

I'm not using anything, just while flying, I press alt tab, go to LNM, and try to drag the map by clicking, and it keeps stuttering. It's very strange, a FPS drop when dragging the map. I don't know what it could be.
I use two screens.

**Comment by albar965** [comment]
Please clarify. LNM does not show FPS. So FPS in MSFS reduces with more map details or what FPS?

Can you answer my question from above:
> Do you use a add-on to show the map inside MSFS or do you use LNM on a second monitor or same screen?

**Comment by albar965** [comment]
Lacking information from submitter. Closing.
