### ISSUE TITLE
XP12.08b3 DataRef change

### ISSUE THREAD

**Issue by gkkes** [albar965/littlenavmap#1063]
From my latest Log.txt

[Little Xpconnect 1.0.10.beta]:
Dataref 'sim/weather/temperature_ambient_c'
Dataref 'sim/weather/temperature_le_c'
Dataref 'sim/weather/visibility_reported_m'
Dataref 'sim/weather/rain_percent'
have been replaced. Please use the new names.

**Comment by albar965** [comment]
Thanks for letting me know. Will fix this for the next LNM 3.0 betas and releases.

**Comment by albar965** [comment]
Just noticed that I already use the new datarefs. Make sure you use the latest Xpconnect 1.0.39 from [Little Navmap 2.8.12](https://albar965.github.io/release/2023/07/16/littlenavmap-stable-2812-released.html).

Let me know if this fixes it.
Alex
