### ISSUE TITLE
IVAO Online ATC

### ISSUE THREAD

**Issue by FGouveia13** [albar965/littlenavmap#1065]
I've noticed that I can't seem to display IVAO online ATC at all in LNM. I see the traffic just fine, but the atc never shows up. If I try with vatsim , it works. Any work around to this? Is this a known issue?

**Comment by albar965** [comment]
I see this here too. Maybe they changed something in the API. Have to check.
Thanks for reporting.

**Comment by FGouveia13** [comment]
I know that they shutdown wazzup years ago, and that theyve introduced wazzup v2 aswell, their api did change a bit. Hope it helps

**Comment by FGouveia13** [comment]
Ah ok, nvm then ahah. Good luck, thanks for the swift answer

**Comment by albar965** [comment]
Previous format:

![grafik](https://github.com/albar965/littlenavmap/assets/15254956/69988839-cefc-49d4-b6d7-13ee26735935)

Current format from https://api.ivao.aero/v2/tracker/whazzup:

![grafik](https://github.com/albar965/littlenavmap/assets/15254956/e096fc1a-253e-41d2-a67f-7b008c82add5)

**Comment by im-alfa** [comment]
Hi,

Thanks for your email. We are working on getting it back :)

[https://heartbeat.ivao.aero/reports/188](https://heartbeat.ivao.aero/reports/188)

Thank you!

**Comment by im-alfa** [comment]
Hi guys,

Sorry for the delay. The fix has been deployed.

Thank you!

**Comment by albar965** [comment]
> Yeap seems to be working! Is there a way to ONLY display IVAO ATC and not the rest of the offline info?

Yes. In `Scenery Library` -> `Airspace Libraries` select only `Online`.

Alex

**Comment by albar965** [comment]
Perfect! Thank you a lot for the fix!

![grafik](https://github.com/albar965/littlenavmap/assets/15254956/f70ae3be-d9af-49d3-b193-b007cb8550a9)

**Comment by FGouveia13** [comment]
Perfect! Now I gotta find a way to show boundaries and we're golden! Thanks both of you!

**Comment by albar965** [comment]
Boundaries from IVAO can be found here: https://www.littlenavmap.org/downloads/Airspace%20Boundaries/
Extract the Zip and import from the extracted folder in LNM from `Scenery Library` -> `Load User Airpspaces`.
Not all centers have a boundary, though.

**Comment by FGouveia13** [comment]
Great! Thanks so much
