### ISSUE TITLE
2.8.12 64 bits disabled buttons

### ISSUE THREAD

**Issue by laurentQuarkfr** [albar965/littlenavmap#1070]
![Capture d'écran 2023-12-22 184048](https://github.com/albar965/littlenavmap/assets/66872031/308df232-3e00-439a-b754-187b5d5f6f58)
hi, when i start the app, i have always these disabled buttons. how to use them ?

**Comment by albar965** [comment]
These features are not available in the MSFS scenery library. You either need X-Plane or a Navigraph navdata update for LNM. Sorry, cannot fix this.

There is more missing. You see the same limitations as mentioned here:
https://www.littlenavmap.org/manuals/littlenavmap/release/latest/en/NAVDATA.html#do-not-use-navigraph-database
