### ISSUE TITLE
Beta 3.0/ MSFS  EDDH has no procedures like SID or Stars 

### ISSUE THREAD

**Issue by AchWoDu** [albar965/littlenavmap#1072]
AIRAC is 2003/12
I don't now why.

**Comment by albar965** [comment]
Do you have the Navigraph update installed in MSFS and/or LNM?
Why the old AIRAC? This does not come from the stock data. LNM cannot extract the AIRAC from the MSFS scenery library.
What are the settings in LNM menu `Scenery Library` -> `Navigraph`?
What LNM version do you use?

Sorry for bombing with questions but otherwise I cannot help.

**Comment by Cryptic-432** [comment]
G'day, 
I'm having what sounds like an identical issue (although I'm using the latest AIRAC cycle), so I'll contribute here.

Some details for you:

LNM **`3.0.0.beta 64-bit (revision 7b8d2138)`** **|**  OS **`Win10`** **|** Sim **`MSFS`** **|** AIRAC cycle **`Navigraph 2312`**
Setting in LNM **`Use Navigraph for Navaids and Procedures`**.

**_Just a note -_** I do all my flying in Aus. 
I have noticed missing procedures at a vast number of airports, so I'll just name a few: _YSSY - YPPH - YBMA - YBUD_

What I have tested: 
Setting: **`Use Navigraph for all Features`** = no missing procedures (all show up as expected)
Setting:  **`Do not use Navigraph database`** = no missing procedures (of course, just not the Navigraph ones)

**_As an aside -_** I did go and check EDDH and it is showing procedures for me (with the **Use Navigraph for Navaids and Procedures** setting, as well as with the other setting options).

**Comment by AchWoDu** [comment]
> Do you have the Navigraph update installed in MSFS and/or LNM? 
Yes! In MSFS and LNM from Navigraph!
Why the old AIRAC? This does not come from the stock data. 
Sorry; AIRAC is 2312
LNM cannot extract the AIRAC from the MSFS scenery library. 

What are the settings in LNM menu `Scenery Library` -> Navigraph`? 
In the past (older LNM versions) I always used "For Navgation and procedures!"
Whis this setting I have the problem now!
Now, when I switch to "Not used Navigraph",  it works! 
I think that is a workaround for me and not normal!? 

What LNM version do you use?
LNM 3.0.0 beta 64Bit/ Windows11
> 
> Sorry for bombing with questions but otherwise I cannot help.
regards
Achim

**Comment by albar965** [comment]
**Please always use the setting `Select automatically` menu `Scenery library` -> `Navigraph`.** This way you get the best selection depending if you have the MSFS and LNM Navigraph update installed or not. Everything else can result in invalid or missing data. You might use outdated Navdata from the free included cycle 1801 using the wrong setting.
**Also make sure to update LNM too when using the Navigraph update for MSFS.**

1. EDDP has procedures here with Navigraph updates installed in MSFS **and** LNM which results in `Use Navigraph for Navaids and procedures` using `Select automatically` in the menu. ![grafik](https://github.com/albar965/littlenavmap/assets/15254956/315dd863-723d-4684-a718-4839f5180e68)
2. Procedures are also present here without any Navigraph updates which results in `Do not use Navigraph Database` having `Select automatically` checked.

What do you see in the information window on tab `Airport` -> `Overview` in section `Data sources`? Maybe another add-on overwriting the airport.

But switch to `Select automatically` first and then report back if it is working.
Read more in [LNM User Manual - Navigation Databases](https://www.littlenavmap.org/manuals/littlenavmap/release/latest/en/NAVDATA.html)

I'll have a look at the latest Navigraph update to see if LNM recognizes the last one.

**Comment by albar965** [comment]
> I have noticed missing procedures at a vast number of airports, so I'll just name a few: _YSSY - YPPH - YBMA - YBUD_

No problems with these using Navigraph updates for both LNM and MSFS.
It could be a problem similar to this reported here: https://www.avsim.com/forums/topic/640654-little-navmap-300beta-released/?tab=comments#comment-5047631
But the airport centers for these are the same in Navigraph and MSFS. I'm at a loss here.

**Comment by Cryptic-432** [comment]
I forgot to mention in my comment above, I tried with **`Select automatically`**  which defaults it to the **`Use Navigraph for Navaids and Procedues`**, looks exactly as in your screenshot, this still results with certain airports showing _no procedures_ 

Sure seems like an odd issue to pop up, I appreciate the help with it all!
This is what it's looking like on my end, using YSSY as an example.

<details><summary>Pic's</summary>
<p>

![Auto](https://github.com/albar965/littlenavmap/assets/120445355/d05e6fa0-32d2-4ba3-8e3f-53f183a3a15f)

![Navigraph_Nav-Proc](https://github.com/albar965/littlenavmap/assets/120445355/94604fca-94ba-4d2d-9bd4-9a6da02643c4)

![Navigraph_Only](https://github.com/albar965/littlenavmap/assets/120445355/01873e0e-3a2c-43c8-8c96-a98014c3c2f6)

![No_Navigraph](https://github.com/albar965/littlenavmap/assets/120445355/82b7993f-d114-4f58-9cf8-2bc973a36e70)

</p>
</details> 

--Tristan

**Comment by albar965** [comment]
Ok. I see. Not an odd issue but just some fuzzy search required on my side (see explanation in the Avsim link above). And that fuzzy search can go wrong. If it does, it better be fixed.

Here is what it looks here on my development computer. 

![grafik](https://github.com/albar965/littlenavmap/assets/15254956/0cf0d10d-85ce-4839-a90a-8e59c6102002)

What do you see in the `Data sources`, BTW?

Ignore the odd paths. This is my Linux development computer. I also tested on Windows.

**Comment by AchWoDu** [comment]
![2 8 12](https://github.com/albar965/littlenavmap/assets/66385065/9023f2a6-9076-4e1b-b96e-9246d90b470f)
![V3 0 0](https://github.com/albar965/littlenavmap/assets/66385065/c7bc436c-dbe6-4a95-af84-2bccb3136b72)

I have switch to the settings "navigraph automatic".
Above you see what I get with V 2.8.12 and then with V3 Beta.
I only changed the files in my program folder!

**Comment by Cryptic-432** [comment]
Good to hear it's not an odd one, thanks for sharing the Avsim link about it too!

Here is what's shown for me with `Select Automatically`  option (which selects the use Navigraph nav and proc)
(can also see what shows with other options in the previous pic's above)

![Screenshot (1927)](https://github.com/albar965/littlenavmap/assets/120445355/d7847880-e204-4fd9-92dd-dd8f28763020)

**Comment by albar965** [comment]
@AchWoDu Ok. That you see this when downloading from SimBrief is important information. Anyway, I cannot reproduce this with the not yet released 3.0.1.beta neither with 2.8.12. I fixed issues in the route description department which most likely might affect this. I'd suggest you wait for 3.0.1.beta and then report back. I fixed quite a few bugs in this version.
I suppose LNM shows procedures when you right click the airport, or not?

@Cryptic-432 We're probably looking at different issues. What happens if you exclude the Flytampa add-on?

**Comment by AchWoDu** [comment]
![0](https://github.com/albar965/littlenavmap/assets/66385065/713bc2e8-aa52-4e51-912e-71aaeb965721)
![1](https://github.com/albar965/littlenavmap/assets/66385065/478bf9f5-a43f-4908-a19c-30f16e57f3c5)
![3](https://github.com/albar965/littlenavmap/assets/66385065/282a4c83-9a11-4a51-b1ef-b7b6ff6fbfe2)
![4](https://github.com/albar965/littlenavmap/assets/66385065/ae8add20-5efb-43c6-ac3e-5fb0509e114a)
![5](https://github.com/albar965/littlenavmap/assets/66385065/71a3a7c4-e6e6-4d9e-9b4f-6f5a71fa2a76)

**Comment by AchWoDu** [comment]
Ok, for now will wait for new version.
Many Thanks
Achim
and wait for tomorow, a new AIRAC will arrive:-). Maybe it will work better!

**Comment by Cryptic-432** [comment]
> What happens if you exclude the Flytampa add-on?

Removed it, rebuilt the database, the procedures now show. All other airports that showed **_no procedures_** now show their procedures again, too.

> We're probably looking at different issues

I think we are!
 
I believe I've found my problem:
When unlinking YSSY  I noticed a folder: **_FlyTampa Libraries_** which shouldn't have been linked to community. No idea how it ended up linked again. It was required way, way back at YSSY's initial release. For a **LONG** time now it hasn't been needed. Seems it has remained in my **_Orbx Library_** folder, somehow it relinked _itself_ .... 

I've relinked just YSSY, and all airports show their procedures again! 

_Not sure what the files in that library folder have against procedures_ 😆 ... but it's seemingly the culprit to my issue!

**Comment by albar965** [comment]
@AchWoDu Feel free to reopen after 3.0.1.beta. I fixed quite a few bugs which certainly affect this too.

@Cryptic-432 Glad it is working now and thanks for the feedback!

Alex

**Comment by AchWoDu** [comment]
Hello,
here is some more information.
After I blocked all addon airports in MSFS, it works.
So the problems are the addon airports.
But I only get this problem in the V3 beta version.
Okay, will now wait for the new version.
Achim

**Comment by albar965** [comment]
@AchWoDu Can you send BGL files of some of these add-on airports? Or let me know which one in case these are freeware or a link?

You can find the user BGL files in the section "Data Sources" in airport overview information.

**Comment by AchWoDu** [comment]
[https://secure.simmarket.com/justsim-hamburg-airport-eddh_msfs-(de_14203).phtml](url)
[https://secure.simmarket.com/justsim-duesseldorf-airport-msfs-(de_14122).phtml](url)

**Comment by albar965** [comment]
Hardlinks should not cause a problem and thank you for the files. All looking fine here.

Note that in the section `Data Source` there is first the add-on airport (1) and on top of it is the Navigraph update (2). The order is important. Check if you have the same order. You can change this in the MSFS file `Content.xml`.

Anyway procedures should never be affected using the Navigraph update for MSFS and LNM since LNM takes the procedures for an airport (sim database) from the Navigraph database.

![grafik](https://github.com/albar965/littlenavmap/assets/15254956/c41aa96b-0c66-416e-9710-aea014f2b2fc)

**Comment by AchWoDu** [comment]
Thank you for your support.
As I already wrote, V2.8 works perfectly.
The beta causes the problems described for me even though I use the same files in local/ABartel.
As I discovered through testing, I don't get the problems with certain airports, but rather when I load the scenery library with more than 5473 files. As soon as it shows that more files have been loaded, the beta is causing problems. For whatever reason?
Since I'm happy with V2.8, I'll stick with this version for now.
Thank you
Achim
If you have any further questions, I would of course be happy to answer them ;-)

![1](https://github.com/albar965/littlenavmap/assets/66385065/47d2f542-e088-48b5-ba9e-afe05930e2ce)

**Comment by albar965** [comment]
LNM has no limitation on number of files. This is a bit strange since nothing has changed in loading MSFS scenery. I'm trying but cannot reproduce it here with either version. I'll keep an eye on it.

Alex

**Comment by AchWoDu** [comment]
I understand that such problems are not always easy to find.
What I just don't understand is that V2.8 works perfectly with the same data. I even completely deleted local/ABarthel and started again. The error was the same after I installed the NAV data for MSFS and LNM from Navigraph:
Beta causes problems, V2.8 works.
If I limit myself to a certain number of AddOn Airports, the beta also works.
As soon as I add another airport, the problem arises again that the procedures cannot be found.
I turn off some airport again. It works.
If I connect any airport again, problem!

**Comment by AchWoDu** [comment]
Is it helpful, when I send you any db-file, maybe the "little_navmap_msfs.sqlite" ?

**Comment by albar965** [comment]
Really strange. And again: There is no limitation on files or airports anywhere in LNM. It might be one airport which trashes the memory in LNM or causes something to overflow while being read and causes these issues. I've seen weird issues already.

About "little_navmap_msfs.sqlite": Thanks but this won't help. This is the file installed by the Navigraph FMS Data Manager and is not changed by LNM. The sim data is stored in "little_navmap_msfs.sqlite" by LNM.
Trying to reproduce this I'd need your whole scenery library (gigabytes ...) and even then its unlikely to show up.

**Comment by AchWoDu** [comment]
Okay, then I'll continue with V2.8 first.
I'm actually completely happy with that :-).
Wish you a happy new year.
In any case, I am grateful to you for making such a great program available to the community for years.
Achim

**Comment by albar965** [comment]
> Okay, then I'll continue with V2.8 first. I'm actually completely happy with that :-). Wish you a happy new year. In any case, I am grateful to you for making such a great program available to the community for years. Achim

A Happy New Year to you too, Achim!

**Comment by AchWoDu** [comment]
:-)) :-)) :-)) :-)) :-)) :-)) :-)) :-)) :-)) 
Beta 301 works perfect!!!
regards
Achim

**Comment by albar965** [comment]
Good to know and thanks a lot. :+1:
