### ISSUE TITLE
Beta 3.0.0 - Issue/Bug: Select Airport Types - Add-On only, no airports visible

### ISSUE THREAD

**Issue by Cryptic-432** [albar965/littlenavmap#1075]
LNM **`3.0.0.beta 64-bit (revision 7b8d2138)`** **|** OS **`Win10`** **|** Sim **`MSFS`**

Previously I would only have the option **`Add-on`** selected, as I only want to see add-on airports visible on the map. Now when this is the only option selected, the map is void of all airports. 
To have them visible I must select the options **`Hard surface`** and `**Soft surface`**. Which, as is to be expected, leads to all airports showing on the map and not just add-on ones. 

**_For clarity -_** when I say _all airports show with hard & soft surface options selected_, airports which require any of the other options selected to become visible on the map aren't visible unless the appropriate option is also turned on. 

_Note 1 -_ Add-on airports which fall into one of the extra categories do not show unless the corresponding option is selected (for e.g. **`Not lighted`** and/or **`No procedure`** 
[This wasn't so previously, where having only **`Add-on`** selected would show all add-on airports regardless of airport _type_]

_Note 2 -_ If I de-select the **`Add-on`** option it makes no change to the airports displayed on the map. (With all other options left the same/all on)

<details><summary>Screenshots of Issue</summary>
<p>

![Screenshot (1915)](https://github.com/albar965/littlenavmap/assets/120445355/f181e4bf-74e7-4c20-994f-ae78f166c9af)

![Screenshot (1916)](https://github.com/albar965/littlenavmap/assets/120445355/992c67fb-7625-4563-bb4e-f30997298874)

</p>
</details>

**Comment by albar965** [comment]
Please see the file `CHANGELOG.txt`:

> * Add-on airport display has changed and now adheres to airport filters instead of forcing an
>  always-on display. Add-on filter now only overrides zoom settings and not filters. This means you
>  can hide all add-on airports having a `Soft Surface`, for example.

> _Note 1 -_ Add-on airports which fall into one of the extra categories do not show unless the corresponding option is selected (for e.g. **`Not lighted`** and/or **`No procedure`**

This is working as intended and was requested by several users. :man_shrugging: 

> _Note 2 -_ If I de-select the **`Add-on`** option it makes no change to the airports displayed on the map. (With all other options left the same/all on)

It does. It forces add-ons to display which were otherwise hidden due to high zoom factor.

**Comment by Cryptic-432** [comment]
> Please see the file CHANGELOG.txt: 

I have given the changelog a good read earlier, though I have seemingly misunderstood the changes surrounding add-on airports. Sorry about that!

> This is working as intended and was requested by several users. 🤷‍♂️

Understood, and definitely a handy feature! 😄 

> It does. It forces add-ons to display which were otherwise hidden due to high zoom factor.

So it does! I just wasn't at a zoom level where I could notice the change, that is my mistake! It works exactly as described. (Also a very handy feature!)

As it seems I've misunderstood some things (my apologies for that! 😅) ... If I am understanding correctly, is there now no way to have only add-on airports visible on the map (while hiding all _default_ ones as was possible before)? Or am I missing something somewhere in the settings?

Even though I've misunderstood the changes. I really like the implementation of the features, they will definitely be extremely handy when planning different flight missions. 

Thank you for your help and reply, I really appreciate it!
-- Tristan

**Comment by albar965** [comment]
> As it seems I've misunderstood some things (my apologies for that! 😅) ... If I am understanding correctly, is there now no way to have only add-on airports visible on the map (while hiding all _default_ ones as was possible before)? Or am I missing something somewhere in the settings?

No. Except zooming out all the way. :man_shrugging:  
Maybe I can add a hard "add-only" mode but not this will be more a future change. I have to avoid making things too complicated by adding too many options. This might overwhelm users.

And no problems at all. :upside_down_face:  
Wish you a Happy New Year!

Alex

**Comment by Cryptic-432** [comment]
> Maybe I can add a hard "add-only" mode but not this will be more a future change. 

No worries at all! If it makes it in one day, it makes it in. If not, that is no big deal at all mate! 🙂 

> I have to avoid making things too complicated by adding too many options. This might overwhelm users.

Completely understand this 100% - I Face similar things myself! 😅 

 
Wishing you a Happy New Year as well Alex! 🛩️
