### ISSUE TITLE
3.0.1.beta - API provided by mapactionscontroller is missing

### ISSUE THREAD

**Issue by bkielczewski** [albar965/littlenavmap#1077]
`curl http://127.0.0.1:8965/api/map/features`

Returns 400 Controller not found.

Commit `03b1181a` would be a suspect?

**Comment by albar965** [comment]
Fixed and a bit more with albar965/atools@2ebcb9d1be991ac3c31709be48e67aba01143416 and acfeb15dedd5c21b5a4f6695283cb5d47164d48b
