### ISSUE TITLE
[3.0.1 Beta] unsufficient menu windows' widths

### ISSUE THREAD

**Issue by ChrisXPP** [albar965/littlenavmap#1078]
Hi @albar965 ,

many thanks for your continuous development on LNM. 👍 

I found a (rather visual) issue with the widths of some menu windows which can occur when changing the user interface font and/or size (for reference, I currently use Noto Sans, 10 pt, normal):

![weather_tab](https://github.com/albar965/littlenavmap/assets/74152765/a2466db0-d148-4ca9-addd-2513bd542670)

![window_tab](https://github.com/albar965/littlenavmap/assets/74152765/c249dccb-3111-4a27-bfd3-251057b3c013)

On my setup, I found this issue on the above shown weather and window menu tabs, only.

Maybe it's worth to increase these widths to match with the other menu tabs?

Cheers & happy new year,

Christoph

**Comment by albar965** [comment]
Hi Christoph,
what OS is this? I see no issues on Kubuntu even with Noto Sans 14.
Not sure if I can fix this since the menus are handled by the OS and Qt.

Alex

**Comment by ChrisXPP** [comment]
Hi Alex,

sorry, forgot to mention this... I have Win 11 64 bit.

**Comment by albar965** [comment]
I see this also on Windows 10 and in a Windows 11 VM. Style Fusion and Night do not show this. No idea how to fix this.
