### ISSUE TITLE
IVAO CTR as Circle, while Boundary seems weel defined

### ISSUE THREAD

**Issue by cowreth** [albar965/littlenavmap#1079]
Hi ✋ 

I've tried to find any issue related, but found none with the info I have there, so I'm opening a new one.

Issue : I see "Circles" for CTR on IVAO, while I have a (seemingly) correct boundary file.

Screenshot : 
![image](https://github.com/albar965/littlenavmap/assets/4106263/271cf9b4-47c5-4964-af56-7944205e00b7)
![image](https://github.com/albar965/littlenavmap/assets/4106263/7a60f6e4-33c0-4c34-8fe6-c53240e36490)

Focused on one CTR particularly, Bordeaux Center :
![image](https://github.com/albar965/littlenavmap/assets/4106263/97c0d06e-1132-4e07-9142-f0a85f5e5cd7)

It seems well defined in my atc_positions.json (extract here, cut is mine), which I downloaded on [LNM's website](https://www.littlenavmap.org/downloads/Airspace%20Boundaries/) ([IVAO ATC Positions 20240101.zip](https://www.littlenavmap.org/downloads/Airspace%20Boundaries/IVAO%20ATC%20Positions%2020240101.zip))

> {"center_id": "LFBB", "middle_identifier": "U", "position": "CTR", "map_region": [{"lat": 42.332, "lng": 2.5328}, {"lat": 42.333, "lng": 2.542}, {"lat": 42.338, "lng": 2.5437}, {"lat": 42.341, "lng": 2.5515}, [........] {"lat": 42.363, "lng": 2.4569}, {"lat": 42.359, "lng": 2.4675}, {"lat": 42.34, "lng": 2.4812}, {"lat": 42.343, "lng": 2.5}, {"lat": 42.332, "lng": 2.5328}], "type": "FIR", "name": "Bordeaux Control"},

I know the matching is quite hard, and that it may not work, but in my case it seems to never work. Is there something I missed ?

Cheeeeers and happy new year o/
Seb

**Comment by albar965** [comment]
Sorry, missed this issue.
Should be improved with the new boundary files I uploaded and with the improved matching.

**Comment by albar965** [comment]
Closing. Let's continue the discussion with the reopened #490
