### ISSUE TITLE
Please show Class G ATZ's that have been recently added to Navigraph

### ISSUE THREAD

**Issue by Jimbo99** [albar965/littlenavmap#1081]
A couple of months ago (October/November 2023), Navigraph added Class G airspaces for the ATZ's of most UK airports. They apply to most UK airports, usually a 2km radius and from ground to 2000 feet AGL. For instance, around EGKB (Biggin Hill) and EGKR (Redhill) as shown here with dotted lines
![image](https://github.com/albar965/littlenavmap/assets/13149215/17cd2240-2d17-40cd-b01c-caa7fd161b72)

But they do not display in Little Navmap when Class G airspace is enabled. I've also tried turning on every airspace in case they were in a different class, but they do not display.
![image](https://github.com/albar965/littlenavmap/assets/13149215/96c69d7f-5d41-449f-9c05-de818eab2614)

I'm using the latest Navigraph data (2313 rev 1) and Little Navmap 2.8.12.

As you can see from the Navigraph chart, they add complexity to VFR departures where the ATZ's are near to each other. It would be great to see these in Little Navmap if possible. Thank you very much.

**Comment by albar965** [comment]
There are already class G airspaces in LNM but not the ones you mention:
![grafik](https://github.com/albar965/littlenavmap/assets/15254956/5c2158ed-56d2-4199-9ea8-cc14ecccc344)

The electronic data differs from the charts in some cases. As far as I remember a recent discussion (cannot find it now) these class G are not a part of the Navigraph DFD Format ([Controlled Airspace](https://developers.navigraph.com/docs/navigation-data/dfd-data-format#controlled-airspace)).

**Comment by Jimbo99** [comment]
Hi! Many thanks for your reply. I wonder when that discussion here was - Navigraph only added these airspaces very recently. Please see the discussion about it here on the Navigraph forum: [https://forum.navigraph.com/t/missing-airspace-at-some-uk-airports/12956/4](url) Stephen from Navigraph explains there that this category of airspaces had been missing from their data, but they are now in place (from release cycle 2309). Hopefully that means they can now be included in Little Navmaps? Thank you.

**Comment by albar965** [comment]
Asking here:
https://forum.navigraph.com/t/how-to-identify-missing-airspaces-in-dfd/14560

**Comment by albar965** [comment]
Data not provided.

**Comment by Jimbo99** [comment]
Thank you for asking them anyway, very much appreciated.
