### ISSUE TITLE
Are the FAA VFR and Sectionals Still Working in LNM 3.0.1 beta?

### ISSUE THREAD

**Issue by GitPuffy** [albar965/littlenavmap#1082]
I had used LNM a year or so ago and recently installed the current 3.0.1 beta.  

I have copied into the Little Navmap application (on macOS: /Applications/Little Navmap/Contents/MacOS/data/maps/earth) the us-vfr-sectionals and us-tac folders from my local "archive" of those files.  When I start LNM and choose either of those from the map themes they do not render.  

Has the ability to use those "files" gone away with the current version of LNM?  Is there a work around or new place to find them.  The AVsim forum had a post about downloading them but when I visit the link (again from my local archive) I get a page not found.  

How are people now using Sectionals and VFR charts with LNM?

Thank you.

**Comment by albar965** [comment]
Chartbundle discontinued the service which was used by some of these map themes. I already updated the map themes [here](https://www.littlenavmap.org/downloads/Map%20Themes/) and removed the obsolete themes.

Not much I  can do about this. Has nothing to do with LNM. ¯\\_(ツ)\_/¯

**Comment by GitPuffy** [comment]
Thank you for the response.  Bummer on the Chartbundle service being shutdown.

**Comment by GitPuffy** [comment]
Thank you for the response. Bummer on the Chartbundle service being shutdown.
