### ISSUE TITLE
SID : Runway not in dropdown, still a SID exists when using Navigraph Database for Navaids and Procedures

### ISSUE THREAD

**Issue by cowreth** [albar965/littlenavmap#1083]
Hello,

Something not really an emergency, but potentially helpful to discover an underlying bug.

I'm on KIAH, Houston.

**Note** : scenery from FSDreamTeam, with Navigraph.

**Note** : Problem only arise when I use Navigraph for Navaid and Procedures. When I check "Do not use Navigraph database", the problem does not exist.

In the procedures list of this airport, I can't select RW 15L. The 15R appears in the list (as highlighted in the screenshot). Still, in the table below with all SIDs, you can see SIDs for the 15L. For example, the BNDTO5 is well defined for the 15L (last line on the screenshot). 

![image](https://github.com/albar965/littlenavmap/assets/4106263/be57194b-752c-4abf-82b1-e09af11d302a)

Since the first column "Description" mention the 15L, I'm enclined to think that everything is well defined in the database, but the dropdown suffer from a small bug. Maybe that's not the case.

Happy to grab more information, if needed or helpful.

**Comment by albar965** [comment]
Thank you a lot for the report. :+1: 

No more information needed so far. I can even see this with MSFS and X-Plane stock airports not matter what setting. Definitely broken somewhere.

Alex

**Comment by albar965** [comment]
Fixed with 52d6ef3035dac6b9e9f7db10d958d20bc978b1c1
Runways were not listed in the filter if they had only SID and STAR but no approach procedure assigned.
