### ISSUE TITLE
Traffic pattern disappear when updating LNM version.

### ISSUE THREAD

**Issue by jpr5551** [albar965/littlenavmap#1095]
Happened several times, when updating LNM version the "Traffic patterns" defined in all airports disappear.

Is there a way to make a backup of the defined "traffic patterns"? Any file? Any table in database?

I think "Traffic pattern" should have similar treatment than "Userpoints"

Thank you for job and time.

**Comment by albar965** [comment]
LNM converts data if the format has been changed. But this works only in one direction. From old to new format. If you use a LNM version 2.8 after 3.0 the data *might* be lost. You can run different versions in parallel if needed to avoid this. Mentioned in the changelog.

Patterns are saved in the configuration file `little_navmap.ini` in section `[Map]` for key `TrafficPatterns2` (LNM 3.0.X).

**Comment by albar965** [comment]
> I think "Traffic pattern" should have similar treatment than "Userpoints"

Unlikely to happen. Certainly not with search and all like the userpoints.

I took note for a zoom limitation for patterns and holdings. This can make sense.

**Comment by albar965** [comment]
Glad I could help. :+1:
