### ISSUE TITLE
Strange Flightplan when exporting to MSFS 2020

### ISSUE THREAD

**Issue by Snipsild** [albar965/littlenavmap#1097]
I am a frequent flyer with the MSFS 2020.  I found your software useful, since it provides better interface for IFR planning between airports. Recently when I made a FP between Vaernes Airport (ENVA) and Ryum (ENRM) in Norway, and tried export it into MSFS2020, I got some anomalis on the route. It seemed to be just a mess, after starting the sim, - when opening the VFR map. Attached are the relevant screenshots of the problem. Why does it become like this?

[Flighplan anomaly.pdf](https://github.com/albar965/littlenavmap/files/14448545/Flighplan.anomaly.pdf)
[FP Littlenavmap.pdf](https://github.com/albar965/littlenavmap/files/14448917/FP.Littlenavmap.pdf)

**Comment by albar965** [comment]
For now I see that you have the MSFS scenery library disabled (`(MSFS)` in LNM title bar) and use only the old cycle 1801. I'd expect all kind of problems with this setting. Better is to use LNM menu -> `Scenery Library` -> `Navigraph` -> `Select Automatically`. This will disable the 1801 data.

If this does not help:

2. Can you attach the plan in LNMPLN and MSFS PLN format?
3. Do you have the Navigraph update in MSFS and LNM installed?

**Comment by Snipsild** [comment]
How do you check if the navigraph is updated in both applcations?


tor. 29. feb. 2024, 17:53 skrev Alexander Barthel ***@***.***

**Comment by albar965** [comment]
> How do you check if the navigraph is updated in both applcations?

You should know if you installed something. :upside_down_face: 
Did you install an update using the Navigraph FMS Data Manager?

In LNM you can see it in the  title bar. You can see something like `MSFS / N 2402` which means you use MSFS airports and Navigraph cycle 2402.

In MSFS you'll see two folders 'navigraph-navdata` and`navigraph-navdata-base` in Community.

Try `Select Automatically` first. I'm sure this solves quite a few issues.
