### ISSUE TITLE
Traffic pattern arrows along the way

### ISSUE THREAD

**Issue by jpr5551** [albar965/littlenavmap#1098]
Once a traffic pattern has been created, it appears on the map with direction arrows along the route, if the zoom allows it.

I understand that these arrows indicate the direction in which the Traffic pattern was created, but once created, this direction, although no longer relevant and has no practical effect, but always appears.

This can lead to visual confusion, because it seems that a pattern has a certain direction, and this is not the case in reality: A defined "pattern traffic" can be used in both directions and runways.

Consider removing these traffic pattern arrows as they appear when zoomed in.

It is not very important, but allow me to share my reflection with you.

Thank you for you job and time.
![traffic patterns arrows](https://github.com/albar965/littlenavmap/assets/126686000/1a9e4c47-eac5-416e-9850-71942980bab5)

**Comment by albar965** [comment]
Considering all the settings in the traffic pattern dialog, the arrows make sense.

**Comment by jpr5551** [comment]
Thanks
