### ISSUE TITLE
losing procedure in xplane 12

### ISSUE THREAD

**Issue by Eyderoe** [albar965/littlenavmap#1101]
Dear Albar965,
I met lossing procedures in xp12 which might due to difference between xplane internal ident and ICAO ident.
- ---------------
software version list below:
lmn 3.0.3.rc1 64-bit
lmn-navdata AIRAC2312
xp12 12.0.9-rc-5 (just download from steam, without any addon)
xp12-navdata AIRAC2312
- ---------------
for example in ZUTF:
![image](https://github.com/albar965/littlenavmap/assets/103725178/1ce56b4e-e6ed-4950-bfaa-2961329be13e)
setting like this
![image](https://github.com/albar965/littlenavmap/assets/103725178/96c3dcef-5be1-45d4-9d2e-7f78fda1a07a)
and i cant get any procedure
![image](https://github.com/albar965/littlenavmap/assets/103725178/a025cb36-1403-4af1-8dd5-75d62d60a09d)
only after active some or all of navigraph features
![image](https://github.com/albar965/littlenavmap/assets/103725178/a4d9c34d-df2e-4204-a69f-08680f527528)
I can get procedures
![image](https://github.com/albar965/littlenavmap/assets/103725178/5f560032-116a-4d17-b192-4fc788662fd1)
- ---------------
although this can solve problem
but this will lossing the procedures edit by myself 
so still hope to fix it
I notice there's a issue similar to this ,and seem that it has been solved.
[https://github.com/albar965/littlenavmap/issues/448](url)
and I also ask in group, only i have this problem
- ---------------
hope: use ICAO ident to read from xplane default navdata folder
If you could solve the problem
I will be appreciate it

**Comment by albar965** [comment]
I see this here too.
Will fix for next 3.0.X update.

**Comment by albar965** [comment]
The problem is that the X-Plane ident XZ0015 does not resolve to ZUTF. This is then already a problem in the X-Plane scenery library. There is a file `CIFP/ZUTF.dat` but no airport with this internal ident.

You can rename your own `CIFP/ZUTF.dat` to `CIFP/XZ0015.dat` which might fix the issue.
Or file an airport ident change in the X-Plane gateway.

With `Use Navigraph for Navaids and Procedures` enabled LNM does fuzzy search between two different databases which results in the right airport.

**Comment by Eyderoe** [comment]
Thanks for your reply and all your efforts

**Comment by Eyderoe** [comment]
> The problem is that the X-Plane ident XZ0015 does not resolve to ZUTF. This is then already a problem in the X-Plane scenery library. There is a file `CIFP/ZUTF.dat` but no airport with this internal ident.
> 
> You can rename your own `CIFP/ZUTF.dat` to `CIFP/XZ0015.dat` which might fix the issue. Or file an airport ident change in the X-Plane gateway.
> 
> With `Use Navigraph for Navaids and Procedures` enabled LNM does fuzzy search between two different databases which results in the right airport.

Thanks for your reply and all your efforts

**Comment by Eyderoe** [comment]
Thanks for your reply and all your efforts

**Comment by albar965** [comment]
I'm still thinking about this but I cannot imagine a solution which fixes this at scenery library compile time.

Best workaround would be to download XZ0015/ZUTF from the X-Plane gateway and the replace its ident XZ0015 with the real one in the apt.dat file. This would enable the custom procedures.

**Comment by Eyderoe** [comment]
@albar965 
I know little about programing
but I wonder whether its possible to replace the inner ident with ICAO when there's no conflict

**Comment by albar965** [comment]
No programming knowledge needed.

Download the airport here: https://gateway.x-plane.com/airports/XZ0015/show
I think you need an account to download.
Then replace `XZ0015` with `ZUTF` in the apt.dat which is a text file. Try it out.

At worst you will see two airports at the same location.

**Comment by Eyderoe** [comment]
ok I prefer rename the .dat files, and it works good
