### ISSUE TITLE
Errors when compiling marble

### ISSUE THREAD

**Issue by Eomer16** [albar965/littlenavmap#1102]
Dear Albar965,

I am following your instructions for compiling marble, atools and littlenavmap from https://github.com/albar965/littlenavmap/wiki/Compiling.

software versions listed as below:
marble lnm/1.1
Windows 10 64 bit
QT 5.15.2
cmake version 3.27.9
minGW version 8.1.0
mingw32-make --version: GNU Make 4.2.1 built for i686-w64-mingw32

The procedure I am following:
-> cd D:\LNM\Project\build-marble-release
-> set PATH=%PATH%;D:\QT\5.15.2\mingw81_32\bin;D:\QT\Tools\mingw810_32\bin
-> cmake -Wno-dev -G "MinGW Makefiles" -DQTONLY=TRUE -DQT5BUILD=TRUE -DWITH_quazip=FALSE -DWITH_libshp=FALSE -DWITH_libgps=FALSE -DWITH_libwlocate=FALSE -DWITH_QtLocation=FALSE -DWITH_liblocation=FALSE -DCMAKE_INSTALL_PREFIX="D:\LNM\Project\Marble-release" -DCMAKE_BUILD_TYPE=Release ..\marble
-> mingw32-make -j2

Unfortunately, I got this error from command line:

D:\LNM\Project\marble\src\apps\behaim\main.cpp:11:10: fatal error: QApplication: No such file or directory
 #include "QApplication"
          ^~~~~~~~~~~~~~
compilation terminated.
mingw32-make[2]: *** [src\apps\behaim\CMakeFiles\marble-behaim.dir\build.make:99: src/apps/behaim/CMakeFiles/marble-behaim.dir/main.cpp.obj] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:2495: src/apps/behaim/CMakeFiles/marble-behaim.dir/all] Error 2
mingw32-make[1]: *** Waiting for unfinished jobs....
[  5%] Building CXX object src/lib/astro/CMakeFiles/astro.dir/planetarySats.cpp.obj
[  5%] Building CXX object src/lib/astro/CMakeFiles/astro.dir/solarsystem.cpp.obj
[  5%] Linking CXX shared library libastro.dll
[  5%] Built target astro
mingw32-make: *** [Makefile:155: all] Error 2

If you could solve the problem I will be appreciate it. Thank you for your help.

**Comment by albar965** [comment]
Sorry the wiki needs to be updated. Will do after the 3.0.4 release.

Looks like you're trying to compile the main application or examples.
Have a look at the build scripts here:
https://github.com/albar965/marble/tree/lnm/1.1/build/win

Alex

**Comment by Eomer16** [comment]
Thank you for your help. Build script are totally working for compiling both Linux and Windows. You are the best !!
