### ISSUE TITLE
new feature request about <flight plan calculation>

### ISSUE THREAD

**Issue by Eyderoe** [albar965/littlenavmap#1107]
Dear albar965
new feature request
for example
depature A -> arrival B
I can designation some points (eg. C) . 
so that when using >flight plan calculation< the route will go through C like A-C-B
![image](https://github.com/albar965/littlenavmap/assets/103725178/0b0a5947-79eb-4c19-9a08-f79cb0541f90)

**Comment by albar965** [comment]
You can already do this ... kind of.

Add A, C and B to the flight plan. Then select A and C, right-click and select `Calculate flight plan for selected range`. Same for C and B.

![grafik](https://github.com/albar965/littlenavmap/assets/15254956/ac72628e-80e2-4e92-9224-d5e12ad19424)

**Comment by Eyderoe** [comment]
cool function, sorry for didnt find it before
