### ISSUE TITLE
Crash Report for embedded linux on hardware

### ISSUE THREAD

**Issue by Eomer16** [albar965/littlenavmap#1108]
Dear Albar965,

I managed to compile the project on Ubuntu host with a toolchain for my embedded device. When I tried to start the application on my device littlenavmap is crashed. Do you have any idea why this is happening? I am sending you to the crash report .zip file.

Thank you for your help.

Crash Report:
[little_navmap_crashreport_3.zip](https://github.com/albar965/littlenavmap/files/14601341/little_navmap_crashreport_3.zip)

**Comment by albar965** [comment]
`Driver not loaded` means that the `libsqlite3.so` is missing or not in the path.

**Comment by albar965** [comment]
BTW: There are also Linux build scripts in the folders `build` in `marble` and `littlenavmap`.
Also use the latest branch `release/3.0` since master is behind.

**Comment by Eomer16** [comment]
I added sqlite libraries of Qt to Linux image using yocto project. It is working now. Thank you for your help 😊

**Comment by albar965** [comment]
You're welcome. :slightly_smiling_face:
