### ISSUE TITLE
3.0.5 UNABLE TO FIND DAYTONA BEACH KDAB AIRPORT

### ISSUE THREAD

**Issue by Flashsolutions** [albar965/littlenavmap#1109]
Version 3.0.5 removed allowing City and State to be entered to locate airports.  In the process, I cannot lookup KDAB ident either.

**Comment by albar965** [comment]
> Version 3.0.5 removed allowing City and State to be entered to locate airports. In the process, I cannot lookup KDAB ident either.

No it did not. Read the changelog it is explained there.
![grafik](https://github.com/albar965/littlenavmap/assets/15254956/63c596aa-1a1b-4b31-9912-cfcaddd2d3c9)
![grafik](https://github.com/albar965/littlenavmap/assets/15254956/bd2fba9c-959e-4344-a74c-308baf7872f8)
![grafik](https://github.com/albar965/littlenavmap/assets/15254956/fbffde2c-cb03-4be0-8808-adf2f5ee90e9)
