### ISSUE TITLE
Support TRACKs imported from SIMBRIEF

### ISSUE THREAD

**Issue by xwing007** [albar965/littlenavmap#1110]
When I open FP from Simbrief, that contains any NAT, I get error :Nothing found for NATx. Ignoring.
I mean "x" as the NAT designation.
Is there any support for NATS form the SIMRIEF ?

**Comment by xwing007** [comment]
![NATs](https://github.com/albar965/littlenavmap/assets/12469764/6534da19-8d95-429c-b145-0a01f4eb9d6c)

**Comment by albar965** [comment]
Interesting and unusual. NATF as shortcut for the track points. Never see this but looks about doable.

Do you also have an example for PACOTS?
Can you post the string after `Route Description` as text` This saves me typing it off the image. :slightly_smiling_face: 
You can simply copy and paste from the dialog window

**Comment by xwing007** [comment]
> Do you also have an example for PACOTS?

No, The Simbrief supports the NATs shortcuts only.

**Comment by albar965** [comment]
> No, The Simbrief supports the NATs shortcuts only.

Ok. Thanks. Did not check, therefore: Isn't there any option in SimBrief to get the NAT waypoints instead of the NAT name?

**Comment by xwing007** [comment]
I read the user guide and there is only short description about NATs.
[](https://dispatch.simbrief.com/guide#route-formats)
`For oceanic flights, [North Atlantic Tracks (NATs)](https://en.wikipedia.org/wiki/North_Atlantic_Tracks) can be entered as airways in the route string. For example, NATU stands for Track Uniform in the following route: GREKI JUDDS MARTN TOPPS N557A NEEKO NATU GISTI SLANY UL9 STU P2 BEDEK BEDE1H`

**Comment by albar965** [comment]
Thanks.

**Comment by xwing007** [comment]
BTW... The RFINDER also uses these shortcuts ;-)
