### ISSUE TITLE
error decode earth_awy.dat in X-Plane

### ISSUE THREAD

**Issue by Eyderoe** [albar965/littlenavmap#1111]
Dear albar965:
holp you might fix
in AIRAC2312 (lnm 3.0.3 rc1) from EVMON to PAPAL via Z8
Z8 was mis-decoded with high instead of low
sorry in Chinese but i choose (show high awy only)
follow xplane AWY1101 1 for low and 2 for high
and I choose no navigraph to ensure data 100% from xplane 
greeting
![image](https://github.com/albar965/littlenavmap/assets/103725178/e54177e3-88c8-43d1-b9ec-3bfa93ac4ae7)
![image](https://github.com/albar965/littlenavmap/assets/103725178/4872b1c9-4e49-43a8-b0c4-9b0fba2c58b4)
![image](https://github.com/albar965/littlenavmap/assets/103725178/0765412b-9d84-49ef-907f-0e3b6dd7dab5)
![image](https://github.com/albar965/littlenavmap/assets/103725178/c284ea8f-4831-42cd-a695-ed0e0d6da6ee)

**Comment by albar965** [comment]
Will check. Gimme a few days.

**Comment by Eyderoe** [comment]
thanks and here attach files
[airway.zip](https://github.com/albar965/littlenavmap/files/14636997/airway.zip)

**Comment by albar965** [comment]
Hopefully fixed. Fortunately this did not affect the Navigraph compiler.
Navigraph cycle 2402 is ok. The error showed up when reading X-Plane data.
![grafik](https://github.com/albar965/littlenavmap/assets/15254956/a896129b-6563-49c3-99ea-f1b8d7f84681)

**Comment by albar965** [comment]
And thanks for reporting! :+1: 
I would never have found such an error.

**Comment by Eyderoe** [comment]
I write some data about procedure, airway, ... . Some of them not work as expected, so I report it

**Comment by albar965** [comment]
This release candidate for 3.0.6 should fix the issue: https://k00.fr/3liopl2z

Alex
