### ISSUE TITLE
Update database airports

### ISSUE THREAD

**Issue by mikoulprostgrandprix** [albar965/littlenavmap#1116]
Hello,

Can the airport database be updated using the ourairports.com source?

regards
Mikoul

**Comment by albar965** [comment]
Sorry, nope. Why if there is already the simulator as airport source?

**Comment by mikoulprostgrandprix** [comment]
Exemple
For airports such as : 
https://flightsim.to/file/69805/ywoh-wongan-hills-wa

This one is not referenced on little navmap.
But it is already present in ourairports :
https://ourairports.com/airports/YWOH/


There must be something I'm forgetting to do to add it to little navmap!

The same applies to all the heliports I've added.
Thanks for your help.
Regards

**Comment by albar965** [comment]
Add airport to `Community`, reload LNM scenery library and there it is:
![grafik](https://github.com/albar965/littlenavmap/assets/15254956/e1c763bd-1789-4081-a5b0-d9e59c3c4002)

Mixing the database of Ourairports and others wouldn't be doable at all. 
But it seems a nice free alternative for a navdatabase.
