### ISSUE TITLE
Gate label ambiguity across zoom levels

### ISSUE THREAD

**Issue by vocux** [albar965/littlenavmap#1119]
Hello! First of all thank you so much for this amazing program!
I realize that in a recent version it was implemented that you can now see the full Gate Labels on the map (for example "Gate A 22"), which is really wonderful, I now don't need to hover over a gate in order to get the gate letter from the tooltip before selecting a gate in GSX. Thank you for that! 🥳

However if I may make a suggestion:
I noticed that this label is represented differently depending on the zoom level. Sometimes a "G" is prepended as an abbreviation for the word "Gate". Like this:

![Screenshot 2024-04-03 011052](https://github.com/albar965/littlenavmap/assets/16946635/a0fabc80-2d2d-47a6-b996-0c3aa9ade071)

Zoomed-out:
![Screenshot 2024-04-03 011056](https://github.com/albar965/littlenavmap/assets/16946635/a0faeecc-ea7d-466c-9bef-b0f46f4176c7)

This "G" however is ambiguous in a way that it could also represent a G Gate (Golf Gate):

![Screenshot 2024-04-03 011337](https://github.com/albar965/littlenavmap/assets/16946635/69330826-7425-49b1-a1ed-b2f51043a70f)

Zoomed-out:
![Screenshot 2024-04-03 011332](https://github.com/albar965/littlenavmap/assets/16946635/dcfbf615-8bdd-415e-9f0f-9978fc70c768)

So while now I don't need to hover over a gate to read the tooltip, I instead need to zoom in in order to determine if a gate I see is Gate 14 or Gate G14.

Could the labels be implemented in a similar way they are implemented for taxiways, so displaying either the full identifaction of the gate ("A10" for Gate A10 and "10" for Gate 10) or nothing at all; so no abbreviation of any kind? I do get the intent of trying to display as much info as possible on a given zoom level but in a current state this ambiguity outweighs the pros of the full gate labels a bit in my opinion.

Best wishes! 😊

**Comment by albar965** [comment]
This is a compromise I have to do when compressing gate numbers. Not doing this would terribly clutter up the airports.

Depending on name and zoom distance you will already see `Gate A10` shortened to `A10`.
I don't see the ambiguity as a big problem and I'm afraid there is not much room for improvement.

**Comment by vocux** [comment]
Thanks for your reply! 😊
I think there was a misunderstanding at some point, my problem isn't the compression of the gate labels overall, it's that the word "Gate" sometimes (but not always) gets compressed to "G", as is "Golf". So you can't tell if "G10" means "Gate 10" or "Gate Golf 10".

I was just asking to keep the same compression behaviour but to just remove the compression of the word "Gate" to "G" entirely and only compress
"Gate 10" to "10" (and never "G10")
and only "Gate G 10" to "G10"

That would solve any ambiguity and clutter the airports even less!

**Comment by albar965** [comment]
There are hardly an Golf gates. 

I also have to compress the gate and parking names of X-Plane which are partly really trash.
Sorry, won't changed.
