### ISSUE TITLE
Flight Plan Route Description dialog box always loads in the monitor opposite of the one where Little Navmap is loaded

### ISSUE THREAD

**Issue by e8vww** [albar965/littlenavmap#1120]
macOS 10.13
Little Navmap 3.0.5

The Flight Plan Route Description dialog box always loads in the monitor opposite of the one where Little Navmap is loaded. How do I make it so the Flight Plan Route Description dialog box always appears on the SAME monitor as the rest of the app?

**Comment by albar965** [comment]
You cannot change this. I'll see if I can fix this for the next update and open the window always centered on top of the main window.

BTW: 3.0.6 is the latest: https://albar965.github.io/release/2024/03/31/littlenavmap-stable-306-released.html

**Comment by e8vww** [comment]
Oh ok I didn't know that. I think there is a provision in macOS to "move all to monitor X" for example under chrome or firefox, the Window menu has this option. very useful for multi-monitor setups when the other monitor might be a tv that isn't turned on.

**Comment by albar965** [comment]
Thanks. Good to know. :+1:
