### ISSUE TITLE
bug report & new function request

### ISSUE THREAD

**Issue by Eyderoe** [albar965/littlenavmap#1121]
bug report: a bug about simulator in logbook
lnm ver. 3.0.3rc1
it seems that the simulator is based on the scenery library simulator(I'm not sure) instead of the simulator you are playing
here are my records
and i even have no xp12 on my computer 
so i guess that this may cause by i choose xp12 here ?
hope fix
![image](https://github.com/albar965/littlenavmap/assets/103725178/c4af98dd-cccb-4b68-aea7-df674bff158a)
![image](https://github.com/albar965/littlenavmap/assets/103725178/1fb37bf3-a0e9-4fa4-bc0f-d76411c0a02f)

--------------------------------------------------------------------------

function request: show the lines between citys which you fly one to another just like volanta
its a simple but pretty cool function, isnt it
![image](https://github.com/albar965/littlenavmap/assets/103725178/9c67a91c-8a76-49b4-98f0-ed836c1c4b97)

**Comment by albar965** [comment]
This sim entry in the logbook is normal. A lot of functions like weather file locations and more depend on the scenery library selection. No matter if the sim is installed or not. Detecting the sim from the connection is a bit too much overhead. No idea how to find the difference between P3D versions or FSX vs. FSX Steam, for example.

You can also look at the flown airports in LNM by selecting the logbook entries in the table.
Here is a sample of all flights from Norway to Germany (filter EN and ED:
![image](https://github.com/albar965/littlenavmap/assets/15254956/8ff75565-cc79-4164-91c4-5be54474257f)

**Comment by Eyderoe** [comment]
thanks
and is there a way to close the label of ICAO Ident and distance ? 
![image](https://github.com/albar965/littlenavmap/assets/103725178/cd20771b-8baa-4bef-966b-f50817040639)

**Comment by albar965** [comment]
> and is there a way to close the label of ICAO Ident and distance ?

Sorry, nope. I might add this to the context menu to speed up the display with many lines.

**Comment by Eyderoe** [comment]
thanks and have a good night (
