### ISSUE TITLE
Strange mapping

### ISSUE THREAD

**Issue by yougoup** [albar965/littlenavmap#1122]
On the afternoon of April 8, 2024, around 16:30, a lot of strange data suddenly appeared on my software map, as shown below. I thought it was an abnormality in my data. It took me a long time to confirm the cause of the problem. Finally, I found out that it was related to time. The problem occurred during this time period of the day. I changed it to other times and there was no problem. This problem really bothered me. feel strange.
![image](https://github.com/albar965/littlenavmap/assets/11360401/6b950a65-a559-400d-b68f-63729b4c51b9)

Key point: There is a problem on this day, 20240408, and the time period is approximately between 16:30 and 17:30. This time period is my testing time. This problem does not exist whether forward or backward one day.

**Comment by albar965** [comment]
This is from the Marble widget which does more unwanted stuff like showing the Eclipse path than expected. I'll see if I can disable this but I doubt it. This is baked into the Marble widget which is not my code.

**Comment by albar965** [comment]
Removed all Sun/Moon eclipse related code from Marble but could not reproduce and neither test this.
