### ISSUE TITLE
crash report 

### ISSUE THREAD

**Issue by Eyderoe** [albar965/littlenavmap#1123]
Dear albar:

This crash can be reliably triggered.
it will crash when change database 
for me:
1. use xp11 database
2. select an airport and its procedure
3. use xp12 database (sometimes crash here)
4. select an airport and its procedure (sometimes crash here).
here's the report and last one is in en. 
[little_navmap_crashreport.zip](https://github.com/albar965/littlenavmap/files/14929421/little_navmap_crashreport.zip)
----------------------------------------------------
may be bug report ?
unistall little navmap when lnm is still running
the software will still run and the folder will not be delete

sincerely, Eyderoe

**Comment by albar965** [comment]
Thanks. I'll check the crash.

About the uninstall: I'll try to detect the running application. Have to see how to do this.

**Comment by albar965** [comment]
Sorry but ZPDQ has no procedures here. Maybe I need a custom ZPDQ.dat file?

**Comment by albar965** [comment]
I found some issues where a wrong airport was selected after: 
1. Use XP12
2. Show procedures for ZUCK
3. Select XP11
4. Restart LNM.
As a result the procedure selection showed "no airport selected" but still a tree of procedures. 

This might fix your crash but I'm not sure. I can only reproduce the inconsistent behavior but not the crash.

**Comment by Eyderoe** [comment]
fine 
now I crash with ZUCK ( hmmm...
here's report
[little_navmap_crashreport.zip](https://github.com/albar965/littlenavmap/files/14932396/little_navmap_crashreport.zip)

**Comment by albar965** [comment]
This might happen because the airport is in the Navigraph database but missing in one of the simulators.
I'll send you a build once I have something to test.

**Comment by Eyderoe** [comment]
it seems that only I have this problem ? lol
and i'm willing to try new build (
I test in VNKT VELR ZUCK ZPDQ ZUUU and all lead to crash.
ZUCK(mark CKG in xp11, ZUCK in xp12), VELR(never changed between xp11 and xp12), ...
and obvious these airports exist in (navigraph, xp11, xp12)
win10 22H2 family ver with latest lnm

thanks a lot ,and have a good day

**Comment by albar965** [comment]
> it seems that only I have this problem ? lol

This happens for airports which do not exist in XP11 but in 12 or vice versa. The procedure search was not correctly updated and remained in a half-initialized state resulting in crashes sooner or later.

Did you install additional procedures manually in X-Plane?

**Comment by Eyderoe** [comment]
install additional procedures means sid star appr procedures?
i add some, but I choose **all navigraph data** to test, result  in same.
many airports both exist in xp11 and xp12 can triger crash (hmmm...

**Comment by albar965** [comment]
Try this here: https://k00.fr/ca0o2ubp
I hope this fixes the issue.

**Comment by Eyderoe** [comment]
I'm sorry in inform you : nope 
[little_navmap_crashreport.zip](https://github.com/albar965/littlenavmap/files/14941296/little_navmap_crashreport.zip)

**Comment by albar965** [comment]
Meh. It blows up somewhere in the procedure search dialog code. I cannot reproduce this here. No matter how often and on what OS I try. I also tried with your settings from the ini file but no avail.

Can you send me any ZUCK.dat or other CIFP files you're using?
Is the airport an add-on? If yes, can you send me the apt.dat if possible?
What are the settings in the Scenery Library menu? You already mentioned "Navigraph for all" on XP11 and XP12?

**Comment by Eyderoe** [comment]
nope, I can crash lnm with any airport lol. and i never add a airport by myself (just download xplane)
hmm.. here crash in VNKT
[VNKT.txt](https://github.com/albar965/littlenavmap/files/14944786/VNKT.txt)
just let the bug go, because it just happen after change database
or maybe one day I will told you if I find what cause it (probably not)
--------------------------------------------------------------
now I hope lnm may autosave at sometimes (eg. calculation enroute, select departure or arrival airports, ...), such key points,

**Comment by albar965** [comment]
BTW: I found a solution to avoid uninstall or install with running LNM.

**Comment by Eyderoe** [comment]
is it impossible to add a sub menu to let user to choose when output gpx trail ? (whole trail or just in flight)

**Comment by albar965** [comment]
> is it impossible to add a sub menu to let user to choose when output gpx trail ? (whole trail or just in flight)

Sorry, not really. I'd rather work on a way to record the startup and taxi too. But this will require the user to trigger the start of a flight in LNM manually.

**Comment by Eyderoe** [comment]
thanks
