### ISSUE TITLE
Feature Request: show multiple procedure at same time

### ISSUE THREAD

**Issue by Eyderoe** [albar965/littlenavmap#1124]
show multi-procedures at same time (by press ctrl or shift)
useful in the airport which have many procedures to one waypoint (4/5 or more)
and different procedure can mark with different color
![image](https://github.com/albar965/littlenavmap/assets/103725178/b51b6625-2857-4a48-8f17-c9686e798594)
![image](https://github.com/albar965/littlenavmap/assets/103725178/bd2d9abe-9eef-4ed9-8959-6374881412b1)

thanks

**Comment by albar965** [comment]
Already there 

https://www.littlenavmap.org/manuals/littlenavmap/release/latest/en/SEARCHPROCS.html#preview-all-procs

![image](https://github.com/albar965/littlenavmap/assets/15254956/66099ed1-e310-4a10-aa27-f6ed84d850ce)

**Comment by Eyderoe** [comment]
pretty cool，thanks

**Comment by Eyderoe** [comment]
hmmm...
I forget eosid (most time like ga track) 
so, its different from a sid (end in different point)
may add a function to select with ctrl or shift?
thanks

**Comment by albar965** [comment]
> I forget eosid (most time like ga track)
> so, its different from a sid (end in different point)
> may add a function to select with ctrl or shift?

As far as I remember I get no engine-out SIDs in the Navigraph data or X-Plane. But I have to check to be sure.

**Comment by Eyderoe** [comment]
yep youre right
there‘s no eosid encode in navigraph
but lnm can read local database so you can write procedure from your company charts and so on

**Comment by albar965** [comment]
Sorry, but this would not be worth the effort for such a rare case. :man_shrugging: 
Procedures are an insanely complex topic.

**Comment by Eyderoe** [comment]
sorry I thought the workload wont too much
