### ISSUE TITLE
Sun shading seems to be later than reality

### ISSUE THREAD

**Issue by malaise** [albar965/littlenavmap#1125]
LNM is connected to XP11, which is in real time.
It is 18:15 local time CEST and 16:15 GMT, so we are far from the sunset. 
Still, LNM shows that we are in the night.
![Night](https://github.com/albar965/littlenavmap/assets/588474/89a7b19e-5ca8-4d4f-9ccf-f197181cef52)

**Comment by malaise** [comment]
Well, this seems to be fixed after starting a new flight (without restarting XP11) 
So this is probably a defect in XP11
![NightOk](https://github.com/albar965/littlenavmap/assets/588474/f08f31bc-2a06-48de-b883-34ebbcbbaca8)

**Comment by albar965** [comment]
I'll check but I've not seen a problem so far. 

LNM will use current UTC but switch to simulator date and time as soon as it is connected and aircraft is loaded. Maybe this was the issue?

**Comment by malaise** [comment]
Well this is quite reproducible
![Night1](https://github.com/albar965/littlenavmap/assets/588474/b84cf8bb-2737-49dc-bb8f-595ac1225af4)

**Comment by malaise** [comment]
And some minutes later this is correct!
![NightOk](https://github.com/albar965/littlenavmap/assets/588474/c747d882-cfb1-4258-8b57-540faa678e16)

**Comment by albar965** [comment]
Still cannot reproduce it, sry. 

Starting LNM with `View` -> `Sun Shading Time` -> `Simulator time`. Shading is correct. 
Start X-Plane with real time tracking and LNM connects. Shading does not change and is still correct.

I'll keep an eye on it.

**Comment by malaise** [comment]
And some minutes later this is correct!
![NightOk](https://github.com/albar965/littlenavmap/assets/588474/c747d882-cfb1-4258-8b57-540faa678e16)

**Comment by malaise** [comment]
Me too.
For the general scenario: I can clarify that I start LNM and then XP11 in the morning, I don't stop them, and I observe the problem in the evening.
I will try to identify if the lag is present at the beginning of if it develops progressively.

**Comment by albar965** [comment]
Thanks for the hint @malaise . I'll check if there is something going wrong over time. I'm already suspecting Marble not updating properly.

**Comment by malaise** [comment]
This evening the problem occurred again (despite I restarted XP11 at noon). 
LNM shading was approx 2-3 hours later that expected. Unfortunately I didn't capture the issue.
But I restarted LNM and the shift was even worth, approx 6hours (capture attached).
![Restart](https://github.com/albar965/littlenavmap/assets/588474/d587f9d5-3df4-4625-897d-d1c2b9b0bd4b)

**Comment by malaise** [comment]
I disconnect LNM from XP11 and the shading becomes correct.
I reconnect it and the shading is wrong gain (as the attachment above).

**Comment by albar965** [comment]
I'll check this but for now I'd like to finish another task.

**Comment by albar965** [comment]
Attempt to fix but could never reproduce it.

**Comment by malaise** [comment]
I experimented it today, with LNM 3.0.8, then it resolved naturally (no restart needed).

**Comment by albar965** [comment]
> I experimented it today, with LNM 3.0.8, then it resolved naturally (no restart needed).

Good to know. Thanks for the feedback. :+1:

**Comment by malaise** [comment]
Not solved in 3.0.9. 
@
![KO](https://github.com/user-attachments/assets/aae4e88f-576e-46a3-bb16-4e12a8004f0f)
I start XP11 and LNM at around 17:40 UTC and LNM shows this.

**Comment by albar965** [comment]
Sorry, could never reproduce this. :shrug: 
Flying XP11 a lot wish shading enabled and it looks always correct.

**Comment by malaise** [comment]
I still reproduce it from time to time... Here are some captures when it is OK and when it fails.
I could check anyway that LNM displays the correct simulator time.
Is there any extra test or log that I can make to help the analysis?

<img width="453" height="114" alt="Image" src="https://github.com/user-attachments/assets/c43cafff-1c51-4bfc-8d92-b24146971412" />
<img width="393" height="106" alt="Image" src="https://github.com/user-attachments/assets/9ab3c69c-8442-4c9d-866a-0c021f7a9a0f" />
<img width="1291" height="1023" alt="Image" src="https://github.com/user-attachments/assets/575a4b32-6db5-46e2-b3b5-81d7b4acdc7d" />
<img width="874" height="604" alt="Image" src="https://github.com/user-attachments/assets/4eb9689b-239b-43aa-9f58-e5a9d3ab5d89" />
<img width="883" height="607" alt="Image" src="https://github.com/user-attachments/assets/bb39dcae-3c09-423d-8dc4-2bcad7c44267" />

**Comment by albar965** [comment]
Thanks for the screenshots. I'll have a look but it is difficult if I cannot reproduce it here.

**Comment by malaise** [comment]
Correction: As shown in the "KO" screenshots, LNM does NOT show the correct UTC time
LNM 5:20PM versus XP11 15:20

 (the local time is correct 4:20PM = 16:20)

**Comment by malaise** [comment]
Reproduced with XP12.
This capture shows the OS local and UTC time. The times displayed by XP12 are correct, but LNM seems to add 1h to local time (in order to compute UTC time) instead of substracting 1h.

<img width="1129" height="131" alt="Image" src="https://github.com/user-attachments/assets/104f2abd-456e-49ce-81fa-cbd42b9f20f1" />

**Comment by albar965** [comment]
What are the settings in XP12 when this happened? Real time? Offset to UTC added?

**Comment by albar965** [comment]
Also what position?

**Comment by malaise** [comment]
> What are the settings in XP12 when this happened? Real time? Offset to UTC added?
No, like in the previous captures: Track real-world date and time
>Also what position?
Close to Sevilla, which is at GMT+1. XP is correct  (its local time is UTC+1) and LNM shows "UTC-01.00".
After moving XP to Toulouse (also GMT+1) XP time is unchanged but LNM time becomes correct (UTC+1).

**Comment by albar965** [comment]
Hopefully fixed by adding a timezone database which now allow correct decoding of X-Plane time information.
