### ISSUE TITLE
Regression in flight plan drawing

### ISSUE THREAD

**Issue by oleesch** [albar965/littlenavmap#1126]
I noticed a regression when drawing flight plans after updating to 3.0.6 from 3.0.5. 
In certain scenarios, flight plans aren't drawn anymore at higher zoom levels. See the following screenshots:

**Drawing OK**
![Drawing OK](https://github.com/albar965/littlenavmap/assets/2054264/9d9fe7fd-9ce2-48e2-b782-60d306ac95ff)

**One zoom level higher - Drawing not OK**
![Drawing not OK](https://github.com/albar965/littlenavmap/assets/2054264/8cd7a08d-66f9-492b-8153-1a18c0d478e2)

This does not happen when using 3.0.5 with the same flight plan: [Demo-Path-Drawing.zip](https://github.com/albar965/littlenavmap/files/15221139/Demo-Path-Drawing.zip)

I've tried clearing all settings by renaming `C:\Users\YOURUSERNAME\AppData\Roaming\ABarthel`, same behavior.

Running Windows 11 23H2 (OS Build 22631.3447).

**Comment by albar965** [comment]
Thanks for the example. Another user reported this with large flight plans. I'll fix this for 3.0.7.
The same issue appears with long aircraft trails.
