### ISSUE TITLE
Export to KLN 90B

### ISSUE THREAD

**Issue by p0lfilt3r** [albar965/littlenavmap#1136]
Dear albar965,

could you please add the export to the KLN 90b?

see
https://github.com/falcon71/kln90b/wiki/FAQ#fpl-file

**Comment by albar965** [comment]
Do you have an example file for the `kln.fpl`?

I know several fpl formats having a different layout (XML, INI, Garmin, etc.) and neither the KLN wiki nor the code have an example.

**Comment by p0lfilt3r** [comment]
It is the same as for the PMS50 GTN750. Just a different folder and a different name.

The info file in the folder of the KLN 90B says:
> _"You can load a .fpl file this way:
> - Put a kln.pln into this folder. The name must be kln.pln, any other file will not be recognized.
> - Go to the SET 10 page, press IMPORT FPL and follow the dialogue
> 
> The kln.pln file must be a valid FS2020 flight plan file. These files can be generated using Little Navmap or Simbrief. 
> If you receive an error, please check if the file is a valid FS2020 flight plan file."_

[kln.zip](https://github.com/user-attachments/files/15526380/kln.zip)

(had to zip it because github doesn't accept fpl-files as attachement)

**Comment by albar965** [comment]
Thanks. This looks like a normal MSFS PLN file. To be more precise the same as PMS50 GTN750.
Will add for 3.0.7.
