### ISSUE TITLE
LNM recognizes airport to have procedures but nothing displayed

### ISSUE THREAD

**Issue by ChrisXPP** [albar965/littlenavmap#1154]
Hi @albar965 ,

when I tried to show the procedures for Weston airfield in Ireland (ICAO: EIWT) which had been added with AIRAC 2406 I noticed LNM correctly recognizes the airport to have procedures (with appropriate airport filter) but doesn't display anything on the map (see screenshot below), i. e. the procedures search tab is not available.
![EIWT_procedures](https://github.com/albar965/littlenavmap/assets/74152765/e8b4d17a-2ba4-460d-9c52-6f8df6a014f9)

As a comparison how this looks like for the nearby Casement AB (ICAO: EIME):
![EIME_procedures](https://github.com/albar965/littlenavmap/assets/74152765/5f820192-bfe1-44e8-8bb7-bb62aa3f3b76)

Windows 11 64 bit, LNM 3.0.6, XP 12.1.0

Kind regards,
Christoph

**Comment by ChrisXPP** [comment]
Nope, doesn't work here...
I reloaded LNM to match 2406 a second time, Navigraph is set to "select automatically", as well.
When I click on EIWT to retrieve the airport information the field "show procedures" is greyed out.
![selection](https://github.com/albar965/littlenavmap/assets/74152765/bfc018b1-f08b-492d-9f77-c2f8b4bf31f8)

**Comment by albar965** [comment]
Ok. Something is strange here. When I click on the airport with option `Show procedures on airport click` on option page `Map Tooltips and Clicks` enabled it shows procedures but the menu item is still disabled. Same for the buttons in the runway dialogs.

Enable `Show procedures on airport click` and try if the procedure shows.

The debug version can make a difference since I changed a lot in the procedure search tab. Next step is to check with 3.0.6.

Will fix. Thanks for the report!

Alex

**Comment by ChrisXPP** [comment]
Many thanks for looking into this!

Btw, your tip about the `Show procedure on airport click` did the trick, I finally got the VOR procedure to show up on the map...

![click_2](https://github.com/albar965/littlenavmap/assets/74152765/67f25974-eee1-4a4c-bc82-934207573b53)

But that's a bit tricky, you need to have the options to look like shown below:

![click](https://github.com/albar965/littlenavmap/assets/74152765/521fec54-9e13-4b5c-8281-8cc0030c1521)

If you untick the "airports" option here (cuz sometimes you don't want the airport info to automatically "blop up" when clicking on it) you will never receive the precise procedure information. And this could affect other airports, as well, I really coincidentally "stumbled" upon this issue.

**Comment by albar965** [comment]
> If you untick the "airports" option here (cuz sometimes you don't want the airport info to automatically "blop up" when clicking on it) you will never receive the precise procedure information. And this could affect other airports, as well, I really coincidentally "stumbled" upon this issue.

That's why I disable `Show procedures on airport click` when the airport is unchecked. 
Somehow this does not make sense. I can change this too.

Anyway, the menu should work as expected in the next release candidate.

Alex

**Comment by albar965** [comment]
Both fixed. Show procedure on click is now also working without airport info on click.
