### ISSUE TITLE
Question about restrict

### ISSUE THREAD

**Issue by Eyderoe** [albar965/littlenavmap#1157]
in this case, GG404 only has restrict in trans leg
and no restrict show on map.
its a bug or it should be.
thanks

![image](https://github.com/albar965/littlenavmap/assets/103725178/b5411f6f-7223-4d7d-a481-750c76629cca)

**Comment by albar965** [comment]
Does the restriction show up if you add it to a flight plan?

ZULS has no RNAV approaches here in 2406. 
Can you post the content of the file `ZULS.dat`?
Maybe an issue in the map display.

**Comment by albar965** [comment]
Ok. So problem solved? :wink:

**Comment by Eyderoe** [comment]
> Does the restriction show up if you add it to a flight plan?
> 
> ZULS has no RNAV approaches here in 2406. Can you post the content of the file `ZULS.dat`? Maybe an issue in the map display.

right, restrict appear after add it to flight plan.
and procedure do not exist in real world, just edit for fun.
thanks for your help

**Comment by albar965** [comment]
> right, restrict appear after add it to flight plan.

Thank you. it is normal that LNM shows some restrictions only after procedures and transitions are stitched together.

Alex
