### ISSUE TITLE
error decode FM leg 

### ISSUE THREAD

**Issue by Eyderoe** [albar965/littlenavmap#1170]
maybe ? I'm not sure
for example OEJN JEDA1C (AIRAC 2312)
course should be 3360 (336.0°)
and theta is 1558 (155.8°) (ARINC 424-18 5.24 Theta, bearing to waypoint from navaid)
![image](https://github.com/user-attachments/assets/c340bce4-694e-4d4a-a137-2166c49f30bb)
but in lnm detail
its 156 seem make a mistake with theta & magnetic course
![image](https://github.com/user-attachments/assets/01c1bbb3-6fae-404e-88e7-06879b9f436b)
and cause the procedure show map in wrong way
![image](https://github.com/user-attachments/assets/782664fa-2695-43ca-9e6a-73adbc1d1892)
![image](https://github.com/user-attachments/assets/1393fffc-1e10-4168-809c-23100fddb4ed)
attach chart
![image](https://github.com/user-attachments/assets/3e5553c2-a1e7-48e8-b3ce-3ff2c992912d)

**Comment by Eyderoe** [comment]
sorry this more like a encoding error

**Comment by albar965** [comment]
Not sure if this is an encoding error. Looks like a special case. the 180° turn should not happen. I see this with `OEJN/34L JEDA1C OEYN` for example.

Outbound course is always 336° M.

![image](https://github.com/user-attachments/assets/c3c08d9d-ba3f-4d38-a04c-c59950c629c6)

**Comment by albar965** [comment]
Yep. Maybe a coding bug or not but the depiction is ok. 156° after CA leg are like a 180.
