### ISSUE TITLE
import picture (chart) and show on map like simbrief [func request]

### ISSUE THREAD

**Issue by Eyderoe** [albar965/littlenavmap#1173]
1. import a picture
2. select two same waypoint (on map & on picture) manually in order to scale and move picture to right place
3. translucent picture 
![WMSA) V2IL 9MY{O4)ZIWFG](https://github.com/user-attachments/assets/df883e03-db7e-45c4-afe4-220130915df6)

**Comment by albar965** [comment]
Sorry, but unlikely to happen. But I keep it on the list.

**Comment by Eyderoe** [comment]
fine, thanks for reply
