### ISSUE TITLE
enhanced user fixs [function request]

### ISSUE THREAD

**Issue by Eyderoe** [albar965/littlenavmap#1179]
Dear Albar965,
hope enhance these below
1. user can choose whether show user wpts
![image](https://github.com/user-attachments/assets/91c6585f-d4c1-4583-8db4-2371b7674340)
i import the whole obstacle of a airport
sometimes may i need it (visual approach, circle land, eosid) and other time not(SID...)
![屏幕截图 2024-08-04 000152](https://github.com/user-attachments/assets/e5b9e72b-2690-4699-8147-605472f8ad3c)
2. scale
user fixs always same size 
and i prefer scale like waypoints
same size,
![image](https://github.com/user-attachments/assets/cce5569c-0774-43a4-a86f-697f7c6f6fc9)
much bigger,
![image](https://github.com/user-attachments/assets/9a002a30-f992-48ff-84ec-cf4122c15bbc)
3. name
usually name is much longer than ident
may only show here ?
![image](https://github.com/user-attachments/assets/a79ddd48-61b7-486f-b517-0318cd62ca3a)

sincerely, 
Eyderoe

**Comment by albar965** [comment]
> 1. user can choose whether show user wpts

Not sure if I undestand. A user can already do this in the userpoints:
![Bild](https://www.littlenavmap.org/manuals/littlenavmap/release/latest/en/_images/userpoint_overview.jpg)

> scale user fixs always same size and i prefer scale like waypoints same size,

Agree. I can scale the userpoint depending on zoom. Maybe even streamline it with similar map objects like userpoint waypoint and obstacle with waypoint. Userpoint airport with airport.

> name usually name is much longer than ident may only show here ?

I'd like to keep the name but I can see if I truncate it more for certain point types.

**Comment by Eyderoe** [comment]
yep, u are right
thanks for help

**Comment by albar965** [comment]
NDB and VOR userpoint sizes now depend on navaid sizes (VOR and NDB).
Userpoint types waypoint, obstacle and VRP depend on waypoint size and are smaller now.
The size still depends on the userpoint symbol size set on options page `Map User`.
![image](https://github.com/user-attachments/assets/8a580cfd-918d-4ed9-854b-c7ff70695b6e)

I'd rather not change the names. If you don't like to see the names on the map put them into the remarks section for now.

**Comment by albar965** [comment]
At 200 percent:
![image](https://github.com/user-attachments/assets/fb5c631a-3373-41d6-8e06-f7da4fa5378c)

**Comment by Eyderoe** [comment]
woo hoo !

**Comment by albar965** [comment]
> woo hoo !

You're welcome. :slightly_smiling_face:
