### ISSUE TITLE
Current AIRAC is 2408 - LittleNavMap is not updating.

### ISSUE THREAD

**Issue by danfly09** [albar965/littlenavmap#1181]
* Include your OS and version in detail like:
`Windows 10`

* Flight simulator and version like:
`MSFS2020`

* AIRAC cycle and navdata source if applicable:
 `Navigraph Cycle 2408`

* Provide all steps to reproduce the error like: Start program with empty database and load flight plan.

1. Not sure if it's only a display issue or an actual DB mismatch. 
2. `Validate Scenery Library Settings` says no issues found. 
3. Navigraph Hub says Cycle2408 is installed. It's also installed in the simulator and all addons (PMDG 738).
4. LittleNavMap says Cycle2407 is installed. 

![image](https://github.com/user-attachments/assets/fdb5c463-300e-4917-8121-bda8bc7f6640)
 
![image](https://github.com/user-attachments/assets/371d49e0-db4d-4376-9fc2-acdb4dc79522)

**Comment by albar965** [comment]
The FMS Data Manager sometimes install an update into the wrong folder or loses its binding. 

Also, if LNM is running during the update, the FMS Data Manager will silently skip the update.

See here: https://albar965.github.io/littlenavmap_navigraph.html

Alex

**Comment by albar965** [comment]
Closing due to missing feedback. Most likely FMS Navdata Manager issue.
