### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by UncleLiuYe** [albar965/littlenavmap#1182]
littlenavmap is a very good and convenient tool, I recently used Littlenavmap to make my own airport program, but every time I modified the data it takes 2-3 minutes to make the changes in littlenavmap, please ask whether to load the landscape into a kind of checkbox, if I only need to load the fix. dat then check fix.dat and the program will only load the data from fix.dat.

**Comment by albar965** [comment]
What simulator do you use? Do you ask to load airports or navdata (waypoints, VOR, etc.) separately?

What you can do is to exclude all or most scenery from loading in options on page "Scenery Library Database". Then
put your own into a separate folder and add this to include on page "Scenery Library Database"

**Comment by UncleLiuYe** [comment]
> What simulator do you use? Do you ask to load airports or navdata (waypoints, VOR, etc.) separately?
> 
> What you can do is to exclude all or most scenery from loading in options on page "Scenery Library Database". Then put your own into a separate folder and add this to include on page "Scenery Library Database"

I'm using the Xplane 12 simulator, I put waypoints in earth_fix.dat, the ils gs I wrote in earth_nav.dat, and the program I wrote in ICAO.dat under CIFP.

**Comment by UncleLiuYe** [comment]
For example, I am now ready to make its program for ZBCF, an airport, and every reload needs to load the whole thing, which takes 2-3 minutes on my machine, after that I excluded the default CIFP data, after that I excluded apt.dat, after that I excluded CIFP under Custom data, and now ZBCF doesn't have an airport drawn, how should I do it? What should I do to make Little nav map load only CIFPs related to ZBCF, because there are 15000 files under CIFPs, I tried to add them manually to the exclusion, but this will make Little nav map completely stuck.
![QQ20240819-092436](https://github.com/user-attachments/assets/b118af55-c2ab-4d35-a44d-ac0a3bc78618)

**Comment by albar965** [comment]
> I'm using the Xplane 12 simulator, I put waypoints in earth_fix.dat, the ils gs I wrote in earth_nav.dat, and the program I wrote in ICAO.dat under CIFP.

Sorry, but there is no way to load only the fixes or CIFP since there are too many cross-dependencies between fixes and procedures. The whole procedure topic is quite complex.
