### ISSUE TITLE
Would like to add aircraft performance data

### ISSUE THREAD

**Issue by Lightdasher360** [albar965/littlenavmap#1183]
I'd like to contribute aircraft performance data for the Hot Start TBM900 for X-Plane 11, but haven't found a specific place to do so. Where do we go to contribute?

**Comment by albar965** [comment]
Very good. All contributions are very welcome. :+1: 

Send it to me and I'll add it to the [LNM downloads section](https://www.littlenavmap.org/downloads/).
Here is my contact: https://albar965.github.io/contact.html

Alex
