### ISSUE TITLE
[minor edge case] airport search within radius incomplete around 180ºE/W

### ISSUE THREAD

**Issue by niobos** [albar965/littlenavmap#1184]
Hi,

First of all, thank you for your effort and time you put into this wonderful project. I really appreciate it.

I think I discovered a bug in the airport search when searching for airports within a certain distance of a center point when near the 180ºE/W meridian.

Steps to reproduce (LittleNavMap 3.0.9 on macOS):

1. Go to Alaska, and locate the airports PASY and PADK.
2. A flight between them is correctly calculated as 343NM.
3. Now search for airports within a distance of 500NM, Any direction.
4. "Set Center for Distance Search" near PADK. Notice that PADK is found, but PASY is not, even though it's only 343NM away.
5. Place the search cursor near PASY. Notice that PASY is found, but PADK is not.

It seems that the distance search is confused by crossing over the 180ºE/W meridian. Placing the search cursor on either side only finds the airport on that side.

I would like to stress that this is a minor bug with only very limited impact as it seems to only occur at the 180ºE/W meridian, which is very sparsely populated (both with people and airports)

**Comment by albar965** [comment]
Thank you for the report. I can confirm this. The anti-meridian is always problematic and I already fixed numerous bugs around it. Will fix for 3.0.10.

![image](https://github.com/user-attachments/assets/b8305729-f375-468e-99ee-553242456d43)

**Comment by albar965** [comment]
Fixed in a base function which means this potentially affected more functionality around the antimeridian.

**Comment by niobos** [comment]
Wow, that was fast! Thank you for the fix! I'm looking forward for the 3.0.10 release.
