### ISSUE TITLE
MSFS scenery: "newer" airport layouts load wrong

### ISSUE THREAD

**Issue by ngollan** [albar965/littlenavmap#1185]
OS: Win11 Pro amd64
Flight sim: MSFS with WU 18 (Germany/Switzerland)
AIRAC: 2401r1

After importing the new EDDM shipping with the latest MSFS World Update 18, it shows up very wrong

![image](https://github.com/user-attachments/assets/7e8151af-c2f8-4597-be82-23c01b21d36b)

and it is similar with LSZA; ESSA (last touched in WU15) appears to have a lot of the taxi grid missing.

Log: [abarthel-little_navmap.log](https://github.com/user-attachments/files/16894793/abarthel-little_navmap.log)

**Comment by albar965** [comment]
Thanks for the screenshot and the log file. Looking at the log it seems that this one is not encrypted.
I'll have a look but I'm not 100 percent sure if I can  fix this.

**Comment by albar965** [comment]
Sorry, debugged half a day through this mess and while other German airports of the same are ok (EDDS) this one is just completely broken. In general I've seen that Microsoft makes the worst structured airports.

It's not easier with the undocumented BGL format. :man_shrugging:
