### ISSUE TITLE
Traffic API to display traffic not from simconnect

### ISSUE THREAD

**Issue by whakamolenz** [albar965/littlenavmap#1187]
## If you'd like propose a new feature:

Hi there - i'm one of the devs for Beyond ATC - in our traffic injection solution we have traffic that is managed by BATC while injected to the sim but also at a greater range just in BATC and not the sim.

Would it be possible to introduce an API for traffic where we could inject traffic aircraft for display in little navmap that are not sourced from simconnect? We could then provide a full view of the traffic in BATC and inject values that simconnect doesn't allow for our style of injection (such as flight number, dep icao, dest icao)

Thanks!

**Comment by albar965** [comment]
Not sure if I have the time to maintain another API. I prefer to use the simulator APIs, SimConnect and the TCAS interface for X-Plane.

**Comment by whakamolenz** [comment]
Ok no problem - as noted BATC only injects into the sim aircraft in visual / TCAS range while still controlling those further out. So people can't see the full picture of traffic in LNM. But understand the position.
