### ISSUE TITLE
Feature request: auto sync scenery library between Navconnect and Navmap

### ISSUE THREAD

**Issue by michalboska** [albar965/littlenavmap#1188]
Hi, this manual is pretty clear about how to share the scenery lib between Flying PC and "Monitoring PC": https://www.littlenavmap.org/manuals/littlenavmap/release/latest/en/NETWORK.html

My question is, since those two PCs are connected via network anyway (Navconnect and Navmap talking to each other), why not just auto-sync the data between them? If Navmap discovers the "server" running Navconnect has something extra in its library available, it could auto download everything needed from the "server". (Navconnect can serve those files to Navmap).

**Comment by albar965** [comment]
I think #31 is the better solution. Simply create the library using LNM on the flying computer and then download it via Navconnect. This is doable using reasonable effort.

Putting all the scenery library code and user interface into Navconnect is too much effort compared to #31.

**Comment by michalboska** [comment]
Yes, that's exactly what I meant, the ticket is missing description however, so I couldn't find it.
Looks like this is a duplicate of #31, will close this.
