### ISSUE TITLE
littlenavmap found not a airport

### ISSUE THREAD

**Issue by BogusCurry** [albar965/littlenavmap#119]
Hello ;D
I have a little problem, when I search a airport, a sample EHAM or PANC. The programm not found this airports. What I make wrong ? 
I use the version 1.4.4 under Win7 64bit. 

Sorry for my bad englisch, I comes from germany.

Have a nice Day ;D

Bogus

**Comment by albar965** [comment]
Hallo Bogus,

schicke mir bitte eine email. Die E-Mail Adresse findest Du im Programm
im Dialog "About". Menü: "Help" -> "About Little Navmap"

Grüße

Alex


Am 01.09.2017 um 01:16 schrieb Bogus curry:

**Comment by albar965** [comment]
Problem caused by an additional entry in the exclude options. Fixed.
