### ISSUE TITLE
This Release doesnt working yet " SBRJ EVKO3A.NAXOP UZ45 IBDA1A SBSP " 

### ISSUE THREAD

**Issue by dunham94** [albar965/littlenavmap#1194]
# Fixed issue with dropped airway information. This affected plans that have only one leg between departure and arrival. As a result an airway was dropped on saving, exporting and using it in the flight plan route description. Example: SBRJ EVKO3A.NAXOP UZ45 IBDA1A SBSP resulted in SBRJ EVKO3A.NAXOP IBDA1A SBSP.

This Release doesnt working yet !

I just tested the new Release and it still bugs when I press Calculate. I did the following:

- I set the altitude to 27,000 FT
- I clicked on "edit route description"
- I wrote ''SBRJ SBSP"
- I created a flight plan
- I set the departure chart for SBRJ - EVKO1F.NAXOP.
- Then in SBSP, I set the Arrival to "STAR OGTA1A.IBDAL."
- I clicked on the button "show flight plan calculation window"
- I pressed calculate
- Airway still doesn't appear

I still don't know what the error could be.

![image](https://github.com/user-attachments/assets/5af4f254-8db5-48c0-879a-442fb9103da8)

![image](https://github.com/user-attachments/assets/1e8c5508-471f-4456-a037-ad6d0a56d4b0)

**Comment by albar965** [comment]
No problems here:
![image](https://github.com/user-attachments/assets/0224122d-b197-4f41-b4cc-a9c0d8b86ee7)
And I could clearly reproduce your report before with 3.0.9.

Calculation was set to use 100 percent airways (slider to the left). Database is X-Plane 12 and cycle 2409.

I'll check if this is affected by settings or maybe OS. Can you send me an issue report? Menu `Tools` and then follow instructions in the dialog window. Maybe this is broken because of a certain configuration option you use.

**Comment by albar965** [comment]
Calculation:
![image](https://github.com/user-attachments/assets/aa4108ed-1c30-4c76-849d-ba004895e602)

**Comment by Eyderoe** [comment]
yep ,airway have some wrong still.
cycle :2312 ver:3.0.10rc1 setting: all navigraph
cant get a route from ZULS-RKZ ~ PR888-VQPR
![image](https://github.com/user-attachments/assets/9fb0f0c7-532f-4a6b-996d-2061afef34b0)

**Comment by dunham94** [comment]
Mine try :

![image](https://github.com/user-attachments/assets/e99d3326-4f6d-4c63-86ba-06185b98c72b)

![image](https://github.com/user-attachments/assets/be344c4e-6b4b-4678-98a9-5a79a6e0f926)

![image](https://github.com/user-attachments/assets/d3b1a6bc-6505-4dc3-97a8-708ea5fd1d22)


didnt show the Airway
Its with bug yet !

**Comment by albar965** [comment]
> didnt show the Airway
> Its with bug yet !

Did you check the flight plan table? It's shown as I highlighted in my screenshots. Also, the airway label on the flight plan line on the map is optional. You have to enable this first in options -> map labels.

Your flight plan in the table is also different to the first one reported. Anyway, this is working too here:
![image](https://github.com/user-attachments/assets/ad42f18c-7506-43fc-b3e3-6c1bec5bb8f2)
For not stick to `SBRJ EVKO3A.NAXOP UZ45 IBDA1A SBSP`.

Please expand the flight plan table. Important information like the airways are not visible on your screenshot. Disable unneeded information since it is too cluttered to see something.

If it still does not work: **Give me the exact steps you do to reproduce the issue. Every button your click and every menu item you select. Show me a screenshot with the full flight plan table and the program window title.**

**Comment by albar965** [comment]
> yep ,airway have some wrong still.
> cycle :2312 ver:3.0.10rc1 setting: all navigraph
> cant get a route from ZULS-RKZ ~ SUBSU-VQPR

![image](https://github.com/user-attachments/assets/d89ce4dc-086f-4a57-88ce-942a06a18f7f)

The calculation will no always give perfect results. There was a lot of tweaking going on.

**Comment by dunham94** [comment]
Dude !!
 I've been racking my brain over this for hours and I can't figure it out! You'd be a lifesaver if you could make a video showing me how you do it. I've tried exactly what you told me, but it's not working.
 
- First, I'm not seeing the option > map label
- I'm not going to do the route directly like you did, I closed it up to LNM and nothing, I can't do it!

**Comment by dunham94** [comment]
https://github.com/user-attachments/assets/1f1a795e-343e-40f0-85ef-ae6ac0650741

Take a look at the way I'm doing it, it's very strange!

**Comment by dunham94** [comment]
https://github.com/user-attachments/assets/50947820-d76d-4154-8a91-5e418e33c5ad

refis as you said, adjusting the options, it still remains in the error, it does not set UZ45. It still remains in the bug

**Comment by albar965** [comment]
> tentativa_2_resized.mp4 
> redo as you said, adjusting the options, it still remains in the error, it does not set UZ45. It still remains in the bug

Thanks for the videos.

The routing algorithm won't use UZ45 since this route is longer. Still, it uses an airway as expected.
You can partially change this by using the slider but not in this case.

I'd not consider this an error if it uses another than the expected or official airway.

**Comment by Eyderoe** [comment]
sorry I may not express clearly due to old data
I mean :
ZULS (SID to IKUBI) 
to
VQPR (STAR from SUSBU)
cant create a route

**Comment by albar965** [comment]
> redo as you said, adjusting the options, it still remains in the error, it does not set UZ45. It still remains in the bug

Moreover the MSFS airway system is quite a mess as it is coded in the BGL files. You'll always get better results using the Navigraph update. Sorry, I cannot fix this.

**Comment by albar965** [comment]
> sorry I may not express clearly due to old data
> I mean :
> ZULS (SID to IKUBI)
> to
> VQPR (STAR from SUSBU)
> cant create a route

There are no close airways between IKUBI and SUSBU. The route calculation does not use such a huge detour.

![image](https://github.com/user-attachments/assets/3b174817-5d6d-465b-8b72-ec2ba80e86df)

**Comment by albar965** [comment]
Gents:
If route calculation does not work your can build your plan manually. Simply enter departure, destination, waypoints and airways in the flight plan route description and create the flight plan.
This is a bit work but not too much for such small routes:
![image](https://github.com/user-attachments/assets/c1e55dc6-7a53-4406-b5fc-f1a8aad9462b)

**Comment by Eyderoe** [comment]
thanks for answer
may i ask why cant create such route 
![image](https://github.com/user-attachments/assets/64b6a1d8-ae2d-47c9-a980-49ac9ca86423)

**Comment by albar965** [comment]
> may i ask why cant create such route

In general you have to manually create one if the auto route does not work in such cases.
You also use an older AIRAC cycle. Maybe airways changed.

**Comment by Eyderoe** [comment]
thanks

**Comment by 6639835** [comment]
> No problems here: ![image](https://private-user-images.githubusercontent.com/15254956/369710452-0224122d-b197-4f41-b4cc-a9c0d8b86ee7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NzYwMjMsIm5iZiI6MTcyODk3NTcyMywicGF0aCI6Ii8xNTI1NDk1Ni8zNjk3MTA0NTItMDIyNDEyMmQtYjE5Ny00ZjQxLWI0Y2MtYTljMGQ4Yjg2ZWU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDA3MDIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3YzNiNDJlMGRmM2E1OTlkY2NkNWJmOTBjNzU2N2QwM2MxM2RiZjc4YWQ1NzlmOWIyOTU5Zjc1ZWU3ZmFmZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NPrnO2cbBkpVQzSIyanNRok3yQqRsws0wHIe_1nzMSw) And I could clearly reproduce your report before with 3.0.9.
> 
> Calculation was set to use 100 percent airways (slider to the left). Database is X-Plane 12 and cycle 2409.
> 
> I'll check if this is affected by settings or maybe OS. Can you send me an issue report? Menu `Tools` and then follow instructions in the dialog window. Maybe this is broken because of a certain configuration option you use.

Why your line is like this haha, it's like translucent

**Comment by albar965** [comment]
> Why your line is like this haha, it's like translucent

You can change this in LNM options:
![image](https://github.com/user-attachments/assets/c2dd288c-3eb0-4a40-abda-4893812520fc)
