### ISSUE TITLE
Flightplan Calculation - ignoring settings

### ISSUE THREAD

**Issue by Darnulf** [albar965/littlenavmap#1199]
Tried a Calculation KJFK - EDDF using primary airways and NAT in the selected options.

Neither is used and it routes via Iceland.

Selected KJFK as Departure
EDDF as destination both added to an empty flightplan.

Selected Calculate
from Departure to Destination
All Airways and NAT checked
preference on the 2nd notch from the left.

Regards
Dirk

**Comment by albar965** [comment]
The flight plan cruise altitude and the track levels have to match.

![image](https://github.com/user-attachments/assets/7c067eb2-bd23-4dfe-b89c-e29c6e13bd82)

Alex

**Comment by albar965** [comment]
Closing due to missing feedback.
