### ISSUE TITLE
Export to GFP and GTN750 issue

### ISSUE THREAD

**Issue by BROADACRES16xFS17MAP** [albar965/littlenavmap#120]
Hi,

I have been in touch with F1Flightsim in regards to an error being thrown when trying to import a plan into the GTN750. The plan is converted by littlenavmap. I create a flight in pfpx then use your program to change to a gfp. This was F1flightsim's reply.

_

> Ben,
> 
> Can you please show me the flight plan created with the planning software?
> Since this is not an issue of the F1 GTN, but a flight planning issue, let me explain.
> 
> It seems like you are trying to load an airway: J37
> But an airways requires an entry and an exit point. The exit point is fine, but the entry point is not defined as a VOR, but as a lat/lon:"S32316E137421" This is incorrect and there is no way for the GTN to load this flight plan. The same error would occur in real life.
> 
> You need to address that waypoint: "S32316E137421", either manually add the airway, or make sure that it uses an identifier.
> 
> Sorry, but it is not us.

_
They have narrowed it down to your program after further discussion. This is the picture of the issue I get.

![untitled 1](https://user-images.githubusercontent.com/7673205/30023152-776263ea-91ad-11e7-956b-d18c344c0abb.png)

Is there a fix please?

**Comment by albar965** [comment]
Problem was an PLN file containing airways for last point to destination airport where airway field was abused to store STAR.
Fixed with 1.6.3.
