### ISSUE TITLE
[function request] dark mode

### ISSUE THREAD

**Issue by Eyderoe** [albar965/littlenavmap#1206]
ui is too bright in night
dark mode might be greater

**Comment by albar965** [comment]
Already available but it has to be enabled manually. Go to menu `Tools` -> `Style` and select `Dark`.
Change map darkness in options on page `Map`.
![image](https://github.com/user-attachments/assets/fc13b7e9-0dc0-4784-84ea-f6fb3747b658)

**Comment by Eyderoe** [comment]
why your menu is dark too
![image](https://github.com/user-attachments/assets/54fc6d93-8ba2-4897-a48e-a0b6fd856d8c)

**Comment by Eyderoe** [comment]
cant find the sitting. gonna sleep zzzz

**Comment by albar965** [comment]
> why your menu is dark too

Depends on OS. Did you select the style `Dark`:

![image](https://github.com/user-attachments/assets/1c970026-01a7-4e11-875e-6ddb156df5ca)

**Comment by Eyderoe** [comment]
pretty cool, i just inspect Tools, thanks
