### ISSUE TITLE
[bug report] (maybe) disappear of distance ring

### ISSUE THREAD

**Issue by Eyderoe** [albar965/littlenavmap#1207]
after scale ++, distance ring disappear
but sometime its fine
ver. 3.0.12 64bit
circle1 : ED0V, 1800NM
circle2 : PANC, 1800NM
![image](https://github.com/user-attachments/assets/49dbd679-9ed2-4a9f-a2e9-e2d95ea742ce)
![image](https://github.com/user-attachments/assets/2654d16a-0e09-4a0f-97cb-abbede475010)
![image](https://github.com/user-attachments/assets/16409206-9bde-4a78-b60c-b451f4d7366a)

**Comment by albar965** [comment]
Meh. :frowning_face: I thought I have this fixed with 3.0.12. 

Thanks for reporting. Will check.
