### ISSUE TITLE
[bug report] error in loading databse procedure

### ISSUE THREAD

**Issue by Eyderoe** [albar965/littlenavmap#1212]
dear albar
seem lnm load xp11 and xp12 data at the same time
strange bug, and only happen in this airport (maybe)
hope you might fix it
kind regard
eyderoe

**using xp11 database**
all procedure list here can load correct into flight plan
![image](https://github.com/user-attachments/assets/22dcf97f-81e5-438f-ac12-4492ba53fa44)
**using xp12 database**
![image](https://github.com/user-attachments/assets/637f626a-ac47-4320-a665-5b49437e2daa)
local xp11 
![image](https://github.com/user-attachments/assets/00e56398-5368-40b3-b715-2f0155a9ecff)
local xp12
![image](https://github.com/user-attachments/assets/47885647-8eb9-44ca-9363-7adeaf244ca7)

**Comment by albar965** [comment]
The procedure loading code is the same for 11 and 12. Are you really sure that the ZUDR.dat CIFP files are the same in XP11 and XP12?

**Comment by Eyderoe** [comment]
sorry I forget that disagree of xp airport ident already fixed in 3.0.12 or 3.0.11
so lnm load XZ002B.dat and ZUDR.dat at same time

and what interesting is
even I delete XZ002B.dat just now, XZ002B still keep in database after reload databse. and still show when list procedures.

fine
thanks for your effort

no need to deal, delete little_navmap_xp11.sqlite and reload database can deal it

**Comment by albar965** [comment]
Good to hear it's working again.
Normally there is no need to delete `little_navmap_xp11.sqlite`. LNM compiles into a temporary database, then deletes `little_navmap_xp11.sqlite` and renames the temporary database to `little_navmap_xp11.sqlite`.

> even I delete XZ002B.dat just now, XZ002B still keep in database after reload databse. and still show when list procedures.

Ok This should really not happen. I'll have a look.

Alex
