### ISSUE TITLE
Autosave mode

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#122]
Setting in options dialog. If checked:
* Changed indication on title bar is removed
* No more "Changed. Save?" dialogs
* Saves automatically on exit, before new flightplan and probably time interval
* Still allows to save manually

**Comment by charliefoxtrot00** [comment]
Interval-based autosave would be very helpful. Lots of time spent flight-planning and occasional CTDs ruin the changes.

**Comment by albar965** [comment]
> Interval-based autosave would be very helpful. Lots of time spent flight-planning and occasional CTDs ruin the changes.

Please report CTDs with log file, settings file and instructions how to reproduce. 
All _known_ crashes are fixed in 2.6.10.

**Comment by albar965** [comment]
Done with 2.8
