### ISSUE TITLE
[question] how to remove msa graph

### ISSUE THREAD

**Issue by Eyderoe** [albar965/littlenavmap#1220]
lnm 3.0.12

Dear Alex,

how to remove this one
i try in context menu and start a new flight (delete msa graph)

![image](https://github.com/user-attachments/assets/8c4fcab3-e112-4ac7-b2be-213112e37886)
![image](https://github.com/user-attachments/assets/97f05f99-9864-47fd-998f-c2fa959509a3)
![image](https://github.com/user-attachments/assets/581f44e2-21ef-4fb6-912e-c290d07061ab)

Eyderoe

**Comment by Eyderoe** [comment]
sorry

**Comment by albar965** [comment]
See here https://www.littlenavmap.org/manuals/littlenavmap/release/latest/en/MAPDISPLAY.html#mouse-click-hotspots about mouse click hotspots. You have to hit certains points of a feature to trigger some menu action.
