### ISSUE TITLE
[bug report] missing airway

### ISSUE THREAD

**Issue by Eyderoe** [albar965/littlenavmap#1221]
Dear Alex,

lnm3.0.12 AIRAC2413
missing airway L888 from PEXUN to SANLI,
and still can click blank to see details

Eyderoe

![image](https://github.com/user-attachments/assets/2a5e4537-f388-4bc4-b597-d732951367ca)
![image](https://github.com/user-attachments/assets/3f80cfe0-ff67-4199-a804-1a007fc6204e)

**Comment by albar965** [comment]
Can reproduce this. Definitely a bug. Thanks for reporting.

Fun fact: The line is there when using the Spherical projection. Seems a bug in Mercator when drawing vertical lines.

 I'll first release a 3.0.13.beta for MSFS 2024. Once this is out I'll take care of all these airway distance circle issues.
