### ISSUE TITLE
[bug report] white background color after show airspace

### ISSUE THREAD

**Issue by Eyderoe** [albar965/littlenavmap#1226]
after show airspace, appear white background color

![image](https://github.com/user-attachments/assets/d2047d30-050c-4a6d-be8c-9e45f77c06d1)
![image](https://github.com/user-attachments/assets/6f9db2a8-5ab6-4e25-994e-45d3f94bdda9)

**Comment by albar965** [comment]
Confirmed. Seems the background color is not reset after drawing airspaces.

**Comment by albar965** [comment]
Fixed for ILS too.
