### ISSUE TITLE
Display IVAO traffic and centers

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#130]
https://ivao.aero/ViewDocument.aspx?Path=/
https://doc.ivao.aero/apidocumentation:whazzup

DATA URL http://api.ivao.aero/getdata/whazzup/whazzup.txt

**Comment by BigPoppaBlunts** [comment]
This would be a nice addition. Possibly VATSIM as well?

**Comment by albar965** [comment]
Yup. VATSIM is already planned: #45

**Comment by albar965** [comment]
Closing since this is duplicate of #45. Both networks cause the same work. Therefore I merged this ticket into the other one.
