### ISSUE TITLE
Automatic zoom while flying

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#133]
Configurable zoom mode to keep current leg visible during flight.
Zoom in to airport after landing.

Jump back to aircraft after given time.

**Comment by albar965** [comment]
Done. Autozoom only active in air.

**Comment by cmtekin** [comment]
Hi Alex thanx for this excellent tool.

Is it possible to auto zoom in (down to readable taxi ways and parking spots) just before touchdown to enable easier taxiing?
