### ISSUE TITLE
SkyVector as map Theme?

### ISSUE THREAD

**Issue by JanC** [albar965/littlenavmap#137]
Hi,
this is an enhancement. Any chance that you add [SkyVecor ](skyvector.com)tiles as map theme? I'm not sure if their tile API is public though ..

cheers,
Jan

**Comment by albar965** [comment]
Not sure if Skyvector allows access to their tiles. Didn't find any clear information. 

You can do it at home but at the end it is a matter of the TOS. Same problem with Google, therefore I will not add this publicly.

You can try it yourself. [Here are links and some basic information how to add map themes.](https://albar965.gitbooks.io/little-navmap-user-manual/content/en/MAPTHEMES.html)

**Comment by albar965** [comment]
Cannot support non public not free APIs per default. Sorry.
