### ISSUE TITLE
Compass rose

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#141]
Add a scalable configurable 360 degree compass rose with range rings or around user aircraft. Using either true or magnetic course.

**Comment by guvner** [comment]
Just what I came here to suggest.  Could I also request that the rose displays degree segments (i.e. 15, 30, 45, 60, 75, 90 etc.) and also the option to display a thin line extending forward from the aircraft nose towards the edge of the rose to allow for a quick and accurate reading of current heading.

**Comment by albar965** [comment]
Sure. No problem. I have the tick drawing code for the VORs already around and can reuse it for the compass rose including the degrees and the line from the center.
Thanks for the suggestions.
Alex

**Comment by albar965** [comment]
Without simulator connection:
![little navmap screenshot compass rose](https://user-images.githubusercontent.com/15254956/36478834-9a99c78e-1706-11e8-8f02-28e5a12432ab.jpg)

With simulator connection showing dotted heading line and solid track line with distance labels:
![little navmap screenshot compass rose 2](https://user-images.githubusercontent.com/15254956/36478893-da147b66-1706-11e8-8b31-8df4bc83e77f.jpg)
