### ISSUE TITLE
Suggest|pln to xplane

### ISSUE THREAD

**Issue by DemonRem** [albar965/littlenavmap#152]
I think maybe becuse fms is old format that hold all the information such as ils altitude and arrival and deaprture information we can do in other way or just create in the tool that will convert those data

**Comment by albar965** [comment]
Here is something much better for X-Plane 11.10:
http://developer.x-plane.com/?article=flightplan-files-v11-fms-file-format
Supports airways, cruise altitude, SIDs, STARs and approaches.

The FMS and GPS in the beta can already load this format and I already added support in LNM. Although, it is still disabled.

**Comment by albar965** [comment]
Closing the ticket since the format is already supported in the latest beta. Feel free to reopen if needed.

**Comment by DemonRem** [comment]
So i can get now ils information

**Comment by albar965** [comment]
Not ILS but approach procedures, SIDs and STARs. 
I don't know of any flight plan format that includes ILS information, sorry.
Alex
