### ISSUE TITLE
Allow saving of several flight plan formats at once

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#165]
Add "multi-save" feature that shows a dialog where target directories, file names and flight plan types can be configured and all save at once.
  

> An ideal solution would be kind of a save file name generation field in the option settings (using placeholders), just as used by some music file management and tagging tools. Something like:
> "[Flight plan type] [Departure Name] ([Departure ICAO]) to [Destination name] ([Dest. ICAO])_[FPlanDate].pln"
> Users may then pick the elements they want in the saved filename and that should make everybody happy.

**Comment by Gulliver54** [comment]
Sounds ok. It prevents repetitive proceedings.
When conducting an Ivao flight planned by LNM , I have to save 3 flightplans. .pln for Active sky, .rte for the Boeing and .txt for Ivao flightplan.

**Comment by nmeier** [comment]
Good idea, I export two only right now (vpilot, fms) - a workflow to export would also reduce the long list of choices in the menu to just one

![export](https://user-images.githubusercontent.com/312857/69362197-1100a180-0c5c-11ea-8ad6-a75c82806a50.jpg)

Replaced with one entry, one dialog where checkboxes for all formats are shown (remembers last selection). The folders for each file (assuming one naming convention pattern) could move to options.

![export2](https://user-images.githubusercontent.com/312857/69363101-d0098c80-0c5d-11ea-9336-d2f83941d27e.JPG)

**Comment by albar965** [comment]
That's the idea. Replace this maze of menu items with a single dialog that updates all chosen files when saving. I also plan to change the save behaviour and add my own flight plan format since the annotated PLN is too limited.
So, one save should update the (future) .lnm flight plan, X-Plane FMS and others.
Alex

**Comment by albar965** [comment]
After configuration all can be saved with one click.

![image](https://user-images.githubusercontent.com/15254956/82037369-8b513200-9691-11ea-877f-d83334dda868.png)

**Comment by Gulliver54** [comment]
Hi Alex,
I Hope you did not forget this option:
[image: 05-15-01.jpg]




Op vr 15 mei 2020 om 11:52 schreef Alexander Barthel <
notifications@github.com>:

**Comment by albar965** [comment]
Sorry, cannot see the image.
But simulator formats and some others can still be exported from main menu. There's also a toolbar button for immediate export to all selected.
![image](https://user-images.githubusercontent.com/15254956/82043585-606bdb80-969b-11ea-87de-ac67d984dd6e.png)

**Comment by Gulliver54** [comment]
Hope it's visible right now

Gradus Hageman
send by my _A310

Op vr 15 mei 2020 13:02 schreef Alexander Barthel <notifications@github.com

**Comment by albar965** [comment]
Sorry, nope. Better login into Github and attach or send me the email directly.
