### ISSUE TITLE
[request] Load fsx/P3D airpsace files in x-plane install

### ISSUE THREAD

**Issue by www2000** [albar965/littlenavmap#171]
Is there possible (in a future version) that i can add fsad_airspace.BGL and fsad_airspace_FIR.BGL to <x-plane install>/Custom Data/Airspaces directory and be scan and add to littlenavmap database?

**Comment by albar965** [comment]
If the airspace files are part of the FSX/P3D scenery library they will be read.
For X-Plane there will be Navigraph support including airspaces soon.
So, AFAIU this feature is not really needed, right?
Alex

**Comment by www2000** [comment]
Thanks Alex
For the X-Plane Airspace in Navigraph that is News for me :smiley:

**Comment by albar965** [comment]
There will be a release 1.8 soon which can be updated with Navigraph cycles. 
I think I can close the issue. Feel free to reopen if needed. 
Alex
