### ISSUE TITLE
Little Xpconnect is not working under Linux

### ISSUE THREAD

**Issue by Moskito99** [albar965/littlenavmap#174]
Hi!

Since 1.8.3 the plugin Little Xpconnect is not working anymore.

I get the following error in the Log.txt:

dlerror:/.../.../X-Plane 11/Resources/plugins/Little Xpconnect/64/lin.xpl: symbol _ZdlPvm, version Qt_5 not defined in file libQt5Core.so.5 with link time reference

X-Plane is working with Little Xpconnect 1.6.7 and Little Navmap 1.8.3 without issues as far as I can see....

Kind Regards,
Marcus

**Comment by albar965** [comment]
Hi Marcus,
thanks for reporting. Unfortunately X-Plane stopped working since I updated my Linux (main development machine) recently. It also refuses to run in a VM. So, testing is a bit difficult.

You can use the old plugin that was included with 1.6 as a workaround . The protocol did not change.

It looks like my plugin is loading the wrong Qt shared library instead of the included one. So, a few questions:
Do you use another X-Plane plugin that contains Qt shared libraries?
Did you delete the old Little Xpconnect folder before installing the new one to avoid merging old and new content in the installation?
What Linux disto do you have? I built this in Ubuntu 17.10 and tested it also with 16.04 LTS.

Give me few days to dive deeper into this. I'm kinda busy now.
Best,
Alex

**Comment by Moskito99** [comment]
Hi Alex,
I'm not aware of any other plugin which is using Qt. 
But to be honest, I don't know :-(

Here are a list of my plugins:
124thATC64, AutoGate, BetterPushback, FlyWithLua, Little Xpconnect, SimpleFMC V1.41rc, TerrainRadar, WorldTraffic 3, XACARS, X-Camera, Xchecklist

My Linux distro is Debian testing.
I know, this is not exactly the "mainstream" distro...

And I deleted the folder befor I copied the new plugin.

Regards,
Marcus

**Comment by albar965** [comment]
Debian testing is close to Ubuntu which is based on Debian.
You can easily find out if there is some Qt in the plugins by running:
`cd "YOURXPLANEPATH/Resources/plugins/" && find -iname "*qt*"`

this returns 
```
./Little Xpconnect/64/libQt5Core.so.5
./Little Xpconnect/64/libQt5Core.so.5.9.1
./Little Xpconnect/64/libQt5Core.so.5.9
./Little Xpconnect/64/libQt5Core.so
```
for me.
You can also try to temporarily disable other plugins.

**Comment by Moskito99** [comment]
OK, I couldn't find any other plugin which used also the Qt library.
So, Little Xpconnect is the only one.
The error in the log is before the gui from x-plane appears.

Marcus

**Comment by albar965** [comment]
Another one to get more information about the loaded shared libraries:
`cd "YOURXPLANEPATH/Resources/plugins/Little Xpconnect/64" && ldd lin.xpl`
Alex

**Comment by Moskito99** [comment]
With 1.6.7:

marcus@pc1:~/Documents/Steam/steamapps/common/X-Plane 11/Resources/plugins/Little Xpconnect/64$ ldd lin.xpl
        linux-vdso.so.1 (0x00007ffe943fe000)
        libQt5Core.so.5 => /home/marcus/Documents/Steam/steamapps/common/X-Plane 11/Resources/plugins/Little Xpconnect/64/./libQt5Core.so.5 (0x00007f79e7a9b000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f79e771b000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f79e7403000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f79e71eb000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f79e6e43000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f79e6c23000)
        libicui18n.so.56 => /home/marcus/Documents/Steam/steamapps/common/X-Plane 11/Resources/plugins/Little Xpconnect/64/./libicui18n.so.56 (0x00007f79e6783000)
        libicuuc.so.56 => /home/marcus/Documents/Steam/steamapps/common/X-Plane 11/Resources/plugins/Little Xpconnect/64/./libicuuc.so.56 (0x00007f79e63cb000)
        libicudata.so.56 => /home/marcus/Documents/Steam/steamapps/common/X-Plane 11/Resources/plugins/Little Xpconnect/64/./libicudata.so.56 (0x00007f79e49e3000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f79e47c3000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f79e45bb000)
        libgthread-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0 (0x00007f79e43b3000)
        libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f79e409b000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f79e841b000)
        libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f79e3e23000)

With 1.8.3:

marcus@pc1:~/Documents/Steam/steamapps/common/X-Plane 11/Resources/plugins/Little Xpconnect/64$ ldd lin.xpl
        linux-vdso.so.1 (0x00007ffd80fc6000)
        libQt5Core.so.5 => /home/marcus/Documents/Steam/steamapps/common/X-Plane 11/Resources/plugins/Little Xpconnect/64/./libQt5Core.so.5 (0x00007f99cad2b000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f99ca9ab000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f99ca693000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f99ca47b000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f99ca0d3000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f99c9eb3000)
        libicui18n.so.56 => /home/marcus/Documents/Steam/steamapps/common/X-Plane 11/Resources/plugins/Little Xpconnect/64/./libicui18n.so.56 (0x00007f99c9a13000)                    
        libicuuc.so.56 => /home/marcus/Documents/Steam/steamapps/common/X-Plane 11/Resources/plugins/Little Xpconnect/64/./libicuuc.so.56 (0x00007f99c965b000)                        
        libicudata.so.56 => /home/marcus/Documents/Steam/steamapps/common/X-Plane 11/Resources/plugins/Little Xpconnect/64/./libicudata.so.56 (0x00007f99c7c73000)                    
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f99c7a53000)                                                                                                             
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f99c784b000)                                                                                                           
        libgthread-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0 (0x00007f99c7643000)                                                                                     
        libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f99c732b000)                                                                                               
        /lib64/ld-linux-x86-64.so.2 (0x00007f99cb6ab000)                                                                                                                              
        libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f99c70b3000)

**Comment by albar965** [comment]
Million thanks for the help! 
The Qt .so loaded is the correct one. It seems that a compiler problem crept in with my last system update.
I'll try to fix this.
Alex

**Comment by Moskito99** [comment]
Kein Problem! 
Immer wieder gern! ;-)

Gruß,
Marcus

**Comment by albar965** [comment]
Can you give this version of Xpconnect a try: https://www.magentacloud.de/lnk/HfFxUd0c
Danke im Voraus
Alex

**Comment by Moskito99** [comment]
Hello Alex,

this version is working without any issue or error message in the log!
And the connection with Little Navmap is also working!
I think you got it! ;-)

btw. I tested this version with X-Plane 11.10 because steam updated X-Plane today...

Gruß,
Marcus

**Comment by albar965** [comment]
Thank you for the quick feedback!
Viele Grüße
Alex
