### ISSUE TITLE
Exporting Ivao flight plan

### ISSUE THREAD

**Issue by birdydma** [albar965/littlenavmap#176]
In X-Plane 11 / Ressources / plugins / X-Ivap Ressources / Flightplans 

is the Default.fpl

I join such a file
[Default.zip](https://github.com/albar965/littlenavmap/files/1524022/Default.zip)

**Comment by albar965** [comment]
Thank you for the file and information. 
Issue is related to #130 
Alex

**Comment by albar965** [comment]
[wetransfer-d03a27.zip](https://github.com/albar965/littlenavmap/files/1524744/wetransfer-d03a27.zip)

**Comment by FSC190** [comment]
IVAP has a different location to store flight plans than x-IVAP
C:\Users\...\AppData\Roaming\IVAO\IvAp\flights

Roland

**Comment by albar965** [comment]
Moved to next release since it is too much effort to add all the dialogs and options for this format. 
You can still copy the route description of LNM to the clipboard and use this in the various online clients.
Alex

**Comment by birdydma** [comment]
No problem Alex.
On my side, but it is may be only me, displaying Ivao traffic is more important.
Exporting flight plan will be only cherry on the cake.

**Comment by albar965** [comment]
Problem is that there is a large amount of not so well documented parameters in the flight plan which needs an extra dialog. Other export options are simpler and often allow to reuse code.
Alex
