### ISSUE TITLE
X-Plane | Reload only Custom Scenery

### ISSUE THREAD

**Issue by Phil57** [albar965/littlenavmap#183]
Hi,

I'm using this tool on a remote computer and loading the Scenery DB for X-Plane takes about 10 minutes.
As airports are published quite often on gateway.x-plane.com it can be a bit long to reload everything every time we download a new airport.

Is there any chance that you add an option in the Load Scenery dialog to rescan only the Custom Scenery folder from X-Plane so it is quick to update the DB when adding or updating a new custom airport ?

Thanks.

**Comment by albar965** [comment]
Hi,
I'd recommend to load the scenery on the flying computer and then copy the database [as described here](https://albar965.gitbooks.io/little-navmap-user-manual/content/en/RUNNOSIM.html). This is much faster, will take only two to three minutes and you can make a script to copy the database from the flying to the remote computer.
Alex

**Comment by albar965** [comment]
Seems to be fixed. :smile:  Closing now. Feel free to reopen if needed.
Alex
