### ISSUE TITLE
Garmin GTN 750 export options

### ISSUE THREAD

**Issue by andrewbernard** [albar965/littlenavmap#192]
There is a new option in 1.8.4 to option to save Garmin GTN 750 flight plans with user defined waypoints only. But whether I turn this on or off, the plan is saved with :F: for the departure and arrival airports, so it seems the option has no effect.

**Comment by albar965** [comment]
Hi Andrew,
just tried it EDDF EDDM without user defined waypoints:
```
FPN/RI:F:EDDF:F:MOVUM,N49570E008316.T109.HAREM,N49371E009249.T104.WLD,N48348E011078.T702.OLETU,N48280E011363:F:EDDM
```
and with user defined waypoints:
```
FPN/RI:F:EDDF:F:N49570E008316:F:N49371E009249:F:N49230E009495:F:N49119E010086:F:N49086E010143:F:N49004E010274:F:N48570E010329:F:N48487E010461:F:N48417E010569:F:N48348E011078:F:N48280E011363:F:EDDM
```
looks OK to me.

I'm using the latest Garmin trainer 6.41. The user defined waypoints are all renamed by the GTN so this export option is more useful for the GNS which doesn't do this. But the waypoints show up.

**Comment by andrewbernard** [comment]
I now see what is going on. I was expecting the destination airport to have :DA: not :F:, but also to muddle things more I had no intermediate waypoints. I can confirm the code is working fine. As always in software, with multiple layers of errors things can be hard to see. It turns out that the outback airport I am trying to import is identically named to a waypoint (YWCA, Wilcannia, Australia) and this is probably confusing the airac 1611 cycle, and the Garmin, maybe. It just so happens that I fly to this tiny remote town, but if I put another outback one nearby such as Cobar. YCBA, the whole process works fine.

So I think I have stumbled upon some limitations with the Garmin data, not being fully correct for outback Australia.

Issue can be closed.

**Comment by albar965** [comment]
Hi Andrew,
`:DA:` and `:AA:` are only used if there are procedures. Otherwise it is `:F:`. `:F:` is also used if you chose the user waypoint option. Anyway, thanks for the feedback and glad it is working. :smiley:
