### ISSUE TITLE
Development of an Android or IOS app

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#194]
Create a simple Qt android app with limited functionality.
Needs to separate drawing code from main application.

Alternatively:
Create a very simple JS and HTML based add that uses the web server from issue #163

**Comment by merspieler** [comment]
I'd prefer the JS and HTML alternative... so you don't have to make a Windows-Phone and Blackberry app too ;-)

**Comment by albar965** [comment]
All you need will be a browser if #163 is done. :-)
Alex
