### ISSUE TITLE
Airway calculation skips waypoints

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#201]
Error in compiled data from Navigraph (Navdatareader). X-Plane airways are calculated correctly.
Example: W13 should be MIA -> NPT -> BGO 

----

**Example: VOR LPD is not used by airway calculation:**

[LPD at Skyvector](https://skyvector.com/?ll=35.434267498194274,12.644714348627142&chart=302&zoom=2)

----

**Wrong airway assignments. LPD is not used:**
![lpd little navmap](https://user-images.githubusercontent.com/15254956/34559093-df9d7236-f140-11e7-8749-002eab1ceb23.jpg)

----

**Correct airway assignments at LPD:**
![auswahl_274](https://user-images.githubusercontent.com/15254956/34643179-1ee7e83c-f320-11e7-9701-7d9c7682b077.jpg)

**Comment by sarunint** [comment]
Is this issue to resolve [this](https://www.navigraph.com/forum/viewtopic.php?f=30&t=5759)?

That's great!

**Comment by albar965** [comment]
Hi Sarun, yes and it is fixed. You can get a release candidate here:
Windows: https://www.magentacloud.de/lnk/AJlR0yWg
macOS: https://www.magentacloud.de/lnk/MNlx0DPq
Linux: https://www.magentacloud.de/lnk/xOlR0vqb
I'll finish and publish this release tomorrow. Navigraph did not update the database yet as far as I've seen but sure they will soon. The problem is fixed in the included 1707 at least.
Alex
