### ISSUE TITLE
Support for XFMC

### ISSUE THREAD

**Issue by JayMonkey** [albar965/littlenavmap#208]
Hi,

This is a great little app, and well on it way to being the best stand alone flight planner for Xplane

Is there any chance you could add export support for X-FMC
https://www.x-fmc.com/

Section 4.3 of the manual has the following info on saved flight plans format  : -

> **4.3 Flight plans and Company routes**
> We have added a special feature in the FMC to make flight planning much easier!
> Many among you use RouteFinder to prepare their flight plan and the format used is:
> “DEP ICAO” SID “ROUTE” STAR “ARR ICAO” (e.g. LFLL SID MOKIP UN854 DJL STAR LFPG)
> If you want to store it, just create a file named DEPARR.FPL (e.g. LFLLLFPO.FPL) with your notepad
> insert the route and save it in the “flightplan” directory in the “XFMC” plugin folder…
> We should warn you that RouteFinder can be helpful but not accurate. If you need to have accurate
> flight plans, you’ll need much more time to prepare your flight!

I've attached a copy of the demo plan that is installed as a demo plan 
[LFLLEHAM.zip](https://github.com/albar965/littlenavmap/files/1678698/LFLLEHAM.zip)

The format looks pretty easy to do so i cant see this being a major issue ..

The plans have an extension of  *.FPL and are saved in for following Folder : -
Path to Root X-Plane 11 Folder\Resources\plugins\XFMC\FlightPlans

Many thanks for al your hard work
Cheers
Jay

**Comment by albar965** [comment]
Hi Jay,
looks interesting. Didn't know about this FMC.
Try the "Export Flight Plan as TXT" which is for JarDesign and Rotate aircraft. The contents of the files are the same. I just tried it.
I'll extend the documentation and the status bar message If you can confirm it is working.
Alex

**Comment by JayMonkey** [comment]
Hi Alex,

Thanks for getting back to me on this so quickly, I will try what you suggest this afternoon and get back to you to confirm if it works ok.
X-FMC for X-plane is a pretty nifty plug-in as it allows you to program any type of GPS/FMC system on any plane and it can act as a co-pilot and deal with things like, flaps, brakes, gear … etc
Check out the official Tutorial video for more info :-

https://www.youtube.com/watch?v=XM1VT8usYbg&t=445s <https://www.youtube.com/watch?v=XM1VT8usYbg&t=445s>

If you fly Xplane-10 or 11 then its a must have plugin

Cheers
Jay

**Comment by JayMonkey** [comment]
Hi Alex,

Exporting the flight plan as TXT seems to work ok, You have to manually rename the TXT extension to FPL using windows explorer but with that done XFMC seems to load the flight plan OK.

Would be nice if you can add the option to export a plan as a FPL file directly from the file menu so no need for manual rename.
Any chance we could have that as a request for the next release ?

I did try saving as FPL in LittleNavMap but it saved the file as FLIGHTPLAN.TXT.FPL

Cheers
Jay

**Comment by albar965** [comment]
Will add a separate menu item to save as FPL. This is not much work since the functionality behind is already there.
Alex

**Comment by JayMonkey** [comment]
Hi Alex,

That would be fantastic … if its a separate menu item then presumably it will remember the export path just like all the others do ?

Many Thanks
Cheers
Jay

**Comment by albar965** [comment]
Right. All exports dialogs remember the last directory.
I'll put it as a separate menu item in the "Export other formats".
Alex

**Comment by albar965** [comment]
Done. Added separate menu item for export.

**Comment by JayMonkey** [comment]
Many thanks Alex .... looking forward to the next release

**Comment by albar965** [comment]
Hi Jay, 
please send me an email (contact here: https://albar965.github.io/) so I can send you the 2.0 beta version for testing the export.
Alex
