### ISSUE TITLE
Changing resolution messes up display of windows

### ISSUE THREAD

**Issue by paume** [albar965/littlenavmap#210]
When I drag the little navmap to another monitor with a different resolution the flight plan and the airport windows get messed up. See attachment.

![little navmap capture](https://user-images.githubusercontent.com/36139078/35782432-2992d49c-09f8-11e8-9810-0fd6ed56c1f8.jpg)

**Comment by albar965** [comment]
I cannot reproduce this. Just moved between monitors and nothing changes. You're probably using text font sizes in the Windows settings.

Can you check the following:
- Does clicking OK in the options dialog fix this (does a refresh of all program parts)?
- Does changing the user interface "Text for Flight Plan Table" size fix anything?
Alex

**Comment by paume** [comment]
Hi Alexander,

Does clicking OK in the options dialog fix this (does a refresh of all
program parts)?

YES, although the fix is temporary. If I close the program and reopen it,
it happens again.

Also, I noticed that there is a large difference between the font size in a
file dialog box and the rest (see attachment). I don't know if this is
related.

Thanks,

Pau

On Mon, Feb 5, 2018 at 10:53 AM, Alexander Barthel <notifications@github.com

**Comment by albar965** [comment]
Hi Pau,
I had to modify the lists since the Qt library I use for this applies a huge spacing which wastes a lot of screen estate. Something there does not play well when fonts are set to anything else than 100% in Windows.
Will fix in the next release.
Alex

**Comment by albar965** [comment]
Will not fix. Qt does not give a font change signal. Even the Windows settings state that an application restart is needed after a font change. 
This occurs only if different font sizes are used on the monitors.
So, move the application to the other monitor where it will remember its position and restart it.
