### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by birdydma** [albar965/littlenavmap#221]
Good day,

I have 2 computers on a Lan. Both with win 10 64 bits.
The have the very same Redistributatbles installed.
[Logs and picture.zip](https://github.com/albar965/littlenavmap/files/1754627/Logs.and.picture.zip)

Auto update (as well as manual update) does nor works on one of them.
Not a big deal of course. I am just curious: why? Also, could help you to catch a bug.

Picture and logs are in the .zip.

Regards.

Claude.

**Comment by albar965** [comment]
Hi Claude,
according to the log there is a problem loading the SSL libraries.
Did you install [OpenSSL for Windows](http://slproweb.com/products/Win32OpenSSL.html) by any chance?
Another user solved the very same problem by installing the MS Visual C++ 2013 Redistributable package which you already did. Can you check if you installed the right one and both 32 and 64 bit?

Here is a link for all redistributable packages: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

Alex

**Comment by birdydma** [comment]
Sometimes i am blind, idiot, and much more.. After a quadruple check, i have catch the culprit. Thank you!

The 2013 32 bits was missing.

PS: apparently, as sometimes i am blind, there is nothing in the documentation about the redistributables.

Have a nice WE.

**Comment by albar965** [comment]
The 32 bit is important even for a 64 bit OS since LNM itself is 32 bit. It doesn't need so much memory to justify a 64 bit build.
Thanks for the feedback and have a nice weekend too.
Alex
