### ISSUE TITLE
suggestion flight book

### ISSUE THREAD

**Issue by bilkaPek** [albar965/littlenavmap#222]
hi Alex
I would like to make a suggestion, in my opinion an option that is missing at LNM,
add a flight-book data table to LNM with flight information that could be manipulated and exported later to generate the flight plan

> This is an example

- Flight_Num = AE75
- Flight_Call = AEA9XR
- Plane_Icao = B77W
- Plane_Registry = E6-EBT
- Airline_icao = AEA
- Departure_Icao = SAEZ
- Departure_Time = "15-05-2017 15:30"
- arrival_Icao = LEMD
- Arrival_Time = "15-05-2017 20:30"
- Flight_Plant = route......
- Distance = 674
- Flight_Time = 12:00
- Flight_Fuel = 265014

greeting
and thank you again for your wonderful work 
Sam.

**Comment by albar965** [comment]
Hi Sam,
I actually have plans to add the logbook functionality to LNM but did not write a ticket yet.
So I'll take this one. :-)
Alex

**Comment by bilkaPek** [comment]
Hi Alex
thanks to you Alex
in my opinion it is a function that is sorely lacking in LNM, my first idea is pretty basic but I think you have an idea at the head more advanced than mine.
rely on me if you need
Sam.

**Comment by albar965** [comment]
I think what you described is perfect for a start. Later I can add saving of the flight plan and flow track.
Alex

**Comment by albar965** [comment]
Another example:
![Another Example](http://xplanewiki.fr/public/images/XAcars16.jpg)

**Comment by albar965** [comment]
Fixed with #346 so far.
