### ISSUE TITLE
Export flightplan in efbr format

### ISSUE THREAD

**Issue by tomac01** [albar965/littlenavmap#226]
http://www.aivlasoft.com

Example: EDDT to EDDK

[AivlaSoft EFB Route - www.aivlasoft.com]
//Saved 08.03.2018 09:13:55z, EFB Version=1.6.15.15942
//AIRAC cycle 1803 / Rev.1, Valid 01/MAR/2018 - 28/MAR/2018
Format=1
ATS=EDDT BRAN2L BRANE Q201 PODER UZ189 RUNER T858 KOPAG EDDK
Generator=RouteFinder
Origin=EDDT
Destination=EDDK
CruiseAltitude=25000
DepartureProcedureInfo=26R|BRAN2L||
ArrivalProcedureInfo=||
ApproachProcedureInfo=14L|ILS Rwy 14L|WYP
Wpt=Sid|0|*RW26R||Fix|0||52.561947|13.309801|0|BRAN2L
Wpt=Sid|1|[alt]|untilalt|User|0||52.557932|13.268313|0|BRAN2L
Wpt=Sid|2|RWNB||Fix|0||52.545058|13.151039|0|BRAN2L
Wpt=Sid|3|[icpt]|intrcpt|User|0||52.542312|13.118229|0|BRAN2L
Wpt=Enroute|0|BRANE|BRANE|Fix|0||52.483911|12.561486|0|BRAN2L
Wpt=Enroute|1|GALKU|GALKU|Fix|0||52.389378|12.079222|0|Q201
Wpt=Enroute|2|BUREL|BUREL|Fix|0||52.344525|11.854544|0|Q201
Wpt=Enroute|3|POVEL|POVEL|Fix|0||52.128378|10.827778|0|Q201
Wpt=Enroute|4|PODER|PODER|Fix|0||51.612447|8.688142|0|Q201
Wpt=Enroute|5|RUNER|RUNER|Fix|0||51.276344|8.387625|0|UZ189
Wpt=Enroute|6|GETNI|GETNI|Fix|0||51.118428|7.954692|0|T858
Wpt=Enroute|7|KOPAG|KOPAG|Fix|0||51.064867|7.810050|0|T858
Wpt=Approach|0|WYP|WIPPER|VOR|109,600000||51.048353|7.279997|0|WYP
Wpt=Approach|1|D270K||Fix|0||51.051161|6.992258|0|WYP
Wpt=Approach|2|OM14L||Fix|0||50.926989|7.062147|0|ILS Rwy 14L
Wpt=Approach|3|*RW14L||Fix|0||50.880462|7.129052|0|ILS Rwy 14L
[END]

**Comment by albar965** [comment]
Thank you for the example. But it contains procedure waypoints which are quite difficult to save and a lot of effort to implement if detailed documentation of the format is not available. I'm talking about fields Sid|0| - Sid|3| and Approach|0| - Approach|3|. These can contain a lot of parameters.
Alex

**Comment by tomac01** [comment]
ok, here is the same example only without SID, STAR and APPROACH.... :-)

[AivlaSoft EFB Route - www.aivlasoft.com]
//Saved 08.03.2018 10:52:36z, EFB Version=1.6.15.15942
//AIRAC cycle 1803 / Rev.1, Valid 01/MAR/2018 - 28/MAR/2018
Format=1
ATS=EDDT BRANE Q201 PODER UZ189 RUNER T858 KOPAG EDDK
Generator=RouteFinder
Origin=EDDT
Destination=EDDK
CruiseAltitude=25000
DepartureProcedureInfo=|||
ArrivalProcedureInfo=||
ApproachProcedureInfo=||
Wpt=Enroute|0|BRANE||Fix|0||52.483911|12.561486|0|DCT
Wpt=Enroute|1|GALKU||Fix|0||52.389378|12.079222|0|Q201
Wpt=Enroute|2|BUREL||Fix|0||52.344525|11.854544|0|Q201
Wpt=Enroute|3|POVEL||Fix|0||52.128378|10.827778|0|Q201
Wpt=Enroute|4|PODER||Fix|0||51.612447|8.688142|0|Q201
Wpt=Enroute|5|RUNER||Fix|0||51.276344|8.387625|0|UZ189
Wpt=Enroute|6|GETNI||Fix|0||51.118428|7.954692|0|T858
Wpt=Enroute|7|KOPAG||Fix|0||51.064867|7.810050|0|T858
[END]

**Comment by tomac01** [comment]
.... and here an exaple-export-efbr from PFPX:

[AivlaSoft EFB Route - www.aivlasoft.com]
//Saved 08.03.2018 11:15:40z
//AIRAC cycle NG1803
Format=1
ATS=BRANE Q201 PODER UZ189 RUNER T858 KOPAG
Generator=PFPX 1.28
Origin=EDDT
Destination=EDDK
CruiseAltitude=25000
DepartureProcedureInfo=26R|||
ArrivalProcedureInfo=14L||
ApproachProcedureInfo=||
Wpt=Enroute|0|BRANE||Fix|0|ED|52.483913|12.561486|0|DCT
Wpt=Enroute|1|GALKU||Fix|0|ED|52.389442|12.079167|0|Q201
Wpt=Enroute|2|BUREL||Fix|0|ED|52.344524|11.854547|0|Q201
Wpt=Enroute|3|POVEL||Fix|0|ED|52.128380|10.827778|0|Q201
Wpt=Enroute|4|PODER||Fix|0|ED|51.612499|8.688056|0|Q201
Wpt=Enroute|5|RUNER||Fix|0|ED|51.276390|8.387500|0|UZ189
Wpt=Enroute|6|GETNI||Fix|0|ED|51.118332|7.954722|0|T858
Wpt=Enroute|7|KOPAG||Fix|0|ED|51.064865|7.810050|0|T858
Wpt=Enroute|8|(FAP)||User|0||50.916401|7.074022|0|DCT
[END]

**Comment by albar965** [comment]
Thanks for the examples. Maybe the EFB can event digest the procedure information without the legs. Will see what is doable. Exporting without procedure information certainly is. 
Alex

**Comment by albar965** [comment]
Done but only saving route. Procedures and user waypoints are not supported.
