### ISSUE TITLE
Error red letters in procedure list

### ISSUE THREAD

**Issue by Forsaken-Player** [albar965/littlenavmap#227]
Hello, 
Sorry to bother but I was curious. What's this? I know it's because of the AIRAC update since it doesn't happen with the provided one (littlenavmap's).
![littlenav](https://user-images.githubusercontent.com/13246441/37223446-4df36dd0-23af-11e8-8bea-fc02a142d3fd.jpg)

**Comment by albar965** [comment]
I don't see this here. What airport?

**Comment by Forsaken-Player** [comment]
it's SACO

**Comment by albar965** [comment]
I cannot even see the transitions D075Q, D090Q or D102Q. This is 1803 revision 1 and LNM 1.8.5. 
Try if you can find the missing fixes in the navaid search. 

![grafik](https://user-images.githubusercontent.com/15254956/37228351-9562ad76-23e0-11e8-8e75-f862e52d0826.png)

**Comment by Forsaken-Player** [comment]
I guess I have the answer.. but not why. They are in the standar airac from Laminar... I guess Littlenavmap mix customdata and defauldata...

**Comment by albar965** [comment]
And the answer to the why is that Navigraph decided to deliver the CIFP.txt files in lower case now. :-/
Use the native LNM Navigraph database. The X-Plane navdata data is the same anyway.
Alex

**Comment by albar965** [comment]
Ahh BTW: Feel free to close if that's ok with you.

**Comment by Forsaken-Player** [comment]
Ok, thank you very much. So if I modify the saco.dat file to SACO.dat it will only show the customdata?

**Comment by albar965** [comment]
> Ok, thank you very much. So if I modify the saco.dat file to SACO.dat it will only show the customdata?

No. Menu -> "Scenery Library" -> "Use Navigraph for Navaids and Procedures".
Alex

**Comment by Forsaken-Player** [comment]
Actually I've modified the Custom nav data to Upper case and it worked (after rebuilding the database).
![captura de pantalla 28](https://user-images.githubusercontent.com/13246441/37231089-9d4d0152-23c8-11e8-8ceb-59bb8148700f.png)

**Comment by Forsaken-Player** [comment]
I did renamed the saco.dat to SACO.dat at the customdata and rebuilt the database and now default navdata doesn't appear as before. 
Thank you for the hint!

![captura de pantalla 29](https://user-images.githubusercontent.com/13246441/37231645-ad62e370-23ca-11e8-9ae5-551e45358e63.png)
