### ISSUE TITLE
Export for iFly flight plan file

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#231]
Default directory for the iFly stored Flight plans is `Prepar3D/iFly/737NG/navdata/FLTPLAN`

Remove .txt extension: 
[YSSYYMML.FLTPLAN.txt](https://github.com/albar965/littlenavmap/files/1856182/YSSYYMML.FLTPLAN.txt)

**Comment by albar965** [comment]
Done but needs testing.

**Comment by jockerfox** [comment]
Oh… YESSSS !

It was two months that I followed your work. Can I test 2.0?

If yes, where can I download for test it ?



Inviato da Posta per Windows 10

Da: Alexander Barthel
Inviato: domenica 15 aprile 2018 13:39
A: albar965/littlenavmap
Cc: Subscribed
Oggetto: Re: [albar965/littlenavmap] Export for iFly flight plan file (#231)

Done but needs testing.

**Comment by albar965** [comment]
Would be great if you could test it. Send me an email. Contact here: https://albar965.github.io/
But give me a few days. The beta is not finished yet.
Alex
