### ISSUE TITLE
Better managment for airspaces

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#236]
Load airspaces from external sources (not simulator and not Navigraph) into a separate database and allow to hide/show these for all simulators.

- [x] Import airspaces recursively from user defined folder
- [x] Enable/disable user airspaces in menu
- [x] Allow to assign airspace to online centers by name.

**EDIT:** Cannot support CSV format below since it is not documented:
[Airspace_AUT_Rev1(1).zip](https://github.com/albar965/littlenavmap/files/2439106/Airspace_AUT_Rev1.1.zip)

**Comment by Phil57** [comment]
Will that help making centers/radar for IVAO what they are on the network ? Or are they "private"/custom to IVAO ?

**Comment by albar965** [comment]
Hi Phil,
these are partially private. But there are sources around the net where you can get airspace files.
Alex

**Comment by albar965** [comment]
Done for now. Probably need another import format depending on VATSIM and IVAO (if) offer.
LNM currenly only does OpenAir.
