### ISSUE TITLE
Move out of Github

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#242]
For obvious reasons.

Alternatives:

1. Own hosted repositiory (best solution) - [Gogs](https://gogs.io) [Gitblit](http://gitblit.com) or [Gitea](https://gitea.io/en-US/) (more active).
2. [TeaHub](https://about.teahub.io/)
2. [Gitlab](https://about.gitlab.com/)
3. [Bitbucket](https://bitbucket.org/) - Atlassian
3. [Sourceforge](https://sourceforge.net/)
4. Freshmeat (least trustworthy - bundled downloads with adware in the past and is infested with ads)

Todo:
1. Move code
2. Move manuals
3. Move wiki
4. Export and import issues
5. Change links in program and pages

**Comment by RaimundNilsGunnar** [comment]
Hi Alex,
Eigentlich wollte ich gerne mit dir zusammen arbeiten (nur ganz wenig, weil
keine Zeit)...
Wie geht es dir?
Gruß
  Raimund (Grün)

Alexander Barthel <notifications@github.com> schrieb am Mo., 4. Juni 2018,
21:36:

**Comment by albar965** [comment]
Hallo Raimund,
long time no see. Mir geht es bestens und ich hoffe Dir auch. Schicke mir mal eine Mail. Der Kontakt ist auf der [Homepage hier](https://albar965.github.io/) oder in jeder Sourcedatei. :)
Viele Grüße
Alex

**Comment by mrconnerton** [comment]
MS has had a great track record with supporting open source software. I don't think its going to be a huge issue. With that said gitlab is cheap and has built in tools to migrate pretty much everything over.

**Comment by albar965** [comment]
Not sure. MS has a great track of destroying companies and technologies (Nokia, Skype, etc.). I don't trust them whatever they say.

For sure there is no hurry to move out but I'll keep an eye on the competition and see how it develops here.

Alex

**Comment by meltinglava** [comment]
Btw. Gitlab self hosted is also an option.

**Comment by albar965** [comment]
Self hosted is the best option IMO anyway. But there is still the download traffic problem. I have to find a provider which does not close the account after the first major release with the following download storm.

#238 is a bigger problem for now since GitBook is getting more and more unstable.

**Comment by albar965** [comment]
Postponed so far.
