### ISSUE TITLE
DeparturePosition in flight plan

### ISSUE THREAD

**Issue by lfpanto** [albar965/littlenavmap#243]
I do not know if it will happen the same in other languages, but in the case of Spanish, when saving a flight plan, in PLN format, in which the exit door of the corresponding airport has been established, when executing said flight plan in the simulator p3d v4.2, the aircraft is not located at the exit gate that has been specified.

After investigating a bit, I realized that in the flight plan file "PLN", in the section "DeparturePosition", where "GATE nº" should appear, Little Navmap had literally translated this parameter into Spanish as "PUERTA nº" , something that the simulator does not understand.

**Comment by albar965** [comment]
Thanks. And that is actually my error and not the translator's error. Some texts should not be translated at all.
Alex
