### ISSUE TITLE
Need IVAO mirror

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#244]
A full website is not needed. IVAO provides the information for centers and clients in two text files:

[status.txt](http://www.ivao.aero/whazzup/status.txt)
[whazzup.txt](http://api.ivao.aero/getdata/whazzup/whazzup.txt)

[Documentation for these files is here](https://ivao.aero/ViewDocument.aspx?Path=/).

LNM supports the Gzipped file download. The `status.txt` is downloaded by LNM on startup only. The `whazzup.txt(.gz)` is downloaded every one or three minutes. The latter one is the bandwidth critical file.

The `whazzup.txt(.gz)` can draw a lot of bandwidth with a size of around 100 KB, up to 800 clients online (what I've seen so far) and an update rate of one to three minutes. A lot of hosting services say that they do no limit bandwidth, but people get their account canceled anyway if an arbitrary limit is exceeded. So, you have to be cautious with that.

Only a cron job (or anything else) is needed to download the [whazzup.txt.gz](http://api.ivao.aero/getdata/whazzup/whazzup.txt.gz) periodically and to put it into a web server folder. If all is set up I can create a configuration file that points to the mirror site. I can post this file to the forums as an update and on my page.

You also need a clearance from IVAO. They will add your server to a whitelist and allow you to poll the files.

**Comment by albar965** [comment]
Mirror set up. Waiting for clearance from IVAO before release.
Alex

**Comment by joe-joachim** [comment]
Super das auch IVAO wieder geht! Falls man noch mit einem Mirror helfen kann, bitte melden. Meine Webpräz langweilt sich manchmal und vielleicht könnte ich hier helfen.

**Comment by albar965** [comment]
Hallo Joe-Joachim,
gerne. :-)

Dazu müsste ich in der Statusdatei [status.txt](https://www.littlenavmap.org/ivao/status.txt) einfach einen neuen Eintrag `gzurl1=https://www.WHEREEVER.de/ivao/whazzup.txt.gz` hinzufügen. LNM wählt die Server zufällig aus. Den Download von IVAO erledige ich mit folgenden Script, das einmal in der Minute ausgeführt wird:
``` shell
#!/bin/bash
cd /var/www/WHEREEVER/httpdocs/ivao
wget -q http://api.ivao.aero/getdata/whazzup/whazzup.txt.gz -O whazzup_dl.txt.gz
mv -f whazzup_dl.txt.gz whazzup.txt.gz
date -R --utc > whazzup_timestamp_utc.txt
```
Der Traffic hält sich im Moment noch in Grenzen. Seit dem 09.02. sind es 7GB aber da sind die Zugriffe auf die Online-Anleitungen mit enthalten.
Alex
