### ISSUE TITLE
Increase preformence on map when zoomed in.

### ISSUE THREAD

**Issue by meltinglava** [albar965/littlenavmap#245]
Finding it hard to move around the taxi map as there are alot of delay when moveing the map.

**Comment by albar965** [comment]
Is this X-Plane? Which airport? 
Some airports are not done very efficient and use a lot of large polygons. Known problem so far but good to have an issue for it.
I wouldn't wonder if these airports eat a lot of resources in the simulator too.
Alex

**Comment by meltinglava** [comment]
i use it with x-plane data. Have noticed it is bad for bought default airports and updated airports.
Airports i have noticed it in is airports like ENGM ESSA EGLL. Generally airports that have abit complicated taxiway layout.

**Comment by albar965** [comment]
Thanks. This is not so easy to fix. Probably have to split the complicated geometry into smaller parts. Have to see.
Alex

**Comment by albar965** [comment]
Drawing times for apron was >100ms before. Now not measurable (< 1ms).

**Comment by Phil57** [comment]
That one works really well !

**Comment by albar965** [comment]
Glad you like it. :)
Alex

**Comment by Phil57** [comment]
Hi @albar965 is there any chance I can get one of the beta of 2.2 somewhere ?
I have a feeling that this one was working a lot better in the betas than in the final release, but I'm not 100 sure

**Comment by Phil57** [comment]
It's running in a Win10 VM on a MBP. I'll try with an old version to check how it was before when I can. I may not remember that it was ultra slow before :)

**Comment by albar965** [comment]
Try 2.0.3 with a complex airport to experience the slowness. :-)
Alex
