### ISSUE TITLE
XP11 route error JD 330 Airbus

### ISSUE THREAD

**Issue by DemonRem** [albar965/littlenavmap#248]
XP11 Jar Desgin AIRBUS 330 support flight plan TXT 

using the littlenavmap 

the fmc say error the route not created

**Comment by albar965** [comment]
I need the flight plan.
Also, tell me which AIRAC cycle is used.
Is there a log file or a more detailed error message of the Airbus?
Alex

**Comment by DemonRem** [comment]
I try few 
[LLBGEDDT2.txt](https://github.com/albar965/littlenavmap/files/2111510/LLBGEDDT2.txt)

as I see for now in the flightplan directory it's all txt files

**Comment by albar965** [comment]
This is:
```
LLBG SID 3160N03454E DCT 3201N03451E DCT D265C DCT SIX DCT D260G DCT DEENA DCT BOAZZ DCT PURLA DCT LCRA DCT LTAI DCT LTBZ DCT BKZ DCT LB25 DCT LR82 DCT LRSV DCT UKLR DCT UMBB DCT EPMO DCT EPIR DCT EPBY DCT EPPI DCT DRE DCT ROGAB DCT OM26R DCT 5234N01319E STAR EDDT
```

Maybe the user defined waypoints (`3160N03454E`, etc.) are an issue. Can you try it again without these.

Like:
```
LLBG SID D265C DCT SIX DCT D260G DCT DEENA DCT BOAZZ DCT PURLA DCT LCRA DCT LTAI DCT LTBZ DCT BKZ DCT LB25 DCT LR82 DCT LRSV DCT UKLR DCT UMBB DCT EPMO DCT EPIR DCT EPBY DCT EPPI DCT DRE DCT ROGAB DCT OM26R STAR EDDT
```

**Comment by albar965** [comment]
BTW: Not sure if the airbus likes airports as intermediate destinations.

**Comment by DemonRem** [comment]
so I check it and report you airbus fmc read it in other way

**Comment by albar965** [comment]
I'm not sure what you mean. Did you test it already?

**Comment by albar965** [comment]
Closing since waited for more information. Reopen if needed.
