### ISSUE TITLE
Ground Speed For FMS 

### ISSUE THREAD

**Issue by DemonRem** [albar965/littlenavmap#249]
what Is the chance to fms support ground speed Legs section in FMC?

**Comment by albar965** [comment]
Not clear to me. Which FMC?

**Comment by DemonRem** [comment]
Boeing 747-800 Aircraft Computer, that will show the speed in the FMC it's called Legs

**Comment by albar965** [comment]
You're talking about the FLTPLAN export format? I think this has a groundspeed field which I could not identify yet.

**Comment by DemonRem** [comment]
correct

**Comment by albar965** [comment]
I have no idea which field that is and cannot find it in flight plans generated from others. 

If the iFly FMC can save flight plans: Can you send me a saved FLTPLAN file?
Alex
