### ISSUE TITLE
[question]Documentation of little navconnect

### ISSUE THREAD

**Issue by www2000** [albar965/littlenavmap#251]
Where can i find the documentation for the protocol that is use by little navconnect.

**Comment by albar965** [comment]
There is no protocol documentation and the protocol is binary. You can look at the classes here which cover all communication:
https://github.com/albar965/atools/tree/master/src/fs/sc
The SimConnect name is historically. The classes are used for X-Plane and network communication too.

The root class which is used to serialize data to sockets is this one:
https://github.com/albar965/atools/blob/master/src/fs/sc/simconnectdata.h
It aggregates all others.

**Comment by albar965** [comment]
Closing. Not an issue per se. Reopen if needed.
