### ISSUE TITLE
Map zoom pixelated

### ISSUE THREAD

**Issue by Phil57** [albar965/littlenavmap#253]
Hi,
the background maps like OpenStreepMap or OpenMapSurfer are not downloading correctly and end up being very pixelated when zooming in.

I think it was working correctly in the past, but it is has being acting up lately. (not sure about a precise date)

Is that "normal" or known ?

**Comment by albar965** [comment]
I use free services to fetch the maps and these can be offline from time to time. Sometimes it takes a day until they are back online. Use another theme until then. [OpenMapSurfer](http://korona.geog.uni-heidelberg.de/) seems to be unavailable right now.
Alex

**Comment by Phil57** [comment]
Thank you for your anwser.

**Comment by albar965** [comment]
Closing. Reopen if needed.

**Comment by Phil57** [comment]
I must add that I'm stupid and should have RTFM ...
I had issues with SSL connections and after installing Visual C++ Redistributable Package as mentioned in the docs, every single map work...

**Comment by albar965** [comment]
Thanks for the feedback.
I added a warning dialog to 2.0.3 which gives information if initializing SSL failed and how to fix it.

**Comment by Phil57** [comment]
That is definitely what helped me here :)

**Comment by albar965** [comment]
Glad it is working now. :-)
