### ISSUE TITLE
Simple aircraft performance

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#255]
Related to #38 but a first and simple step
Add new tab to flight plan window:
* Average climb rate
* Average fuel flow
* Move ToD rule from options to this tab
* Move TAS to this tab

Save for different aircraft
Detect values automatically
Draw climb phase in elevation profile.

https://www.skybrary.aero/index.php/Fuel_-_Flight_Planning_Definitions

**Comment by vranki** [comment]
Fuel calculations would be useful for IRL flying. I'd be happy if you could set max fuel amount per aircraft type and the flight plan would display used fuel and fuel remaining. Also there could be a warning if amount of fuel is less than safety limit (45 minutes).

**Comment by albar965** [comment]
All and probably a bit more than this done.

**Comment by Gulliver54** [comment]
Hi Alex,
I am eager to see a screenshot if possible.
A hand full changes but not everything as clear as a Crystal ball to me.
Thanks
Gradus

**Comment by albar965** [comment]
Here you go.
Alex
![auswahl_385](https://user-images.githubusercontent.com/15254956/47227066-7b884380-d3b1-11e8-9f43-024a3cbaee4d.jpg)

**Comment by albar965** [comment]
![grafik](https://user-images.githubusercontent.com/15254956/47227296-05381100-d3b2-11e8-9451-debfbed40511.png)

**Comment by Gulliver54** [comment]
Hi Alex,

Thanks for the screenshots.

🍺
