### ISSUE TITLE
Warning dialog when switching to Navigraph only

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#262]
Show a warning dialog with help button when users switch to Navigraph only data to avoid confusion about missing aprons and other stuff.

**Comment by albar965** [comment]
Done. Now showing warning dialog with link to manual.

**Comment by Gulliver54** [comment]
Hi Alex,

Is it possible that LNM starts up, after an update, in the Navigraph only status?

I received from 4 people in The Netherlands a problem that they could not see the afcad (building and parkings) anymore after an update. Knowing this problem, it was easy to fix.
I did no investigation whether this was a changed setting by the user!

Regards
Gradus

**Comment by albar965** [comment]
Hi Gradus,

did they exit LNM before running the update? I have to check if LNM does any weird things when the database is locked. Normally it throws an error dialog.

A lot of people run into problems when switching to this "Navigraph only" mode. Got a lot of emails about this.

The message below should help if users switch accidentally to this mode:
![grafik](https://user-images.githubusercontent.com/15254956/46316818-b2dcaf00-c5c0-11e8-8dd9-aceaec6efa14.png)

Best
Alex
