### ISSUE TITLE
Insert flight plan at position

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#264]
Menu item in flight plan table that allows to insert a flight plan or snipped after the clicked leg.

**Comment by Gulliver54** [comment]
Most welcome. Thanks

**Comment by Gulliver54** [comment]
Thanks Alex. Great show

**Comment by albar965** [comment]
It was a bit more work than expected since I have to drop and add procedures depending on source and current flight plan. 
I like that the imported legs are now selected after import which helps to see what is new.
Alex
