### ISSUE TITLE
Improve map context menu

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#270]
Display sub menus if several items are available for a function like: Show information for airport, VOR, etc.
Use a more precise selection which fills only one tab in the information window.

**Comment by Gulliver54** [comment]
Procedure right now:
If I disable tab logbook ect. in Information tab, and click on a logbook entry Search ,the tab logbook is shown in tab information. Smart!
When i leave logbook in Search the tab logbook remains inside Information.
 
Why not remove the tab logbook in Information so the initially setup Information tab choices (set by user) is restored?

**Comment by albar965** [comment]
> Why not remove the tab logbook in Information so the initially setup Information tab choices (set by user) is restored?

Well ... by what critera? When the mouse leaves the window? User clicks on anything else? I suppose closing windows automatically might annoy users.
Alex

**Comment by Gulliver54** [comment]
Criteria: 1. when activating an other Information Tab,  and 2 restarting LNM.

**Comment by albar965** [comment]
![grafik](https://user-images.githubusercontent.com/15254956/89554203-d604c500-d80e-11ea-93ea-ed764c71dec5.png)
![grafik](https://user-images.githubusercontent.com/15254956/89554251-e74dd180-d80e-11ea-84f9-1e623aff98d0.png)
