### ISSUE TITLE
Dock window focus on mouse over

### ISSUE THREAD

**Issue by merspieler** [albar965/littlenavmap#276]
I'd expect the active dock window to be the one beneath my cursor. This isn't the case but it would make life much easier if you don't have to click a dock window (and maybe select something unwanted with it)

Example situation:
I look up procedures of an airport. One procedur is outside the current map view so i move the map. When i now return to the procedures window and i press the <Down> key to continue in the list, the map moves instead of the list selection tho the mouse is over the procedure window.

**Comment by albar965** [comment]
Have to see if that is doable without messing up Qt's event loop. 

What could also help:
- Implement Ctrl+Tab functionality to switch between dock windows and tabs.
- Fix inconsistencies for shortcuts: Alt+Left works on all windows but left not.

**Comment by albar965** [comment]
Done as of 2.6
