### ISSUE TITLE
Crab Angle

### ISSUE THREAD

**Issue by Gulliver54** [albar965/littlenavmap#284]
Hi Alex,

Regarding crab angle in compass rose :

In the picture below you see that the track/course to reach next waypoint from current position is 256º
Heading needed to reach 256º is roughly 301º .
Basically, you find this crab angle by trial and error. Look at the track line and centre it on the desired track and the result is your heading.

Question:
Can you add the calculated crab angle (298º) in the window "Progress"? It makes things easier. It prevents me from doing that arithmetic by myself.  (The correct aircraft heading is a result  from this arithmetic = 256º+42º=298º)

Perhaps you find room on the compass rose to display the crab angle also. I don't really know if this is doable or necessary. Perhaps it is more disturbing than advantages.   

![07-13-01](https://user-images.githubusercontent.com/33782220/43676828-a8bde228-97f8-11e8-8bfb-2aecb92096c7.jpg)

**Comment by albar965** [comment]
Related to #285
Will add the crab angle to the progress window and compass rose too (probably later).
Thank you for the example and clear description.
Alex

**Comment by albar965** [comment]
Added crab angle to aircraft progress and compass rose. Also showing course to next WP in compass rose.
Additionally added a "more/less" switch to the progress display to hide less important values.
