### ISSUE TITLE
Polar view in spherical projection does wierd things to some procedure parts.

### ISSUE THREAD

**Issue by merspieler** [albar965/littlenavmap#287]
When in spherical projection, as soon as the center of view approaches the north pole, some parts of the route go crazy:  
![bug](https://user-images.githubusercontent.com/29063255/44006645-e48a8726-9e87-11e8-9a8f-9b6aaa790d23.png)

The problematic parts seem to be the holding pattern and the curve after passing 2000ft on departure.

[ziped flightplan seen in the image](https://github.com/albar965/littlenavmap/files/2281361/IFR.Zurich.LSZH.to.Miami.Intl.KMIA.zip)

**Comment by albar965** [comment]
Thanks for reporting. It is already partially fixed in the current development version but some parts in your example are still freaking out. Will fix. 
There is no need to draw bows, curves and holds at this zoom level.
Alex

**Comment by albar965** [comment]
Fixed by switching off labels and curves at high zoom factors.
Small problems like disappearing flight plan legs can still happen but labels should not freak out now.
