### ISSUE TITLE
Manual weather setting

### ISSUE THREAD

**Issue by vranki** [albar965/littlenavmap#290]
For IRL flight planning it would be useful to be able to set weather (mostly wind) manually.

Probably it would be enough to add a dialog to set manual weather and checkbox in settings to use it instead of simulated or actual weather.

**Comment by albar965** [comment]
Good idea to do this manually until  #283 is done.
Also related to #255. Probably I can fix this together with #255. Have to see.
Alex

**Comment by albar965** [comment]
#283 is done and it still allows to set cruise wind manually. LNM even allows to display wind barbs at route waypoints for this manually set wind (interpolated to ground).
