### ISSUE TITLE
Drag file plan (from a file manager) to LNM

### ISSUE THREAD

**Issue by gaabne** [albar965/littlenavmap#291]
Would be helpful for quick display of a .pln when flight plan folder contains a lot of files...
Thank for a future release...

Gérard

**Comment by albar965** [comment]
Hi Gérard,
thanks for creating the ticket. :-)
I had this only on my internal TODO list for now.
Alex

**Comment by gaabne** [comment]
Thanks

**Comment by albar965** [comment]
Moved to 2.2 and implemented already. Needed for testing many flight plans.

**Comment by gaabne** [comment]
Hi Alex,
> Needed for testing many flight plans.

Thank you so much. Have a lot of different flight plans to test it during the beta !
Gérard
