### ISSUE TITLE
Display altitude restrictions in elevation profile

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#298]
Let descent and ascent lines follow altitude restrictions in a simple way (always use lowest value - this is not a FMC).
Probably display limitations graphically in profile.
Follow up for #34.

**Comment by albar965** [comment]
Whew! This was quite a piece of work. But now it is good. :)
Limitations are displayed, TOD and TOC adhere to altitude restrictions and are calculated considering them.

![grafik](https://user-images.githubusercontent.com/15254956/46172597-70029a80-c293-11e8-805d-5234009cf41c.png)

**Comment by Gulliver54** [comment]
Awsome peace of work Alex.

The two sliders at the right side are they functional regarding zooming in horizontally and vertically?

**Comment by albar965** [comment]
>The two sliders at the right side are they functional regarding zooming in horizontally and vertically?
Exactly. There is much more. I also added a context menu, scrolling with mouse drag and drop, zooming with the mouse wheel, keyboard navigation like the map, etc. The profile now has almost as much functionality as the map.
Currently working on #299 where I already added ILS and VASI display.
Alex

**Comment by antoonh** [comment]
When creating a flightplan from EHAM, RWY27, SID GORL1P with 2.2.1-beta, the first waypoint is described by AIS-NL as follows: "Climb on course 267° MAG, at or above 500 ft AMSL turn right". 

With the first SID waypoint being fixed in space near the far threshold of RWY27, LNM will generate a "cannot comply with altitude restrictions". It would be great to be able to suppress altitude compliance for waypoints like these.
![image](https://user-images.githubusercontent.com/14786141/48198275-9dde0300-e358-11e8-8212-3b78f18d8a22.png)

**Comment by albar965** [comment]
This is an error. Have to check. Other similar altitude restriction have no problems.

**Comment by albar965** [comment]
Plenty thanks for the report. Fixed now.
Alex

**Comment by antoonh** [comment]
on the presumption that you pushed this fix to the beta channel: my current LNM (2..2.1-beta) doesn't report a new update available :-)

**Comment by antoonh** [comment]
Testing now with arriving at EGHI, STAR EAS1B arriving RWY 20. (I tested from EHGG, without a SID activated yet) It suggests it cannot comply with altitude restrictions.

**Comment by albar965** [comment]
You have to set cruise altitude at or above 16.000 ft because there is an "at" restriction in EAS1B.
Alex

**Comment by antoonh** [comment]
Understood. Not sure where that came from. Meant for FL200. It would be helpful if the warning reported the actual waypoint in the plan that has the altitude restriction that can't be met. In this case OCK

**Comment by albar965** [comment]
Yup. Makes sense. I noted this for future versions. Probably 2.2.X
Alex

**Comment by mtadeu** [comment]
Hello @albar965,

I'd like to express strong interest in this feature and provide a specific use case that would greatly benefit from altitude restrictions and step climb capabilities.

Use Cases:

**IFR Long-haul flights**: Step climbs (e.g., FL350 → FL370 → FL390) for fuel efficiency, common in airline operations.

**VFR Visual Corridors**: Flying through controlled airspace with mandatory altitude changes at different corridor segments (e.g., Class B transitions, coastal routes, mountainous terrain corridors where specific altitudes are required for different segments).

**Current Limitation**: While Little Navmap excels at flight planning, the single cruise altitude restriction limits realistic route planning for complex flights that require altitude changes mid-route.
Suggested Enhancement: Building on your concept of following altitude restrictions in the elevation profile, could this also support user-defined step climbs? This would complement the existing "Edit Flight Plan Position" functionality by allowing altitude changes at specific waypoints to be visually represented in the profile.
The **step climb** concept has been discussed in issues #295 and #166, and could potentially be integrated with this altitude restriction framework for a comprehensive solution.

**Benefits**:
Enhanced realism for both IFR and VFR flight planning;
Critical for VFR corridor navigation with mandatory altitude restrictions;
Better integration with external tools like SimBrief (which supports step climbs);
Visual representation of planned altitude changes in the elevation profile;
Compliance with airspace requirements in complex terminal areas.

This feature would significantly improve Little Navmap's capabilities for advanced flight planning scenarios.

 **Thank you** for considering this enhancement and for the **excellent work on Little Navmap**!

Looking forward to any developments on this front.
-- 
Marcos Tadeu
[](https://youtube.com/@sobrevoandobra)
