### ISSUE TITLE
Calculate magnetic declination

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#300]
Calculate magnetic declination on the fly for current year instead of using fixed files.

http://www.edwilliams.org/avform.htm#Var

https://github.com/FlightGear/simgear/tree/next/simgear/magvar

**Comment by jdvalleiz** [comment]
Hi there,

Why not use the WMMCOF from https://www.ngdc.noaa.gov/geomag/WMM/soft.shtml
I think that X-Plane use this coefficient file (WMM.COF). it brings declination for a location (lat/lon) and a precise date (day). Therefore it's not a bunch of static values and it agrees with X-Plane values, moreover it can covers 5 years accurately (2015-2020 for WMM2015COFv2).

Many thanks for your work Alex, please keep up the great job!

**Comment by albar965** [comment]
Thank you for the link! Very helpful.  :-)
I'll add the WMM software to the atools library once this issue is due. This seems to be the most accurate solution so far.
Alex

**Comment by jdvalleiz** [comment]
Alex,

Glad that it can contribute to LNM jewel!

You can find libraries to use the WMM.COF here : 
https://www.ngdc.noaa.gov/geomag/WMM/thirdpartycontributions.shtml

I use daily the python version (Christopher Weiss contribution on the page above) and it sticks very well with values provided through X-PLANE : magnetic bearings without crosswinds on long legs are very precise.

Cheers!
Jean-Eudes

**Comment by jdvalleiz** [comment]
You are perfectly right. Long haul navigation is not as simple as it appears.
Dead reckoning navigation (beyond VOR/NDB range) is always a challenge, but it's also so fun.

Regards,
Jean-Eudes

**Comment by gaabne** [comment]
I fear the inconsistencies that this may rise with the magdec.bgl used by the sim (FSX or P3D).
To limit them, I copy the one used by the simulation to LNM mapdec directory.

Does this make sense ?

Regards
Gérard

**Comment by albar965** [comment]
Hi Gérard,
not needed. LNM uses the FSX/P3D magdec.bgl if present in the scenery library. The included one is a fallback for X-Plane. You can see that in the log file:
`... Reading ".../Prepar3D v4/Scenery/BASE/Scenery/magdec.bgl"`
Alex
