### ISSUE TITLE
ETA Online aircraft

### ISSUE THREAD

**Issue by Gulliver54** [albar965/littlenavmap#303]
Hi Alex,
Below you see a screenshot from online aircraft with destination LEBL.

![09-23-01](https://user-images.githubusercontent.com/33782220/45927069-e323ae00-bf2d-11e8-9c5e-8112e59c0f0b.jpg)

It would be most welcome if you can add a column with ETA. 
In that case a pilot can try to figure out his speed to manoeuvre himself in a landing strategy sequence with the other air planes heading for the same destination.
Perhaps notation in Online Clients also?
![09-23-02](https://user-images.githubusercontent.com/33782220/45927075-f0409d00-bf2d-11e8-89c6-9c887efed0af.jpg)

It will be an approximation because the program can't figure out the different landing procedures of all the aircraft, but in cruise mode it will give you some pretty good information.

Perhapse, because of performance reason,  only calculate ETA if a valid destination has been entered in the online client destination box.

Gradus

**Comment by albar965** [comment]
Will have a look at it. I'm currently busy with profile stuff which takes much longer than expected.
Alex

**Comment by Gulliver54** [comment]
Take your time. An example:
![20181005_024214](https://user-images.githubusercontent.com/33782220/46510459-69eb5b80-c849-11e8-944f-14fd9b26d013.png)
#

**Comment by albar965** [comment]
Looking at it a second time, it seems easy. Departure and enroute time are available and do not need any calculation or flight plan parsing.
Simply adding the ETA column to the table should suffice.
Alex

**Comment by albar965** [comment]
Added ETA to search table and information tab and formatting time better now.
Feel free to reopen or comment if something is missing.
Alex
![grafik](https://user-images.githubusercontent.com/15254956/46528745-0c283500-c884-11e8-9a0a-c36a2da9bb73.png)

**Comment by Gulliver54** [comment]
great stuff Alex,
Thanks for the swift action.

Just checked webeye and saw DLH755 is scheduled for landing 16 minutes later than in your screen shot. Great.
Now I have the problem to wait for this new enhancement until the next release. But never mind that. It's all in the game.

High regards
Gradus

**Comment by Pilotwillem** [comment]
Witch url do you use  for to gt this data in littleNM. ( I use https://opensky-network.org/api
) but the aircraft didn't show up. any idea?

**Comment by albar965** [comment]
https://status.vatsim.net/status.txt or http://www.ivao.aero/whazzup/status.txt 
various URL extracted from these files.
The latter one is actually mirrored by me but the content is the same.
OpenSky-Network is not supported.
Alex
