### ISSUE TITLE
Highlight clicked airspaces on the map

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#308]
Highlight airspaces if clicked in the information window.

This is only a part of the bigger task to improve airspace handling.

Part of  #146

**Comment by jockerfox** [comment]
Beautifully ! [*THUMBS_UP*]




------ Messaggio originale ------
Da: "Alexander Barthel" <notifications@github.com<mailto:notifications@github.com>>
A: "albar965/littlenavmap" <littlenavmap@noreply.github.com<mailto:littlenavmap@noreply.github.com>>
Cc: "Subscribed" <subscribed@noreply.github.com<mailto:subscribed@noreply.github.com>>
Inviato: 02/10/2018 23:32:53
Oggetto: Re: [albar965/littlenavmap] Highlight clicked airspaces on the map (#308)


Closed #308<https://github.com/albar965/littlenavmap/issues/308>.

**Comment by albar965** [comment]
It is only a slight improvement, but it is. There is a lot more to do with the airspaces but I have to back off a bit, otherwise this release will never be finished.
Alex
![grafik](https://user-images.githubusercontent.com/15254956/46422930-e59fb800-c724-11e8-8eca-7d7d68e657d4.png)
