### ISSUE TITLE
Show Navaids from search bar?

### ISSUE THREAD

**Issue by martinlest** [albar965/littlenavmap#312]
Hi. Just a small thing, but I found it really useful when making flight plans - now it's gone. Must be something I did, but I have tried for some days to 'fix' it, with no luck...

When I typed a navaid identifier into the Navaids tab of the search pane, the navaid (or list of those with the same name, along with their co-ordinates) used to appear in the pane below. I could right-click one and choose to add it to a flight plan. Now, typing a navaid into the search box brings up nothing.. I have tried dozens of navaids now with the same result (zero!). If I type an airport ICAO in the airport search tab, the airport shows up fine.. 

How do I reset/get this to work again please? Nothing I have tried has worked. Many thanks.

**Comment by albar965** [comment]
Hi Martin,
try context menu in result table and then `Reset Search` or `Ctrl+R`. Usually there is some other obscure option selected which hides all results.
Alex

**Comment by martinlest** [comment]
Ctrl+R did the trick. many thanks!
