### ISSUE TITLE
[BUG] Flight Plan FOR PMDG 747 Error

### ISSUE THREAD

**Issue by DemonRem** [albar965/littlenavmap#315]
when I finished my flight plan over  the tool and importing it to the aircraft it's say NOT IN DATABASE
the simulator is Prepar3D V4

**Comment by albar965** [comment]
Does this happen for all flight plans or only one? Probably AIRAC mismatch?
Please attach the flight plans, both(PLN and RTE.
Alex

**Comment by DemonRem** [comment]
for all of them I also tried to import both of them i already updated the prepar3d AirAC , does i need to do so for littlenavmap?

**Comment by DemonRem** [comment]
Solved

**Comment by albar965** [comment]
How?
Alex
