### ISSUE TITLE
New Format for the Modify 738-900  (FMX)

### ISSUE THREAD

**Issue by DemonRem** [albar965/littlenavmap#325]
Dear @albar965 
i make my own flight plan in fmx <plane format>
include ground speed approach ILS waypoint and deparure take a look at the plan

more info on the plane :

https://forum.thresholdx.net/topic/201-download-links-license/
[FlightPlan.zip](https://github.com/albar965/littlenavmap/files/2640213/FlightPlan.zip)

**Comment by albar965** [comment]
You have any documentation for the format? E.g. where and why should I add DISCONNECT in a flight plan file?
Alex

**Comment by DemonRem** [comment]
on the fmc he dispaly that discontiyu after before ILS i dont know why so this is the output plan the same as the fmc

**Comment by albar965** [comment]
Seems this is not needed since the Zibo mod can load X-Plane FMS files:
https://forums.x-plane.org/index.php?/forums/topic/167360-cant-get-flight-plans-to-load-properly-in-zibo-fms/&

The FMX format is apparently only an internal format which is rarely used.
Alex
