### ISSUE TITLE
Add holding pattern to map

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#326]
Similar to airport traffic pattern but for holds which can be placed manually and are pure display objects independent of the flight plan.

#363 will come later and show enroute holds from Navigraph and X-Plane data.

**Comment by Gulliver54** [comment]
Hi Alex,
I suppose holdings will have a 
starting point from waypoint/nav aid.

Is it also possible to give the user an option to draw a (few) radial(s) from a waypoint/nav-aid? (Usefull for ATC purposes and pilots intercepting a given radial or vfr planning).

Perhaps make one menu for both, holding and radial. (Sort off "display airport traffic pattern...)

Regards,
Gradus

**Comment by albar965** [comment]
Can add a starting point like the measurement lines. Not a big problem.
Radials: Not sure. Isn't that already covered by the measurement lines? They change color and label if you start drawing them from a radial.
![grafik](https://user-images.githubusercontent.com/15254956/57537436-c9589f00-7335-11e9-8ff3-0d4e7bc3bd4f.png)
Alex
