### ISSUE TITLE
User aircraft updates are not smooth

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#33]
Try to use floating point position on highest update rate.
Additionally create a mode that follows the map constantly (no boxed mode).

**Comment by albar965** [comment]
I got reports that the new 2.0.2 does not update aircraft positions. Will look at it and fix it for a 2.0.3.
The click should not be necessary. This is bug.

Other player positions: You mean online network aircraft (orange) or the while simulator AI?

But this is unrelated to this issue.
Alex

**Comment by mrconnerton** [comment]
Today is actually the first day I have used the app. When I connect to multiplayer the white aircraft from other users are the ones I was tracking that were not updating

**Comment by mrconnerton** [comment]
Yes on 2.0.2. Don't have it all open at the moment. Will post a screenshot when I do. In the meantime I'm using the top option to connect, 100ms everything checked.
