### ISSUE TITLE
MORA shown only when using Navigraph for procedures

### ISSUE THREAD

**Issue by mastazi** [albar965/littlenavmap#331]
This is a problem regarding the new feature "Show Minimum Altitude (MORA)".

My copy of X-Plane has a different AIRAC compared to the Navigraph included in Littlenavmap, so sometimes I end up selecting an approach in Littlenavmap, but that approach is not available in the X-Plane in-game GPS. To avoid this problem I have selected "Do not use Navigraph database". 

However when I select that option, the feature  "Show Minimum Altitude (MORA)" is not available any more.

I think that maybe the minimum altitudes are taken from Navigraph? If so maybe we could have an option "Use Navigraph only for MORA but not for procedures"?

**Comment by albar965** [comment]
Right. Agree. If the data is there (a Navigraph database is present) it should be displayed always. No matter what is set in the menu.
Alex

**Comment by albar965** [comment]
Done. Now always displayed.
