### ISSUE TITLE
Airplane icon elevation profile

### ISSUE THREAD

**Issue by Phil57** [albar965/littlenavmap#332]
![capture](https://user-images.githubusercontent.com/10242493/49870675-61e50480-fe14-11e8-8b16-e5f427779120.PNG)

Using LNM 2.2.2 (Windows version) the airplane icon is all squished on the Elevation Profile.

**Comment by albar965** [comment]
That's on purpose to give the impression of a side view. This was easier than duplicating 18 (aircraft type, ground, user or AI, etc.) icons for a side view.
Alex

**Comment by Phil57** [comment]
Roger that 👍
