### ISSUE TITLE
Consider wind when calculating TOC and TOD

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#339]
Consider average wind as given in the GUI or downloaded from NOAA or X-Plane when calculating top of climb and top of descent.

This help to avoid too high or early approaches at the destination.

**Comment by Gulliver54** [comment]
Hi Alex,
GUI. Graphic user interface.
_**Quote "Consider average wind as given in the GUI or downloaded from NOAA....."**_
Does this mean that winds produced by the sim are also used?
Can I choose between NOAA and Sim weather?

**Comment by albar965** [comment]
Hi Gradus,

the old method where you can select wind direction and speed at cruise manually is still available. That's what I was referring to "given in the GUI".

NOAA is a six hour forecast updated four times a day. X-Plane uses the same format (GRIB2) and therefore I can offer the option to read the wind file downloaded by X-Plane.

FSX/P3D have neither programming interface nor a file which allows me to access the high altitude winds. At least the file format is not documented. No wind access for P3D, therefore.

ActiveSky gives the winds only per airport and not in a one-degree grid which would require quite some effort to display this in LNM. This will maybe come in a future version.

In any case you can use the NOAA wind option since all (P3D, AS, X-Plane) use it as a source, I suppose.

Alex
