### ISSUE TITLE
Add zoom and scroll functionality in elevation profile

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#34]

**Comment by Gulliver54** [comment]
Can you change aircraft picto, nose-down in descent and nose-up in ascent?

**Comment by albar965** [comment]
Should be doable. Rotating the icon is not a big deal. I just have to calculate the aircraft deck angle.
Alex

**Comment by gaabne** [comment]
Yes :)
Thank you for having included this in Release 2.2 objectives.
It is my dream since the very first release of LNM 
Gérard

**Comment by albar965** [comment]
It's my dream too. :-) This is the most limited part in LNM but a lot of work to fix it.
Alex
