### ISSUE TITLE
Show aircraft range on map

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#341]
Display an aircraft range ring on the map based on current fuel flow and fuel in tanks.

**Comment by Gulliver54** [comment]
I hope this range ringe is prioritised over #367 or stands out clearly because I consider #340/341 as more important.

**Comment by albar965** [comment]
#367 is required for this one. No usable fuel number, no range ring. All these three issues are not too much effort (unlike the high altitude winds, for example).
Alex
