### ISSUE TITLE
Show nearby navaids for airport

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#344]
Add the navaids nearby an airport to the airport tab or a new one.

**Comment by Gulliver54** [comment]
Hi Alex,
There is a tab Navaids available in "Information" Perhaps you can use this one.
Supplementary; Is it an idea to import also available waypoints/procedure points in this tab within 20 miles radius from the airfield.

**Comment by albar965** [comment]
I'd probably add these to a new tab which is messy until #345 is done.
Alex

**Comment by albar965** [comment]
Added extra tab to show two lists for selected airport:

- Nearest radio navaids until 50 NM distance maximum of 15 rows.
- Nearest airports having procdeures until 50 NM distance maximum of 15 rows.

Can be changed/extended easily but more will affect performance.

**Comment by Gulliver54** [comment]
🔝
