### ISSUE TITLE
Improve Logbook

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#346]
Move logbook entries to own database, search tab and info display.
Merge entries for one flight

**Comment by albar965** [comment]
Agree. This is going on my nerves too. I added this to 2.4.

The 2.4 list of changes needs cleanup. A lot of issues in 2.4 will be moved to later versions.
Alex

**Comment by Gulliver54** [comment]
Great stuff, can`t wait to see. 
:)

**Comment by albar965** [comment]
Yep. I like it too. ;-)
Now I have to finish at least one flight without writing down a bunch of bugs.:(
Alex

**Comment by Gulliver54** [comment]
Can you make a screenshot showing the available database colums during the checkout flight?

**Comment by albar965** [comment]
Give me a few days to fix bugs and find time for a flight. :)
Alex

**Comment by gaabne** [comment]
Hello Alex,
Great new !
Would you mind giving the new database format of the logbook.
Just to start thinking what can be collected from...
Gérard

**Comment by albar965** [comment]
Hi Gérard,
shortcut to the self explaining SQL:
https://github.com/albar965/atools/blob/master/resources/sql/fs/logbook/create_logbook_schema.sql
Will post screenshots later.
Alex

**Comment by albar965** [comment]
Hi Gérard,
shortcut to the self explaining SQL:
https://github.com/albar965/atools/blob/master/resources/sql/fs/logbook/create_logbook_schema.sql
Will post screenshots later.

CSV Export sample:
```
aircraft_name,aircraft_type,aircraft_registration,flightplan_number,flightplan_cruise_altitude,flightplan_file,performance_file,block_fuel,trip_fuel,used_fuel,is_jetfuel,grossweight,distance,distance_flown,departure_ident,departure_name,departure_runway,departure_lonx,departure_laty,departure_alt,departure_time,departure_time_sim,destination_ident,destination_name,destination_runway,destination_lonx,destination_laty,destination_alt,destination_time,destination_time_sim,simulator,description
Beech,BE58,N45XS,,3000,/home/alex/Nextcloud/Flight Simulator/Flightplans/IFR Reichelsheim (EDFB) to Aschaffenburg (EDFC).pln,,0,0,40.932739,0,4607.231934,25.785984,31.994833,EDFB,Reichelsheim,,8.878667,50.338665,402,2019-07-11T23:26:53.435,2019-07-11T06:04:16.000Z,EDFC,Aschaffenburg,08,9.062500,49.938835,410,2019-07-11T23:39:26.908,2019-07-11T06:17:01.000Z,X-Plane 11,
```

Alex

**Comment by albar965** [comment]
Logbook entry information in separate tab and logbook search. All separate now and not mixed with the user waypoints. Logbook entry is shown with blueish text background and line.

Track and actual flight plan are not saved yet. I keep this for the next version. Otherwise 2.4 would never be finished.

![grafik](https://user-images.githubusercontent.com/15254956/61484326-3ae44780-a98e-11e9-9979-f40ba40b623c.png)

Alex

**Comment by albar965** [comment]
Edit dialog has three tabs. The third tab contains only the description.

![grafik](https://user-images.githubusercontent.com/15254956/61484670-e8eff180-a98e-11e9-8b0a-34d1c7757c81.png)
![grafik](https://user-images.githubusercontent.com/15254956/61484721-04f39300-a98f-11e9-93fc-4c17947cba3c.png)

**Comment by Gulliver54** [comment]
most useful. 
Thanks for the overview.

**Comment by albar965** [comment]
You're welcome. :) Let me know if something is missing.
Some parameters like night (difficult) and IFR flying time (no idea how to find out) cannot be added.
Alex
