### ISSUE TITLE
Highlight airways like airspaces

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#348]
Add map link and "remove highlights" to a separate airway tab.
Clicking the link shows the whole airway.

**Comment by Gulliver54** [comment]
I fancy this enhancement.

**Comment by albar965** [comment]
Since it is not terribly much effort, why not put this into 2.4. :-) 
Have to weed the 2.4 release a bit out anyway and postpone the less useful stuff.
Alex

**Comment by Gulliver54** [comment]
Hi Alex
Do you plan to highlight NAT and PACOT tracks also, once available #82?

**Comment by albar965** [comment]
Hi Gradus,
yes. I'll definitely reuse this functionality when implementing #82. That NAT/PACOT issue is a huge task because it affects map display, route calculation and more. This has to wait for 2.6.
Alex
