### ISSUE TITLE
Flight plan transfer to flight simulator and back

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#35]
Once the flight plan changes in Navmap automatically copy it to FSX computer and call
SimConnect_FlightPlanLoad.

If a flight plan  changes in the simulator load it:
SimConnect_SubscribeToSystemEvent with FlightPlanActivated parameter.

Check if this is also doable for X-Plane.

**Comment by daheise** [comment]
I notice this feature is from 2016 - given the release of MSFS2020, is it safe to assume support for it is planned, and not just FSX?

**Comment by albar965** [comment]
This even more important for MSFS but needs some time. Probably have to change the communication protocol.

**Comment by Kebas53** [comment]
Would like this option very much for MSFS2020.
1 vote for me

**Comment by daheise** [comment]
So, I'm trying some naive stuff using [Python-SimConnect](https://pypi.org/project/SimConnect/) with MSFS2020 that might save you some troubleshooting down the line. Here is my naive code:

```python
sm = SimConnect()
print(sm.load_flight_plan("path to .pln"))
sleep(5)
sm.exit()
quit()
```

I'm testing with the MSFS2020 Cessna 172 G1000.

I have found a few interesting things.

1. If I load up a plane with no flight plan, and run this code, everything populates into the G1000 and everything is happy.
2. If I load a flight plan, and then attempt to load a new flight plan over the top, the CDI/PFD updates accordingly, but *not* the FPL in the G1000. The old waypoints remain, but none are shown as active.

In situation (2) if I delete the flight plan, I can load up a new one but the same issue persists - no waypoints. No active leg.

Now, if I reload the aircraft (using developer mode), whatever the last plan I called with `sm.load_flight_plan` appears correctly. However, this comes with other MSFS oddities like the avionics brightness being nonadjustable (at least on the C172 G1000).

**Comment by albar965** [comment]
@daheise Plenty thanks for the research. I looks like MSFS needs more time to get this stable. 😞
Quite annoying there is no way to change the flight plan without restart.

**Comment by daheise** [comment]
There's an issue on the MFS forums here that can be voted on: https://forums.flightsimulator.com/t/better-support-for-simconnect-flightplanload/307388

**Comment by albar965** [comment]
Thanks. Voted. Will watch this.
