### ISSUE TITLE
Display enroute holds

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#363]
Related to #326 but shows official holds and no user defined.

http://developer.x-plane.com/wp-content/uploads/2018/12/XP-HOLD1140-Spec.pdf

**Comment by Gulliver54** [comment]
Hi Alex,
Are en-route holds always visible (perhaps only visible if ticked in a menu) on the map, or does it come with as an extra option in the context menu together with user defined holds?

**Comment by albar965** [comment]
The en-route holds can be hidden like all other map features in menu `View` -> `Navaids`.
The user holds are a different animal can be hidden in `View` -> `User Features` as before.
Alex

**Comment by albar965** [comment]
![grafik](https://user-images.githubusercontent.com/15254956/150560926-553822f3-95e5-4b82-a364-7d0f63018f5b.png)
