### ISSUE TITLE
Userpoint picto covering Airfield pictogram

### ISSUE THREAD

**Issue by Gulliver54** [albar965/littlenavmap#366]
Hi Alex,
When I enable "display userpoints" on the map, the logbook picto is covering the airfield pictogram. Can you place it beside airfield picto?
![01-04-01 eham](https://user-images.githubusercontent.com/33782220/50690498-d420c180-102d-11e9-8f3f-426ed5c0c8b3.jpg)

Best wishes for 2019
Gradus

**Comment by albar965** [comment]
Similar to the weather icon. Can do that. This is going on my nerves too.

Note that the logbook entry has no relation to the airport. Therefore I can only add an offset to the position of all logbook icons. 

Other userpoint types won't change.

Alex

**Comment by albar965** [comment]
Hotspot is now top left. Moving it more away would be confusion because the hotspot remains above the airport.

![grafik](https://user-images.githubusercontent.com/15254956/50726443-e91c5400-1104-11e9-9573-0bff56c46894.png)

**Comment by Gulliver54** [comment]
Enough room to tick picto.
Thanks.
