### ISSUE TITLE
Feature reuqest: Use font, designed for cockpits

### ISSUE THREAD

**Issue by merspieler** [albar965/littlenavmap#373]
There's the B612 font designed by Airbus (and others) to get the "perfect" font for cockpits.

It is open source so I tought it would be nice if LNM uses it.

**Comment by merspieler** [comment]
Forgot to link it: http://b612-font.com

**Comment by albar965** [comment]
Seems to be quite easy in Qt to load and change the program font. I added a few quick INI file options to change the GUI font for the next 2.2.4:
```
[Options]
GuiFontFamily=B612
GuiFontFile=b612-master/TTF/B612-Regular.ttf
GuiFontPixelSize=12
```
Will remove these settings in 2.4 and put them into the options dialog.
