### ISSUE TITLE
Auto zoom in just before landing

### ISSUE THREAD

**Issue by cmtekin** [albar965/littlenavmap#374]
Hi @albar965  thanx for this excellent tool.

Is it possible to zoom in (down to readable taxi ways and parking spots) just before touchdown in order to enable easier taxiing after landing?

**Comment by albar965** [comment]
I think the settings below can achieve this. LNM zooms close to the destination airport (and all waypoints) when approaching. This will be close enough to see taxiways and parking.

The two lower marked boxes allow you to move around in the map while flying.

![little navmap - options_041](https://user-images.githubusercontent.com/15254956/51871388-25cb1c00-234e-11e9-84d9-e7929416d55c.jpg)

See manual [Options - Simulator Aircraft](https://albar965.gitbooks.io/little-navmap-user-manual/content/en/OPTIONS.html#simulator-aircraft) in the manual.
Alex

**Comment by ChickenDipper1** [comment]
Hi albar965,

I just tried these settings, it almost works but it is one zoom level out. LNM zooms to 0.7nm and it needs to be 0.3nm to see the taxiway labels and gate numbers.
Is there a way to make it zoom that last bit automatically when on the ground?

**Comment by albar965** [comment]
Sorry. This cannot be changed at present. I plan to add more zoom options in the future.
Alex

**Comment by ChickenDipper1** [comment]
No problem, not a big deal, just a nice to have :)

**Comment by albar965** [comment]
Lets zoom in closer if aircraft touches down.

**Comment by ChickenDipper1** [comment]
I really really wish this was a feature in LNM "Zooming closer as aircraft touches down" or "zoom level setting based on speed".
For me this is the biggest thing missing from LNM, I like to park properly and having to click out of the sim into LNM to manual zoom which usually ends with the map also in the wrong place till it resets while trying to taxi and park.

This small feature would be a huge QOL upgrade for LNM I think.

**Comment by albar965** [comment]
I already added optional zoom in on touchdown. You can define a fixed zoom level for this in options.
Actually did not notice that this already an issue for 3.0.

Fixed with 2a46817edb3112e5344fc99e9675a74eca2846c5

Zoom on speed maybe later.

**Comment by ChickenDipper1** [comment]
Wow nice work just me not seeing this then.
Could you tell me where to locate this setting in the options? I cannot seem to find it.

Thank you

**Comment by u-an-i** [comment]
Hi, see also https://github.com/albar965/littlenavmap/pull/775 for an addition to the Web Server map in a future release. Btw. I‘ll try to look into @KOKAProduktion PR sometime after vacation. Happy Blue Skies everyone in 2022!

**Comment by albar965** [comment]
> Wow nice work just me not seeing this then. Could you tell me where to locate this setting in the options? I cannot seem to find it.
> 
> Thank you

It's in the current development version not publicly released yet, sorry.

**Comment by albar965** [comment]
Wish you all a good start into the New Year! :fireworks:

**Comment by ChickenDipper1** [comment]
Oh noooo :( guess I have can wait a little longer or maybe a lot longer lol

**Comment by Gulliver54** [comment]
> Oh noooo :( guess I have can wait a little longer or maybe a lot longer lol

A few days or weeks longer won't make that difference, but personally I'm looking foreward to this new feature too. No fiddling after touchdown is really cool .

**Comment by albar965** [comment]
Wait for the alpha version. There's a ton of new stuff which can be tested. :slightly_smiling_face: 
But bear with me. It will already take hours to update the changelog.

**Comment by u-an-i** [comment]
@albar965 if you like you can adapt the web plugin autozoom code and data to the main application and mix it with your predefined limits. This could result in a combined auto + user defined „preferred“ zoom which @KOKAProduktion could add to the webapi. Then I could add a checkbox to the web ui „preferred zoom“ and we could relegate the autozoom plugin to demo status. The idea of working is I would poll the „preferred zoom“ value every x seconds and the webapi would report that value plus perhaps the x for the next poll (as is present in the current autozoom code and data)
