### ISSUE TITLE
Issue: "New flightplan from route discription

### ISSUE THREAD

**Issue by Gulliver54** [albar965/littlenavmap#376]
Hi Alex,
I used this feature many times but today, version 2.2.4 gives some problems I did not encounter before.

Although airports are visible in Airport Search, the same ICAO code does not respond very well this time.
Picture below, 3 airports are not accepted via NFFRD (New Flightplan....). In earlier versions this seemed to be ok. By then, rejected ICAO codes did not exist in the search database.
Hope you can find the problem.
Gradus

**Comment by Gulliver54** [comment]
![02-06-01](https://user-images.githubusercontent.com/33782220/52346577-2a639480-2a20-11e9-8bcd-de43b28176a1.jpg)

**Comment by albar965** [comment]
Hi Gradus,
this happens on purpose to avoid invalid waypoints to be replaced by far away duplicates. 
I'm calculating great circle distance from departure to destination and use this to limit the search radius.

The problem is that the input string might be based on an older AIRAC which opens all kind of issues.
I'd rather drop waypoints instead of getting a plan doing zig-zag across the globe.

Alex

**Comment by Gulliver54** [comment]
Hi Alex,

I understand your reasoning.

But if reading input in LNM isn't flawless anymore and no solution is at hand , you'd better disable this function. 

Regards
Gradus

**Comment by albar965** [comment]
I can disable the distance criteria for all four-letter codes which are airports. Apart from that I see no reason to disable anything.
Alex

**Comment by Gulliver54** [comment]
I use this feature when creating a flightplan consisting only ICAO codes. Some plans contain more than 50 entries.  
So , if you can make this happen by disabling the distance criteria for ICAO codes that would be great.
Gradus.

**Comment by albar965** [comment]
Exclusion of airports by distance is now switched off. For navaids the limit is now 5000 NM or two times the route distance to get a halfway decent result for duplicates (also airports vs. navaids with same names) and AIRAC mismatches.
