### ISSUE TITLE
How do I unhide a dialog box?

### ISSUE THREAD

**Issue by theckman** [albar965/littlenavmap#382]
I accidentally clicked "Do not show" on the box that pops up and tells me NavConnect disconnected. I didn't mean to do this. How do I undo it?

**Comment by albar965** [comment]
Menu Tools -> [Reset all Messages](https://www.littlenavmap.org/manuals/littlenavmap/release/2.2/en/MENUS.html#reset-all-messages) does the trick.
For such a question better post in the Avsim support forum or send me an email. ;-)
Alex
