### ISSUE TITLE
Does Little Navmap 2.2.4 work with just FSX:SE?

### ISSUE THREAD

**Issue by el-ahrairah** [albar965/littlenavmap#389]
Running Little Navmap 2.2.4 with FSX:SE on Win 10 home 64 bit. No FSX "box" installation. It can't find my FSX airport information.

At the bottom, it says "Connected (FSX/P3D)" and "Database empty."

In the "Scenery Library" menu, there is a "Load Scenery Libary" dialog, but the simulator drop down lists only "X-Plane 11". My simulator drop down does not list "Microsoft Flight Simulator X". Only "X-Plane 11" can be selected.

The "Scenery Configuration File" text box and button are disabled. I cannot enter a path there nor click on the "Select:" button. 

When I specify D:\SteamLibrary\steamapps\common\FSX (which is where my fsx.exe is) in the Little Navmap 2.2.4 Load Scenery Library dialog as Flight Simulator Base Path, I get an error message:

Cannot read "D:\SteamLibrary\steamapps\common\FSX".
Reason: "Resources\default data" not found.

I have the "Show airports" buttons on.

How do I add FSX:SE airports?

**Comment by albar965** [comment]
LNM supports FSX SP2, FSX Accel, FSX SE and P3D. Regarding X-Plane only: [See here in the FAQ](https://albar965.github.io/littlenavmap-faq.html#xplane-connection-only).

You have to install the FSX SP2 SimConnect but this is normally not needed in FSX SE. It is a bit strange that you cannot see the FSX option in the scenery library dialog but can connect to FSX.

The paths for the simulators are listed here in the manual: [Load Scenery Library Dialog](https://www.littlenavmap.org/manuals/littlenavmap/release/2.2/en/SCENERY.html).
Alex

**Comment by el-ahrairah** [comment]
I looked at the indicated section in the manual, thanks.
It gave me the idea to try the Windows Universal Remedy.  I ran littlenavmap.exe as administrator.  Now FSX shows in the Load Scenery Library dialog, with the appropriate Base Path and Scenery.cfg file.
Airports are now showing.

**Comment by albar965** [comment]
Glad it's fixed.  :)
Alex
