### ISSUE TITLE
Cauclactor Fuel Planner & Cost Index

### ISSUE THREAD

**Issue by DemonRem** [albar965/littlenavmap#391]
I wonder if that possible to add a feature for Calculate fuel plan & Cost index Calculate for the flight plan?

**Comment by tonghuix** [comment]
It is vary for different manufacturers, airplane types and operating airline, so I think it would be too complicated. 

Well I am not a developer, and fly small / light general aircraft most of the time.

**Comment by DemonRem** [comment]
wrong value can cuz fail on the flight , that why I search a way to caucalte it

**Comment by albar965** [comment]
Calculating the cost index is not doable due to the reasons @tonghuix stated.
There are a lot of forum threads on RW cost index values. Use one of these and then collect aircraft performance for one value. Or create different performance files for different cost indices.
Alex
