### ISSUE TITLE
Multiple map views

### ISSUE THREAD

**Issue by SamPoulton** [albar965/littlenavmap#393]
I use Little Navmap to aid in air traffic controlling for several small FSX servers, and I love it. One thing that I would really appreciate would be to have multiple views available at the same time so I can cover ground and approach at the same time (that's how it works on these smaller servers). Is this something that is easily doable? Would do it myself but I'm useless at C++.

**Comment by Gulliver54** [comment]
Similar to #322

**Comment by SamPoulton** [comment]
Didnt see that. I'll close this
