### ISSUE TITLE
Online FlightPlan Issue reported by the ATC

### ISSUE THREAD

**Issue by DemonRem** [albar965/littlenavmap#395]
Online ATC report for incorrect route format what I have made with littlenavmap , 

this is the format I get from the site IVAO give me look like that :

Start | EDDF

End | EDDT | Rules | I | STAR | n/a

Altitude | FL230 and below | Type | High | Alternate | n/a

Route | SULUS Z12 LASGA/N0400F270 T202 MILGU

FMS Route | SULUS Z12 LASGA T202 MILGU

Comments | AFTER LASGA ODD FL270 OR ABOVE

you may also check the result this site bring : 

https://www.ivao.aero/DB/route/default.asp

**Comment by albar965** [comment]
Thanks. Will check later for 2.4.
Alex

**Comment by DemonRem** [comment]
@albar965 I see 2.4 is already out so its fixed now?

**Comment by albar965** [comment]
2.4 is still WIP. See here: https://github.com/albar965/littlenavmap/milestone/7
Sorry, it will take a while until this is out.
Alex

**Comment by albar965** [comment]
Cannot see what's wrong there. Need more information.
```
[FLIGHTPLAN]
CALLSIGN=
PIC=Alex B.
LIVERY=
AIRLINE=
SPEEDTYPE=N
POB=0
ENDURANCE=0342
OTHER=
ALT2ICAO=
ALTICAO=
EET=0242
DESTICAO=EDDT
ROUTE=SULUS Z12 LASGA T202 MILGU
LEVEL=70
LEVELTYPE=F
SPEED=100
DEPTIME=2103
DEPICAO=EDDF
TRANSPONDER=
EQUIPMENT=
WAKECAT=
ACTYPE=D228
NUMBER=1
FLIGHTTYPE=
RULES=I
```

**Comment by DemonRem** [comment]
I don't know to tell you but online atc report this data not correct

**Comment by albar965** [comment]
Sorry, but I need to know what is not correct. The route description (SULUS Z12 LASGA T202 MILGU)?
What is the output from the IVAO tool (I cannot get past the login)?
I need examples.
Alex

**Comment by DemonRem** [comment]
I think its must to be in one line as I posting you

**Comment by albar965** [comment]
Will check but still have no idea.
Alex

**Comment by xwing007** [comment]
Hi guys.
There are little differences between the X-Ivap and the Ivap.
The LNM 2.2.4 contains only one export fomat (Ivap?)
I hope this help you

[IVAO.zip](https://github.com/albar965/littlenavmap/files/3512825/IVAO.zip)

**Comment by DemonRem** [comment]
thank what I mean

**Comment by albar965** [comment]
Thanks for the files. I see.
AIRLINE, CALLSIGN, FMCROUTE, LIVERY and PIC is missing.
It uses ALT2ICAO instead of ALTICAO2. ID should not be there.
FMCROUTE is empty. Is that actually needed?

Screenshot from sorted files to allow comparison.
![image](https://user-images.githubusercontent.com/15254956/63229145-f64a0700-c1ec-11e9-9c88-ce5cab8e3ad6.png)

**Comment by xwing007** [comment]
> FMCROUTE is empty. Is that actually needed?
You can it leave empty, it is not mandatory.
