### ISSUE TITLE
Error in plain text flight plan exported for BBS

### ISSUE THREAD

**Issue by Cistoge** [albar965/littlenavmap#396]
Hello,

I used little navmap yesterday to convert an FSX XML flight plan to an FS9 plain text flight plan for use in a BBS airbus and noticed that there was a little error in the result, a = character was missing in the line for the cruise altitude. I have not tried yet if this has any effect when that flight plan is loaded into the BBS airbus MCDU.

Regards
  Christoph

**Comment by albar965** [comment]
Thanks, Christoph. There is indeed a equals sign missing.
Alex

**Comment by albar965** [comment]
Fixed in albar965/atools@e8d9758669811dfad4ae92a483e01e4e25d8e88d

**Comment by fleurenf55** [comment]
Greetings, 
The problem I’m having is that when I export the flightplan to BBS and load it up, the FMC does not use the correct waypoints hence It doesn’t recognise the ones created in Little Navmap.
I have the latest version and both Little Navmap and BBS have the latest Airac.
