### ISSUE TITLE
Show alternate fuel units in performance module

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#401]
Allow to switch between lbs/gal and kg/l in edit dialog.
Show alternate units in performance report depending on options.

**Comment by Persojet** [comment]
Thank you for the job earlier. Any chance to get this also for true airspeed and weights?

**Comment by albar965** [comment]
> Thank you for the job earlier. Any chance to get this also for true airspeed and weights?

What places? 
Weights have this already in progress tab. I see it missing for TAS and a few not so relevant altitude values
