### ISSUE TITLE
Cannot Comply with Altitude Restriction

### ISSUE THREAD

**Issue by martinlest** [albar965/littlenavmap#417]
As per emails Alex, here is another flight plan (most I now load seem to cause this error message). If I use a v3 flight plan (not XP11), without the SID/STAR/Approaches, the error then reads 'Cannot calculate top of climb or top of descent'. The flight is almost 1000 miles - FL370 should obviously be no problem. 
If you need other data, I'll copy it here of course
Many thanks :-)
-----------
I
1100 Version
CYCLE 1905
ADEP UUWW
DEPRWY RW01
SID OKLI3D
ADES USTR
DESRWY RW03
STAR BU03A
APP I03-Z
NUMENR 14
1 UUWW ADEP 686.000000 55.599136 37.265427
11 BESTA DRCT 11095.297852 55.916668 37.741390
2 RW DRCT 18310.195313 55.711388 38.228054
2 MF DRCT 36233.128906 56.026112 39.634167
11 OSBUR DRCT 37000.000000 56.561111 41.439167
11 KRESA DRCT 37000.000000 56.837776 43.123055
11 LAMGU DRCT 37000.000000 57.348057 46.771946
11 LANIL DRCT 37000.000000 57.911667 49.086388
11 ABURI DRCT 37000.000000 58.078888 52.138054
11 GIMUN DRCT 37000.000000 58.166943 54.976665
11 BUMUR DRCT 37000.000000 57.803612 58.435001
11 ABDIR DRCT 37000.000000 57.521946 60.606667
11 REPSA DRCT 37000.000000 57.336666 61.929722
1 USTR ADES 377.000000 57.168335 65.316109

**Comment by albar965** [comment]
Thanks. I'll have a look at it. Feel free to attach more examples if you find them.
Alex

**Comment by martinlest** [comment]
OK, you're going to love this! The same flight plan today does not give me any errors Alex. I made no changes. Be interesting to see if you can reproduce the problem with that plan. If I get another plan which causes the same issue any time soon, I'll post it here. Thanks for looking into this.

**Comment by albar965** [comment]
I also cannot reproduce it here. But please attach the file if you run into the again with another flight plan. This helps a lot.
Alex

**Comment by Gulliver54** [comment]
Is it possible, Martin, that you entered FL 370 instead of 37000ft?  If so, LNM thinks you enter only 370ft and that altitude does not comply with procedure altitudes restrictions.
Gradus

**Comment by albar965** [comment]
Have not seen any of these cases again. Feel free to reopen if this happens again.
Alex
