### ISSUE TITLE
Info & Procedures do not match

### ISSUE THREAD

**Issue by martinlest** [albar965/littlenavmap#421]
Hi,
I notice every now and again that whilst the LNM map and info pane have the same runway data, the procedures page does not match. For instance, Madrid LEMD: the Runways tab and the map show 33 L&R, but the procedures shows 32 L&R. Odd that they should be different. Should such instances be reported?

**Comment by martinlest** [comment]
Another similar example of the 'mismatches' I see. The flight plan/plan pane shows (runway 9 or 10??):

Agadir Al Massira (GMAD) Runway 10 to Mohamed V (GMMN)
Depart runway 09 via SID AGAL4D . Arrive via STAR RAVO8A (17R) and ILS-Z FF17R (I17RZ) to runway 17R .

**Comment by albar965** [comment]
Hi Martin,
this might be due to renamed runways which differ between Navigraph procedures and X-Plane or P3D airports. 
You can see the Navigraph runway layout if you switch to "Navigraph only" mode. Otherweise LNM shows runway numbers from the simulator scenery .
Alex

**Comment by Gulliver54** [comment]
Because of the shifting magnetic pole, (and that's changing very fast right now) runway headings have to be adjusted once in a while.  Navigraph, as mentioned above, provides the correct heading.
