### ISSUE TITLE
Add field "comment" to userpoint

### ISSUE THREAD

**Issue by labrador999** [albar965/littlenavmap#429]
Add a field "comment" to userpoint, which shows up in "print flightplan" (similar to some waypoints in procedures).
This comment could be used to store a navigation hint (radial, distance etc).

**Comment by albar965** [comment]
Make sense but requires #293 to store this information. The current FSX PLN workaround is not sufficient.

Assigned to 2.6.

Alex

**Comment by albar965** [comment]
Done. Added fields comment, region, name and ident. 
All fields are copied to the flightplan point when creating one based on a userpoint.
All data is saved with the new LNMPLN flightplan format.
