### ISSUE TITLE
Add more logbook options

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#432]
Follow up from #346

- [x] Include flight plan and performance file in entry
- [x] Include route description string
- [x] Add aircraft trail (display later)
- [ ] ~~Show flight plan points in preview (later)~~
- [ ] ~~Show alternate airports (later)~~

**Comment by albar965** [comment]
Remaining stuff will be done in #524 later

**Comment by Gulliver54** [comment]
Hi Alex,
Some questions.
1. Added performance file to logbook.
Does this copy the values of a existing performance file or does it refers to a perf-file?
2. I sincerely hope that changing headers and adding columns does not mix up my recorded logbook entries.
Regards Gradus

**Comment by albar965** [comment]
Hi Gradus,

> Does this copy the values of a existing performance file or does it refers to a perf-file?

The files (flight plan, track and perf) are attached to the logbook entry and can be saved as or loaded from there. They can also be exported to and from CSV.

> I sincerely hope that changing headers and adding columns does not mix up my recorded logbook entries.

Absolutely not. I always try to keep LNM backward compatible. There are only three columns added to the CSV export. Database is updated automatically. It is a bug if something is mixed up.

Alex
