### ISSUE TITLE
AIRAC 1909 use IATA codes instead of ICAO codes

### ISSUE THREAD

**Issue by sarunint** [albar965/littlenavmap#443]
I've just updated my Navigraph database from 1908 to 1909 and realise that the most airport use IATA as their identifier.

**Environment:**

* Version: Littlenavmap v2.2.4
* Database: Navigraph cycle 1909

![image](https://user-images.githubusercontent.com/3850197/63137027-cccb8880-bffe-11e9-91a8-31d958d99bbf.png)

**Comment by albar965** [comment]
Thanks for the report. I'm working on it.
Alex

**Comment by albar965** [comment]
Fixed by Navigraph. Update is on the way.
https://www.avsim.com/forums/topic/558288-latest-1909-nav-data-ksfo-proceedures-wrong/

Feel free to reopen if something is still wrong.

Alex

**Comment by sarunint** [comment]
The update arrived minutes ago, and it worked.

Thank you

**Comment by albar965** [comment]
You're welcome and glad it's working now.  :)
