### ISSUE TITLE
Application crash on exit

### ISSUE THREAD

**Issue by 737simpilot** [albar965/littlenavmap#445]
Installed the latest version 2.4.0 beta. Upon closing LittleNavMap I get a Windows crash pop up that reads the following:

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	littlenavmap.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5d7251bf
  Fault Module Name:	ntdll.dll
  Fault Module Version:	6.1.7601.17514
  Fault Module Timestamp:	4ce7ba58
  Exception Code:	c0000005
  Exception Offset:	0002dfa1
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Using Windows 7 64 Ultimate. FSX SP2, but it's not Sim related. I can launch LittleNavMap and close it and then this error pop up occurs. Never happened before until I installed this latest update.

**Comment by 737simpilot** [comment]
Now I'm not getting the crash anymore. Don't know what to make of that.

**Comment by 737simpilot** [comment]
Here is the log. 
[abarthel-little_navmap.zip](https://github.com/albar965/littlenavmap/files/3613689/abarthel-little_navmap.zip)

**Comment by albar965** [comment]
Thank you for the log but I see only normal shutdowns in there. Please save the log file right away if this happens again. 
Alex

**Comment by 737simpilot** [comment]
Okay, now got a crash. Error log attached. 
[abarthel-little_navmap.zip](https://github.com/albar965/littlenavmap/files/3619454/abarthel-little_navmap.zip)

**Comment by albar965** [comment]
Sorry, but I can see only normal exits of LNM in the log file.
Wait for 2.4.1.beta (hopefully tomorrow). This contains a few fixes for crashes when calculating the elevation profile.
Alex

**Comment by 737simpilot** [comment]
Okay. I did some research on this and I see with Win 7 the ntdll.dll is problematic for some applications. If you do a Google search on ntdll.dll crash you'll see.

**Comment by albar965** [comment]
Did that happen again with the 2.4.2.beta?
Alex

**Comment by 737simpilot** [comment]
I haven't played FSX in a while, but I just saw the update and updated now. So far no crash, but I'll wait here and see what happens.

**Comment by albar965** [comment]
I fixed quite a few crashes for the release candidate. I think this is solved now.
Do not hesitate to reopen this issue when the problem appears again.
Alex
