### ISSUE TITLE
Produce a pdf flight plan for VFR flight

### ISSUE THREAD

**Issue by AntoineLeo** [albar965/littlenavmap#446]
I would enjoy to be able to get a pdf output of my flight plan with common informations we use in VFR flight.

**Comment by albar965** [comment]
The 2.4.X.beta versions already have a function to export a HTML flight plan. I could extend this a bit and add the PDF export.

* Add the header from the flight plan window
* Add block and trip fuel shortened fuel report

**Comment by AntoineLeo** [comment]
I did not know that the HTML output feature was already in beta. I think HTML is already good but pdf would be a little more confortable to use.

Attached, a flight plan sample.

Many thanks for your attention.

[FlightPlan.pdf](https://github.com/albar965/littlenavmap/files/3665540/FlightPlan.pdf)

**Comment by albar965** [comment]
Thanks for the sample. Look for `File` -> `Export flight plan to other formats` -> `Export Flight Plan as HTML Page`.
Alex

**Comment by albar965** [comment]
Sorry. Too much effort and there is already the widely configurable print (to file) functionality with map, flight plan table, fuel planning and whatnot.
