### ISSUE TITLE
Logbook ICAO filter with AND and OR condition

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#455]
Allow to filter logbook airport by destination AND/OR departure.

**Comment by Gulliver54** [comment]
One report for an airport. Most welcome

**Comment by albar965** [comment]
More handy than the destination and departure limited search (which is still there).

![image](https://user-images.githubusercontent.com/15254956/82036570-95266580-9690-11ea-8ed7-ca0bc4412e95.png)
