### ISSUE TITLE
Chinese version 

### ISSUE THREAD

**Issue by wanghuqiang123** [albar965/littlenavmap#467]
I like your software very much. It is a very excellent software. I want to run your software, but there is no Chinese version of your software.

**Comment by tonghuix** [comment]
Hi @wanghuqiang123 , I am translating this software into Chinese now, please be patient.

**Comment by wanghuqiang123** [comment]
> 
> 
> Hi @wanghuqiang123 , I am translating this software into Chinese now, please be patient.

你好，请问你是如何配置这个项目的环境呢，搞了很久，一直没配置好。

**Comment by wanghuqiang123** [comment]
> Hi @wanghuqiang123 , I am translating this software into Chinese now, please be patient.

请问   我可以用下你们的翻译嘛？非常感谢

**Comment by tonghuix** [comment]
> > Hi @wanghuqiang123 , I am translating this software into Chinese now, please be patient.
> 
> 请问 我可以用下你们的翻译嘛？非常感谢

没问题。 https://github.com/tonghuix/littlenavmap

注意我有几个月没有更新，代码部分可能与主线有一点差距。今年一直比较忙，而且主界面并没有翻译（需要翻译的太多了）。

**Comment by fishheadsam** [comment]
> > > Hi @wanghuqiang123 , I am translating this software into Chinese now, please be patient.
> > 
> > 
> > 请问 我可以用下你们的翻译嘛？非常感谢
> 
> 没问题。 https://github.com/tonghuix/littlenavmap
> 
> 注意我有几个月没有更新，代码部分可能与主线有一点差距。今年一直比较忙，而且主界面并没有翻译（需要翻译的太多了）。

您好，请问我可以在您汉化的基础上继续进行汉化吗？看您最近好像没有更新

**Comment by tonghuix** [comment]
> > > > Hi @wanghuqiang123 , I am translating this software into Chinese now, please be patient.
> > > 
> > > 
> > > 请问 我可以用下你们的翻译嘛？非常感谢
> > 
> > 
> > 没问题。 https://github.com/tonghuix/littlenavmap
> > 注意我有几个月没有更新，代码部分可能与主线有一点差距。今年一直比较忙，而且主界面并没有翻译（需要翻译的太多了）。
> 
> 您好，请问我可以在您汉化的基础上继续进行汉化吗？看您最近好像没有更新

可以，咱们一起做如何？

**Comment by fishheadsam** [comment]
> > > > > Hi @wanghuqiang123 , I am translating this software into Chinese now, please be patient.
> > > > 
> > > > 
> > > > 请问 我可以用下你们的翻译嘛？非常感谢
> > > 
> > > 
> > > 没问题。 https://github.com/tonghuix/littlenavmap
> > > 注意我有几个月没有更新，代码部分可能与主线有一点差距。今年一直比较忙，而且主界面并没有翻译（需要翻译的太多了）。
> > 
> > 
> > 您好，请问我可以在您汉化的基础上继续进行汉化吗？看您最近好像没有更新
> 
> 可以，咱们一起做如何？

好啊，我现在就在您的基础上准备把主界面和那几个字符多的整了，我翻译完了发给您校对一下？

**Comment by tonghuix** [comment]
> 完了发给您校对一下？

不用这么客气，众人拾柴火焰高
