### ISSUE TITLE
Hi @wanghuqiang123 , I am translating this software into Chinese now, please be patient.

### ISSUE THREAD

**Issue by wanghuqiang123** [albar965/littlenavmap#469]
Hi @wanghuqiang123 , I am translating this software into Chinese now, please be patient.

_Originally posted by @tonghuix in https://github.com/albar965/littlenavmap/issues/467#issuecomment-549647283_

你好，请问你是如何配置这个项目的环境呢，搞了很久，一直没配置好。

**Comment by tonghuix** [comment]
@wanghuqiang123 你是指开发环境？我做翻译的时候不需要设置开发环境，所以我也不知道怎么设置开发环境哦。

**Comment by albar965** [comment]
Answered. Feel free to reopen if needed.
