### ISSUE TITLE
How to configure the development environment? Which version of Qt should I use,I've been trying for a long time and still haven't successfully configured the project

### ISSUE THREAD

**Issue by wanghuqiang123** [albar965/littlenavmap#470]

**Comment by albar965** [comment]
See the files below:
https://github.com/albar965/atools/blob/master/BUILD.txt
https://github.com/albar965/atools/blob/master/atools.pro
https://github.com/albar965/littlenavmap/blob/master/BUILD.txt
https://github.com/albar965/littlenavmap/blob/master/littlenavmap.pro
Alex

**Comment by albar965** [comment]
Answered.
Alex
