### ISSUE TITLE
I want to translate it into Chinese, but I don't know how to load the.qm file

### ISSUE THREAD

**Issue by wanghuqiang123** [albar965/littlenavmap#473]
> **Delete this text _after reading_ before posting the issue.**

**Comment by albar965** [comment]
Read the Wiki here: https://github.com/albar965/littlenavmap/wiki/Translating
Also contact @fishheadsam since he takes care about the user manual translation.
Alex

**Comment by albar965** [comment]
Answered. Please send me a mail instead of creating an issue for questions.
Alex
