### ISSUE TITLE
Incorrect waypoint reading in BBS Airbus

### ISSUE THREAD

**Issue by fleurenf55** [albar965/littlenavmap#474]
Greetings, 
I have an issue with BBS Airbus reading the imported flightplan from Little Navmap. It doesn’t recognise the waypoints created with Little Navmap. Meaning whilst Little Navmap created the correct route, when importing it into the FMC, the route had incorrect waypoints and as a consequence, the flightplan created waypoints at wrong locations due to waypoint id being the same but at different lat/Lon.
Can you advise? It may well be a BBS Airbus issue.
Much appreciated. 
Fred

**Comment by albar965** [comment]
Hi,
can you attach an example? The original PLN and the BBS export file would help so I can check if something is wrong.
Alex

**Comment by fleurenf55** [comment]
Hi Alex,
Files attached.

Thanks for looking into this
Regards,
Fred

**Comment by albar965** [comment]
Thanks for the files. I'll have a look at it in the 2.6 release cycle (next one after 2.4).

**Comment by albar965** [comment]
@fleurenf55 Finally arrived at this issue. Took some time. :smiley: 

What you attached seems like an Aerosoft Airbus flight plan.

I did some small improvements to the BBS export and attached two plans from current LNM development version.

[BBS.zip](https://github.com/albar965/littlenavmap/files/4959993/BBS.zip)

Feel free to reopen if it does not work.
