### ISSUE TITLE
Allow Marble widget URLs containing special characters

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#479]
Fix marble widget for example https://www.geoportail.gouv.fr/donnees/carte-oaci-vfr 
for URLs containing `%2F` and `&`

**Comment by scls19fr** [comment]
Hello @albar965,

Coming from https://www.x-plane.fr/showthread.php?t=65933&p=580958&viewfull=1#post580958 and seing also discussions with @ailgorbot at https://forums.x-plane.org/index.php?/files/file/41694-little-navmap/&page=6&tab=comments#comment-286172 I wonder what is current status of this issue.
Is there an issue opened upstream (ie KDE / Marble) ?
https://marble.kde.org/support.php
-> https://bugs.kde.org/enter_bug.cgi?product=marble&component=general&bug_severity=normal
If so could you post link of this issue ?

Kind regards

**Comment by albar965** [comment]
There is no upstream issue in Marble.
Status is as the issue says: "Open".

**Comment by scls19fr** [comment]
Issue opened upstream at https://bugs.kde.org/show_bug.cgi?id=430290
Feel free to add more information

**Comment by albar965** [comment]
Fixed with albar965/marble@ba4c867cabc7ac179444ee7c33f6fad3163a50a7 by replacing `%3F` with `?`. Other characters were not affected.

**Comment by scls19fr** [comment]
Thanks @albar965

**Comment by scls19fr** [comment]
Good news thanks! What LNM version are you using?

**Comment by scls19fr** [comment]
It should probably be added to https://github.com/h0wardch3ng/map-extensions-for-little-navmap

**Comment by h0wardch3ng** [comment]
@cowreth @scls19fr Thank you very much, the code has been merged.

**Comment by albar965** [comment]
@h0wardch3ng I suppose you're continuing the maps from here: https://www.avsim.com/forums/topic/548994-new-maps-for-lnm/

I always had issues with the Google maps showing labels mixed in Dutch, German, English and other languages.
But this can be fixed by adding a language parameter `hl=en` to the download URL. This will return only map tiles with English labels:

`<downloadUrl protocol="https" host="mt1.google.com" path="/vt/lyrs=p&amp;x={x}&amp;y={y}&amp;z={zoomLevel}&amp;hl=en" />`
This works for all LNM versions.


The new LNM alpha allows to force the labels to the user interface language by using:
`<downloadUrl protocol="https" host="mt1.google.com" path="/vt/lyrs=p&amp;x={x}&amp;y={y}&amp;z={zoomLevel}&amp;hl={language}" />`
This works from LNM 2.7 versions.

**Comment by scls19fr** [comment]
https://sdoaci.skydreamsoft.fr/FRANCE/Z$z/$y/$x.png
provides also interesting VFR french map tiles of size 512 with max zoom of 12
