### ISSUE TITLE
Flight Plan Import

### ISSUE THREAD

**Issue by DemonRem** [albar965/littlenavmap#488]
Flight Plan to Airbus A320 in P3D , I don't understand how do I import flight plan I make with littlenavmap into airsoft airbus a320

**Comment by albar965** [comment]
What A320? BBS? 
Alex

**Comment by Gulliver54** [comment]
I think you have to read the A320 manual .
Succes

**Comment by DemonRem** [comment]
Aerosoft

**Comment by albar965** [comment]
Sorry. Don't have that. You can send me the important parts about the format per email.

I'm a bit confused. Is this an error report for a present function or a request for a new one?

Maybe a duplicate of #184 ?

Alex

**Comment by albar965** [comment]
Closing due to lack of feedback.
Alex
