### ISSUE TITLE
KICR not showing up

### ISSUE THREAD

**Issue by jengle53** [albar965/littlenavmap#494]
Thanks for a great tool.

KSFD was changed to KICR in 2007.  Navigraph and x-plane have the airport correctly as KICR.  Navigraph does not find KICR - only KSDF.
PC:  Windows 10
Sim:  X-Plane 11.41
Little NavMap:
     Version 2.4.4 (revision 0946e328)
     atools Version 3.4.4 (revision b96521a)
     OpenSSL 1.1.1b 26 Feb 2019 (build)
     OpenSSL 1.1.1d 10 Sep 2019 (library)
Little NavMap Navigraph Cycle_Info.txt
     AIRAC cycle    : 2003
     Version        : 1
     Valid (from/to): 27/FEB/2020 - 26/MAR/2020

Navigraph AIRAC cycle 2003 rev 1

Thanks!

**Comment by jengle53** [comment]
Checked on another PC and it's OK.  More troubleshooting to do.

**Comment by albar965** [comment]
Winner Regl. shows as KICR in X-Plane 11.41 data and Navigraph data (cycle 2001 here - should not make a difference).
I can find KSFD (Wiley in city Winner) only in the stone age FSX data.

You have an old add-on airport installed by any chance?

Alex

**Comment by jengle53** [comment]
Hi Alexander!  I updated the post as closed with a note that I had to do some more troubleshooting.  Sure enough, somehow Little NavMap had not read in the X-Plane data.  I did a re-install a few weeks ago and must have been flying like that.  Sorry for the mess up;  great product.  Anyways once I read in the X-Plane airports & nav data everything is golden again. Jeff Sent from Mail for Windows 10 From: Alexander BarthelSent: Wednesday, March 18, 2020 3:22 AMTo: albar965/littlenavmapCc: jengle53; State changeSubject: Re: [albar965/littlenavmap] KICR not showing up (#494) Winner Regl. shows as KICR in X-Plane 11.41 data and Navigraph data (cycle 2001 here - should not make a difference).I can find KSFD (Wiley in city Winner) only in the stone age FSX data.You have an old add-on airport installed by any chance?Alex—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by albar965** [comment]
Hi Jeff, 
thanks for the kind words and glad its working again.
Alex

BTW: I edited your post to remove the Outlook stuff.
