### ISSUE TITLE
Very laggy program?

### ISSUE THREAD

**Issue by Dani3lNL20** [albar965/littlenavmap#496]
Win 10 64bit, FSX Stock, Ryzen 5 3600, program moved to my fastest PCIe SSD after installation.
Program freezes A LOT.

**Comment by albar965** [comment]
Try not to display airport weather symbols from the simulator. Use NOAA or another service.
"Weather" -> "Airport Weather Source" -> select anything except simulator.
This is a SimConnect issue which cannot deal with the large amount of request.
Alex

**Comment by Dani3lNL20** [comment]
thank you very much!
