### ISSUE TITLE
ZBAD being added?

### ISSUE THREAD

**Issue by martinlest** [albar965/littlenavmap#499]
Hoping that the next update will include ZBAD, major new Beijing hub, especially now there is an XP11 payware scenery. Thanks. Martin

OK, sorry - forget this, silly of me: added ZBAD to the default scenery apt.dat file and then ran LNM database & the airport shows up fine of course. :-)

**Comment by albar965** [comment]
Good it's solved. Closing issue. Happy flying!
Alex
