### ISSUE TITLE
Crash when create or delete an approach to the airport 

### ISSUE THREAD

**Issue by badbass55** [albar965/littlenavmap#500]
Hi Alex, thanks for the great job!

I encountered strange behavior when trying to insert or remove an approach to the airport (right click, Crash when create or delet an approach to the airport).

The Log does not seem to show any anomalies, perhaps with just a video it would be possible to report the behavior of trying to remove the item to generate the error.

note: I can only get the error to occur when I try to edit (insert or remove) a flight plan with start, destination and legs.
When the destination airport is alone, it is possible to insert and remove normally

https://youtu.be/9ncdaUZblMA

Windows 10, 1909 64bit
Xplane 11, 11.41r1 (build 114100 64-bit)
Airac 2004
Little Nivemap Version 2.4.4 (revision 0946e328)

[abarthel-little_navmap.log](https://github.com/albar965/littlenavmap/files/4415957/abarthel-little_navmap.log)

[VFR Uberaba (SBUR) to Marte (SBMT).zip](https://github.com/albar965/littlenavmap/files/4416231/VFR.Uberaba.SBUR.to.Marte.SBMT.zip)

**Comment by albar965** [comment]
Hi,
thanks for the report. A video is not needed. 

But I cannot reproduce this here. Can you list the exact steps that lead to the crash, i.e. which menu items selected or buttons are pressed in what order? 
Alex

**Comment by badbass55** [comment]
Sorry, I was trying to record in a less bad way
I also changed the Flight Plan file, which was incorrect.
I had a flight plan that I had managed to enter, but I saved it over the top.

https://youtu.be/9ncdaUZblMA

**Comment by badbass55** [comment]
symptom updated in the initial report

**Comment by albar965** [comment]
Thank you. The video helps. I can reproduce this even in my Linux development environment. Should not be difficult to fix for the next release (which still far away, sorry).
Alex

Reproduce:
1. Use flight plan [IFR Uberaba (SBUR) to Campo De Marte Airport (SBMT).pln.txt](https://github.com/albar965/littlenavmap/files/4416289/IFR.Uberaba.SBUR.to.Campo.De.Marte.Airport.SBMT.pln.txt)
2. Select custom procedure in context menu of flight plan table.
3. Crash follows after selecting a runway in the dialog.

**Comment by badbass55** [comment]
No problem Alex, I am happy to help in some way, I believe it was not noticed before, as it is not common to use this feature. Maybe that's why you don't even need to prioritize for the next release.
Thank you for your commitment and dedication to this incredible tool.

**Comment by albar965** [comment]
You're welcome. The crash appears only if there are used defined waypoints (green rectangles) in the flight plan. Anyway, I hate crashes and will fix it. :-)
Alex
