### ISSUE TITLE
Autoscroll Flight Plan?

### ISSUE THREAD

**Issue by martinlest** [albar965/littlenavmap#501]
Hi, hope you are keeping well in these awful times!

Not an issue, as such... Is there an option to have the Flight Plan window scroll down automatically, so that the next waypoint, in magenta, is always at the top (ideally, with upcoming waypoints below).  Like many, my LNM is on a second monitor.. and XP11 doesn't always seem to like it for some reason if I click on apps there.. be good if I could just the let waypoints move along by themselves. If there is no such option, is it possible to add that perhaps?

Many thanks.

**Comment by albar965** [comment]
Hi Martin,
I'm doing well. Hope you're OK too!
Regarding flight plan table and active leg: See options dialog on page `Simulator Aircraft`, title `While flying`: Check `Keep active leg on top of flight plan table`. Active leg will be put on second row in table whenever it changes.
BTW: I also run X-Plane in fullscreen and LNM on a second monitor. The mousewheel works without clicking into LNM. This avoids the annoying flash in XP when clicking LNM.
Alex

**Comment by martinlest** [comment]
Great. Thanks, as ever Alex.
