### ISSUE TITLE
Print map / flight plan work only once

### ISSUE THREAD

**Issue by dupont-al-videotron-ca** [albar965/littlenavmap#502]
After printing (or print preview) a flight plan that works, printing a second time the same flight plan give a empty page.

**Comment by albar965** [comment]
Sorry, cannot reproduce this so far by printing twice to PDF.
Can you give me more information? What OS? What simulator?
Please also attach the flight plan.
Thanks
Alex

**Comment by albar965** [comment]
Lacking more information still after a long time. Closing.
