### ISSUE TITLE
I see no my plane on the map with 2.4.4

### ISSUE THREAD

**Issue by BogusCurry** [albar965/littlenavmap#504]
Hello ;D
I have a little problem, I can no more sse my plane on the map. I am connect to P3D 4.5, but I can not see the plane. I no know what is the problem, I become no error message or so .. 

Have a nice Day

Bogus

**Comment by albar965** [comment]
See aircraft progress in the tab? Reset display settings?
Alex

**Comment by BogusCurry** [comment]
ja verbunden steht da ja, das ist ja das merkwürdige, es steht verbunden und, aber trotzdem sehe ich meine Flugzeug nicht. Auch nachdem ich die Anzeige zurückgesetzt hab, sehe ich mein Flugzeug ncht ..

**Comment by albar965** [comment]
Was steht denn in `Simulatorflugzeug` -> `Fortschritt`?

**Comment by BogusCurry** [comment]
WArte auf Aktualisierung ....

**Comment by albar965** [comment]
Flug auch wirklich gestartet? D.h. im Cockpit.
Schicke mir im Zweifelsfall mal die Logdatei per email.
Alex

**Comment by BogusCurry** [comment]
Ok, wo finde ich die Logdatei ? Oder meinst du die Einträge im Logbuch ?

**Comment by albar965** [comment]
Diese hier: `C:\Users\YOURUSERNAME\AppData\Local\Temp\abarthel-little_navmap.log` unter Windows oder `/tmp/abarthel-little_navmap.log` unter Linux.
Vorher einen Verbindungsversuch starten, wo der Flug im Simulator auch schon gestartet ist.

Was auch helfen könnte: 
Alle MSVC Redistributables installieren: [Visual C++ Runtime Installer (All-In-One) v56 auf www.majorgeeks.com](https://www.majorgeeks.com/files/details/visual_c_runtime_installer.html).

[SimConnect hier von www.littlenavmap.org](https://www.littlenavmap.org/downloads/SimConnect/SimConnect-FSX_SP2.zip) hier installieren bzw. reparieren.
Alex

**Comment by BogusCurry** [comment]
Danke dir .. werde ich mal machen und dann melde ich mich wieder ;D

**Comment by BogusCurry** [comment]
Hallo ;D
Keine Ahnung warum, aber nun hat sich das Flugzeug sich entschieden, aus der Versenkung zu erscheinen ;D Ich nun mein Flugzeug auf der Map ;D

Danke für deine Hilfe ;D

Have a nice Day ;
Bogus

**Comment by albar965** [comment]
Egal. Hauptsache es klappt jetzt. :-)
Ich mache dann mal zu.
Viel Spaß beim Fliegen!
Alex
