### ISSUE TITLE
LNM 'not connected to simulator'

### ISSUE THREAD

**Issue by martinlest** [albar965/littlenavmap#505]
I am at the end of day two, moving XP11 to Windows 10. I have spent these two full days, not flying, but  troubleshooting one issue after another (as I manage to fix one, a new one is likely to appear) - and I am really, _really_ weary of it now. Sorry. Just to put this post into context! :-)

I have managed to fix most issues, or some just went away by themselves (like 'Problems with OpenGL.... simulator has crashed'), but one of those left to resolve is that LNM shows as 'not connected to simulator'. The map is grey with no a/c icon and the Simulator Aircraft window has no data. Flight plans load OK of course. I have looked through the online manual and found nothing, but as I say, I am getting  really tired now searching for solutions to XP problems online and may have missed what I need. For this problem, apart from the Googling I have done over the last 30 minutes (no fix found), I am not sure what to do next.

Thank you very much! 

Martin

**Comment by albar965** [comment]
Hi Martin,
it is better to send me an email about installation problems instead of using the issue space. This is more for bugs and requests.

About `Not connected`: Did you install the Xpconnect plugin into the right folder? Can you see it loaded in the plugin manager of X-Plane?
Alex
