### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by J0hnLiu** [albar965/littlenavmap#506]
https://github.com/albar965/littlenavmap/blob/c679faff61f7d23e54d150753902b183d75f05d8/src/common/htmlinfobuilder.cpp#L1989

  else if(hold.navType == map::NDB)
    navType = tr("NBD");

NBD should be a typo.

**Comment by albar965** [comment]
It is. Thanks for reporting. Let me know if you find more and attach them here.
Alex

**Comment by J0hnLiu** [comment]
https://github.com/albar965/littlenavmap/blob/master/src/options/options.ui#L3025
https://github.com/albar965/littlenavmap/blob/master/src/options/options.ui#L3068
Statue Miles per Hour (mph)
Shoule be :
**Statute** Miles per Hour (mph)

**Comment by J0hnLiu** [comment]
https://github.com/albar965/littlenavmap/blob/master/src/options/options.ui#L3146
Line end with comma, should be a period

**Comment by J0hnLiu** [comment]
https://github.com/albar965/littlenavmap/blob/master/src/options/options.ui#L3258
also

**Comment by albar965** [comment]
All fixed so far in master branch. f5d875106261ae13261d21cd687a28f64282c523
Alex

**Comment by albar965** [comment]
Closing. Feel free to reopen if you find more.
