### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by martinlest** [albar965/littlenavmap#508]
Hi Alex.. just wondered whether you would entertain a little tweak (unless it can be done already somehow). It's good to have the map follow the aircraft in flight so you don't have to keep dragging the map by hand to follow the a/c icon. But could that be disabled on the ground (or there be an option for this) somehow? When looking at an airport map, I like to see the a/c at the gate in one corner and the runway I'll be using in the other, for easy taxiway navigation (and on landing, vice versa). With the current settings that's not possible, the plane icon keeps switching back to centre map. Thanks

**Comment by albar965** [comment]
Hi Martin,
have a look at the options page [Simulator Aircraft](https://www.littlenavmap.org/manuals/littlenavmap/release/2.4/en/OPTIONS.html#simulator-aircraft). There a ways to disable the centering for a certain time when clicking around in the map but not specially while on ground.
Alex

**Comment by martinlest** [comment]
Will do - that would probably do it. I kind of guessed that there may be something already: you seem to have thought of everything! Thank you Alex.
