### ISSUE TITLE
Translation files for unshipped language won't take effect 

### ISSUE THREAD

**Issue by J0hnLiu** [albar965/littlenavmap#511]
For some reason or maybe I messed up something, simply adding Language=XX to the [Options] for cn won't take effect in release/2.4.

I have to make it pretend a shipped language in translation folder to test by renaming littlenavmap_cn.qm to littlenavmap_fr.qm and set fr as language in option file.

**Comment by albar965** [comment]
You have to run [lrelease](https://doc.qt.io/qt-5/linguist-manager.html) to create the binary qm files from the ts source files. Then copy the qm files to the LNM `translations` folder.

**Comment by J0hnLiu** [comment]
I created qm file with qt linguist and copied  to translation folder, won't work.

**Comment by albar965** [comment]
Do you force English in the options dialog by any chance? Page `User Interface`.
Even new translations should be loaded on startup if LNM can find the file and the OS language is set to the corresponding language.

**Comment by J0hnLiu** [comment]
Nope, that option is not changed.

I have tried some other unshipped languages such as pl, hu and even uk. All working fine after force Language=XX, only cn won't work. Remove Language=XX won't show up chinese UI also.

**Comment by albar965** [comment]
No idea what's going on there.
But I'll most likely create a LNM 2.4.5 minor update for P3D v5. I'll merge the translations and send you the whole package for testing and updating once done. This will also include the disambiguations and translation fixes.
Alex

**Comment by J0hnLiu** [comment]
Sure, I'll try setup a dev env for qt and trace into that to see what I can find also.

**Comment by albar965** [comment]
This is probably the reason. `atools_cn.ts`, e.g.: 
```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="zh">
<context>
...
 ```
The correct language code is `zh` and not `cn`. Will rename the files.
Alex

**Comment by albar965** [comment]
![grafik](https://user-images.githubusercontent.com/15254956/79801266-55988200-834d-11ea-8df4-08f52e760816.png)

**Comment by J0hnLiu** [comment]
Great, I  forgot the language code for Chinese even after I opened the file to modify zh_cn to zh for a better compatibility.
Issue confirmed resolved.
