### ISSUE TITLE
Bug: Problem with showing some airports on the map.

### ISSUE THREAD

**Issue by merspieler** [albar965/littlenavmap#515]
When searching for `NZSP` and then in the context menu on `Show on Map`, it zooms out as far as possible instead of zooming in on the airport.

lnm: 2.4.4
os: debian bullseye

**Comment by albar965** [comment]
Can reproduce with Mercator projection. Works fine with Spherical.
Will have a look but no promises. This is the Marble widget freaking out. It already has numerous display issues especially in Mercator and at the anti-meridian which required workarounds. 
Frankly thinking about removing this projection ....

**Comment by Gulliver54** [comment]
Ok, understand your point but I rather have Mercator display with some issues than the  less crystal clear image that Sferical produces. Specially for ATC purpuses Mercator is very usufull.

**Comment by albar965** [comment]
Fixed several Mercator display issues. But this specific problem in NZSP won't fix in Mercator display. Sorry, but use Spheric if you fly near the poles.

**Comment by merspieler** [comment]
Add a warning, if in mercator and do something to close to a pole? ... just an idea to avoid similar issues in future

**Comment by albar965** [comment]
Warning on double click or center whatever at the poles is possible. Noted.
But not in 2.6. Otherwise, this release will never be finished.

**Comment by albar965** [comment]
Added a warning dialog when zooming > 85°N/S
