### ISSUE TITLE
Error: Can not calculate profile. See tooltip on this message for details.

### ISSUE THREAD

**Issue by DavidBerkut** [albar965/littlenavmap#517]
Error: Can not calculate profile. See tooltip on this message for details.

FSX plans end up with this message after an update to 2.4.5. version. Deleted the LNM and installed the older 2.4.4. still the same error.

**Comment by albar965** [comment]
Did you check the constraints? Too high cruise? Invalid performance profile? Procedure restrictions? Whatever is shown in the tooltip of the message.

I need the used flight plan and the aircraft performance profile. Can you attach both?

Alex

**Comment by DavidBerkut** [comment]
I guess I can.

But,that ToolTip message,where to find it?

Here is the FP

сре, 6. мај 2020. у 11:41 Alexander Barthel <notifications@github.com> је
написао/ла:

**Comment by albar965** [comment]
Hover the mouse over the message.
Rename the flightplan to .txt and attach it to this message. Same for performance file. But please check the constraints before if something is violated as mentioned above.

![grafik](https://user-images.githubusercontent.com/15254956/81164630-2fdfbf80-8f80-11ea-83ef-8089ab3985d2.png)

**Comment by DavidBerkut** [comment]
Big ,big thanks for this. Din't know how to solve it. I guess the FSX
sometimes creates an invalid FP which can't be properly opened by the LNM.
Same plan with a SID and STAR works. Big thanks.

Regards

сре, 6. мај 2020. у 12:00 Alexander Barthel <notifications@github.com> је
написао/ла:

**Comment by albar965** [comment]
Closing the issue. Feel free to reopen if this happens again without reason. There were bugs in the past in this function so it can happen.
Alex

**Comment by DavidBerkut** [comment]
Also,I have a problem that FSX simply can't see the SID and STAR procedures
and a lot of waypoints when I make an edit to the plan in the LNM,why is
that happening?

When I download the plan from SimBrief,everything is there.

сре, 6. мај 2020. у 12:31 Alexander Barthel <notifications@github.com> је
написао/ла:

**Comment by albar965** [comment]
FSX cannot load procedures from PLN. It's not supported in the simulator. No idea about P3D but it's no problem in X-Plane. You have to select the procedures manually in the GPS in FSX. This is often the case in add-on aircraft too.
