### ISSUE TITLE
xpconnect: Watch for number of AI planes > 20 (XP11.50b8)

### ISSUE THREAD

**Issue by TwinFan** [albar965/littlenavmap#520]
With version 11.50b8 X-Plane will provide a new way of dealing with TCAS. Details are [in a blog post here](https://developer.x-plane.com/article/overriding-tcas-and-providing-traffic-information/).

The gist that affects xpconnect is: `XPLMCountAircraft` can potentially return a number larger than 20. I have [XPMP2](https://github.com/TwinFan/XPMP2) adapted to that approach already and wanted to help testing the new feature, including provisioning of values to the "legacy" multiplayer dataRefs that many plugins use, like xpconnect.

With xpconnect I could make X-Plane crash as soon as the 23rd plane is created. X-Plane crashes in `XPLMGetDataf`, ie. when fetching a `float` dataRef.

Looking at the source I am suspecting that in [xpconnect.cpp:338](https://github.com/albar965/littlexpconnect/blob/dbe1920ca6a84c652ba0873f4934abf05f74c974/src/xpconnect.cpp#L338) you might potentially access uninitialized array elements or even unallocated memory if `numAI` now becomes larger than `20`.
And that then a garbage dataRef handle is passed to `XPLMGetDataf` which causes the crash.

[Log_Crash_Counting_XPLMCountAircraft.txt](https://github.com/albar965/littlenavmap/files/4612511/Log_Crash_Counting_XPLMCountAircraft.txt)

I'd suggest as a quick fix that you cap `numAi` at your array size.

In the long run you may want to change to read the new TCAS/target dataRefs, providing up to 63 (check array size, don't hard code) planes' values as float and int arrays.

**Comment by albar965** [comment]
Thanks for the report. I would never have noticed that. :-(
Looks like a Xpconnect fix is needed.
I'll make the array better grow dynamically (but still limited).
Alex

**Comment by TwinFan** [comment]
> I'll make the array better grow dynamically (but still limited).

Not quite sure what that is supposed to mean.

For clarification: There will still only be 20 sets of `sim/multiplayer/position/plane...` dataRefs. So as long as you stick to these dataRefs, array size 20 is fine.

_But_ `XPLMCountAircraft` could return values larger than 20. Even then will you have access to the first 20 planes only via the `sim/multiplayer/position/plane...` dataRefs as there simply aren't more than 20. So you'll have to use `min(20,numAI)` for the moment just not to exceed your array boundaries.

--

Only later, when you convert to the `sim/cockpit2/tcas/targets` dataRefs does it make sense to deal with more dynamic numbers. But as each of these dataRefs is an array dataRef the code for reading them will need to be rewritten to a certain extend. It's not too big a deal, but the loop logic needs to be changed from looping over dataRefs to looping over arrays returned by an array dataRef.

**Comment by albar965** [comment]
Thanks for the clarification and the link. Will limit to 20 for a quick fix and have a look at the tcas datarefs for 2.6.
Alex

**Comment by albar965** [comment]
Just published a release 1.0.19 which simply limits to 20.

Again: Thank you very much for the issue! I wouldn't have noticed that since the link above did not show up in my RSS feed of developer.x-plane.com. 

Alex

**Comment by TwinFan** [comment]
I've downloaded the mac build from Git and can confirm: Works, no crash any longer, even with all 63 slots filled.

**Comment by albar965** [comment]
Thanks a bunch!
Alex

**Comment by albar965** [comment]
Follow up is  #525

**Comment by Kaan88** [comment]
This should be mentioned on the homepage, I've had so many crashes and X-Plane kept blaming in the logs "XPLM_PLUGIN_XPLANE" every single time except once and I thankfuly found this issue. Who knows how many people are experiencing this and have no idea about the updated plugin? (Especially since most of the time your plugin isn't the cause in the logs for some reason)
