### ISSUE TITLE
More display options for logbook

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#524]
- [x] Add aircraft trail display in preview
- [x] Show flight plan points in preview

Follow up of #432

**Comment by Gulliver54** [comment]
Can't wait to use this enhancement.

**Comment by Gulliver54** [comment]
Yesterday wanted to change existing logbook-entry by using build in calender .
Although the date to be changed was the day before yesterday, the calendar started, if I remember well, somewhere in 2018.
Isn't it a better idea to start calender use on present day or the initial date entry?

**Comment by albar965** [comment]
Will check the calendar. It should start with whatever is set in the entry.
Alex
