### ISSUE TITLE
Cant use flight plans from FSX

### ISSUE THREAD

**Issue by lmcbrady** [albar965/littlenavmap#527]
Any time i try to import a flight plan from FSX:SE i get a cannot calculate profile and it says the airport destination is not valid even though im useing the airport names like for tampa its KTPA

**Comment by lmcbrady** [comment]
Also the runways are not showing ILS anymore just shows inner in purple its been some time since ive used FSX or LNM but it used to be a green approch with the heading and the ils freq on it

**Comment by albar965** [comment]
I need the plan - obviously ;-)
Alex

**Comment by albar965** [comment]
More: A screenshot of the whole situation would help. 
In most cases is the cruise altitude too high, the aircraft performance file has errors or other reasons.
Alex

**Comment by lmcbrady** [comment]
nvm i fixed it for some reason since the last time i played FSX with LNM it unloaded the scenery library idky i didnt look at that lol

**Comment by albar965** [comment]
I see. Great you found the problem. :-)
Closing issue. Feel free to reopen if anything strage like this happens again.
Alex
