### ISSUE TITLE
Options dialog don't follow style settings.

### ISSUE THREAD

**Issue by aunoor** [albar965/littlenavmap#529]
Little Navmap: 2.4.5

OS: Archlinux 2020.05
DE: Plasma 5.18

Options dialog don't follow style settings.
On dark themes font of labels is not readable.

![Screenshot_20200530_195846](https://user-images.githubusercontent.com/13893144/83334707-fcf3c780-a2b0-11ea-867a-8c26e630108f.png)

**Comment by albar965** [comment]
No idea how this can be fixed (if, at all). Do not use the style `Fusion`. Others seem to be ok.
Alex

**Comment by aunoor** [comment]
Looks like setting stylesheet for QSplitter affect and on it's children.
And if you remove this line
https://github.com/albar965/littlenavmap/blob/d8ce952bbd0b0513c83425857de956b0f4a3eb06/src/options/optionsdialog.cpp#L130
the dialog begins to display with normal colors.
![Screenshot_20200531_210504](https://user-images.githubusercontent.com/13893144/83359391-a35bcd80-a382-11ea-923f-cefb62055fe2.png)

**Comment by albar965** [comment]
Wow! Excellent catch! I added this style because the splitter is barely visible and people usually don't notice such a subtle thing.
I'll see what I can do. At least I can disable this thing on the Linux builds.
Alex
