### ISSUE TITLE
Bug: Modifying holding spawns second pattern

### ISSUE THREAD

**Issue by merspieler** [albar965/littlenavmap#530]
When you edit a holding pattern, two patterns are shown.

To reproduce:
1. Add a holding pattern.
2. Click again on `Display Holding at <wpt>` and change the Course.

Current behavior: two holdings are shown.

Expected behavior: The existing pattern is updated to the new course.

**Comment by albar965** [comment]
You cannot modify holdings and traffic patterns. Delete them an add a new one. The dialog remembers the parameters from adding the last hold/pattern which might look like editing.
