### ISSUE TITLE
Little Xpconnect conflicts with SAM Jetways

### ISSUE THREAD

**Issue by lazlo92** [albar965/littlenavmap#533]
SAM Jetways don't provide anymore docking help and automated jetways when Little Xpconnect plugin is present.
Configuration: Linux Fedora 32, XP11.41, SAM Base Plugin 2.0.7, WorldJetways 1.0.1, Little Navmap 2.4.5, Airport EDDF V2
Lazlo

**Comment by albar965** [comment]
Please contact SAM developers about this. Its their plugin which stops working and I can only debug and fix my own code. Xpconnect only reads datarefs and is very unlikely to conflict with others.

**Comment by lazlo92** [comment]
Fair enough. I will and keep you posted here.
