### ISSUE TITLE
Hello, I like this software very much. It's really an excellent open source software, but I can't code it. I hope I can get the flight plan in the following format, and it can also be exported, which is very useful. Can you help me? Thank you very much

### ISSUE THREAD

**Issue by wanghuqiang123** [albar965/littlenavmap#535]
`[ROUTE]
DepAirport=ZUUU
ArrAirport=ZBTJ
AIRAC-Cycle=1907
Waypoint000-Name=ZUUU
Waypoint000-Airway=SID
Waypoint000-Latitude=30.580000 
Waypoint000-Longitude=103.948333
Waypoint000-Altitude=1681
Waypoint001-Name=OGOMO
Waypoint001-Airway=W29
Waypoint001-Latitude=30.851667 
Waypoint001-Longitude=105.005000
Waypoint001-Altitude=0
Waypoint002-Name=TOREG
Waypoint002-Airway=W29
Waypoint002-Latitude=31.358333 
Waypoint002-Longitude=106.063333
Waypoint002-Altitude=0
Waypoint003-Name=SUBUL
Waypoint003-Airway=G212
Waypoint003-Latitude=32.328333 
Waypoint003-Longitude=106.710000
Waypoint003-Altitude=0
Waypoint004-Name=ONEBA
Waypoint004-Airway=G212
Waypoint004-Latitude=32.810000 
Waypoint004-Longitude=107.495000
Waypoint004-Altitude=0
Waypoint005-Name=NSH
Waypoint005-Airway=G212
Waypoint005-Latitude=33.318333 
Waypoint005-Longitude=108.311667
Waypoint005-Altitude=0
Waypoint006-Name=ZS
Waypoint006-Airway=G212
Waypoint006-Latitude=34.221667 
Waypoint006-Longitude=108.853333
Waypoint006-Altitude=0
Waypoint007-Name=OD
Waypoint007-Airway=G212
Waypoint007-Latitude=34.598333 
Waypoint007-Longitude=108.915000
Waypoint007-Altitude=0
Waypoint008-Name=MIZ
Waypoint008-Airway=G212
Waypoint008-Latitude=34.820000 
Waypoint008-Longitude=108.995000
Waypoint008-Altitude=0
Waypoint009-Name=WJC
Waypoint009-Airway=G212
Waypoint009-Latitude=35.778333 
Waypoint009-Longitude=109.376667
Waypoint009-Altitude=0
Waypoint010-Name=OKVUM
Waypoint010-Airway=W134
Waypoint010-Latitude=36.473333 
Waypoint010-Longitude=110.510000
Waypoint010-Altitude=0
Waypoint011-Name=XIVEP
Waypoint011-Airway=W134
Waypoint011-Latitude=37.631667 
Waypoint011-Longitude=112.658333
Waypoint011-Altitude=0
Waypoint012-Name=UBLAT
Waypoint012-Airway=B215
Waypoint012-Latitude=38.050000 
Waypoint012-Longitude=113.443333
Waypoint012-Altitude=0
Waypoint013-Name=ISGOD
Waypoint013-Airway=B215
Waypoint013-Latitude=38.285000 
Waypoint013-Longitude=114.090000
Waypoint013-Altitude=0
Waypoint014-Name=AKLOL
Waypoint014-Airway=B215
Waypoint014-Latitude=38.396667 
Waypoint014-Longitude=114.400000
Waypoint014-Altitude=0
Waypoint015-Name=OC
Waypoint015-Airway=B215
Waypoint015-Latitude=38.455000 
Waypoint015-Longitude=114.555000
Waypoint015-Altitude=0
Waypoint016-Name=UBTAB
Waypoint016-Airway=B215
Waypoint016-Latitude=38.496667 
Waypoint016-Longitude=114.675000
Waypoint016-Altitude=0
Waypoint017-Name=SAKOD
Waypoint017-Airway=B215
Waypoint017-Latitude=38.673333 
Waypoint017-Longitude=115.163333
Waypoint017-Altitude=0
Waypoint018-Name=ENGIL
Waypoint018-Airway=B215
Waypoint018-Latitude=38.775000 
Waypoint018-Longitude=115.446667
Waypoint018-Altitude=0
Waypoint019-Name=JB
Waypoint019-Airway=B215
Waypoint019-Latitude=39.043333 
Waypoint019-Longitude=116.198333
Waypoint019-Altitude=0
Waypoint020-Name=BOBAK
Waypoint020-Airway=B215
Waypoint020-Latitude=39.126667 
Waypoint020-Longitude=116.405000
Waypoint020-Altitude=0
Waypoint021-Name=VYK
Waypoint021-Airway=STAR
Waypoint021-Latitude=39.195000 
Waypoint021-Longitude=116.571667
Waypoint021-Altitude=0
Waypoint022-Name=ZBTJ
Waypoint022-Latitude=39.123333 
Waypoint022-Longitude=117.345000
Waypoint022-Altitude=13
NumberOfWaypoints=23
`

**Comment by albar965** [comment]
Thank you for the kind words!
Can you tell me what format this is?
Also: Attach the plan as a .txt file since Github destroys the formatting when adding the content.
Alex

**Comment by albar965** [comment]
Closing until I get more information or a better description.
