### ISSUE TITLE
Some Regional formats cause error

### ISSUE THREAD

**Issue by jaser** [albar965/littlenavmap#536]
If selecting  RTL language as **Regional format** in windows 10 it causes wind data reading error 

example:
![Regional format](https://user-images.githubusercontent.com/1474038/86494522-2c996200-bd7e-11ea-8277-d8c9aa4eb90a.png)

error:
![error](https://user-images.githubusercontent.com/1474038/86494528-30c57f80-bd7e-11ea-8a33-c69b25b1b659.png)

**Comment by albar965** [comment]
Thanks. Will check and get back to you.
Alex

**Comment by albar965** [comment]
Fixed for next version. Unfortunately there is no workaround except changing locale settings. :-(
Thanks for reporting!
Alex
