### ISSUE TITLE
Linux - Kein Connect mit Linux - XPConnect

### ISSUE THREAD

**Issue by BogusCurry** [albar965/littlenavmap#538]
Hallo ;D
Ich hab ein Problem mit XPConnect unter Linux Mint. Hab mir die aktuellste Version von XPConnect hier von Github runtergeladen, hab es in den richtigen Ordner kopiert und das Plugin wird auch im XPlane 11.41 aktiviert. Nur wenn ich Littlenav Map starte, kriege ich kein Connect, aber hab auch keine Fehlermeldung. Firewall ist nicht vorhanden.
Unter Windows läuft XPConnect dagegen klasse.

Nun die Frage, hab ich einen Fehler gemacht oder liegt das an XPConnect ?

TSchöö

Bogus

**Comment by albar965** [comment]
Hi,
wenn Xpconnect im X-Plane Plugin-Manager angezeigt wird sollte es eigentlich laufen. Außerdem wird noch eine eigene Logdatei `abarthel-little_xpconnect.log` angelegt.

Firewall ist egal, da XPconnect und Navmap kein Netzwerk benutzen.
Sind Xpconnect, X-Plane und Navmap auf dem gleichen Computer?

Alex

**Comment by BogusCurry** [comment]
Hallo ;D
Ja alles auf gleichen PC, ich schau mal was in der log datei steht ;D

Bogus

**Comment by BogusCurry** [comment]
Da wurde keine Log datei mit dem Namen abarthel-little_xpconnect.log erstellt. Dann wird wohl auch kein connect zu stande gekommen sein oder ?

**Comment by albar965** [comment]
Kannst Du das Plugin im X-Plane Plugin-Manager sehen? Wenn ja, wurde es auch erfolgreich geladen.
Wenn nicht fehlen vielleicht Bibliotheken (.so). Probiere mal einen anderen Linux Download. Einer basiert auf Ubuntu 16.04 und einer auf 18.04.
Wenn nichts hilft, kannst Du auf der Kommandozeile mit `ldd` die eventuell fehlenden Bibliotheken herausfinden. Z.B.:

```
cd ~/X-Plane 11/Resources/plugins/Little Xpconnect/64
ldd lin.xpl
```
Welche Linux Mint Version hast Du?

**Comment by BogusCurry** [comment]
> Welche Linux Mint Version hast Du?
Ich nutze LM 20, also die neueste Version von LM ;D

Ok, ich werde mal schaun, vielleicht finde ich ja den Fehler 👍 

Danke dir

**Comment by albar965** [comment]
Was sagt denn `ldd? so? 🙂

**Comment by BogusCurry** [comment]
ldd lin.xp sagt
`	linux-vdso.so.1 (0x00007ffc384c1000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f814cfce000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f814cfab000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f814cdca000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f814cc7b000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f814cc60000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f814ca6e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f814d9c3000)
`

**Comment by albar965** [comment]
Alle benötigten .so sind da. Sollte eigentlich problemlos laden (?).

**Comment by BogusCurry** [comment]
hmm .. ich versuchs morgen mal, in moment ist mir hier zu warm ;D 

Aber warum schreibt er dann keine logdatei ?

**Comment by albar965** [comment]
Steht in der X-Plane Log.txt so etwas, wie:
```
Loaded: /data/alex/Programme/X-Plane 11/Resources/plugins/Little Xpconnect/64/lin.xpl (ABarthel.LittleXpconnect.Connect).
```

**Comment by BogusCurry** [comment]
Moin Alex ;D
In der Logdatei steht dieses hier 
`Loaded: /home/gerriet/.local/share/Steam/steamapps/common/X-Plane 11/Resources/plugins/Little Xpconnect/64/lin.xpl (ABarthel.LittleXpconnect.Connect).`

Also das sieht sehr correct aus ;D

Tschöö
Gerriet

**Comment by albar965** [comment]
Hast Du eine Ahnung, woran es lag? Das hilft mir bei ähnlichen Problemen.
Ich mache das Ticket vorerst mal zu. 
Alex
