### ISSUE TITLE
Duplicate airspaces (from Navigraph and P3D databases)

### ISSUE THREAD

**Issue by laurinius** [albar965/littlenavmap#540]
I updated my P3D data with fsAerodata, so it also contains the same airspaces as the Navigraph source.
Now in Little Navmap every airspace is duplicated, in the tooltip when hovering over the space or in the airspace dialog when clicking. The list contains each airspace once from the P3D and once from the Navigraph database.

This is not affected when choosing to not use Navigraph or choosing to use Navigraph for all functions, the airspaces are still there from both sources.

Would it be possible to add an option to select a single source for all airspaces and ignore the other?

![AS1](https://user-images.githubusercontent.com/50016928/90445656-4994b500-e0e0-11ea-9c1e-91abcb134e6d.PNG)
![AS2](https://user-images.githubusercontent.com/50016928/90445662-4bf70f00-e0e0-11ea-9227-ecf81303eb27.PNG)

**Comment by albar965** [comment]
There is already an option exactly for this. The airspaces are independent of the setting in `Scenery Library`. The sources can be selected in `View` -> `Airspace Source`. Ok, maybe a bit misplaced. I could move this to `Scenery Library`.
Alex
