### ISSUE TITLE
Support for Microsoft Flight Simulator 2020

### ISSUE THREAD

**Issue by thor** [albar965/littlenavmap#541]
I was unable to find a previous issue targeting this, so here's to it: I'd like to propose support for loading airport (and more) information from Microsoft Flight Simulator (2020).

While I'd happily add more information, I'm not sure what else there is -- I imagine getting track of the scenery information is perhaps most useful, with other integrations being of lower priority.

**Comment by mariusvn** [comment]
up

**Comment by albar965** [comment]
https://www.avsim.com/forums/forum/780-little-navmap-little-navconnect-little-logbook-support-forum/

**Comment by albar965** [comment]
Issues for separate topics (flight plan, connection) will follow. Probably have to postpone the LNM 2.6 beta release. Will see.

**Comment by albar965** [comment]
Allow me to close this issue and refer to specific ones for the required building blocks.
I use these also to collect information: #542, #543 and #544.

I'm glad for any information and help. Especially for detecting simulator location (registry) or reading the BGL format. Feel free to comment.
