### ISSUE TITLE
Read MSFS2020 Scenery Library

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#542]
Detect, traverse and read MSFS scenery.
Adapt LNM to BGL file changes.

- [X] Stock airports
- [X] Stock navdata
- [X] Add-on airports

# Paths

Default simulator location MS installer:
`C:\Users\USER\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\UserCfg.opt`

Default simulator location Steam installer:
`C:\Users\USER\AppData\Roaming\Microsoft Flight Simulator\UserCfg.opt`

Get package path from there (example with default MS path):
`InstalledPackagesPath "C:\Users\USER\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages"`

Content (not used in Little Navmap):
`C:\Users\USER\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Content.xml`

Add-ons:
`C:\Users\USER\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\Community`

Default scenery files for additional airports (no airport information):
`C:\Users\USER\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\Official\OneStore\asobo-airport-eidl-donegal\scenery`

Airports
`C:\Users\USER\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\Official\OneStore\fs-base\scenery\0000\APX00070.bgl`
Airport name, city, state and country is localized and can be found in `en-US.locPak` for example.

Navdata
`C:\Users\USER\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\Official\OneStore\fs-base-nav\scenery\0000\ATX00000.bgl`

# Approach to read scenery library

Read `UserCfg.opt` which is supposedly always in the same location:
`C:\Users\USER\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\UserCfg.opt`

Get package path from there:
`InstalledPackagesPath "C:\Users\USER\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages"`

Iterate over 
`C:\Users\USER\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\Official\OneStore`
and read read packages with name `fs-base` and `fs-base-nav`.

Read manifest.json and check for `"content_type": "CORE"` or `"content_type": "SCENERY"`.
Then read `layout.json` and  iterate over paths: `"path": "scenery/0000/ATX00000.bgl"`,

Then read add-on packages as above from
`C:\Users\USER\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\Community`

**FSX/P3D/MSFS filename prefixes:**

- APX	Airports
- ATX	Routing information
- BRX	Bridges
- CVX	Various coastlines waterpolys roads
- NAX MSFS procedures and navaids with dummy airports and COM
- NVX	Navaids - VORs, NDBs, & associated scenery objects.
- OBX	Objects
- DEM	Digital elevation map
- WSX MSFS Scenery objects
- bvcf.bgl	CENTER type airspace boundaries.
- BNXWorld*	Geopolitical and airspace boundaries.

**Comment by nabeelio** [comment]
Looks like the Steam edition is located in AppData\Local\Packages\
Microsoft.FlightDashboard_8wekyb3d8bbwe

**Comment by albar965** [comment]
That's the default path. Hmmm... maybe we should ask here: https://www.fsdeveloper.com/forum/forums/msfs2020.155/ or here https://forums.flightsimulator.com/c/self-service/sdk-discussion/164 .
I'm digging through the BGL changes for now. A lot has changed. For now I can read the airports and runways (partially).

**Comment by Bpendragon** [comment]
Based on my experience at least for a steam install where the package location was changed, there is nothing at `C:\Users\USER\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe` The folder itself doesn't even  exist. 

However, it would appear that the `UserConfig.opt` and `Content.xml` are both located in `AppData\Roaming\Microsoft Flight Simulator` in my case (note roaming, not local)

**Comment by albar965** [comment]
Thanks for the information. What a mess. 🙁

**Comment by Bpendragon** [comment]
> What a mess. 🙁

Yeah, I've conversed with some friends that have the Windows Store Version. It appears that when it comes down to it relevant information will either be in `Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe` or `Roaming\Microsoft Flight Simulator` 

At the very least it's just two paths to check, and it also appears (but I cannot guarantee) That you can check if the `Local` folder exists, and if not, jump over to the `Roaming` folder.

**Comment by albar965** [comment]
Updated **installation locations** above.

**Comment by albar965** [comment]
Good enough for now. #548 might follow in a minor update after the relase or during the beta cycle.
