### ISSUE TITLE
Options windows washed out, no fonts

### ISSUE THREAD

**Issue by Gfurst** [albar965/littlenavmap#545]
Hello there, first let me express my appreciation for this utility, incredibly useful flight planning without need third party, and often, unreliable websites.

![Screenshot_20200824_161717](https://user-images.githubusercontent.com/12454141/91086999-21e4a600-e626-11ea-9160-66d8400c62ab.jpeg)
This picture really says it all, its a weird thing because I use KDE plasma desktop, and qt is standard on most of my applications. I have to say as well, the ui looks reasonably proper everywhere else, is just seems to be affecting the option window, I am at a loss on where to look next, so let me know if I should for anything on my end.

As a side question, I wanted to ask on how to use the topography files the app warns about every start, I figured how to get the files, but how to get the app to read them is very unclear, of course the option window issue didn't help.

Thanks

**Comment by albar965** [comment]
Hi. 
the Linux UI issues are already fixed for the next release (duplicate of #529).

Regarding GLOBE data: Extract the archive to any place (e.g. in `Documents/GLOBE`). The go to the LNM `Options` on page `Cache and Files` and click `Select GLOBE Directory ...`. Choose the folder with the extracted files. That's it.

**Comment by Gfurst** [comment]
Thanks, it all seems solved now!
