### ISSUE TITLE
Building Marble on Unix - Fails building GpsInfo

### ISSUE THREAD

**Issue by ninoz** [albar965/littlenavmap#549]
Hi

I'm following the compilation guide on the wiki and I have atools etc compiled.

I'm having some issues getting marble compiled, I have cloned the repo as per the guide but its failing at this step and I can't work out why, it looks to be failing on GpsInfo, make being ran with debug enabled:

> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> Reading makefiles...
> Updating makefiles....
> Updating goal targets....
>  File 'src/plugins/render/gpsinfo/CMakeFiles/GpsInfo.dir/depend' does not exist.
> Must remake target 'src/plugins/render/gpsinfo/CMakeFiles/GpsInfo.dir/depend'.
> Successfully remade target file 'src/plugins/render/gpsinfo/CMakeFiles/GpsInfo.dir/depend'.
> GNU Make 4.2.1
> Built for x86_64-pc-linux-gnu
> Copyright (C) 1988-2016 Free Software Foundation, Inc.
> Licence GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> Reading makefiles...
> Updating makefiles....
> Updating goal targets....
>  File 'src/plugins/render/gpsinfo/CMakeFiles/GpsInfo.dir/build' does not exist.
>    File 'src/plugins/render/gpsinfo/libGpsInfo.so' does not exist.
>      File 'src/plugins/render/gpsinfo/CMakeFiles/GpsInfo.dir/GpsInfo.cpp.o' does not exist.
>     Must remake target 'src/plugins/render/gpsinfo/CMakeFiles/GpsInfo.dir/GpsInfo.cpp.o'.
> [ 65%] Building CXX object src/plugins/render/gpsinfo/CMakeFiles/GpsInfo.dir/GpsInfo.cpp.o
> /opt/dev/simtools/release/marble/src/plugins/render/gpsinfo/GpsInfo.cpp:87:24: error: return type ‘class QIcon’ is incomplete
>  QIcon GpsInfo::icon () const
>                         ^~~~~
> /opt/dev/simtools/release/marble/src/plugins/render/gpsinfo/GpsInfo.cpp: In member function ‘virtual void Marble::GpsInfo::icon() const’:
> /opt/dev/simtools/release/marble/src/plugins/render/gpsinfo/GpsInfo.cpp:89:51: error: invalid use of incomplete type ‘class QIcon’
>      return QIcon(QStringLiteral(":/icons/gps.png"));
>                                                    ^
> In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h:54,
>                  from /usr/include/x86_64-linux-gnu/qt5/QtCore/QObject:1,
>                  from /opt/dev/simtools/release/marble/src/lib/marble/RenderPlugin.h:17,
>                  from /opt/dev/simtools/release/marble/src/lib/marble/AbstractFloatItem.h:18,
>                  from /opt/dev/simtools/release/marble/src/plugins/render/gpsinfo/GpsInfo.h:20,
>                  from /opt/dev/simtools/release/marble/src/plugins/render/gpsinfo/GpsInfo.cpp:11:
> /usr/include/x86_64-linux-gnu/qt5/QtCore/qmetatype.h:1971:1: note: forward declaration of ‘class QIcon’
>  QT_FOR_EACH_STATIC_GUI_CLASS(QT_FORWARD_DECLARE_STATIC_TYPES_ITER)
>  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
> make[2]: *** [src/plugins/render/gpsinfo/CMakeFiles/GpsInfo.dir/build.make:67: src/plugins/render/gpsinfo/CMakeFiles/GpsInfo.dir/GpsInfo.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:1151: src/plugins/render/gpsinfo/CMakeFiles/GpsInfo.dir/all] Error 2
> make: *** [Makefile:163: all] Error 2

**Comment by albar965** [comment]
You probably cloned the wrong branch. Also, some Qt versions cause these include issues which can be easily solved by just adding them. Lemme know if that happens.

**Comment by ninoz** [comment]
Hi , I had cloned the lnm/1.1 branch.  I managed to "solve" the issues by adding 

#include <QtWidgets>

At the top of the files which raised the errors, and it seemed to compile everything, so I closed the issue.

Just having issues compiling Little Navmap now but ill have a go at fixing first myself :)
