### ISSUE TITLE
Map on top of other windows (request)

### ISSUE THREAD

**Issue by GabrielSampol** [albar965/littlenavmap#551]
Hi,
I have just started to use Little Navmap and I am missing a feature, that I consider very important.

I run MS Flight Simulator windowed (in Windows 10) but covering the full screen. I would like to follow the flight on the Little Navmap Map that is great, but I can't see both windows at a time. It would be great if you could make the map window to be always on top of other windows so that it is always shown on top of the MS FS window.  In that way it could replace the very limited navigation map of MS FS.

**Comment by albar965** [comment]
Hi Gabriel,
I guess this was done with a49540ad704261cbb0c753b76c0eb24980b5bd02 which will be published with the next beta.
But this only keeps the LNM main window on top. It does not integrate into MSFS and I did not check with MSFS running in full screen yet.
Test it once the beta with MSFS support (and much more) is out.

I'm running LNM on an old second monitor. You an also use the networked option and run LNM on an old Notebook across the network.

I'm closing this issue. Feel free reopen if needed.

Alex

**Comment by AndersHogqvist** [comment]
Or check this out: https://spacedesk.net/

Free app that makes your tablet a second screen. I've used it with a very old Galaxy Tab and that worked well except a considerable lag. The tablet is laggy on its own so that would probably be better using a newer model.
