### ISSUE TITLE
[SUGGESTION] Option to add IVAO/VATSIM ID so user plane isn't shown twice

### ISSUE THREAD

**Issue by rodrifo6** [albar965/littlenavmap#552]
Hi everyone.

I just started using the program and I'm in love with it. I use it for all my flights on IVAO and it's really useful that you can see the online traffic on the program itself.

However, the app also shows your aircraft twice: once for the simulator-based tracking, and once for the data it receives from the online servers.

For that reason I'd like to suggest a new field be added to the configuration window where the user can enter their ID and the option for the app to ignore online data from that particular ID. This way you won't get duplicated entries on the map for the user.

Player acft shown twice:
![image](https://user-images.githubusercontent.com/68970319/92360036-93126780-f0c2-11ea-869a-c68eb4fc2502.png)

**Comment by albar965** [comment]
You can remove the duplicates if the registration of the aircraft injected as AI into the simulator matches the callsign in the online interface (`whazzup.txt`). 
LNM will detect the duplicates for user and other aircraft and show only the ones fetched from the simulator. See [22.1. Simulator and Online Aircraft Duplicates](https://www.littlenavmap.org/manuals/littlenavmap/release/2.4/en/ONLINENETWORKS.html#simulator-and-online-aircraft-duplicates).

There might be a setting on the online client (X-IvAp or others) which should inject the callsign as the registration into the simulator aircraft. I'll keep this issue as a future option.

**Comment by rodrifo6** [comment]
Hi, Albar. Thanks for the answer.
I have to confess I didn't know that already existed. As I said I'm kinda new to the app and I didn't really RTFM.
As it happens, I just tried what you described on MFS2020: I set my callsign to the same I'm using online, and it still showed me a duplicated airplane.
![image](https://user-images.githubusercontent.com/68970319/92417667-b4626a80-f139-11ea-907c-924a32050559.png)

Maybe it's reading the tailnumber instead of the callsign?

Thanks again for the answer.
Rodrigo

**Comment by albar965** [comment]
Yes, the feature is a bit hidden in the manual. You proposal is probably the easiest way to get rid of the dupes.

The callsign has to match the field `Registration`. You can see the reg in the `Simulator Aircraft` dock on the `Aircraft` tab.
I did not try this in MSFS yet.
I had a screenshot showing the relation but I cannot find it. 🙁

**Comment by tonghuix** [comment]
I will try this solution!

**Comment by ferryvanaesch** [comment]
Is it possible to compare the VATSIM Registration to the Flight Number field in the Aircraft properties? They do seem to match?

**Comment by albar965** [comment]
> Is it possible to compare the VATSIM Registration to the Flight Number field in the Aircraft properties? They do seem to match?

I can try this as an additional criteria. Thanks for the hint.
But the idea is to compare the aircraft position to find the matching ones right after downloading the online clients (#761).

**Comment by albar965** [comment]
> I have LNM running on a different computer?

This does not make a difference. The data transferred through the network (Navconnect to Navmap) is the same.

**Comment by ferryvanaesch** [comment]
Ok, in that case I don't really know why it doesn't seem to match in my case.

**Comment by albar965** [comment]
Current stable LNM 2.6 only checks Callsign (online) versus Registration (simulator).
I'll add a better solution to one of the next alpha versions.
