### ISSUE TITLE
Minimum size of lower docked windows too large

### ISSUE THREAD

**Issue by marccreal** [albar965/littlenavmap#556]
In the screenshot, you see all the docked windows ("Flugplanung", "Höhenprofil" etc) to their minimum size (with respect to the direction of corresponding screen border). The minimum size of the lower windows ("Höhenprofil" and "Simulatorflugzeug") seem too big (at least I see no reason why it should not be possible to make it smaller). 
It just tried around undocking and redocking these windows and with that, the minimum size reduces to the height of the window when it was undocked. When I "Reset Window to Default Layout", the situation is again as shown in the screenshot.
![Screenshot (116)](https://user-images.githubusercontent.com/63705372/93661764-b2ae7600-fa5a-11ea-8075-d5181c64f91d.png)

**Comment by albar965** [comment]
This is an annoying problem with the dock window and layout manager of the Qt library I'm using. Hard to fix for me. I have already tried all possible workarounds, but without success.

Sometimes it goes away when you restart or re-arrange the docks.
Also, disallowing to undock the map window helps.

**Comment by albar965** [comment]
Should be fixed in the later 2.6 betas. The default layout does not leave the elevation window blocked anymore.
