### ISSUE TITLE
MSFS does not load some flight plans.

### ISSUE THREAD

**Issue by Caid8** [albar965/littlenavmap#557]
MSFS refuses to load a flight plan if it contains non-English characters. 

For example, Little Navmap shows that LETI Spanish airport name is 'El Tiétar', which is correct. MSFS shows that LETI's name is 'El Tietar'.

If you create a flight plan that includes 'El Tiétar' and export it to a PLN file, MSFS will not be able to load this plan unless you manually edit the file and change 'é' as 'e'. You should change both the content and the file name.

These are the Spanish characters that can cause problems, and how they should be changed when the flight plan is exported:

á -> a
é -> e
í -> i
ó -> o
ú -> u
ñ -> n

OS: Windows 10 Pro 64 bit
Flight sim: MSFS
Steps to reproduce: create a flight plan with an airport with a tilde or ñ letter (like Tiétar, León or Coruña) , and export it to MSFS PLN file.

Attached files: 

[VFR Cuatro Vientos (LECU) to El Tietar (LETI).zip](https://github.com/albar965/littlenavmap/files/5249812/VFR.Cuatro.Vientos.LECU.to.El.Tietar.LETI.zip)

Many thanks for your work in Little Navmap :) Kind regards.

**Comment by albar965** [comment]
Known problem and already fixed. Commits 4577a3e56329954f0d941e66bb7fb398ccb4227b and ca812e5c8f86ceb10c79ef528e966211ef6a9119 deal with this and remove all the diacritics from characters in the file name (ä -> a, etc.).
Thanks for the report.

BTW: This is actually a MSFS bug and should be reported to them.
