### ISSUE TITLE
cant open the exe

### ISSUE THREAD

**Issue by kartal2339** [albar965/littlenavmap#558]
hi.. i downloaded this but in my file i cant see the exe properly and when i try to open it that said me choose a program ..i tried with java but i cant oppen ...what can i do for it ?
![C__Users_unsal_Documents_littlenavmap-master 19 09 2020 16_23_17_LI](https://user-images.githubusercontent.com/33800597/93668412-c2e34700-fa94-11ea-84ac-52a5f21fe9db.jpg)

**Comment by albar965** [comment]
You downloaded the sources. This is the right download for Windows: [LittleNavmap-win-2.6.0.beta.zip](https://github.com/albar965/littlenavmap/releases/download/v2.6.0.beta/LittleNavmap-win-2.6.0.beta.zip)
