### ISSUE TITLE
Incorrect Airline for AI/multiplayer 

### ISSUE THREAD

**Issue by hass-laughingman** [albar965/littlenavmap#559]
Hi albar965.
I'm currently trialing the 2.6.0.beta, on Windows 10x64 with MSFS2020, connected locally.
I've noticed the Airline for AI/Multiplayer traffic is the same as the player plane. Screenshot included indicating the issue.

![mapview](https://user-images.githubusercontent.com/9951907/93686522-b4098e00-faae-11ea-9f20-48384aa29cc3.png)
![player](https://user-images.githubusercontent.com/9951907/93686523-b4a22480-faae-11ea-9d05-9742c81b88bd.png)
![ai1](https://user-images.githubusercontent.com/9951907/93686519-b2d86100-faae-11ea-8da3-5cc82b66ac2e.png)
![ai-flying](https://user-images.githubusercontent.com/9951907/93686520-b370f780-faae-11ea-8729-7f9a9398a11e.png)

I've previously used the 2.4.5 version again connected locally to MSFS2020 and it was showing the correct airline name for the traffic. I can't confirm if the issue is with LNM or MSFS2020 since there was an update for MSFS2020.

Thanks for working on the app, it really is great and a must-have for flight sim.
Regards, Hass

**Comment by albar965** [comment]
Thanks for the detailed report but a tiny bit too late. 🙂
I just fixed this in commit 6aba1eeb8d5fee4b2d5df3e48f93efa5589f9453.

**Comment by hass-laughingman** [comment]
awesome! thanks again
