### ISSUE TITLE
Planes Injected for VATSIM all have the same call sign

### ISSUE THREAD

**Issue by jct32** [albar965/littlenavmap#561]
I don't know if there is way to get around this but I prefer using the traffic from the simulation when I fly on VATSIM since it gets updated more often. However all the planes have the same type and call sign as the user plane. Am I configured wrong with something? 

Below is an example picture. I'm using LNM 2.4.5 with the 11.50 Release of X-Plane 11 and the latest version of xPilot.

![lnm1](https://user-images.githubusercontent.com/23410466/93724646-9ac81680-fb6e-11ea-97c9-0074aa1433c3.PNG)

**Comment by albar965** [comment]
This is most likely an xPilot issue. LNM simply ready all the AI/multiplayer datarefs.

**Comment by jct32** [comment]
Yeah, I think I'll get in contact with the developer for it. As a data point, I upgraded my LNM to the latest version same with Little Navconnect. It no longer displays my own ship information for every aircraft now but instead just gives a number (1, 2, 3, 4) for the planes. I can post a screenshot later tonight if you are interested.

**Comment by jct32** [comment]
Just as an update I passed the information to them and they said they are pushing the data via XPMP2. Below is the link to that.

https://github.com/TwinFan/XPMP2

**Comment by albar965** [comment]
> It no longer displays my own ship information for every aircraft now but instead just gives a number (1, 2, 3, 4) for the planes.
This is already fixed but not released yet. Although, this affects only AI.
Thanks for the link. I didn't know this project. Will have a look at it but too busy now.

**Comment by jct32** [comment]
No worries. I really enjoy your project and I really enjoy VATSIM. Just trying to make the best of it with both :)

**Comment by albar965** [comment]
Should be fixed with 2.6.1.beta
