### ISSUE TITLE
Exception thrown when loading the FS 2020 database

### ISSUE THREAD

**Issue by davidp57** [albar965/littlenavmap#565]
Hello,

I'm using FS 2020 1.8.3.0 on Windows 10 1804.

I get an exception regarding a failed constraint in the database when I try and load the FS 2020 library.

Here's what I do :
[https://i.imgur.com/p1BkLjZ.jpg](url)

And here's what happens :
[https://i.imgur.com/wg1WERu.jpg](url)

I attached the log file.
[abarthel-little_navmap.zip](https://github.com/albar965/littlenavmap/files/5286358/abarthel-little_navmap.zip)

**Comment by albar965** [comment]
Thank you for the detailed report. This was a common problem with add-on airports. This will be fixed with the upcoming 2.6.1.beta.
For now you can exclude the Community folder or the suspected airport add-on.
Alex
