### ISSUE TITLE
Using MSFS Navigraph beta, Airport information is missing

### ISSUE THREAD

**Issue by AndLindemann** [albar965/littlenavmap#566]
I started using the new Navigraph beta to add Navigraph data into MSFS.
After adding the Navigraph data, it seems LNM has trouble reading the MSFS scenery library.
The Airports in LNM are now missing some of their information, especially names. I can only search by ICAO codes now for example.

From the screenshot you can see LNM (correctly?) reads both the MSFS library file and the custom data file with the Navigraph data. But the airports where Navigraph data is read, are missing a lot of information in the search window.

![CD583B2F-4F0E-4C5B-975C-FA960CC45BE7](https://user-images.githubusercontent.com/4157845/94357413-0fccac00-0099-11eb-82f7-ac5b0ccf841e.jpeg)
![15B995BB-A592-4543-85F2-58156187EA81](https://user-images.githubusercontent.com/4157845/94357414-10fdd900-0099-11eb-9370-21c9611ea74c.jpeg)

My Navigraph scenery library setting is set to use Navigraph data only for navaids and procedures, if that matters - and I did add updated Navigraph data to LNM as well to have the same data available in the Sim and LNM.

Obviously if I switch the setting to use Navigraph for all data, things are working fine.
But then there might be inconsistencies between the Sim and LNM I guess for airport details and things not covered by the Navigraph MSFS data?

**Comment by albar965** [comment]
Thank you for the detailed report.

Keep in mind that 2.6.0.beta was not adapted to the Navigraph update at all.

For the upcoming 2.6.1.beta:

- Missing names when using Navigraph is already fixed.
- Country name missing is an MSFS issue. They are not part of the translation tables.

Names are taken from translation tables. These might change after reloading when you change the LNM UI language in `Options` -> `User Interface`. An example is `Munich` vs. `München`.

MSFS does not define a scenery loading order. There is no `scenery.cfg` and I've not seen a `manifest.json` containing a priority. Bad omission of Asobo. 
Therefore, if you use add-on airports you have to rename them to put them back into the loading hierarchy after the Navigraph update. Simply prefix the add-on folder with a `z_` or something else to change loading order. Did not test this in MSFS yet. Feel free to report the results.

Closing issue for now. 
**If you see any problem where LNM behaves unexpectedly or different to the simulator with the 2.6.1.beta: Please report it here.**

Screenshot below from Linux test environment (developing on Linux, tesing on Windows):
![grafik](https://user-images.githubusercontent.com/15254956/94362293-9ba30000-00ba-11eb-8253-b75f0225a4cb.png)

**Comment by AndLindemann** [comment]
Perfect. Thanks for the hint on the load order thing regarding base/navigraph/community addons also. Going to check how that looks for the few airports where I have a mod installed now. 👍

**Comment by albar965** [comment]
Just did some more research and it seems that the `Content.xml` might play a role in ordering.

But there is no way in MSFS to reorder this and packages are simply added to the end of the list. 🙄
And it is not documented at all.😠
