### ISSUE TITLE
Little Navmap 2.6.1 and Little Xpconnect 1.0.19: version mismatch

### ISSUE THREAD

**Issue by Skarafaz** [albar965/littlenavmap#568]
Hi! Thanks for the wonderful app and for your work. 

Is the latest beta version of Little Navmap compatible with the latest version of Little Xpconnect? When I try to connect, it tells me that Xpconnect is too old.

Thanks

**Comment by albar965** [comment]
The programs are not compatible anymore. I had to do few changes.
Install the Xpconnect version 1.0.20.beta that is include in the LNM download archive. This will fix the issue.
Alex
