### ISSUE TITLE
Separate Map window

### ISSUE THREAD

**Issue by johanneseckert** [albar965/littlenavmap#571]
in LNM 2.6.0 beta it does not look like you can undock the Map window for an isolated map view. Undocked windows can also be resized to a very small size, which will be helpful to include the Map as an OBS overlay

**Comment by albar965** [comment]
Latest is 2.6.1.beta. I did some changes to the docking functionality there. Please check it there.

You can enable undocking in options on page map. I disabled undockability as default for new users since it makes arranging the windows a tedious task. Users can still can enable it if wanted.

**Comment by johanneseckert** [comment]
great! thank you. this setting makes window management feel more _modern_

brings me to #572
