### ISSUE TITLE
Undocked windows can't be captured by OBS

### ISSUE THREAD

**Issue by johanneseckert** [albar965/littlenavmap#572]
I'd like to be able to capture an undocked window of LNM into OBS. I.e. i want to put the map view into the corner of my stream.

![image](https://user-images.githubusercontent.com/545926/95515066-52f21d80-09bd-11eb-91a3-7f0db1fc855d.png)

Unfortunately, OBS does not detect undocked windows. I wouldn't be surprised if that's a framework issue, but maybe there's a workaround?

![image](https://user-images.githubusercontent.com/545926/95515048-4c63a600-09bd-11eb-8432-5fa32aefb8dd.png)

**Comment by albar965** [comment]
Have a look at the [Web Server](https://www.littlenavmap.org/manuals/littlenavmap/release/2.6/en/WEBSERVER.html) in LNM. Maybe this is more helpful thank the dock windows. The dock windows have a few limitations which I'm trying to workaround for a long time already.

**Comment by SgtFreddy713** [comment]
> I'd like to be able to capture an undocked window of LNM into OBS. I.e. i want to put the map view into the corner of my stream.
> 
> ![image](https://user-images.githubusercontent.com/545926/95515066-52f21d80-09bd-11eb-91a3-7f0db1fc855d.png)
> 
> Unfortunately, OBS does not detect undocked windows. I wouldn't be surprised if that's a framework issue, but maybe there's a workaround?
> 
> ![image](https://user-images.githubusercontent.com/545926/95515048-4c63a600-09bd-11eb-8432-5fa32aefb8dd.png)

Hey! A good solution is this. Let the map in the default view of LNM nad caputre LNM with obs, after that use the filter "crop" or something like that, and you can crop the scene and leave only the map. Idk I do not know if I express myself well, but if you do not understand let me know and I will leave you some photos! Good luck

**Comment by johanneseckert** [comment]
I think this will work. luckily, the window layout presets in LMN include application size as well. It need to make the map rather small, so the scale works out on stream. I'll try this next time @SgtFreddy713

**Comment by SgtFreddy713** [comment]
> I think this will work. luckily, the window layout presets in LMN include application size as well. It need to make the map rather small, so the scale works out on stream. I'll try this next time @SgtFreddy713

Good! Good luck with that

**Comment by albar965** [comment]
Capturing dock windows won't work. Use the web server. Closing.
