### ISSUE TITLE
Load Scenery Library - Still crashing!

### ISSUE THREAD

**Issue by ChrizzyO** [albar965/littlenavmap#573]
Read the changelog: "Remove the MSFS Community folder from the ignore list in Little Navmap, Options, page Scenery Library Database if you added it. The exclusion to avoid the crash is not needed anymore."

I still get a exception window when loading the scenery library when it scans my community folder filled with freeware airports as well as payware ones etc.

**Comment by albar965** [comment]
Can you post the error message? 
There are still a few airports which cause a recoverable error but I have no idea if I can fix this. I suspect these are compiled with a very old MSFS SDK.

**Comment by albar965** [comment]
No feedback but I suppose this is fixed with 2.6.3.beta
