### ISSUE TITLE
Little Navmap doesn't load FS2020 scenary library.

### ISSUE THREAD

**Issue by SgtFreddy713** [albar965/littlenavmap#579]
Hello. I have Little Navmap and doesn't load scenary library of FS2020, i do the correct steps i think, here is some photos

![image](https://user-images.githubusercontent.com/68628541/96508345-d5d26e00-1230-11eb-8abd-86f9d929b890.png)
![image](https://user-images.githubusercontent.com/68628541/96508423-f5699680-1230-11eb-988b-2f0b76812067.png)

I have a custom route of the game because i have it in other HDD. Thanks for the help :)

**Comment by albar965** [comment]
What means "does not load"? Do you get an error message?
Do you use the latest 2.6.2.beta?
Did you try to reset the path?
Can you tell me where the file `UserCfg.opt` is located on your computer and what is the last line in it?
Did you install several different versions of MSFS like first MS subscription and then Steam?

You can also help me if you send me the log file of LNM after running a loading attempt. Contact is here on my page: https://albar965.github.io/index.html
Alex

**Comment by SgtFreddy713** [comment]
> What means "does not load"? Do you get an error message?
> Do you use the latest 2.6.2.beta?
> Did you try to reset the path?
> Can you tell me where the file `UserCfg.opt` is located on your computer and what is the last line in it?
> Did you install several different versions of MSFS like first MS subscription and then Steam?
> 
> You can also help me if you send me the log file of LNM after running a loading attempt. Contact is here on my page: https://albar965.github.io/index.html
> Alex

Hey! Well, i mean the airports, waypoints. etc if you see the photo i send it loads, but isn't showing in the map, The community and official folders are in "D:\Juegos\DATOS FS2020" Just a custom route, and UserCfg.opt are in "C:\Users\myuser\AppData\Roaming\Microsoft Flight Simulator"
And yes, im using the last version. 2.6.2 beta

**Comment by albar965** [comment]
Sorry. Stupid me. I did not look at the object counts. Too many emails and posts recently.🙁

The numbers look about ok to me.

Now seeing this it looks like an issue with the LNM display settings. Can you try `View` -> `Reset display settings`?

Log file can be opened in `Tools` -> `Files and directories` -> `Open logfile`.
Alex

**Comment by SgtFreddy713** [comment]
> Sorry. Stupid me. I did not look at the object counts. Too many emails and posts recently.🙁
> 
> The numbers look about ok to me.
> 
> Now seeing this it looks like an issue with the LNM display settings. Can you try `View` -> `Reset display settings`?
> 
> Log file can be opened in `Tools` -> `Files and directories` -> `Open logfile`.
> Alex

Yeah, no problem! :). I try reset display settings and still doesn't show some airports, I load again the scenery library and this is the log file

[abarthel-little_navmap.log](https://github.com/albar965/littlenavmap/files/5410584/abarthel-little_navmap.log)

**Comment by albar965** [comment]
Are some airports missing or all?

**Comment by SgtFreddy713** [comment]
> Are some airports missing or all?
> 
> **Edit: I see no obvious issues in the log. All is loading fine.**

I think all, because in LNM there is the default airports i think, and a lot of airports of FS doesn't appear ,And it seems strange to me, because a friend has the game too and loads everything well, and we made comparisons of airports and the ones that he have, I don't have. Nothing happens, anyway thanks for the help :D

**Comment by albar965** [comment]
This is a display issue which cannot be detected from the log. Please post a screenshot of the whole LNM window including title bar. Sometimes this helps to detect wrong settings.

**Comment by SgtFreddy713** [comment]
> This is a display issue which cannot be detected from the log. Please post a screenshot of the whole LNM window including title bar. Sometimes this helps to detect wrong settings.


I just disabled airspaces and minimum altitudes because i don't like it, but all is default i think

![image](https://user-images.githubusercontent.com/68628541/96798302-f9cfb400-13d6-11eb-99cc-84cdca007aa0.png)

**Comment by albar965** [comment]
You're using Navigraph only mode which you can notice by the `(MSFS)` in brackets. No wonder that airports are missing.

Didn't you read the warning dialog when switching to this?

See here in the manual: https://www.littlenavmap.org/manuals/littlenavmap/release/2.6/en/NAVDATA.html
