### ISSUE TITLE
Adjust flight plan alt button for hemispherical rule

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#58]
Add a button that takes the current altitude and adjusts it according to hemispherical rule.
If the whole route goes westerly make even otherwise odd thousands.
If VFR add another 500 feet.

Add option for transition  altitude for this rule (6000 in Europe, 18000 rest)..

**Comment by albar965** [comment]
Done but will not add an option for the transition altitude. Can be done manually by the user.

**Comment by PaulFWatts** [comment]
Tested on Mac and Windows
