### ISSUE TITLE
LNM not launching

### ISSUE THREAD

**Issue by zazaboeing** [albar965/littlenavmap#584]
MSFS 2020 latest patch / Windows10

Crashing (not opening) every time (after initial splash screen is displayed).Tried as administrator and all other compatibility modes. 

Error in event viewer:

_Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: littlenavmap.exe
P2: 0.0.0.0
P3: 5f8d5dca
P4: littlenavmap.exe
P5: 0.0.0.0
P6: 5f8d5dca
P7: c0000005
P8: 00382c17
P9: 
P10: 

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_littlenavmap.exe_988299a0de11d5bf9f3e09da878e31e19c634af_d17c15fa_3a36d2c2-8343-4aa4-b924-88792b33f0f2

Analysis symbol: 
Rechecking for solution: 0
Report Id: 47690897-d7b7-4f25-bec6-a9317dc7b13b
Report Status: 4
Hashed bucket: 
Cab Guid: 0_

**Comment by albar965** [comment]
Please send me the LNM log per email (contact here: https://albar965.github.io/index.html)

Log file is `C:\Users\YOURUSERNAME\AppData\Local\Temp\abarthel-little_navmap.log`

Alex

**Comment by albar965** [comment]
I guess this is fixed.

**Comment by zazaboeing** [comment]
Hi Alex, sorry to be so late to respond. It suddenly started working again, I did NOTHING and after some PC restarts it works. Thanks for the help.

**Comment by albar965** [comment]
Ok. This might also be caused by a certain flight plan or performance profile. Let me know if it blows up again. :-)
