### ISSUE TITLE
Online airspaces could use some improvement

### ISSUE THREAD

**Issue by Gfurst** [albar965/littlenavmap#585]
First let me tell I've trying to setup user airspaces and getting my ass kicked, the airspace definitions according to http://www.winpilot.com/UsersGuide/UserAirspace.asp seem really unintuitive, and there is no clear distinction between airspace class ( A, C, E...) and purpose (CTR, TWR, APP...). If there are proper ways to define this with the format in question please let me know.

But to the point in question, I'm using navmap alongside X-Plane and the Vatsim network, its being really troublesome to assign one of the defined airspaces to a online controller, I've tried both methods (of single file vs named airspace), and they some times will fit the boundaries, sometimes will not, plus there is the issue of ATIS service being shown as its own tower instead of a service for an already existing tower. 

So I'd like to propose that instead having to define a whole airspace in the manner that is currently, that instead we just assign pointers to existing named airspace, found in any of sources already available (navigraph, simulator or user defined). This could be simply within the interface of the app for easiness, but it also could open the opportunity have more than a single airspace assigned to the same controller. For example I've ran into this tricky situation where the CTR is the APP for an area, but it has two distinctively defined airspace, a smaller for lower ground level, and much larger one for high flight levels.

**Comment by albar965** [comment]
This might get interesting with #585
Let's target this for 2.8. 
2.6 is too much delayed for my taste so far.

**Comment by Gfurst** [comment]
Nice

**Comment by albar965** [comment]
Isn't this fixed with #593 and #490?

I just wish I had a better data source for VATSIM.

Feel free to reopen or create a new issue if something is missing.
