### ISSUE TITLE
Unable to set as departure in 2.6.2 beta

### ISSUE THREAD

**Issue by davidbuckleyni** [albar965/littlenavmap#588]
Since new update i cannot set an airport departure when i right click set as departure is not avail and when i try to upload into msfs it says i am airborne im wanting to take off from airport Aldergrove Belfast  runway 25

![Desktop Screenshot 2020 11 02 - 13 14 49 13](https://user-images.githubusercontent.com/5619229/97872123-66b74800-1d0d-11eb-9cb1-9d8bbca1a682.png)

**Comment by albar965** [comment]
You have to right click on the airport icon.
