### ISSUE TITLE
LittleNavMap Hangs on macOS Big Sur

### ISSUE THREAD

**Issue by waterbwuk** [albar965/littlenavmap#589]
I saw a post about this on another website, but no open or closed issues on here.

Little Navmap 2.6.2 Beta on macOS Big Sur 11.0.1 Beta hangs on application load. The log file only has one line:

`static void NavApp::initSplashScreen()`

@albar965 I know from reading your post on the other forum that you (at least at that time) do not have access to a machine with Big Sur. I can run some tests for you or give you remote access to my system if it would help.

**Comment by albar965** [comment]
Thank you for the offer but this is already fixed for the upcoming 2.6.3.beta. LNM is now built using the latest development tools on Catalina.
Watch here for the beta announcement soon: https://albar965.github.io/index.html
Feel free to reopen the issue if you still see problems with the next release.
