### ISSUE TITLE
Range ring distances get corrupted by number formatting when using Swedish numbers formatting

### ISSUE THREAD

**Issue by Wnthr** [albar965/littlenavmap#590]
OS:
* `Windows 10 64 bit`

Description: When configuring the range rings in Options -> Map:
* Using the Swedish number format with spaces as 1000-separator, any ranges over 999.999 NM gets visually converted into two rings with the smaller numbers (1 500) for 1500.
* On save, the formatted distances are being written to the settings instead of the raw values
* When starting the application again, the ranges are reduced to the smaller numbers.
Steps to reproduce:
* Enter range 500 1000 1500 2000 2500 into the range field
* Apply or click OK
* Put a range ring in North America
* Quit LNM
* Make sure you have Swedish number format selected in Windows
* Open LNM
* Put a range ring in Europe
* Compare the rings
<img width="947" alt="Screenshot 2020-11-12 205418" src="https://user-images.githubusercontent.com/14862505/98989643-ad851900-2529-11eb-816f-e3c2a8ecc484.png">

**Comment by albar965** [comment]
Thanks for reporting. Will fix for the next 2.6 release (most likely a rc)

**Comment by albar965** [comment]
Fixed. Thank you for the clear and detailed report!
