### ISSUE TITLE
Logbook Records - Logging Hours

### ISSUE THREAD

**Issue by simonedmondson** [albar965/littlenavmap#592]
I have a suggestion to improve the flight logging feature:

Given I have completed a flight
When I view my logbook
Then I should see the time flown in hours

This is because it would be nice to see this figure at a glance, and have it reported. Currently, a user needs to open the log detail and calculate the flying time manually by subtracting the departure time from the arrival time.

It would also be a nice bonus if my **total hours flown** were available somewhere.

Apologies of these features already exist.

Thanks for a great app

**Comment by albar965** [comment]
Seems total hours flown is missing in the statistics. Will add. Makes sense.
