### ISSUE TITLE
Unable to load MSFS data from Linux version of littlenavmap

### ISSUE THREAD

**Issue by scresante** [albar965/littlenavmap#594]
OS: Archlinux 5.9.1-arch1-1 x86_64 
FS:  MSFS 1.10.11.0

Steps to reproduce:
* Download and extract LittleNavmap-linux-20.04-2.6.4.beta.tar.gz 
* Mount Windows partition in preparation for loading MSFS data
* Start littlenavmap

Upon doing so, there is no option to select MSFS as a simulator, only X-Plane 11.

![Screenshot_2020-11-18_14-08-58](https://user-images.githubusercontent.com/2119829/99576257-bf424280-29a7-11eb-8bd0-df509c24e03f.png)

MSFS should be an option for the dropdown, giving the ability to work on MSFS flight plans from a Linux system.

**Comment by albar965** [comment]
There is nothing to copy except the LNM Sqlite database:
https://www.littlenavmap.org/manuals/littlenavmap/release/2.6/en/INTRO.html#how-to-run-a-network-setup

Much easier and faster than sharing files.
