### ISSUE TITLE
SID/STAR/Approach Overview

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#595]
Show all airrivals or departures for an airport or a selected runway (use filter in procedure search)

https://www.avsim.com/forums/topic/589961-feature-request-sidstarapproach-overview/

**Comment by Azzhoe** [comment]
This is a very handy feature to have and would make flight planning all the better. Not only is it visually appealing to see the all the different possibilities laid out so clearly but also makes it easier for us to choose connecting waypoints, transitions, etc.

**Comment by stephr64** [comment]
Would appreciate vertical ILS/RNAV profile such as:
![image](https://user-images.githubusercontent.com/4012034/102351818-5a2e3c80-3fa7-11eb-9c59-532609fe7ee4.png)
I still use Jeppview to view the vertical profile.

**Comment by albar965** [comment]
@stephr64  This is more a topic for a new issue: #601 (I stole your image for the new issue :slightly_smiling_face: )
While it will certainly not look like the Jeppview quite a few things can be improved. Some data like the MDA is not available since it depends on aircraft category and more.

**Comment by Gulliver54** [comment]
Can't wait to see this in action. Great.

**Comment by albar965** [comment]
Tooltips for departures indicating multi colors. The transparent flight plan line is enabled. Hence the different display without black outline. Can be customized by the user:
![image](https://user-images.githubusercontent.com/15254956/144745263-85c1806f-3647-4222-bd10-a9304dfe7699.png)

Selection menu with sub-menu for disambiguation:
![image](https://user-images.githubusercontent.com/15254956/144745311-c557d26c-bd5b-4932-8498-ce0e5848af66.png)

Filter SID by names starting with `NE`. Preview for all is automatically updated while typing:
![image](https://user-images.githubusercontent.com/15254956/144745376-6c387e12-8cd1-4806-9965-0e34d23e7b77.png)

Selecting a STAR which usable for all runways (same applies for SID/STAR with parallel runway assignment):
![image](https://user-images.githubusercontent.com/15254956/144745532-4e79fb0d-2774-4f8c-b7c6-d55060a37eac.png)

Runway selection dialog for STAR HELE2A now used instead of a sub-menu:
![image](https://user-images.githubusercontent.com/15254956/144745558-a0e11be3-eaf2-4d43-94a8-2363e735f4ed.png)

**Comment by Gulliver54** [comment]
Hi Alex,
Thanks for your extensive aswers.

Will look into it more thoroughly tomorrow.
Now we are celebrating Sinterklaas.

vr.gr. Gradus
Send from my A41

Op zo 5 dec. 2021 13:01 schreef Alexander Barthel ***@***.***

**Comment by Azzhoe** [comment]
Looking good Alex! Thanks for working on this. Definitely looking forward to using this soon! :)

**Comment by gabfus** [comment]
Hello, is very usefull. But when I have more sid and star on airport (when I see all the selection is not clear. 
You can add when I move with mouse over a sid or star in map autoselect sid or star in Find windows Pocedure? Or color procedure with the same color into map? Or when I select a SID or Star on Find procedure panel, grayed all unselected procedure and see only selected procedure.

Thanks for your job

**Comment by Gulliver54** [comment]
Hi Gabfus,

You have to narrow down your selection. Fill in the expected runway and procedure type in the search window. In your case Runway 15 and Departure.  It also helps to show transparent lines.
Gulliver

![afbeelding](https://user-images.githubusercontent.com/33782220/154840219-82ffb781-5684-4200-a55e-beb9d7e7d11e.png)

**Comment by albar965** [comment]
Not sure what can be improved to distinguish the procedures. Currently there are colors which also show up in the menu and you can highlight a procedure additionally by selecting it in the procedure view.

Dotted lines to show different colors?
Displaced lines?

The map context menu already provides disambiguation.

BTW: It looks better if you select the transparent mode for the flight plan line in options.

**Comment by stephr64** [comment]
... or partly faded out drawing for all, say alpha 40%, while keeping the colors and highlighting a procedure when hovering it's name in a side list
________________________________

**Comment by albar965** [comment]
I'll check if I can highlight it while hovering in the context menu.
Selection in procedure list already highlights it.

**Comment by GitPuffy** [comment]
> BTW: It looks better if you select the transparent mode for the flight plan line in options.

The dense must be strong in me.  I cannot find "transparent mode" in Preferences > Flight Plan (I'm on a Mac) or under any of the options in Preferences.  Please point me in the right direction.  I want to see what the difference may look like.

Thank you.

**Comment by albar965** [comment]
> The dense must be strong in me. I cannot find "transparent mode" in Preferences > Flight Plan (I'm on a Mac) or under any of the options in Preferences. Please point me in the right direction. I want to see what the difference may look like.

No need to feel guilty :slightly_smiling_face: . The alpha version has no manual yet. Go to menu -> "Little Navmap" -> "Preferences" and there check transparent line:
![grafik](https://user-images.githubusercontent.com/15254956/155196072-1e1c03b9-28c9-4e72-85cd-fe22685cf4f2.png)

As a result the flight plan looks like on SkyVector.
