### ISSUE TITLE
file saving 

### ISSUE THREAD

**Issue by approxdec** [albar965/littlenavmap#596]
little navmap 2.6.4
windows 10

the save system is a bit clunky after what i remember from 2.4.5

what happens now
the save name for a .lnmpln file is not persistent
that is, once selected and saved once, we must input a filename
each time we save

same for a .pln export. once having selected a filename and exported
we need to input a filename each time the .pln is exported

what should happen
having once selected a filename for a .lnmpln that filename should
be persistent until we change it [for various exports for example]

having selected a filename for a .lnmpln file control-S should save
to that filename until we change it

export should use the .lnmpln filename unless we need to change it

rationale
once we have started a new flight plan and selected 
a name to save it, that is our current 'project' so we would likely want
the file saved with that name. exporting would also likely use that name
unless we want to change it for some reason

**Comment by albar965** [comment]
> the save name for a .lnmpln file is not persistent
> that is, once selected and saved once, we must input a filename
> each time we save

Not the case. File name is always prefilled in the `save as` dialog.
`Save as` does not consider a user changed file name and always builds one by departure and destination.  But that's what `save` is for. 

I can change the logic for `Save as` to use the last user input filename, though. Makes sense.

> same for a .pln export. once having selected a filename and exported
> we need to input a filename each time the .pln is exported

No. I've never seen this. There is always a user constructed file name. User changes are not considered, though and this is also not needed. This would be too complicated in the whole logic. 

Exported files like PLN are disposable output files anyway and can be safely overwritten. The important information is stored in the `lnmpln` file which can always be used to create the exported again. 

> having once selected a filename for a .lnmpln that filename should
> be persistent until we change it [for various exports for example] File name 

I can do this for `Save as` but not for export since some tools are picky about filenames (like MSFS). See above (disposable).

> having selected a filename for a .lnmpln file control-S should save
> to that filename until we change it

I don't understand. That is already the case. Change file name with `Save as` and then a following `Save` will use the same name.
 
> export should use the .lnmpln filename unless we need to change it

No. For reasons above. Some exports need short names, some can use long names and some have restrictions on names.

**Comment by approxdec** [comment]
thanks Alex.

in 2.6.4 , Windows 10

new flight plan with departure and destination.
[image: image.png]

first 'Save Flight Plan' [or 'Save Flight Plan As LNMPLN']
[image: image.png]

filename is departure only.

having input a desired filename, Little Navmap title bar shows that.

[image: image.png]

go to 'Export Flight Plan as P3D or FSX PLN ...'

[image: image.png]

filename has reverted to short form, departure only.

if i return to  'Save Flight Plan As LNMPLN'
i get the short form filename rather than the filename i have selected.

if i return to 'Export Flight Plan as P3D or FSX PLN ...'
i get the short form filename rather than the filename i had selected last
time.


regards
joe




<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by approxdec** [comment]
of course, i can pick up the <filename>.pln i have chosen from the file
dialog
but that is not as convenient as having the filename already there
especially when doing a large flight plan with many iterations.
joe

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by albar965** [comment]
Sorry but I cannot see the images. Please don't reply to the email but insert the images here.

**Comment by approxdec** [comment]
thanks Alex.

in 2.6.4 , Windows 10

new flight plan with departure and destination.
![1](https://user-images.githubusercontent.com/3886404/100294229-5166ce00-2fda-11eb-8626-f6d411cf1a1c.png)


first 'Save Flight Plan' [or 'Save Flight Plan As LNMPLN']

![2](https://user-images.githubusercontent.com/3886404/100294257-66dbf800-2fda-11eb-9bed-1101c0bbcea3.png)


filename is departure only.

having input a desired filename, Little Navmap title bar shows that.

![3](https://user-images.githubusercontent.com/3886404/100294279-73f8e700-2fda-11eb-8285-6875832eb745.png)

go to 'Export Flight Plan as P3D or FSX PLN ...'

![4](https://user-images.githubusercontent.com/3886404/100294294-7ce9b880-2fda-11eb-80c2-b742b4e7d5e1.png)


filename has reverted to short form, departure only.

if i return to  'Save Flight Plan As LNMPLN'
i get the short form filename rather than the filename i have selected.

if i return to 'Export Flight Plan as P3D or FSX PLN ...'
i get the short form filename rather than the filename i had selected last time.


of course, i can pick up the <filename>.pln i have chosen from the file dialog
but that is not as convenient as having the filename already there
especially when doing a large flight plan with many iterations.


regards
joe

**Comment by albar965** [comment]
The filename reverting to the short form is a bug. I'll fix this for the next release. It should keep the user filename. Certainly when doing manual saves and export. But not for multiexport. Have to see.

Regarding the file name containing only the depature: Check this setting. Click `Long` to revert to the default if this is not intended:
![grafik](https://user-images.githubusercontent.com/15254956/100337702-077ce880-2fd8-11eb-930f-1241c53f9f1a.png)

**Comment by albar965** [comment]
Using `Save as` now shows the current file name given by the user instead of a generated one. This was a small bug IMO since all programs like Office do the same.

All exports (the ones which use the long names like PLN but not FMS) now adhere to the name given in `Save as`. I agree that this is more intuitive.

From the manual:
> 37.3. File Names
> 
> Name changes in the file dialog from Save Flight Plan as LNMPLN and Save Flight Plan will also be applied to all exported files for formats which allow long file names: LNMPLN, PLN (only FSX, P3D and MSFS), FGFP (FlightGear), HTML and GPX.
> 
> Otherwise the default file name is used for export. See Flight Plan for configuration of default file names.
> 
> This means for example: Renaming the file to My Flight Plan.lnmpln while doing Save Flight Plan as LNMPLN will result in renamed files (My Flight Plan.pln) and FGFP (My Flight Plan.fgfp) files when exporting.

**Comment by albar965** [comment]
Reverted changes back due to conflicts with automatic file name proposals.
Too much effort for small gain.
