### ISSUE TITLE
Flight duration was not recorded correctly

### ISSUE THREAD

**Issue by IslandJohn** [albar965/littlenavmap#597]
* Include your OS and version in detail like: `Windows 10 64 bit` 2004
* Flight simulator and version like: MSFS 1.11.6.0

I did a flight from LOWI to LOWZ, and MSFS showed a flight time for 37 minutes, but LNM recorded it as only 10 minutes.
I performed a few active pauses during the flight.
I had to reset weather half-way through the flight (but did not adjust time of day).

I'll do some more testing on a subsequent flight.

**Comment by albar965** [comment]
LNM records only time from takeoff to touchdown. Other times cannot be recorded reliably since user might change aircraft, time, fuel and whatever before.
