### ISSUE TITLE
Show only addon airports with hard runways?

### ISSUE THREAD

**Issue by Thralni** [albar965/littlenavmap#599]
I distinctly remember in older versions of LNM it was possible to only show airports with hard runways, That way I was able to hide all the tiny airports that are included with OrbX regions. However, in he most recent version, this option doesn't seem available, or doesn't work correctly? When I click "Show addon airports" I see all addon airports, and when I also click "Show airports with hard runways" it shows also all default airports with hard runways in addition to all the addon airports. Would it be possible to make the "Addon airport" button to be a toggle between showing _only_ addon airports or _all_ airports?

**Comment by albar965** [comment]
I just changed this on purpose and public request (Avsim forum). 
Maybe later as a part of the task for more fine grained map display settings.

**Comment by albar965** [comment]
Follow this up for #600 for a finer control of airports.
