### ISSUE TITLE
Add Marble Daylight overlay

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#60]
Show dark/bright zones on earth depending on time.
Time can be changed manually or taken from simconnect.

Example from Marble:
![grafik](https://user-images.githubusercontent.com/15254956/36063506-1f6927de-0e7e-11e8-8ad6-ecf57818006e.png)

**Comment by albar965** [comment]
For my most valued tester. :-)

**Comment by albar965** [comment]
Yes, it is. I had to disable it only for the offline maps because it did not work properly there.
Alex
![grafik](https://user-images.githubusercontent.com/15254956/47494667-bec73400-d841-11e8-8f72-314311f70ee5.png)

**Comment by Gulliver54** [comment]
That is a fast reaction.
Thanks Alex
