### ISSUE TITLE
Improve elevation profile for approach

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#601]
- [x] Add scale and/or horizontal distances for legs
- [x] Horizontal course as in flight plan on map
- [x] Altitude lables along line (or waypoints)
- [x] Approach slope in degree independent of ILS and PAPI on final leg
- [x] FPA for all decent legs?

Add options to enable or disable above.

Now:
![grafik](https://user-images.githubusercontent.com/15254956/102378819-7c838280-3fc6-11eb-9bfa-bdb9ca49b44b.png)

Example:
![grafik](https://user-images.githubusercontent.com/15254956/102378233-de8fb800-3fc5-11eb-8937-387a4883794d.png)

**Comment by stephr64** [comment]
Thank's Alex for your answer (on personal email).

ILS, RNAV or GPS approach requires representation of horizontal course leading to final slope interception (FF). Then, the angle of the final (3°, 3.5, 4 ...), heights and distances at intermediate points (such as markers) between FF and runway. Even on ILS approach, we need a way to be sure being of the slope. This is especially true in IMC...

**Comment by albar965** [comment]
@stephr64  Will consider this and updated the original issue text.

**Comment by Azzhoe** [comment]
Would love to have a vertical profile like those we see on Jeppesen charts. Or similar to that, where we can easily interpret and understand our approach.

**Comment by albar965** [comment]
Distance and course are no problem. Vertical angle is already implemented. MDA is not available in data and therefore not doable.
Maybe also add altitude restriction as text. Have to see.

**Comment by albar965** [comment]
![grafik](https://user-images.githubusercontent.com/15254956/147969389-ee4725d8-c30e-406f-8571-23d600673a4b.png)
