### ISSUE TITLE
Unable to search by state

### ISSUE THREAD

**Issue by Toneking77** [albar965/littlenavmap#602]
I can search by ICAO code.  City works too.  But there no State names in the "State or Province" column. So, unable to search for all airports in a specific State.

**Comment by albar965** [comment]
You issues lacks plenty of information. What simulator, for example.

This all depends on the simulator scenery library, if add-ons are used or not. LNM can just show what it reads from the simulator.

For MSFS countries are missing in the source data. City and state/province are partially missing.
For X-Plane city is partially given, country mostly but not always and state/province not given at all.

**Comment by Toneking77** [comment]
I apologize for jumping the gun!  I'm a new user and didn't realize that I had missed a step (a **HUGE** step).  

I had originally loaded up LNV to use with Xplane.  Just recently, I started using MSFS.  Well, I had not loaded the Scenery Library for MSFS yet.  Again, I apologize for the boneheaded move!  All if working fine now.

Also, if I ever need to submit an issue in the future, I'll be sure to provide plenty of info/details.  

All The Best,

Mike

**Comment by albar965** [comment]
I see. No problem. 
I have to find a way to warn users if they use the wrong scenery library when connecting to a simulator. Happens to me too from time to time.

But I'd really wish the simulators would provide better country, state and city information. Even the old FSX data is more complete than anything else.
Alex
