### ISSUE TITLE
Little XPConnect: need to UNBLOCK FILE on MS Windows

### ISSUE THREAD

**Issue by togfoxy** [albar965/littlenavmap#604]
I installed LNM v2.66 and as per instructions, extracted the LXPConnect into the plugin folder.

LXPC did not show in the admin plugin hence I couldn't use 'live tracking' in LNM. After fumbling around for a while, I right-clicked the LXPC file in MS Windows Explorer and UNBLOCKED the file. This told windows it was a trusted file. I restarted XPlane and LNM and everything worked.

Suggest adding this to MS Windows installation instructions for LXPC and to include a line in the FAQ.

**Comment by albar965** [comment]
Are you sure "Unblock" is a Windows function and not a function of an anti-virus tool. Never seen this on Windows.

**Comment by togfoxy** [comment]
Windows 10

https://mywindowshub.com/how-to-unblock-a-file-in-windows-10/

**Comment by albar965** [comment]
I see. Thanks for the link. I'll add this to the manual.

**Comment by albar965** [comment]
I took note of this internally. Will update installation instructions in readme and user manual.

**Comment by albar965** [comment]
Just added to the manual for 2.6.7.
