### ISSUE TITLE
Have an easy way to add a POI

### ISSUE THREAD

**Issue by davidbuckleyni** [albar965/littlenavmap#605]
I was trying to add a poi which is  POI32->POI13 and POI14 but when i search in the search airports or anywhere else it does not appear how does one add a poi via little nav map please alex? And yes its the mach loop.

**Comment by albar965** [comment]
https://www.littlenavmap.org/manuals/littlenavmap/release/2.6/en/USERPOINT.html
Right click in map and userpoint submenu or Ctrl+Shift+Click into map.
Userpoints have their own search. Be sure that the userpoints are enabled in the view menu.
