### ISSUE TITLE
VATSIM Datafeed

### ISSUE THREAD

**Issue by mbozwood** [albar965/littlenavmap#606]
VATSIM is retiring the current text data feed at the beginning of March, with the potential extension to the end of March, in favour of a more frequently updated JSON format.

The v3 URLs can be seen https://status.vatsim.net/ as `json3=` or we provide an array in https://status.vatsim.net/status.json

A full data specification for the JSON feed can be seen at https://api.vatsim.dev/#operation/DataServerV3 

We will not be retiring servers.txt as this is required by older clients on the network however it is encouraged to use the servers from the JSON data file.

Please direct any questions to me at vpdev[at]vatsim[dot]net

**Comment by albar965** [comment]
@mbozwood Thank you a lot. I would never have noticed that. This is no bigger problem to replace the old whazzup stuff in LNM.

I'll send a few questions by email.

**Comment by albar965** [comment]
@mbozwood: I noticed that the center coordinates are missing in the array `controllers` for each controller in https://status.vatsim.net/status.json 
Any way to add them like they are present in the old http://data.vatsim.net/vatsim-data.txt ?
