### ISSUE TITLE
Missing data for Navigraph AIRAC 2014

### ISSUE THREAD

**Issue by Tatpolc** [albar965/littlenavmap#607]
There is some missing data from the navigraph AIRAC data 2014 which is Phnom Penh (Cambodia) TCA airspace for 2 airport and a whole lot of CTA, TMA and CTR in the Chinese Airspace.

![image](https://user-images.githubusercontent.com/60070229/105615041-0a416180-5e00-11eb-9db9-6c98d54488aa.png)

![image](https://user-images.githubusercontent.com/60070229/105615046-12999c80-5e00-11eb-96d6-07a1dbe910d9.png)
 This is Phnom Penh FIR

![image](https://user-images.githubusercontent.com/60070229/105615067-407ee100-5e00-11eb-9411-72395360dd11.png)

![image](https://user-images.githubusercontent.com/60070229/105615107-9eabc400-5e00-11eb-80de-2329c6095ec9.png)
This is the Chinese Airspace.

**Comment by albar965** [comment]
Thank you for the report. I'll check and try to fix for the next update.

**Comment by albar965** [comment]
Added new airspace types. Unknown new types are now added as general control area.
