### ISSUE TITLE
Erroneous Altitude Data in PLN File

### ISSUE THREAD

**Issue by jgyo** [albar965/littlenavmap#608]
**Problem**

The following steps produce a PLN file that contains a node for the BTE VOR containing a huge altitude field of 39 digits left of the decimal. (Six integer digits can express all reasonable altitudes.) I found the problem when the file caused an XML reading error within FSFlyingSchool for Microsoft 2020.

The "Steps to Reproduce" I give below produced the error on my computer a second time.

**System Config**

OS: Windows 10 64-bit
Microsoft Flight Simulator 2020
Navigraph AIRAC Cycle 2014

**Attachments:**

[Testing Steps.lnmpln.txt](https://github.com/albar965/littlenavmap/files/5862615/Testing.Steps.lnmpln.txt)
[Testing Steps.pln.txt](https://github.com/albar965/littlenavmap/files/5862616/Testing.Steps.pln.txt)
[abarthel-little_navmap.log](https://github.com/albar965/littlenavmap/files/5862614/abarthel-little_navmap.log)

**Steps to reproduce:**

1. Reset for a new flight plan. 
2. View SPHI on the map and Set parking 4 as departure.
3. Find SPEO and show all procedures.
4. Expand Approach VOR 19.
5. Right-click Transition (Full) and select Use SPEO and approach as the destination.
6. Under the Flight Plan menu, select Calculate Flight Plan.
7. Set the Cruise Altitude to 15,000 ft and click adjust.
8. Click Calculate.
9. Close the Calculate Flight Plan dialog box.
10. Save the Flight Plan to an FLT file.
11. Save the Flight Plan to a PLN file.

**Comment by albar965** [comment]
Thank you very much for the detailed report. Will fix with next update.

**Comment by albar965** [comment]
Sorry, I cannot reproduce this. Can you also attach the file `Beechcraft Bonaza.lnmperf` since this might be an issue with the altitude calculation. 
BTE should not appear in the plan at all since it is a part of the procedure.

**Comment by jgyo** [comment]
I just ran the steps again with the following aircraft and reproduced the bug. I've uploaded the lnmpln and pln files I created just now that both show it, too.

[Testing Steps 2.pln.txt](https://github.com/albar965/littlenavmap/files/5898898/Testing.Steps.2.pln.txt)
[Testing Steps 2.lnmpln.txt](https://github.com/albar965/littlenavmap/files/5898899/Testing.Steps.2.lnmpln.txt)
[Beechcraft Bonaza.lnmperf.txt](https://github.com/albar965/littlenavmap/files/5898891/Beechcraft.Bonaza.lnmperf.txt)

**Comment by jgyo** [comment]
I created a video of the steps I used to reproduce the bug that you can download from my OneDrive account here:

[https://1drv.ms/u/s!At8jZTR4z_zW5GFPdS5jRNiQl8mc?e=5brtop](ALT BUG.wmv)

**Comment by albar965** [comment]
@jgyo Thank you for the video, Gil. This helped a lot. These waypoints are only added if a airway leads from or to a procedure and had no altitude updated.
