### ISSUE TITLE
Scratch over the map

### ISSUE THREAD

**Issue by SgtFreddy713** [albar965/littlenavmap#609]
Hello, i have a idea for LNM, sometimes i wanna "draw" on some part of the maps for guide for the flight or teach some things to my friends, could be cool that feature. thx

**Comment by albar965** [comment]
Well, not sure. There are already userpoints, measurment lines and flight plan remarks to legs. Have to see.

**Comment by SgtFreddy713** [comment]
> Well, not sure. There are already userpoints, measurment lines and flight plan remarks to legs. Have to see.

No problem!, Thx anyway :)
