### ISSUE TITLE
[Enhancment] Be able to add position by lat and long

### ISSUE THREAD

**Issue by davidbuckleyni** [albar965/littlenavmap#610]
Sometimes it can be hard to find areas of interest when a scenery pack is installed even with refreshing the libary but we can find everything with Latitude and Longitude under the map menu should be a goto position where a dialog where one can enter lat and long and it would centre the map.,

**Comment by albar965** [comment]
I had this already on my internal list of issues. Idea is to select a menu item "Jump to coordinate" which opens a dialog that can read the various coordinate formats. Click `Ok` and program jumps and zooms to position.

For now you can add a userpoint at any position and then edit its coordinates manually. Then double click the point in the list.

**Comment by davidbuckleyni** [comment]
Yeah I ended up just hacking the xml file lol good to here it will be their just its helpful when finding some points of interest.

**Comment by davidbuckleyni** [comment]
It would be good when you add user points and way points u could name them like say gchq if u flying around chelttleman u could put that in the name columns it looks like ur meant to be able to do it but don't see how

**Comment by davidbuckleyni** [comment]
I guess it didn't make it in as was just bug fixes @albar965

**Comment by albar965** [comment]
The last release was still 2.6 versions which receive bug fixes only. This is scheduled for 2.8 as you can see in the milestone assignment. 2.8 is many months away.

**Comment by davidbuckleyni** [comment]
@albar965 i gather u decided not to persue that

**Comment by albar965** [comment]
@davidbuckleyni  It's scheduled for milestone 2.8 (this is the next after the 2.6 series). But don't expect this soon.

**Comment by albar965** [comment]
![image](https://user-images.githubusercontent.com/15254956/143504049-60e9545c-ba7c-41af-a230-f56cc4a732cc.png)
![image](https://user-images.githubusercontent.com/15254956/143504082-9669f3e0-161f-4cbe-bbdf-c844af49adbb.png)

**Comment by davidbuckleyni** [comment]
Sweet happy to see that

**Comment by davidbuckleyni** [comment]
Question how do we get the coordinates in that format is their a way to have it come from google?

**Comment by albar965** [comment]
> Question how do we get the coordinates in that format is their a way to have it come from google?

LNM tries to recognize various coordinate formats. You can try if LNM detects the Google format in the "add userpoint" dialog, for example.

From the tooltip on the coordinate input field:
```
Recognized coordinate formats:
- Degrees, minutes and seconds : N49° 26' 41.57" E9° 12' 5.49" or 49° 26' 41.57" N 9° 12' 5.49" E
- Degrees and minutes: N54* 16.82' W008* 35.95', N 52 33.58 E 13 17.26 or 49° 26.69' N 9° 12.09' E
- Degrees only: 49.4449° N 9.2015° E or N 49.4449° E 9.2015°
- Degrees with sign: 49.4449 9.2015. Negative is west or south. Order for latitude and longitude depends on option settings.
Degree, minute and second signs can be omitted for above formats.
Latitude has to be first and N/S and E/W designators are required.
A space is only needed to separate latitude and longitude or degrees/minutes/seconds if no signs used.
Other formats:
- Degrees and minutes: N44124W122451, N14544W017479 or S31240E136502
- Degrees only 46N078W
- Degrees and minutes 4620N07805W
- Degrees, minutes and seconds 481200N0112842E (SkyVector)
- Degrees and minutes in pair "N6500 W08000" or "N6500/W08000"
- NAT type 5020N
Formats above have to be given exactly as shown in the examples.
```
