### ISSUE TITLE
Position co-ordinates issue?

### ISSUE THREAD

**Issue by simonedmondson** [albar965/littlenavmap#611]
I have copied flight plan route description to clipboard, for loading into another application (Volanta) and when doing so, the custom way-points are offset and translating incorrectly.

As a test, I took one of the coordinates and put it into Bing maps. It also showed the same incorrect position. 

I have attached images of a route copied from LNM and translated by another application, and another image of a point placed into Bing maps for your reference.  Test route example:

MYBS N0175A020 WIERS 2545N07935W UCRAZ 2531N07941W QUODS 2526N07922W MYCC

- When I paste this route back into LNM, it shows correctly. 
- When I paste it into a different app, the custom positional points are offset to the south-east (2545N07935W, 2531N07941W, 2526N07922W). 
- The points on markers (WIERS, UCRAZ, QUODS) are positioned correctly

![route](https://user-images.githubusercontent.com/2641270/105986514-f4989a00-6094-11eb-869d-58df792e2159.png)
![route2](https://user-images.githubusercontent.com/2641270/105986509-f4000380-6094-11eb-8f2e-e288dd8d0eec.png)

**Comment by albar965** [comment]
What you see is the format `Degrees and minutes (11 characters)`:
https://www.littlenavmap.org/manuals/littlenavmap/release/2.6/en/ROUTEDESCR.html#coordinates

The plan reads fine on SkyVector when I paste the string into the route box. You have to contact the author of the other application.

**Comment by simonedmondson** [comment]
Thank you
