### ISSUE TITLE
Runway selection is not reflected in position coordinates for v2.6.7

### ISSUE THREAD

**Issue by bametz** [albar965/littlenavmap#613]
**Observed Behaviour**
The starting position based on runway selection is not updating the location parameters in the flight plan. The starting coordinate remain always similar to the general coordinates of the airport.
`<Departure>`
`<Pos Lon="9.767263" Lat="48.114849" Alt="1903.00"/> // does not change`
`<Start>22</Start> // does change`
`</Departure>`

This only happens for LittleNavMap Version 2.6.7. In Version 2.6.6. the values change as expected.

**Expected Behaviour**
The position values are updated in version 2.6.7. as well.

**System**
Windows 10 64bit
MSFS (latest version) 
MSFS Scenery Library with Navigraph (for navigation help and procedures)

**Reproduce**

1. Open flightplan
2. Select runway 22 for EDMB save 
3. Check XML
4. Select runway 22L save
5. Check XML

[IFR_Biberach_An_Der_Ri_EDMB_to_Biberach_An_Der_Ri_EDMB.zip](https://github.com/albar965/littlenavmap/files/5897945/IFR_Biberach_An_Der_Ri_EDMB_to_Biberach_An_Der_Ri_EDMB.zip)

**Comment by albar965** [comment]
Thanks for the report. This is even more an issue for exported plans.

**Comment by albar965** [comment]
Fixed for LNMPLN and FSX/P3D PLN. Other formats like MSFS PLN do not use starting positions anyway. MSFS can't load start positions the last time I tried.
