### ISSUE TITLE
Avia Maps - Garmin FPL (bin) support (patch)

### ISSUE THREAD

**Issue by slawekmikula** [albar965/littlenavmap#616]
There is Android Mapping software Avia Maps. https://goremy.co/#divAviaMaps. It can generate Garmin FPL flightplan in (fpl.bin format?). Anyway, it differs than well formed XML file. I've created a patch to support this file. Patches for (atools, littlenavmap) and example file exported from the Avia in the attachment.

[avia-flp-patch_example.zip](https://github.com/albar965/littlenavmap/files/6017825/avia-flp-patch_example.zip)

**Comment by albar965** [comment]
Thanks for the patch. Adding to next small update.

**Comment by albar965** [comment]
Patch added. Thank you for your contribution!
