### ISSUE TITLE
Missing data/maps/earth folder on macOS Catalina

### ISSUE THREAD

**Issue by Toneking77** [albar965/littlenavmap#618]
MacBook Pro running macOS Catalina 10.15, and LNM 2.6.8.  Sim is MSFS, latest version.

Description of issue: I can’t find the   **data/maps/earth**   folder to add new map styles.  Really strange.

I am able to use LNM with the stock map themes (OpenStreet, OpenTopo, Simple, Plain, etc.)  There are 8 of them in the drop down.  No error message when I start the program.  I've tried searching and can not locate the folder where they are stored.

I've attached log and ini files.

As a side note: I have a Windows 10 PC as well with LNM running well.  I have added extra map themes to that machine, added the better Elevation Data... no issues there.  

Thank you in advance!

Michael
[Archive.zip](https://github.com/albar965/littlenavmap/files/6026889/Archive.zip)

**Comment by albar965** [comment]
Hi Michael,

you have to right click on the `Little Navmap` icon and select `Show Package Contents`

The path is a bit different from the other OS:
`Little Navmap.app/Contents/MacOS/data/maps/earth`

Alex

**Comment by Toneking77** [comment]
OOOOOOOOOOOOh... tricky :)     Found it.  Thank you so much!  I thought I was losing it :)

I'm so glad that I hadn't missed something simple or something in plain sight.  I really didn't want to bug you, but I was _seriously_ stumped.

Thank you for the quick response, and a **HUGE** thank you for LNM.  I really amazes me how much useful functionality you've managed to pack in.  Truly amazing!

Thanks again.  All the best to you and yours,

Michael

**Comment by albar965** [comment]
Thank you for the kind words, Michael!
