### ISSUE TITLE
Updating- suggestion for folder placement

### ISSUE THREAD

**Issue by Toneking77** [albar965/littlenavmap#619]
Thank you for the ongoing development of LNM!    I just updated to 2.6.10 and have a suggestion regarding the update process.

Could the data/maps/earth folder be located with the other folder structure that LNM creates (Little Navmap Files).  Screenshot attached.

This would eliminate the need to manually move the "earth" folder aside temporarily and then move it back after the new version is in place.   I do that since I have additional map styles saved. 

Just a thought :)

Thank you again for the time and effort you devote to making this amazing app what it is.  I truly appreciate it a whole lot!

Michael

![LNM Folder struct](https://user-images.githubusercontent.com/68136616/110229650-12012500-7ed9-11eb-94a6-f9807524b3b6.jpg)

**Comment by albar965** [comment]
Yep. Like to do have this outsourced too but this needs changes in the Marble widget (not my code) and is a bit effort.
I'll try to do this for next major release 2.8

**Comment by Toneking77** [comment]
Thank you so much!!!

**Comment by albar965** [comment]
We need to keep the issue open as a reminder for me. :slightly_smiling_face:

**Comment by Gulliver54** [comment]
Ls,
In my opinion it isn't necessary to set aside the folder "earth" temporarily.  When executing an update version simply allow "overwrite folders..." Aditional map styles wil remain untouched.

**Comment by albar965** [comment]
Added to next minor update since this is a requirement for an installer. Program might be installed in folders where user has no access.

**Comment by albar965** [comment]
Fixed by  91d3f0797149facd090d343d6834ee39b953c17a and albar965/marble@21a5f69a098ef4a87c115f063335e08a1dfc297a.


![grafik](https://user-images.githubusercontent.com/15254956/233120537-855d7d43-a19b-4422-8f43-4e8247c5d363.png)
