### ISSUE TITLE
wrong runway ils heading

### ISSUE THREAD

**Issue by DemonRem** [albar965/littlenavmap#620]
hello @albar965 i have a issue with littlenavmap once i check the arrival information for example 
i gonna tried to land at EDDT runway 26L , your tool show heading is 256 while the fmc said 257 , now once i try to put the number 256 number for the 26L the aircraft didn't recognize the approach then once i put the number 257 the aircraft detected the runway its important for me to let you know that i didn't update the cycle info on xplane and littlenavmap 
i don't think its the problem if so i will buy subscription on navigraph i just want your opinion here.

**Comment by albar965** [comment]
The magnetic heading is calculated based on the true heading given in the various navdata sources (simulators) and the magnetic declination for the region. See [here](https://www.littlenavmap.org/manuals/littlenavmap/release/2.6/en/SCENERY.html#magnetic-declination) about the sources for the different simulators.

There can always be slight differences of one degree or so which can even change if the magnetic declination is updated in the simulator. Rounding errors also play a role. It also depends on the add-on aircraft and how they calculate it. Some allow slight differences.

A navdata update is unlikely to help. I'd rather try one degree more or less if the aircraft does not accept it.

**Comment by albar965** [comment]
Supposedly fixed. Feel free to reopen if the issue pertains.
