### ISSUE TITLE
OpenLayers Web UI Integration

### ISSUE THREAD

**Issue by KOKAProduktion** [albar965/littlenavmap#622]
Heyho @albar965!

First of all, you are a god providing this "little" software to everyone! Thank you! My sim experience is not even half the fun without it. I mean it!

I was seeking for a similar experience inside VR mode using Little Navmaps built-in web UI embedded inside in-game panels and the awesome [msfs2020-toolbar-little-nav-map](https://github.com/bymaximus/msfs2020-toolbar-little-nav-map) mod by @bymaximus. As cool as this already was, i was badly missing the ability to look around (by mouse drag pan) for crucial info available on the map.

So i couldn't resist having a peek on the code and to write an [OpenLayers](https://openlayers.org/) implementation consuming the Little Navmap web service. 

This is a quick prototype with visible issues but it reveals the potential of Little Navmap to serve like a WMTS server while utilizing OpenLayers' framework features:

[KOKAProduktion/littlenavmap-openlayers](https://github.com/KOKAProduktion/littlenavmap-openlayers)

In VR my implementation already does her job the way i want it, as during my "default" usage i do not encounter any issues critical or annoying to me. However it was a lot o fun doing this and I'd like to contribute more if i can, but choosing and going the next step would only make sense in coordination with you. And only if you would see any value in it.

I've been browsing through the issues section and found some possibly related items:

#322 More than one map screen 
- web-based views already work simultaneously but i guess they require implementing more logic to reflect the existing in-app behaviour. OpenLayers may serve as a shortcut here...

#112 suggestion add weather map Layers
- Any WMTS or other OpenLayers supported map data source could be integrated with assumingly less effort i guess.

#397 Extend web server with JSON data interface
- This is probably the hottest topic to discuss :)

#621 VR? 
- Not sure if i fully get the described issue, but "not having to take the goggles off" got me started on this in the first place.

So if you find the OpenLayers implementation in any way useful for the Little Navmap project and have interest to discuss this approach further, I'd be very happy to hear from you. But even if not, I'll still be very thankful for the software :)

One more time, thank you and the contributors for Little Navmap! It is pretty damn awesome! In so many ways!

Cheers!

**Comment by albar965** [comment]
Sorry, give me some time to look at it. Too busy now. :-(

I'm definitely happy for all improvements to the web interface.

**Comment by KOKAProduktion** [comment]
Please, no hurry. Same here :)

**Comment by albar965** [comment]
@KOKAProduktion Have a look at #654 . Maybe you can combine your efforts.
