### ISSUE TITLE
Wind data error

### ISSUE THREAD

**Issue by cristi-neagu** [albar965/littlenavmap#623]
Hello,

It looks like Little Navmap cannot download winds data from the NOAA server. 

![image](https://user-images.githubusercontent.com/30549178/112362906-dcc44780-8ccc-11eb-8010-e195af5eba53.png)

I have found past references to this in the past where the issue was caused by NOAA servers being down, so i was going to give it a few days. But now i hear from a different source that NOAA have changed something about their API. And checking the file structure at https://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_1p00.pl this seems plausible to me, especially since it seems the location is perfectly accessible. So i thought i should flag this as a potential issue, so that hopefully Navmap can be updated if that is the case.

Thank you.

**Comment by albar965** [comment]
NOAA has changed the Web-address and I cannot fix this except in a new release. 
I'll try to get something together for next week.

Keep NOAA winds off until this is fixed. If you use X-Plane switch to wind from simulator.

**Comment by craigusus** [comment]
I have Weather > Wind > Disabled selected (Although I have to set this every time I open the app)
I have it turned off in Options > Weather:
![image](https://user-images.githubusercontent.com/6324863/112697253-16d54b00-8e7f-11eb-8252-4d35a147dfc8.png)
I have also removed the files paths from Options > Weather  Files:
![image](https://user-images.githubusercontent.com/6324863/112696796-66674700-8e7e-11eb-886b-4e15960e2ef0.png)

But the app is still checking somehow, as I get the message that appears randomly saying it cannot download wind data.

What else do I need to turn off to stop the app from checking the noaa site?

**Comment by cristi-neagu** [comment]
I didn't bother turning it off. It does the check one at startup, throws the error, then stops checking.

**Comment by craigusus** [comment]
I still get the message appearing on startup, even though all reference to the NOAA site has been removed. But also get it appear randomly when using the app.

**Comment by albar965** [comment]
Leave the URLs alone (better reset them back to default [see here for defaults](https://www.littlenavmap.org/manuals/littlenavmap/release/2.6/en/OPTIONS.html#weather-files-weather-files)) and disable the download as described here in the support forum:
https://www.avsim.com/forums/topic/597802-noaa-wind-download-error/

You also tampered with the wrong URL. METAR download has nothing to do with this.

> Keep NOAA winds off until this is fixed (menu "Weather" -> "Wind Source" -> "Disabled", use "Manual" if needed).
If you use X-Plane switch to wind from simulator by checking "Weather" -> "Wind Source" -> "Flight Simulator" which is the better choice for X-Plane anyway. 

Please wait until I release a fix.

**Comment by craigusus** [comment]
> Keep NOAA winds off until this is fixed (menu "Weather" -> "Wind Source" -> "Disabled", use "Manual" if needed).

Is not remembered after a restart.

If the NOAA Wind Service Base URL is removed stating that 'weather reports are disabled', why/how does it still check?

**Comment by albar965** [comment]
> Is not remembered after a restart.
It is. Just tried it on several test systems. Check your settings in options on page `Startup and Updates`. Maybe reload of the map display settings is disabled and reverts back to default on startup.

> If the NOAA Wind Service Base URL is removed stating that 'weather reports are disabled', why/how does it still check?
Maybe a bug. I'll check. Anyway, put the URLs back to avoid issues.
