### ISSUE TITLE
Add my name to Chinese translator

### ISSUE THREAD

**Issue by tonghuix** [albar965/littlenavmap#624]
Hi, I started the Chinese translation for this project in [2019](https://github.com/tonghuix/littlenavmap/commits/master/littlenavmap_zh_CN.ts) and paused some month later. So could you please add my name to Chinese translator?

While thanks to @J0hnLiu 's continued and hard working #509 , he finished most of "the left-over" and did very good job! From now on, I would provereading all and make the translation meet FOSS Chinese Translation Standard.

**Comment by albar965** [comment]
I added both of your names to the acknowledgments in the manual where they were missing unfortunately.
Let me know if you need anything else.
