### ISSUE TITLE
[Feature suggestion] Show airspace's name and vertical boundary on map

### ISSUE THREAD

**Issue by tonghuix** [albar965/littlenavmap#625]
Something like ForeFlight, see picture below:

![2021-03-26 20-48-45 的屏幕截图](https://user-images.githubusercontent.com/423703/112705636-200dea00-8e76-11eb-9b16-7d559b816133.png)

It's would be really perfect if the vertical boundary is shown, make VFR flight planning much more easier.

**Comment by albar965** [comment]
Related or duplicate of #234 and #585. I'll keep this for now.

**Comment by albar965** [comment]
![grafik](https://github.com/albar965/littlenavmap/assets/15254956/6c745402-ae33-47d9-a165-961d8131eab1)
