### ISSUE TITLE
Daylight savings not recognized

### ISSUE THREAD

**Issue by cristi-neagu** [albar965/littlenavmap#627]
Looks like LNM doesn't recognize when daylight savings occur and it adds (or subtracts) and extra hour to the real logbook time. The simple fix is to use UTC for the real time as well, although this has the disadvantage that the user can no longer see their local time easily.

To be honest, this is more of an inconvenience than a bug. Just thought i'd point it out if an opportunity arises for a fix.

**Comment by albar965** [comment]
Have to see how to fix this. One solution is to save the offset with the actual time.

**Comment by albar965** [comment]
Fixed with 2.6.12. Offset for timezone is now saved in database and shown in information display.
