### ISSUE TITLE
Suggestion for aircraft saved with the flight plan.

### ISSUE THREAD

**Issue by gaabne** [albar965/littlenavmap#629]
Hi Alex,

Now that there is a LNM flight plan format, would be nice to "remember" the aircraft selected for the flight plan.

Gérard

**Comment by albar965** [comment]
Aircraft profile name is already saved in LNMPLN but not shown in LNM. I could save the aircraft ICAO type from the profile or connection and then show this in the tab `Remarks` (not editable).

**Comment by gaabne** [comment]
Alex,
My idea was in fact to have the corresponding profile automatically loaded with the flight plan,
to get the right fuel report, elevation profile... and collected performance.
I forget to do it too much times ;)
Gérard

**Comment by albar965** [comment]
I understand I usually take the perf when looking at the logbook entries where the reference (and much more) is stored too.
Have to see.

**Comment by albar965** [comment]
Done with b47046169394a0450ef39f1ed661b0dd447608f8 and e7696b09fd791779e746d959bec19791ba7d11cf .
The aircraft from the performance file is now saved in the flight plan and shown on the remarks tab.

**Comment by gaabne** [comment]
Hi Alex,
Will it be possible to have the aircraft performance file directly opened (replacing the latest active one before the fight plan load...) ?

I know, always asking for more more...

Gérard

**Comment by albar965** [comment]
Hi Gérard,
sorry, not soon. But I keep this in mind for a future version if I have an idea for an easy solution.
Alex
