### ISSUE TITLE
"Load Error" - Flight Plan import in the Aerosoft CRJ 700

### ISSUE THREAD

**Issue by AllCanor** [albar965/littlenavmap#632]
Hi,

first of all: thanks for the great software.

However I'm having issues importing the exported flight plan (flp-file) into the CRJ700 in MSFS. It simply gives a "load error". I also tried exporting the same route via simbrief and the import was successful.

Any idea what could be the reason for that?

**Comment by albar965** [comment]
I'll try to fix this but it is not easy since I do not own the CRJ and the error messages given by the aircraft are unfortunately quite meaningless.

**Comment by AllCanor** [comment]
I attached the two default plans of the plane. I'm also looking into the differences myself. Will report back if I find something useful.

[flightplans.zip](https://github.com/albar965/littlenavmap/files/6264394/flightplans.zip)

Also attached the manual for the flight plan structure: [CRJ Flightplan Format.pdf](https://github.com/albar965/littlenavmap/files/6264406/CRJ.Flightplan.Format.pdf)

Danke!

**Comment by albar965** [comment]
Please see thread here:
https://www.avsim.com/forums/topic/597425-flightplan-export-to-aerosoft-crj-flp-format/
