### ISSUE TITLE
[feature request] Using littlenavmap on linux with MSFS 2020 running on a different PC

### ISSUE THREAD

**Issue by scresante** [albar965/littlenavmap#634]
I am running archlinux and I have a separate machine for MSFS2020, Win10 build 21354. Littlenavmap compiles and runs with absolutely no problem using the AUR for arch, and without needing any patching or hacking, which is really nice. Thank you for this excellent software, and especially for releasing it open source!

Both machines are on the same network. I'd like to use littlenavmap on the linux machine, synced to MSFS on the Windows PC. 

Unfortunately this is currently not possible. The linux version only has X-Plane 11 as an option. ![pic-selected-210416-0137-00](https://user-images.githubusercontent.com/2119829/114976618-46f78480-9e54-11eb-957b-1bc525ba0e0b.png)

I tend to prefer using my laptop for navigation and flight planning, with the PC running only MSFS, so this would be a pretty great feature. 

Sharing the requisite files that littlenavmap reads to build its database over the network is easy, so the flight simulator base path is accessible to linux. The problem is that only X-Plane 11 is an option for the database initialization in linux. 

Correction to the above: I've fixed the problem so this will be open and closed, leaving it as an issue in case anyone else needs the advice.

**Comment by scresante** [comment]
The correct solution to this problem is to use the little navconnect utility, which allows for remote instances, and works perfectly. Thanks!

**Comment by albar965** [comment]
See here for details: https://www.littlenavmap.org/manuals/littlenavmap/release/2.6/en/NETWORK.html
