### ISSUE TITLE
How to dock below the map?

### ISSUE THREAD

**Issue by Neutrino-Sunset** [albar965/littlenavmap#637]
Windows 10 64 bit
MSFS 2020

How do I dock anything below the map so that it does not encroach on space used by items docked at the side?

The same as is done here
https://youtu.be/IXfoFwGRduQ?t=1027

**Comment by albar965** [comment]
You have to enable `Allow to undock map window` in options on page `Map`.

See also https://www.littlenavmap.org/manuals/littlenavmap/release/2.6/en/DOCKWINDOWS.html , https://www.littlenavmap.org/manuals/littlenavmap/release/2.6/en/LAYOUT.html and https://www.littlenavmap.org/manuals/littlenavmap/release/2.6/en/OPTIONS.html#map .

**Comment by Neutrino-Sunset** [comment]
If I enable `Allow to undock the map` and restart, the map is not visible at all and there is no obvious way to bring it back.

**Comment by albar965** [comment]
It's mentioned in the manual, the text below the options and the tooltip of the checkbox:
https://www.littlenavmap.org/manuals/littlenavmap/release/2.6/en/OPTIONS.html#allow-to-undock-the-map-window

> You might also need to reset the window layout in case the map window is missing after a restart.
> Use menu Window -> Reset Window Layout in the main menu to clean up the layout after the restart if needed.

![image](https://user-images.githubusercontent.com/15254956/116070645-2d90dc80-a68d-11eb-8d1b-27b851b38ed5.png)
