### ISSUE TITLE
METAR: Report is not valid.

### ISSUE THREAD

**Issue by ESMP** [albar965/littlenavmap#638]
Lately I've been receiving a "Report not valid" on certain airports when using ActiveSky. For example:

> Time: | UTC -- | --
> Flight Rules: | - Map
> Wind: | Variable, Speed not valid
> No visibility report |  
> No clouds |  
> 
> Report is not valid. Raw and clean METAR were:
> MMZH 202043Z E22006KT 7SM SCT250 29/22 A2991 RMK SLP116 57021 913 8/002 HZY
> 

I noticed there's a closed report on apparently this same issue regarding variable wind speeds, that is, when METAR does not contain wind speeds.

**Comment by albar965** [comment]
The issue is the wind prefixed with `E`. Clearly not valid. I'd report this to Hifi.
