### ISSUE TITLE
Map is always reloading

### ISSUE THREAD

**Issue by wodoor** [albar965/littlenavmap#644]
Hi all, 

I have a small problem, always when I have a flight in progress, the map go for "reload" and that take up to 2 minutes before I can follow the flight again. That is a bit terrible when I short for landing.
Is that a reason of the map display or...?

**Comment by albar965** [comment]
Can you post a screenshot, a video or the logfile or send me one per [email](https://albar965.github.io/contact.html) ?

**Comment by wodoor** [comment]
I have tried several times to sent a mail with vido,, you got it?

**Comment by albar965** [comment]
@wodoor Sorry, did not get anything. Not even in the spam folder. 
You can add the file to https://wetransfer.com, https://www.dropbox.com or whatever cloud server is around and add the link here.
