### ISSUE TITLE
Feature: Add "Keep Centered On Aircraft" option to webserver

### ISSUE THREAD

**Issue by PaulWalkerUK** [albar965/littlenavmap#645]
It would be a nice addition to the webserver if there was a way to keep the user's aircraft centered evertime it auto-refreshes.
I've noticed the "User Aircraft" button that centres it now also resets the zoom - personally, I would prefer if this didn't happen, but maybe that's just me. The "Keep Centered" option would need to maintain the zoom and not reset it.

**Comment by albar965** [comment]
Makes perfect sense. :slightly_smiling_face:
