### ISSUE TITLE
Cannot load scenery library if a particular addon plane is installed.

### ISSUE THREAD

**Issue by HobAnagerik** [albar965/littlenavmap#646]
Windows 10 20H1
Microsoft Flight Simulator
Navigraph AIRAC cycle 2104
LNM 2.6.11

If the SimworksStudios CH701 is installed, attempting to load the scenery library will generate the following errors:

![image](https://user-images.githubusercontent.com/32840954/118894659-94a45880-b8fc-11eb-8258-5c8d9badb549.png)

![image](https://user-images.githubusercontent.com/32840954/118894675-9a01a300-b8fc-11eb-85b4-b48600b3bdf3.png)

I attempted to add some exceptions in, first of all for the top level folders, then the "checklist" folder itself, and finally just the "library.xml" file:

![image](https://user-images.githubusercontent.com/32840954/118894732-b8679e80-b8fc-11eb-925b-c90806075bdc.png)

![image](https://user-images.githubusercontent.com/32840954/118894734-bb628f00-b8fc-11eb-96a4-f2dc7161bf04.png)

Removing the folder "sws-aircraft-zenith701-wheels" from the "Community" folder allows the load to complete.  I also have a "DISABLED" folder, where I put mods that I don't want MSFS to load, and hiding it one level down also works.

**Comment by albar965** [comment]
Known issue. Will be fixed with the next small release. Actually, this is already solved in the current development version. Closing therefore.
Move the aircraft temporarily to another folder when loading the LNM scenery library.
