### ISSUE TITLE
Read new MSFS SID and STAR records

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#649]
Related to #555

SID and STAR are mostly recognized but not all due to the new records below which were introduced with 1.16.2.0:
The records SID_STAR_MSFS_DEPARTURE (0x004a) and SID_STAR_MSFS_ARRIVAL (0x00f0) are still unknown and cannot be read.

Disabled skeleton code is here: 
https://github.com/albar965/atools/blob/release/3.6/src/fs/bgl/ap/sidstar.cpp#L159-L185

**Comment by icykoneko** [comment]
Uggggh, and after I went to all that trouble lol

**Comment by albar965** [comment]
I feel with you. It took me a lot of time to find the changes in the current new records. :slightly_frowning_face: 
Therefore, I'd be glad for any help. :+1: 

Alex

**Comment by icykoneko** [comment]
Sure thing.  Looks like you've already made a few changes to the code since my original PR, but I did happen to have copies of a couple BGLs from the previous version, and compared them with the latest ones.  As far as I can tell, it was only the `FSProcedureChildType` enumeration that got additions:

Type | Old | New
---|---|---
Transition | 0x002C | 0x0049
RunwayTransitions | 0x0046 | 0x0046 *(unchanged)*
EnrouteTransitions | 0x0047 | 0x004A
ApproachLegs | 0x00E1 | 0x00EC
MissedApproachLegs | 0x00E2 | 0x00ED
TransitionLegs | 0x00E3 | 0x00EE
RunwayTransitionLegs | 0x00E4 | 0x00EF
CommonRouteLegs | 0x00E5 | 0x00F0
EnrouteTransitionLegs | 0x00E6 | 0x00F1

The only changes I could really find was 8 bytes added to the end of the `Leg` structure, an array found in parent types `*Legs` above.  And the `Transition` and `EnrouteTransitions` structs each contain 8 bytes before starting the *LegContainer* of types `*Legs` above.  For those two, the 8 bytes seem to contain a string representing the IF, but it's kinda redundant.

**Comment by albar965** [comment]
I think I have it. Your table helped a lot. 
Forget what I wrote above with `bglcomp.xsd`.

**Comment by icykoneko** [comment]
Did you already commit a fix?
I noticed in `sidstar.cpp` where it appends the `ApproachLeg`s, the record type needs to be `legRec.getId()`.  If you don't use that, you'll miss the RUNWAY_TRANSITIONS_MSFS case.

**Comment by albar965** [comment]
Just pushed.

**Comment by albar965** [comment]
I see. Like 
``` C++
          Record legRec(options, bs);
          int numLegs = bs->readUShort();
          for(int i = 0; i < numLegs; i++)
          {
            qint64 pos = bs->tellg();
            ApproachLeg leg(bs, legRec.getId<rec::ApprRecordType>());
```
and

``` C++
          Record legRec(options, bs);
          int numLegs = bs->readUShort();
          for(int i = 0; i < numLegs; i++)
            legs.append(ApproachLeg(bs, legRec.getId<rec::ApprRecordType>()));
          insertEnrouteTransition(legs);
```

**Comment by icykoneko** [comment]
yea, okay, let me sync this with my local branch, cause I kinda was messing with it myself, and just finished up.  About to test the code out now.
I think I renamed some parts and formatted a little different

**Comment by albar965** [comment]
`legRec.getId<rec::ApprRecordType>()` gives strange record types like 0xEF

**Comment by icykoneko** [comment]
You don't happen to know the BGL that contained the entry would you?

**Comment by albar965** [comment]
`.../Official/OneStore/fs-base-nav/scenery/0000/NAX07070.bgl`

**Comment by icykoneko** [comment]
No, that's what you want.  The extra 8 bytes in the leg records is determined by the *container* for the legs, in this case, `0xEF` is the new `RunwayTransitionLegs` container type, which is inside the `RunwayTransitions` of type `0x46`.  Remember that's the only one that didn't get a new record type.

**Comment by albar965** [comment]
Okay. I see. This could make the hack in the RUNWAY_TRANSITIONS_MSFS redundant, right? Can you do the change? Maybe easier.

**Comment by icykoneko** [comment]
Yea, I see it too.  The current code assumed there'd be only one of those records, but it can actually have multiple.  Maybe the old type only supported one?

**Comment by icykoneko** [comment]
![PAKP SID 02](https://user-images.githubusercontent.com/28579746/119731057-77afde00-be44-11eb-803c-ca3b8191bb99.png)

**Comment by albar965** [comment]
Perfect. Matches with X-Plane and Navigraph data.

BTW: How do you test? Hopefully not by running the whole LNM to comile? I use the navdatareader with a filter in `navdatareader.cfg` on selected files. Runs through in a few seconds.

**Comment by icykoneko** [comment]
Uhhhhhhhhh...... I... I use the tool... but... I rebuild it all eehehe.  I should just do it for a select few airports.

**Comment by albar965** [comment]
Copy the navdatareader.cfg from the resources folder to the ABarthel in Roaming. Then filter by files:
```
IncludeFilenames=NAX07070.bgl,APX07070.bgl,APX28310.bgl,NAX28310.bgl,APX28310.bgl,NAX28310.bgl,APX07390.bgl,NAX07390.bgl,APX06240.bgl,NAX06240.bgl,APX26160.bgl,NAX26160.bgl ,APX03070.bgl,NAX03070.bgl
```
and/or airports:
```
IncludeAirportIcaoFilter=NTAR,PAKP,SKSV,PHKO,CYTZ,PAPO
```
Keep in mind that LNM uses this file too. Rename or delete after testing.

**Comment by icykoneko** [comment]
I had to step away for a little bit, but just about ready to submit pull
request.

**Comment by icykoneko** [comment]
![CYTZ RNAV-Y 08 LENOG](https://user-images.githubusercontent.com/28579746/119736342-8cdc3b00-be4b-11eb-9dd7-ef1eed1a31a8.png)

**Comment by icykoneko** [comment]
I think this ought to do it.
https://github.com/albar965/atools/pull/12

**Comment by albar965** [comment]
Hmhm. RF legs are fine now. I also added the speed limits. Unfortunately there is no information if this is max, exact or minimum speed what they give in the BGL.

**Comment by icykoneko** [comment]
Yea, hey, you submitted the ticket to them about the RF legs right; guess they listened.

**Comment by albar965** [comment]
Yup. Good thing they actually listening to users.

Just compiled without any warnings (at least no unexpected ones). Perfect!
Thanks a lot! I have a few more tasks and bugs on my list. Maybe a release (maybe a beta first) in a week or two. Have to see.

Going to call it a day now. :sleeping: 

Alex

**Comment by albar965** [comment]
Working perfect now. 

I get missing waypoints with the Navigraph update but this is not relevant anyway since users can update the LNM database with Navigraph directly.
