### ISSUE TITLE
Multiexport Options Request/Suggestion

### ISSUE THREAD

**Issue by jfwharton3975** [albar965/littlenavmap#650]
One of the aircraft I use is the FSLabs A320 which isn't one of your export options.  It imports flight plans saved in C:\Users\Public\Documents\FSLabs Data\Routes folder with the .pln extension.  I have modified one of the default multiexport options to point to that folder but it would REALLY be nice if  I could modify the Usage field as well as the Export Path, or better yet allow me to create a new export option where I enter the appropriate information for each field.  Thanks for a great program.

**Comment by albar965** [comment]
Would it help if I create a new FSLabs export option which saves FSX/P3D PLN files? One which allows to set a separate path besides the P3D PLN export?

This would be the easiest solution. Allowing to create new export options is more for a future version.

**Comment by jfwharton3975** [comment]
Thank you that would be great.

**Comment by albar965** [comment]
I'll try it for the next update but I cannot promise anything. Maybe I have to postpone this change for another version. Have to see.
