### ISSUE TITLE
.pln files are not the same

### ISSUE THREAD

**Issue by jfwharton3975** [albar965/littlenavmap#657]
I have been trying to create flight plans for my FSLabs A320.  That aircraft loads flight plans from Documents\Prepar3D v5 Files (or v4 files).  I tried changing the path for the blackbox aircraft (which says it uses the .pln file) to export to that folder because when it exports it does so in the format I want to use, for example KDENKJAC.pln.  When I do this the FSLabs A320 does not recognize the file.  If I use the multiexport FSX P3D annotated option or from the file menu select the option to export flight plan as P3D or FSX pln it will read the flight plan.  The issue there is that it exports using the standard long format (IFR Denver Intl (KDEN) to Jackson Hole (KJAC).pln) which the A320 can't read because it longer than 10 characters.  If I change the default path to short it then exports to this format KDEN Denver Intl.pln.  Which doesn't do me any good as I need the destination in the export name.  Is there any way I can get an export in the KDENKJAC.pln format that the FSLabs A320 will read in without having to edit the file name when exporting a flight plan?

I should have added that I expected when using one of the multiport export options for pln files that the A320 would read the file but it seems that pln files are not all the same.  Is that the case?

**Comment by jfwharton3975** [comment]
Nevermind I found how to modify the short format to DEPARTIDENT DESTIDENT.  Could not delete this issue so please close it and sorry I didn't dig deeper into LittleNavMap.

**Comment by albar965** [comment]
No problem. Closing now.
