### ISSUE TITLE
Aircraft Trail should not draw dotted line for large jumps across the planet

### ISSUE THREAD

**Issue by smitty97** [albar965/littlenavmap#678]
I like to keep the Aircraft Trail persistent for many trips in the simulator (MSFS).  As I fly many different spots in the world, there are huge great circle trails crisscrossing all the oceans from teleporting to the next departure.

Can an option be added to the aircraft trail section "Don't draw dotted line trail between points greater than ___ (mi/km/lat-long degrees) apart" ?

**Comment by albar965** [comment]
Test this with 2.6.13. It should be fixed there. From the changelog:

> * Corrected loading and saving of GPX tracks. Now also saving timestamps and considering
  disconnected trail segments. A flight where the aircraft was moved or warped during flight results
  in a straight line connecting the two segments. Changing aircraft, restarting the simulator or
  *Little Navmap* results in disconnected trail segments.

**Comment by kidden** [comment]
Unsubsribe



Enviado desde mi iPhone

**Comment by kidden** [comment]
Unsubscribe

**Comment by albar965** [comment]
Please close if this is fixed.
