### ISSUE TITLE
Ability to delete or zero out elevation data from Aircraft Trail

### ISSUE THREAD

**Issue by smitty97** [albar965/littlenavmap#679]
As I fly many trips in the simulator, the Flight Plan Elevation Profile view becomes a mess of dotted lines. 

I would like to keep the positional data of the aircraft trail, but have the ability to zero-out the previous elevation data so this view becomes clearer.

There could be an option in the Map menu "Delete Aircraft Trail elevation data only"

**Comment by smitty97** [comment]
Thanks, what i mean specifically is i want to remove dotted lines from here:


But keep them here:


So if all the elevation points were set to 0ft it would accomplish cleaning it up.

Will check out 2.6.13 for crisscross.

-Tom

**Comment by albar965** [comment]
There's also a separate trail removal menu item in the elevation profile context menu.

> Delete Aircraft Trail
>
> The aircraft trail is saved and will be reloaded on program startup.
> This menu item removes the user aircraft trail from the elevation profile only. It does not remove the trail from the map. Use this if the trail appears in the wrong place or shape after creating of modifying a flight plan.
>
> The trail in the elevation profile is of no relevance for the GPX file export.

**Comment by smitty97** [comment]
Wonderful, thanks!

**Comment by albar965** [comment]
Feel free to close if issue is solved.
