### ISSUE TITLE
Import MSFS POI database to userpoints

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#695]
Import BGL into LNM userpoint database with MSFS tag.

https://www.fsdeveloper.com/wiki/index.php/FS20_BGL_File_Format#LandmarkLocation

**Comment by albar965** [comment]
Already available as a third party download.

**Comment by daheise** [comment]
Can you comment what third party you have in mind? The sources I used seem to have stopped updating ([Aquila Simulations](https://www.google.com/maps/d/u/0/viewer?mid=1KUg5jwyT_9k2A9n5IZ99UChlhfVUfO5S&ll=27.396291317250547%2C-21.446883884521867&z=3) and [Little Navmap - MSFS POI database](https://flightsim.to/file/17193/little-navmap-msfs-poi-database)).

**Comment by albar965** [comment]
I'm sorry but I don't have the time to additionally maintain these databases. Also, importing the MSFS POIs is not too simple since the BGL format is not documented.
