### ISSUE TITLE
Custom departure

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#696]
Add option `Create Departure` similar to `Create Approach`.
Allows to select departure runway instead of using a SID

**Comment by Gulliver54** [comment]
Hi Alex,
Is it correct that you combined Create Approach with Create Departure in one item for context menus? If possible send a screenshot of the context menu. 

Great that the create approach now has the offset course possibility too.

**Comment by albar965** [comment]
> Is it correct that you combined Create Approach with Create Departure in one item for context menus? If possible send a screenshot of the context menu.

Not one. I completely reorganized the context menus and move all flight plan related options further up.

Keep in mind that these (VFR) arrivals and departures are internally treated like procedures. You cannot combine these with procedures.

Departure dialog:
![image](https://user-images.githubusercontent.com/15254956/140541820-bd9131aa-c3b8-417e-b7b1-2e08035dc3f1.png)

Arrival with offset:
![image](https://user-images.githubusercontent.com/15254956/140541995-6ccef566-3fa1-47f5-97a0-e45193673a42.png)

The result on the map and in the profile also showing the new flight plan semi-transparency options requested by users:
![image](https://user-images.githubusercontent.com/15254956/140542661-b45bcff9-74e3-460b-968c-da1599a938f0.png)

The menu:
![image](https://user-images.githubusercontent.com/15254956/140543162-f49c8ca3-1c30-417f-b4e6-ae66ba8ecea7.png)

**Comment by Gulliver54** [comment]
Thanks Alex,

These screenshots clarify a lot.
Like the way you organized the context menu.
It's clear to me that a create approach.... can't be combined with
procedures.
Nice to see the descent angle visible in the elevation profile.

Gradus




Op vr 5 nov. 2021 17:16 schreef Alexander Barthel ***@***.***

**Comment by albar965** [comment]
Glad you like it. I'm about to make the context menu smaller now by collapsing all the "Hide Holding" etc. into one. Wanted to do this for a long time already.
