### ISSUE TITLE
More label options at user and AI aircraft

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#708]
- [x] Coordinates for user and AI/multiplayer
- [ ] Distance to user aircraft for AI/multiplayer

**Comment by Gulliver54** [comment]
Ticket #143 seems to be same.

**Comment by albar965** [comment]
> Ticket #143 seems to be same.

Right. Thanks!

**Comment by Gulliver54** [comment]
Hi Alex,

Sometimes I tend to commend in active tickets but also in tickets that are
closed. Do you receive an response-flag in both occasions?




Op ma 8 nov. 2021 om 13:10 schreef Alexander Barthel <
***@***.***>:

**Comment by albar965** [comment]
I get notifications on comments for closed and open issues. Only if somebody reacts with a smiley or other I do not get anything.
