### ISSUE TITLE
Simple stripped down Linux VM for running LNM

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#709]
As VirtualBox, LibVirt or Docker images for Intel or Raspi.

Related to #522

**Comment by OS17279** [comment]
I could possibly help with this, what’s your vision ?

**Comment by albar965** [comment]
You could use an Ubuntu 20.04 since I can provide a binary for it. Or maybe another small distro which is simple and lean like Xubuntu or Lubuntu.

No need to compile LNM yourself. Use a minimal installation or strip all unneeded stuff off (LibreOffice, media player, whatever). Keep a browser and a PDF reader for the manual. Allow user to connect to shares. Compress the VM disk to save space.

In VirtualBox you can export the Appliance to a compressed file once done.
No idea about KVM/Qemu/libvirt. You probably need the VM disk and a XML configuration file for the user to import.

Be sure to leave no private passwords in the machine. I'd create an account `lnm` with password `lnm` in it.

The idea is to help users who do not have a compatible OS or other problems. They can use the VM via Navconnect to attach LNM to the simulator.

For Linux users #522 would be even better.

Let me know what you think about this. And thanks for trying to help!

Alex

**Comment by OS17279** [comment]
Thanks for that! Will try find some time for this, im keen to investigate further, will be in touch. Thanks for your hard work, will be sure to donate soon.

**Comment by OS17279** [comment]
Spent the weekend playing around and found the distro DietPi [https://dietpi.com/](url) to be the most reliable and lightweight. Your 16.04/18.04 releases work well, but not 20.04 (I'm not sure technically what differences there are but for now it runs fast on 3+ and 4+ pi. There are a few configuration gremlins I need to work through specific to screen resolution but I belive this can be worked around with some very clear documentation that could be prepared. The distro has chromium/SMB for fileshare access, a lightweight HTTP server if needed and networkablity via navconnect

**Comment by albar965** [comment]
Substituted by flatpak.
