### ISSUE TITLE
Fix OpenSSL errors that break the OpenTopoMap

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#72]
Appears only on Windows.
The OpenTopoMap added a permanent redirect to HTTPS which is broken under Windows only. 
Therefore tiles are not loaded.

Fix is to compile Qt with OpenSSL support.

**Comment by albar965** [comment]
Done but XP compatibility is now broken

**Comment by PaulFWatts** [comment]
Confirmed working on Windows 10
