### ISSUE TITLE
Show Information on SIDs and STARs

### ISSUE THREAD

**Issue by coopermor** [albar965/littlenavmap#727]
Currently you cannot "Show Information" on navaids in SIDs and STARs. This would be a useful feature to be able to see frequencies and other information. Currently you have to either search for navaids or "Show on Map" then click the navaid to update the information panel. 
![2021-06-30 21_46_36-Little Navmap 2 6 13 - XP11 2105 _ N 2106 - _ - Boeing 737-800X Zibo lnmperf](https://user-images.githubusercontent.com/8049699/124163753-8605a100-da65-11eb-8d0c-8abc3353e5ab.png)

**Comment by albar965** [comment]
I see. This almost qualifies as a bug for me. :slightly_smiling_face:  
I'll try to fix this for the next minor update.
