### ISSUE TITLE
[Idea]Remote Database

### ISSUE THREAD

**Issue by LievreAI** [albar965/littlenavmap#733]
hey @albar965 

i have idea for ya if its possbile
i have my game installed already in my second pc , can you do a option to remotly connect to the simultor
with ip that littlenavmap will read the game from a remote pc that located in the same network?
to allow the program to load the database from the pc that run the game on the same network?

**Comment by LievreAI** [comment]
nevermind i find the answer on a difrrent issue post

**Comment by albar965** [comment]
A remote database is not doable but I intend to automatically download the database (#31).
However, this is low priority. Sorry.
