### ISSUE TITLE
Procedures missing for airports

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#735]
MSFS 1.18.9 introduced (again) new record types for procedures and procedure legs.

**Comment by albar965** [comment]
@icykoneko If you have any information on this. Otherwise I'll dig into the new records.

**Comment by icykoneko** [comment]
I haven’t run it since update. I may get a chance to look at it tomorrow though. Why must they mess everything up so much.

**Comment by albar965** [comment]
There are new records for procedure legs:
- Approach: 0xf4 (leg) and 0xf5 (most likely missed leg)
- Transition: 0xf6 (leg)
- SidStar: 0xf8 (unknown leg)

> Why must they mess everything up so much.

You can say that again! We've got better things to do. And I'd rather fix bugs and add new features to LNM. :slightly_frowning_face:

**Comment by icykoneko** [comment]
Yea I hear ya. I plan on taking a look at it tonight. Hopefully it’s not
much different from the last change. Probably just a new field added, that
sorta thing.

**Comment by albar965** [comment]
I'm looking at classes Approach and Transition now.

**Comment by albar965** [comment]
The new approach and transition records have 4 bytes extra at the end of the structure. No idea about the content.

**Comment by albar965** [comment]
I also looked at the SidStar. Same change but the new record is for common route and there are new leg records.

**Comment by albar965** [comment]
Looks ok so far. Can deal with 1.18 and also with the current 1.17. Change is in `master`.

Development build right here:
https://www.magentacloud.de/lnk/hfrAAvmF
