### ISSUE TITLE
Fetch weather data from simconnect

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#74]
This can make weather program integration redundant since you can get to the weather as it is at an airport.
If this is working Use _Active Sky route weather_ #10 can be dropped.

**Comment by albar965** [comment]
Done. Working across network and with direct connections. METARs are also displayed in decoded text in an extra tab in information dock window.

**Comment by PaulFWatts** [comment]
Test on Mac & Windows. Have had no parsing errors.
