### ISSUE TITLE
Incomplete ground vertical profile

### ISSUE THREAD

**Issue by malaise** [albar965/littlenavmap#746]
![Profile](https://user-images.githubusercontent.com/588474/130350339-852d57bb-263e-43e8-ae2c-c8948b58baa1.jpg)
 
Along this route from CYEG to PANC the ground vertical profile stops at some point. Still the minimum altitudes are correctly displayed on the main map window all along the route.
Restarting LNM does not solve the issue.

**Comment by albar965** [comment]
This is a known problem. Install the offline GLOBE elevation data as hinted in the warning dialog on first start.
https://www.littlenavmap.org/manuals/littlenavmap/release/2.6/en/OPTIONS.html#cache-elevation
You can close this issue if this fixes it.

**Comment by malaise** [comment]
Indeed. Didn't find it in the issues. Now it is.
Solved.
Thank you
![Profile](https://user-images.githubusercontent.com/588474/130354534-03bb6aea-80f7-46be-90bd-05254dd635ec.jpg)

**Comment by albar965** [comment]
Thanks for the feedback. I think I can close this now.
