### ISSUE TITLE
Add more flight plan export formats like PMDG (was Sugestion Flight plan)

### ISSUE THREAD

**Issue by bilkaPek** [albar965/littlenavmap#75]
hello Alexander
It would be nice to be able to add and read the flight plan for Pmdg  and Airbus

"Sorry for my english i translate with google"
SAM.

**Comment by albar965** [comment]
Sam, I'd like to have this feature too, but I could not find any documentation on these file types used by PMDG. Therefore I have to experiment.
About the Airbus: Aerosoft or Flight Sim Labs? I have neither of them.

**Comment by bilkaPek** [comment]
Thank you Alexander
Yes it is very difficult to find documentation

**Comment by albar965** [comment]
Added PMDG RTE and Aerosoft Airbus FLP formats.

**Comment by bilkaPek** [comment]
Helo Alexander
I can not wait to test this new version :)
thank you for your work

**Comment by albar965** [comment]
Hi Sam,
send me an e-mail and I can send you the link to a development version.
Alex
