### ISSUE TITLE
Mobile Support

### ISSUE THREAD

**Issue by illegitimate-egg** [albar965/littlenavmap#769]
If it's possible, I'd like to see a mobile version of the software that can connect to PC through Little Navconnect. This would be good because i would be able to continue flying while looking at the map.

**Comment by albar965** [comment]
This is a huge task and more likely a full new development. At best there will be a very limited LNM on Android or iOS.

Maybe this can use the web API to show a simplified LNM.

**Comment by KOKAProduktion** [comment]
@boomcreeper11 does the application really have to run **natively** on the device?

Maybe your use case is already covered by opening the LNM's Web UI in your mobile devices browser while on the same local network? (Given proper network conditions) 

You can find your local LNM's Web UI URL's at the `Settings` -> `Webserver` panel

If the goal is not to have LNM running on the sim host, its sim data needs to be exposed to the local network and processed by a native mobile version of LNM. This sounds huge as @albar965 said...

I hope this helps? Cheers!

**Comment by albar965** [comment]
Webapi can be used instead.
