### ISSUE TITLE
LittleNavMap Hanging When Updating the Scenery Library

### ISSUE THREAD

**Issue by Gelowims** [albar965/littlenavmap#774]
I have been using LitleNavMap since v13 and have never had a problem with it. I am now upgraded to v16 after v14, v15 without issue. The issue i am having is that when i try to update the scenery library . The scan goes well until it reaches about 78% complete. I have excluded the offending file to know avail. when i restart the program the exclusion is no longer the and again hangs on the same offending file. I am attaching the log file and would appreciate any help in getting this issue resolved. Great [program![

**Comment by albar965** [comment]
You have to save the settings after adding an exclusion **if** the program crashes. `Tools` -> `Save options and application state`.
This way LNM keeps the exclusion.

You can help me to find the issue:

1. Run LNM and load the scenery library without exclusion until it breaks.
2. Do not restart LNM but save the log file here `C:\Users\YOURUSERNAME\AppData\Local\Temp\abarthel-little_navmap.log`
3. Attach the last few hundered lines of the log file here.

I'll probably ask for the offending file.

**Comment by albar965** [comment]
Seems to be fixed: https://www.avsim.com/forums/topic/606572-scenery-library-hangs-at-78/
