### ISSUE TITLE
My Documents LNM folder name is duplicated across languages

### ISSUE THREAD

**Issue by u-an-i** [albar965/littlenavmap#782]
Hi,

I noticed i now have a `Little Navmap Dateien` and `Little Navmap Files` folder in my `My Documents` folder.

I think this is due to the language LNM is set to.

I guess settings storage can be reduced by unifying these folders.

**Comment by albar965** [comment]
This can happen if you change the UI language. The dialog pops up again asking to create folders. No idea how to solve this.

But all paths (e.g. file dialogs, GLOBE path, etc.) remain as set before independent of language if you cancel out of this question dialog.

**Comment by u-an-i** [comment]
can you define the folder name yourself (without Windows adding a suffix like `Files`or `Dateien` perhaps based on the OS language)? Is simply `Little Navmap` a possible folder name?

**Comment by albar965** [comment]
> Is simply `Little Navmap` a possible folder name?

Makes sense but the sub-folders are still localized.
I can add an option to select your own folder. 

But I won't move files around after a user creates his own set again in a different language. This is still up to the user IMO.

**Comment by u-an-i** [comment]
I didn't check the sub folders. Yes, they are localised, which is a nice "touch" for users.

> I can add an option to select your own folder.

But so switching languages might result in having the subfolders in several languages names inside `Little Navmap`.
Perhaps inform the user about this.

I see trying to move and merge folders and files around is troublesome.

On the other hand, given aviations primary language is english, might non-localised sub folders names with perhaps "official" aviation language terms be fine?

**Comment by albar965** [comment]
> But so switching languages might result in having the subfolders in several languages names inside `Little Navmap`.
> Perhaps inform the user about this.

The folders are only created on user action if he confirms the dialog. Just switching languages does not create the folders and does not change any path references in LNM. No need to inform user.

I can also suppress the dialog **after** first installation and provide a menu item to create the folders on demand. This would silence the dialog on language changes.

**Comment by u-an-i** [comment]
> This would silence the dialog on language changes.

This will likely be the "best" solution :)

**Comment by albar965** [comment]
> This will likely be the "best" solution :)

Will do.
