### ISSUE TITLE
Elevation Profile shows Aircraft Landing away From Airport KCHA

### ISSUE THREAD

**Issue by jgyo** [albar965/littlenavmap#783]
For KCHA elevation profile shows the plane landing in the wrong place.

OS: Windows 10 64 bit
Simulator: MSFS 2020
Navigraph Cycle 2109

Steps to reproduce:
1. Loaded Inmpln file into LNM (added ".TXT" to upload.)
[IFR Hartsfield-Jackson Atlanta Int Airport (KATL) to Lovell (KCHA).lnmpln.TXT](https://github.com/albar965/littlenavmap/files/7231416/IFR.Hartsfield-Jackson.Atlanta.Int.Airport.KATL.to.Lovell.KCHA.lnmpln.TXT)
2. Loaded pln file into MSFS 2020 on World Map page.
[IFR Hartsfield-Jackson Atlanta Int Airport (KATL) to Lovell (KCHA).pln.TXT](https://github.com/albar965/littlenavmap/files/7231419/IFR.Hartsfield-Jackson.Atlanta.Int.Airport.KATL.to.Lovell.KCHA.pln.TXT)
3. Flew the plan in MSFS 2020.
4. The following elevation profile is the result though the map shows the plane at the correct airport.
![Snag_1ee86df8](https://user-images.githubusercontent.com/2886615/134809165-e151a02e-335c-4fde-aa98-d946a9450b93.png)

LNM Logfile:
[abarthel-little_navmap.log](https://github.com/albar965/littlenavmap/files/7231410/abarthel-little_navmap.log)

**Comment by albar965** [comment]
Most likely fixed with 797f0502300ade5120f3c358074d50418563ec30.
