### ISSUE TITLE
MapPaintWidget::showRect* methods clamp map distance value

### ISSUE THREAD

**Issue by KOKAProduktion** [albar965/littlenavmap#784]
Hiho @albar965,

may i ask for a bit of your time?

I have an issue with the `MapPaintWidget` output for tiled image retrieval. The following lines reset the map distance value to the user options value if below.

https://github.com/albar965/littlenavmap/blob/da29c5e69c85c92d144cc71f5dde7a5c2d49f00c/src/mapgui/mappaintwidget.cpp#L786-L789

This prevents me to request smaller `Rect`s (having less distance than the options default value: 1,5 nm) and therefore to zoom in to closer tiles.

Commenting out the lines solves my issue.

Do you have a suggestion or preference on how i should handle that?

- **A:** Clone the required `MapPaintWidget::showRectStreamlined` method without the distance reset
- **B:** Extend the existing method params by a flag for applying the reset

Since this is core code, i just wanted to double check that with you.

Thanks for your thoughts and cheers!

**Comment by albar965** [comment]
You're free to change this since the `showRectStreamlined` is used by the `WebMapController` only.
You can add a parameter to the call which instructs the method to use min zoom or not.
But I'd rather remove the `getMapZoomShowMenu` call and minimum zoom since this is a GUI specific thing.

**Comment by KOKAProduktion** [comment]
So you think it's safe to just remove these lines? That would be the easiest solution. I have to admit that i didn't research further what they are for and i wouldn't want to break @u-an-i 's map retrieval...

Thanks!

**Comment by albar965** [comment]
You can add a boolean for adhering to min zoom and set a default value to true. This will not break anything.
But just remove it. It is really a GUI thing set in the options dialog. Blame me if something blows up. :grin:

**Comment by KOKAProduktion** [comment]
Aight! :) Thx!
