### ISSUE TITLE
Option to disable automatic selection of active leg

### ISSUE THREAD

**Issue by JanCraymer** [albar965/littlenavmap#785]
Hello,

first of all, thanks for this great application. I really appreciate the effort you have put into this!

Now there is something I'm missing (or I did not find the right option for this yet). Imagine flying in an older plane which does not have any kind of GPS map and so on. Maybe just basic VOR navigation and you would have to fly VFR. I'm using LNM to plan the flight and have the map open on a second screen to look out for references I could use VFR. I can disable the visibility of my plane on the map and also the track but I did not find an option to disable the automatic selection of the active leg. So it's not possible to fly really 'blind'. Maybe this can be added?

I know I could just disconnect from the simulator but it would be nice to look after the flight how far off course I went, fuel usage and so on.

Thank you :)

**Comment by albar965** [comment]
Active leg selection cannot be disabled internally. Too much like the progress window content depends on it.

I could add an option to omit the highlighted magenta segment in the flight plan table and on the map. Also omit the grayed out passed segments on the map and elevation profile.

Would that help?

**Comment by JanCraymer** [comment]
Yes, I think that would be sufficient.

**Comment by albar965** [comment]
Progress window and distance to destination in elevation profile would still be updated. But these can be closed or ignored.
