### ISSUE TITLE
MSFS_LNM close without message (SU6 Beta)

### ISSUE THREAD

**Issue by charliebravoAT** [albar965/littlenavmap#799]
Hi guys,

I just want to update the "Szeneriebibliothek" since I had some new addons and also the new SU6 Beta Update.
Suddenly LNM closed without an error. So I tried it again, same result.

So I thought, okay, it must be a problem with one of the new mods.
So just cleaned up the Community folder (so that it was empty), started LNM again, but same thing.

I just made it to get a screenshot in the moment of closing:
![LNM Error](https://user-images.githubusercontent.com/59689726/137287596-dab689ae-53b5-432a-b62c-395ed34260dd.png)

Also the 2 log files:
[abarthel-little_navmap.zip](https://github.com/albar965/littlenavmap/files/7344708/abarthel-little_navmap.zip)

I don't know if it is sth with Win 11 or with the new MSFS Beta, but I think its the new Beta. Also tried to delete LNM, download the latest Version and start it again, no difference at all.

Would be cool, if you could have a look at it, since I'm not able to update my database anymore.

Cheers,
CB

Specs:
Windwos 11 Pro 21H2
MSFS SU6 Beta

**Comment by charliebravoAT** [comment]
Hi @albar965 ,

just sent you a BGL.
Thanks for investigating it.

Cheers,
CB

**Comment by albar965** [comment]
@charliebravoAT Please try this version if it still crashes:
https://www.magentacloud.de/lnk/J1rgAYzP

Changelog is updated. This version contains a few more fixes than the one for MSFS SU6.

**Comment by charliebravoAT** [comment]
> 
> 
> @charliebravoAT Please try this version if it still crashes: https://www.magentacloud.de/lnk/J1rgAYzP
> 
> Changelog is updated. This version contains a few more fixes than the one for MSFS SU6. Feel free to pass this test version over to others.

It works @albar965 , thank you so much :D

**Comment by albar965** [comment]
*sigh* Big relief. You should also see aprons since these moved into a new record type.

Und vielen allerherzlichsten Dank für den Hinweis und den Test!

**Comment by albar965** [comment]
Closing. Let me know if there are any issues left. Will release 2.6.17 tomorrow or Tuesday.
