### ISSUE TITLE
Missing airways. Unable to add waypoints with colocated VOR/NDB.

### ISSUE THREAD

**Issue by tobylorenz** [albar965/littlenavmap#807]
Hello,

I found a video on how to fly the 737 in X-Plane 11 from EDDG to EDDH. Now I try to resemble the flight plan in Little Navmap and have issues to assign the airways. The route is EDDG OSN9E OSN M170 BASUM Z78 WSN T903 RIBSO RIBS4A EDDH.

I'm using X-Plane 11 under Linux. The Navdate in Little NavMap is hence X-Plane 11 AIRAC cycle 1802 and Navigraph AIRAC cycle 1801. Both have matching entries for the intended flightplan.

I observed the following: OSN is available as waypoint and as VOR. Same with WSN, which is available as waypoint and as NDB.
![image](https://user-images.githubusercontent.com/855960/139207211-e3f3edbc-77f8-44bb-a905-8348cf409033.png)

The waypoints have linked airway information...
![image](https://user-images.githubusercontent.com/855960/139207706-de26d095-e338-48d2-a7c1-6247e0955bd0.png)

... while the VOR/NDB is missing linked airway information:
![image](https://user-images.githubusercontent.com/855960/139207800-9794193a-3b7e-442f-93e2-b6abc2a3b2c8.png)

Now independent whether I choose to add the waypoint or the VOR/NDB to the flightplan, the flightplan will only have the VOR/NDB in the end. And as this is not linked to airways, the flightplan doesn't show any airways.
![image](https://user-images.githubusercontent.com/855960/139207357-9ce92a27-f19f-42e1-aed8-b590749dcd1d.png)

I'm not sure what proper fix would be:

- Navdata might just be incomplete as it doesn't have airway information for VOR/NDB.
- LittleNavmap should allow me to add waypoints, even if a VOR/NDB is colocated.
- LittleNavmap could merge airway information for VOR/NDB and colocated waypoints.

This might be related to #710.

I hope the issue became clear. I can add further information or test proposals if needed ;-)

Apart from this, I pretty enjoy the tool, especially as it works with the Navdata I have available in my sim, while all online flight planners usually work with the latest AIRAC cycles, which I cannot enter in my FMS.

Bye Tobias

**Comment by albar965** [comment]
> Is this the reason, why I cannot add the waypoints, because they are artificial?

Not really because they are artificial but because I change all waypoints back to VOR/NDB after plan calculation.
I can have a look to avoid the conversion when adding these manually but  #357 is probably the better solution.

BTW: You can also select a range of flight plan legs and then [calculate between these](https://www.littlenavmap.org/manuals/littlenavmap/release/2.6/en/ROUTECALC.html#calculate-for-selection-in-flight-plan-table). This way you also get the airways. Maybe this helps a bit.

Alex

**Comment by albar965** [comment]
Sorry, not worth the effort IMO. This would touch too many internal structures.
