### ISSUE TITLE
Import route as simple text

### ISSUE THREAD

**Issue by scls19fr** [albar965/littlenavmap#812]
Hello,

it will be nice if a flight plan could be defined simply by copy pasting simple text of route (given simply waypoint names)

For example
https://www.ivao.fr/fr/tours/vfr21_lfee
LFLH LFGI LFGI LFSU LFEU LFGR LFSN LFSE LFGA LFSH

https://skyvector.com/?fpl=LFLH%20LFGI%20LFGI%20LFSU%20LFEU%20LFGR%20LFSN%20LFSE%20LFGA%20LFSH

Kind regards

**Comment by albar965** [comment]
What about https://www.littlenavmap.org/manuals/littlenavmap/release/2.6/en/ROUTEDESCR.html :slightly_smiling_face: 
![grafik](https://user-images.githubusercontent.com/15254956/140740062-d85c763e-0297-4446-b277-9c9b4e6b3d11.png)

**Comment by scls19fr** [comment]
Sorry for noise!
I wasn't aware such feature ever existed but pasting

    LFLH LFGI LFGI LFSU LFEU LFGR LFSN LFSE LFGA LFSH

results in the following flight plan

![image](https://user-images.githubusercontent.com/109167/140743526-14f1e8fc-55ac-420c-ae98-739baba211ec.png)

![image](https://user-images.githubusercontent.com/109167/140744007-3d173473-3129-436a-93ce-7e5913fc0143.png)

instead of

![image](https://user-images.githubusercontent.com/109167/140743838-a5315a96-1f33-4808-8e35-7929985db1e6.png)

![image](https://user-images.githubusercontent.com/109167/140743874-22aaee2f-d64a-4067-a584-cff1fb9b0a1d.png)

LNM should provide a way to turn the first flight plan to the second one which is quite difficult (changing destination AD but also removing "alternative".

**Comment by albar965** [comment]
[See manual again](https://www.littlenavmap.org/manuals/littlenavmap/release/2.6/en/ROUTEDESCR.html#alternates). :wink: 
Uncheck `Read trailing Airports as Alternates` in the drop down menu button and all airports will be read as intermediate waypoints.

**Comment by scls19fr** [comment]
Great! Sorry @albar965 
Thanks for your kind help!

**Comment by albar965** [comment]
No prob. LNM is complex enough to run into all kind of traps.
