### ISSUE TITLE
Support for NAT, PACOTS and AUSOTS tracks

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#82]
Display tracks on the map and allow to use them for routing.

North Atlantic Tracks (NAT) and Pacific Organised Tracks (PACOTS)
change every day according to wx etc. but would be nice if you
could see the day's NAT/PACOTs within LNM

Using the following services now:
```
curl  "https://notams.aim.faa.gov/nat.html" > NATS.html
curl --data "queryType=pacificTracks&actionType=advancedNOTAMFunctions" https://www.notams.faa.gov/dinsQueryWeb/advancedNotamMapAction.do >PACOTS.html
curl  "https://www.airservicesaustralia.com/flextracks/text.asp?ver=1" > AUSOTS.html
```

**Comment by www2000** [comment]
Hi i wand to see to add also AUSOTS tracks:
https://www.airservicesaustralia.com/ausots/ausotstoday.asp
There is a JSON api for NAT and PACOT tracks:
https://flightplandatabase.com/dev/api

**Comment by albar965** [comment]
Thank you for the links. Very helpful. I'm not sure when I can find time to add this feature because it is quite some effort. Download, display, routing and more have to be changed.
Alex

**Comment by Gulliver54** [comment]
👌

**Comment by albar965** [comment]
![grafik](https://user-images.githubusercontent.com/15254956/80581321-86874f80-89fc-11ea-96dd-e02f9dcef7bf.png)
