### ISSUE TITLE
Little Navmap displays airports than cannot be selected in MSFS (do not exist)

### ISSUE THREAD

**Issue by piero-la-lune** [albar965/littlenavmap#820]
I have noticed a very strange behavior (that may be a MSFS bug, not a Little Navmap bug?)
* MSFS 1.21.13.0
* Little Navmap 2.6.17

After importing MSFS data, Little Navmap displays a few imported airports that actually cannot be selected in MSFS.

For instance, PS88 is correctly displayed with all its info (runway length, etc.) in Little Navmap:

![image](https://user-images.githubusercontent.com/614507/143699033-236e40c6-5b8a-495e-b9c8-fb090926b575.png)

But is not not possible to select it as a departing (or arrival) airport in MSFS:

![image](https://user-images.githubusercontent.com/614507/143701804-9fd3e150-41b3-497a-a637-a22765e32a5b.png)

I found the same issue with at least another airport (T38), but there might be more.

Any idea what is happening?

**Comment by albar965** [comment]
Maybe you cannot select seaplane bases in MSFS? Both airport have only water runways.

**Comment by piero-la-lune** [comment]
I can, the airport just above (0PN1) can be selected.

**Comment by piero-la-lune** [comment]
I have been digging a bit more. I could only find another airport (WN19) with the same issue, also a seaplane base. In the end, all of the seaplane bases work totally fine except these three: WN19, PS88 and T38 (there might be others).

I do not understand why these airports cannot be used even though there are referenced in the MSFS data files. Something tells me it is rather a MSFS issue, but anyway I wanted to let you know

**Comment by albar965** [comment]
Strange that it happens only with a few. The airports have valid water runways as shown by LNM and are stored in stock APX files (not some add-on). I'd say this is rather a MSFS issue since LNM cannot "think out" airports. The only reason I can think of could be a closed airport indicator that is not recognized by LNM.

**Comment by albar965** [comment]
Will check for 2.8.

**Comment by BuffyGC** [comment]
I think this affects all airports that are marked as "Closed" in the AirportRecord, but the Runway SubRecs are not, regardless if water or not. Another example: LANO

**Comment by albar965** [comment]
Most likely a MSFS issue. LANO is valid, no seaplane base and has no closed markings for either runway or airport.
Feel free to reopen if you think this is a LNM problem.

**Comment by BuffyGC** [comment]
Hi Alex,
As far as I know, the airport is closed in MSFS. It is not selectable as neither Departure nor Destination or FMS.
In scripted missions there is no landing detection available. SimConnect doesn't report any "OnAirport" or "OnRunway".
I've checked APX53170.bgl where LANO is defined and for LANO in the AirportRecord at offset 0x36 bit 2 is set.

I've created a small mod where only "closed" is set to "False" and afterwards, the Airport is visible in MSFS, SimConnect and usable in scripted missions.
Please keep in mind, MSFS has also 0x04 as closed flag, not 0x40 only.

Technical info (Sim Version 1.24.5.0):
fs-base\scenery\0602\APX53170.bgl
RecordFileOffset	0x000000000004997c (301436)	long
Flag-Position	0x00000000000499b2 (301490)	long
flags 	0x04 (4)	byte

Have a nice Sunday,
BuffyGC

**Comment by albar965** [comment]
Already checking bit 2:
https://github.com/albar965/atools/blob/b5dd408dbd21018326a699436244a1c3a4a6fa24/src/fs/bgl/ap/airport.cpp#L101-L110

**Comment by BuffyGC** [comment]
Don't know how you create that link, but it is great. Tried it, too, but didn't work for me.

I guess it is around line 672ff in the same file.
Airport is closed, but the runways are not marked at closed maybe. (line 679)

**Comment by albar965** [comment]
> Don't know how you create that link, but it is great. Tried it, too, but didn't work for me.

In Github? Click on the line number on the left and then extend the selection with Shift+Click. Then three-dot-menu at the start of the selection.

> I guess it is around line 672ff in the same file.
> Airport is closed, but the runways are not marked at closed maybe. (line 679)

Good catch. I missed this one while debugging. This was introduced with albar965/atools@c99d3e61b27113fe64c2cfb930d641b8228ccdaa. Example for this change was KODX which is closed but has open runways. 

Disabling [677-679](https://github.com/albar965/atools/blob/b5dd408dbd21018326a699436244a1c3a4a6fa24/src/fs/bgl/ap/airport.cpp#L677-L679) marks LANO as well as KODX now as closed. 

I guess this is better now.

Alex
