### ISSUE TITLE
Hi, after win reinstall I have denied voice com access REGDB_E_CLASSNOTREG

### ISSUE THREAD

**Issue by robbintheedge** [albar965/littlenavmap#821]
[16:46:47] xPilot Version 1.3.38
[16:46:47] Error starting voice server client: Retrieving the COM class factory for component with CLSID {F447B69E-1884-4A7E-8055-346F74D6EDB3} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).

I think I've screwed it by copying and pasting xplane and user folders after win10 reinstall and I'm having this issue. Xpilot logs in good. I see other TCAS and models inside the sim, com1 and 2 tune accordingly with vhf selected frecs, but when selecting audio source (have multi screens) have this error. The rest of the xplane environment looks fine. I have a 2nd copy of xplane inside user folder (basic, zero add ons) and the installer reported failure to install certain files. So I think I have a access to folder restriction. If you have an idea of which service is buzzing, I'll re install it. If not, will have to wipe all out and reinstall win10 again. Let me know. Thanks in advance.

**Comment by albar965** [comment]
I think you got the wrong project. :slightly_smiling_face:  Your issue looks more related to [xpilot-project](https://github.com/xpilot-project).
Alex
