### ISSUE TITLE
Add the ability to view aircraft elevation profile independently from fligh plan

### ISSUE THREAD

**Issue by olfMombach** [albar965/littlenavmap#822]
Hi Alex, thanks for the excellent application!

I wanted to suggest adding the ability to view the elevation profile of the aircraft trail alone, independent from any flight plan. Currently you can only view the actual aircraft elevation data relative to an existing flight plan, but I often fly VFR where I don't follow the flight plan, so the elevation profile is very skewed, but I still want to see my elevation profile.

Thanks

**Comment by albar965** [comment]
At best I could display a profile based on the flown distance since I don't know your destination. This would show only the trail of the past. Not sure if this is really helpful without ground display ahead and all. 

Why not use a simple "plan" just connecting departure and destination. Do a few `Ctrl+Alt+Click`s for intermediate points to build your path. Do not even save it, just fly along.

**Comment by olfMombach** [comment]
Yes, using the distance flown as the x-axis would be exactly what I meant, because I primarily just look at the route after I've flown it, it's more of a recap/replay/history than live monitoring. I have also tried to retroactively create a flight plan following the aircraft trail after I've flown it, but it seems to also get distorted because I start at a parking position but the flight plan starts in the middle of the airport, which creates a length disparity that translates in "backwards" movement in the end of the flight:

![image](https://user-images.githubusercontent.com/28447061/144688196-49ce8ed7-4599-4555-9760-d97c1befba98.png)
![image](https://user-images.githubusercontent.com/28447061/144688202-8ff84634-0364-4d08-919f-64d31404e9dd.png)
![image](https://user-images.githubusercontent.com/28447061/144688205-a79584e9-7a1a-4b0b-926c-e4738c3f1ec8.png)
![image](https://user-images.githubusercontent.com/28447061/144688207-7f6bc528-9680-4950-b383-79c95639f3a3.png)

**Comment by albar965** [comment]
The length disparity happens only if you divert heavily from the plan. It can also happen in some cases for procedures but I've not seem such big issues like in the screenshots while flying. Looks like you landed at a different airport. The small difference airport/runway cannot cause this.

I might revisit this but this will not happen soon. For now the projection depends on the flight plan.

**Comment by albar965** [comment]
Sorry, thinking about this again and is too much effort for a small effect. Simply create a flight plan to workaround this or do not use the elevation profile.

**Comment by olfMombach** [comment]
> Sorry, thinking about this again and is too much effort for a small effect. Simply create a flight plan to workaround this or do not use the elevation profile.

My created flight plan didn't really deviate that much. 

How about maybe just an option to "dump all recorded flight data" (or I think it's called simulator aircraft trail in the program) so that I can then write my own script to parse and visualize the height profile? Or is there maybe already an option for that?

**Comment by GitPuffy** [comment]
That is already possible.  See ticket #863 .  From your logbook entry the option exists to export your flight data in GPX format.  I used Google Earth (the desktop version in my case) to visualize the track and elevation events.

**Comment by olfMombach** [comment]
Ooh well that is just perfect. I completely missed this functionality somehow while searching related terms.

**Comment by albar965** [comment]
You can really quickly build a plan and also modify it while flying. `Ctrl+Alt+Click` into the map at any place. Also good for VFR and no need to save the plan.

I'm sorry but I have to prioritize. It's all a bit too much for one. The program becomes incredibly complicated, and despite careful programming, the tasks can become an enormous effort and lead to a lot of newly introduced errors. I know the critical parts in LNM. :slightly_frowning_face:

**Comment by olfMombach** [comment]
I completely understand your concerns about those things becoming very time consuming, speaking from experience too. No worries, the GPX export is perfect for me, a bit of beautifulsoup and matplotlib will fetch me the height profile just as well 😉

**Comment by olfMombach** [comment]
Just if anyone finds this issue and wants to plot their own height profile, here's the small script I wrote which you have to supply with the GPX file (Logbook tab -> right click the flight you want to view -> Files -> Save attached GPX trail as...). Very basic and extendable
https://gist.github.com/olfMombach/14ba9b24d408177c6dbffa4f1e44c00c

**Comment by GitPuffy** [comment]
@olfMombach Your script to display flight altitude works great!  Thank you.
