### ISSUE TITLE
Compiled MarbleWidget issue : mingw81 upgrade : blank black map view

### ISSUE THREAD

**Issue by KOKAProduktion** [albar965/littlenavmap#825]
Hey @albar965, hey @u-an-i!

First of all, I want to apologize for the unannounced silence. I didn't want to disappear like that but the last 2 months have been of the "all at once" type. I wasn't able to contribute anything... Sorry!
I hope you guys are doing well?

Sadly I have an issue getting LNM assembled since the `mingw73` -> `mingw81` upgrade. Everything looks and handles as usual but I get a blank black map view and the application crashes **only** briefly after I mouseenter the maps widget area. So I guess something's wrong with my Marble widget build.

Did you have to recompile the Marble widget with `mingw81` or is it still `mingw73` for it? I think I've tried both builds with the same result but I'm not sure if I'm messing something up there.

I've tried to reconstruct the necessary steps from our first building discussion (https://github.com/albar965/littlenavmap/discussions/688). So maybe I'm outdated?

Can you think of anything else introduced by the `mingw73` -> `mingw81` upgrade I need to take care of? Or am I "on the wooden path" to this one? :)

Thank you for your time and thoughts!
Have a nice weekend. Cheers!

**Comment by u-an-i** [comment]
Hi @KOKAProduktion ,

I have been silent as well. I built a new PC system and haven't installed Qt etc yet. 2 pull requests of mine are still to be merged, I guess @albar965 waits for the release of the next major version to be closer.
An upgrade of `mingw` eluded me, the last upgrade of a build tool I was aware of is Qt to 5.15.2.

**Comment by albar965** [comment]
Hi Guys,

no problem with the silence. 
All good here and I'm slowly coding through the huge pile of issues for 2.8. The release is still moons away. 

@KOKAProduktion  I'm using "C:\Qt\5.15.2\mingw81_32" to build Marble and LNM. No problems with this configuration. A black map usually means the the folder `data` with the Marble files is missing. Maybe something went wrong with deploy?

@u-an-i Let me know when I can merge the pull requests and which ones.

Alex

**Comment by u-an-i** [comment]
Hi @albar965 , I mentioned on the PRs which can be merged that they can as a comment. Btw.: the random flight plan generator is not available yet on purpose, right?

**Comment by albar965** [comment]
> Btw.: the random flight plan generator is not available yet on purpose, right?

Not sure if I understand. It's part of the development build. Nothing in there is yet publicly available.

**Comment by u-an-i** [comment]
> It's part of the development build.

this is what i meant, it is not in the public build. ( i just wanted to check)

**Comment by albar965** [comment]
> this is what i meant, it is not in the public build. ( i just wanted to check)

Should be visible in all builds from master.

**Comment by KOKAProduktion** [comment]
Hiho @albar965,

you're the best, thanks! That was it!

> A black map usually means the the folder data with the Marble files is missing

I should've read the startup log output and the project file more carefully :)
https://github.com/albar965/littlenavmap/blob/148bd90aeac6630e634f611fc1f271540c122a0b/littlenavmap.pro#L850

Hiho @u-an-i,
Grats on your new rig! :) Yeah, I think @albar965 updated `mingw` along with Qt here: https://github.com/albar965/littlenavmap/commit/a151430d35f9728983ff9e76730e5d1d1fdd5e45

Glad to be back on board!
Thx and cheers!

**Comment by albar965** [comment]
> you're the best, thanks! That was it!

You're welcome.  :slightly_smiling_face: This is a know issue to me since a few users had this problem already after incomplete installation/extraction.

And welcome back, of course! :+1:
