### ISSUE TITLE
Connect with X-Plane11- but  no plane [solved]

### ISSUE THREAD

**Issue by BogusCurry** [albar965/littlenavmap#827]
Hello ;D
I have a very stupid problem, I see no plane in LittleNavemap. I have connect to X-Plane 11 and the plugin is install, but no plane. That all under Windows10, What make I wrong ?

Cheers 

Bogus

**Comment by albar965** [comment]
Connecting to X-Plane is normally no issue.

1. Check if you can see the Xpconnect plugin in the X-Plane plugin manager. It is correctly installed and loaded if you can see it there.
2. Just to rule out the obvious: You need to have LNM and X-Plane running on the same computer. Then you have to open the LNM connect dialog and select the sim to connect. The aircraft is shown as soon as you "sit in the cockpit".
3. Look at the LNM view menu if `Show aircraft` is checked.
4. Check if you see progress messages in window 'Simulator Aircraft'.

Alex

**Comment by BogusCurry** [comment]
Hallo Alex ;D
Ich hab das Plugin drin und ist auch im manager installiert, der Simulator und LNM ist auf demselben PC. Aber Zeige Flugzeug, also das Icon und auch die Option im Menu war ausgegraut. 
Aber als ich über die Simulator Flugzeug ging, was bei mir Flugzeugverbindung heisst. Da erschien das Flugzeug im X-Plane, keinen Schimmer was da schief gelaufen ist. Aber nun weiss ich ja wo ich nachschaun muss ;D

-------------------------------------------
I have the plugin in and is also installed in the manager, the simulator and LNM is on the same PC. But Show Aircraft, so the icon and also the option in the menu was grayed out. 
But when I went over the simulator aircraft, which for me means aircraft connection. Since the plane appeared in X-Plane, no clue what went wrong. But now I know where I have to look ;D

Danke für deinen Support ;D

Have a nice Day ;D

**Comment by albar965** [comment]
No problem. :upside_down_face:  Glad it's fixed. The icon is normally grayed out if there is no connection to a sim.
Und Frohe Feiertage! :christmas_tree:
