### ISSUE TITLE
Can't remove Traffic Pattern

### ISSUE THREAD

**Issue by MedicoreV8** [albar965/littlenavmap#837]
Hi,

After placing a traffic pattern for different airports (in this case EHVB and EBWE).
I can't remove them by right clicking the airport (as show in the screenshot).
Can't find any other open/closed issues relating this problem.

[https://i.ibb.co/TcCDv94/Cant-Remove-Traffic-Pattern.png](https://i.ibb.co/TcCDv94/Cant-Remove-Traffic-Pattern.png)

* OS: Windows 10 Por 64-bit Version 21H2 OS Build 19044.1415
* LNMP Version: 2.6.17
* AIRAC cycle: 2113

**Comment by albar965** [comment]
From the [manual](https://github.com/albar965/littlenavmap/issues/837):

> Traffic patterns can be removed by either selecting Map -> Remove all Ranges, Measurements and Patterns or by right click on the **hotspot (circle) at the runway threshold**.

Alex

**Comment by albar965** [comment]
I suppose this is fixed. Feel free to reopen if needed.
