### ISSUE TITLE
OSM Tiles show error message while obtaining them from OSM

### ISSUE THREAD

**Issue by Blerg-Blerg** [albar965/littlenavmap#838]
LNM 2.6.17, Win 10 21H2

Started LNM just now centered on airport 2A2 (Holley Mountain), with OpenStreetMap as tile server. Instead of showing the tiles a message is shown on each (uncached?) tile: 

Contact [User:TheDJ]] if you want to maintain OSMdb and/or the wmflabs' OSM tiles server. 

Crosschecked this on openstreetmap.org with all available six layers: all layers work properly. Possibly a deactivated OSM account?

See also here (screenshot snippet). Logfile from today also attached

![OSM error message LNM 2 6 17](https://user-images.githubusercontent.com/85830629/150650925-cce3a485-6286-4c48-ae9a-b770f1dce03b.png)
[abarthel-little_navmap.log](https://github.com/albar965/littlenavmap/files/7919029/abarthel-little_navmap.log)

)

**Comment by albar965** [comment]
Sorry I cannot fix this. Seems OSM is broken. Use another map theme or contact https://www.openstreetmap.org or https://en.wikipedia.org/wiki/User:TheDJ

Alex

**Comment by Blerg-Blerg** [comment]
Ah ok, my assumption was that there is a technical user used by you which was disabled. Thanks for the quick reply! :-)

**Comment by albar965** [comment]
Update: This is related to the hillshading.

Uncheck the button on the toolbar or in menu "View" -> "Show Hillshading"

You can use OpenTopoMap or StamenTerrain map themes which do not require a separate hillshading source since it is included in the map images.

Or use these as and alternative:
https://www.avsim.com/forums/topic/548994-new-maps-for-lnm/

Alex

**Comment by albar965** [comment]
Reopening since this is a real issue. I probably have to remove the hillshading soon because there is no alternative available.

**Comment by albar965** [comment]
Seems that the "DJ" gave up on maintenance of the service since it is something he does "not enjoy". :man_facepalming: :roll_eyes: 

https://phabricator.wikimedia.org/T187601#7642399

**Comment by albar965** [comment]
There is no replacement for this service but I added more maps with #85
