### ISSUE TITLE
Request: Option to label all airports on the map with 4-letter ICAO code

### ISSUE THREAD

**Issue by oMrSmith** [albar965/littlenavmap#845]
Would it be possible to add an option
which will label all airports with the good old 4-letter ICAO code?

This seems like the most important information on the map...

Simbrief, X-Plane, FS2020 and every FMC I know:
All depend on the good old 4-letter ICAO code.

Since a recent update 
you always have to hover over an airport
just to find out the code...

This would be highly appreciated - at least from my point of view!

**Comment by albar965** [comment]
Hi,
this option is not needed. Please reload the scenery library to fix this. ICAO is and was always default for all displays.
Alex

**Comment by oMrSmith** [comment]
Wonderful. Thanks! Now everything is fine again.
