### ISSUE TITLE
OpenStreetMap not working anymore

### ISSUE THREAD

**Issue by christianseiler** [albar965/littlenavmap#849]
When selecting OpenStreetMaps it shows the message: "Contact [[User:TheDJ]] if you want to maintain OSMdb and/or the wmflabs' OSM tiles server.
![OSM_LittleNavmap_issue](https://user-images.githubusercontent.com/89343298/153593653-b3b26a10-6ef7-4fe7-b207-aa4c8a16e425.png)
"

**Comment by albar965** [comment]
See Avsim pinned topic https://www.avsim.com/forums/topic/613903-map-display-issues-with-openstreetmap-and-other-maps/?tab=comments#comment-4709913
or FAQ: https://albar965.github.io/littlenavmap-faq.html#hillshadingissues

You have to disable hillshading in the LNM menu "View" or use another map theme like OpenTopoMap or StamenTerrain to fix this.

Alex
