### ISSUE TITLE
Allow keys in Marble URLs and themes

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#85]
Need to modify the marble widget to allow passing keys in. See attached map theme.

[mapbox.zip](https://github.com/albar965/littlenavmap/files/646045/mapbox.zip)

**Comment by albar965** [comment]
Now needed even more due to #838

**Comment by albar965** [comment]
![grafik](https://user-images.githubusercontent.com/15254956/151385970-0e9eb797-3589-4e0f-a744-cf5da90c7062.png)
![grafik](https://user-images.githubusercontent.com/15254956/151386315-ea3fefbd-21ea-4633-b4bd-6d4c28a4711c.png)

**Comment by albar965** [comment]
> It's doesn't work.

What does not work?

**Comment by albar965** [comment]
The attached Mapbox theme is irrelevant. A whole bunch of supported themes requiring a login are already included plus an example file.

**Comment by h0wardch3ng** [comment]
@albar965 https://github.com/h0wardch3ng/map-extensions-for-little-navmap

I have collected some of the available map extensions for little navmap,
If you are also interested, you can submit the extension about mapbox.

**Comment by albar965** [comment]
> I have collected some of the available map extensions for little navmap, If you are also interested, you can submit the extension about mapbox.

Thanks for the offer.

I've already included MapBox, Thunderforest and Maptiler themes in the [current alpha 2.7.7](https://www.avsim.com/forums/topic/614851-little-navmap-alphadevelopment-277-released/). Have a look at these.
Note that there is a crash in LNM when using these with spherical map projection. This is already fixed for the next alpha release.

There is also a documented [example.dgml](https://github.com/albar965/littlenavmap/tree/master/marble/data/maps/earth/example) included.

Feel free to post new themes, create a pull request or send them to me by email.

Alex
