### ISSUE TITLE
MSFS and LNM Remote function

### ISSUE THREAD

**Issue by pacha35** [albar965/littlenavmap#850]
Hi,
in the past, (old release) it was possible to connect LNM remote on a PC thru internet. 
With the last release (2.6.17 for LNM and Littleconnect) it's OK on local network but it's impossible to use this function by internet (I have mapped port 8965 with external IP).
The distant PC has LNM 2.6.17 too.
Is it a bug ou I have something more to do ?
Regards?
Pacha35

**Comment by albar965** [comment]
Network code did not change in any of the 2.6 branches. Default port used is 51968, BTW. 
Anti-virus on Windows blocking? Port all the same on Navmap, Navconnect and the forward?
