### ISSUE TITLE
Development public build of LittleNavMap crashes at application closing

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [albar965/littlenavmap#853]
LittleNavMap development public branch (2.7.7) crashes at application closing, reproduceable multiply times.
Release 2.6.17 - works fine.
I tested with completely clean database, without any simulators installed - currently I can't install it for test, but I could try later today. Anyway 2.6 is works fine, 2.7.7 - does not.

OS: `Windows 7 64 bit`.
Flight simulator and version like: `None` - issue is reproduceable on develop public build with clean databases
* AIRAC cycle and navdata source: `Navigraph Cycle 1801 (bundled with LNM)`.
* Log and crashdump files:
[logs and crashdump.zip](https://github.com/albar965/littlenavmap/files/8066475/logs.and.crashdump.zip)

**Comment by albar965** [comment]
Thanks for the report. See here in the thread for solutions: https://www.avsim.com/forums/topic/614851-little-navmap-alphadevelopment-277-released/

There are currently two workarounds to avoid the crashes:
1. Start the Webserver in Tools to avoid the crash after loading the scenery library.
1. LNM crashes when using MapTiler or MapBox maps with Spherical map projection. Select Mercator if you'd like to use MapTiler or MapBox map themes.

Sorry for the mess. I'll release an update the next days. The problems are already fixed internally.

Alex

**Comment by gandalfthewhite19890404** [comment]
Hi! Here are some results.

Start the Webserver in Tools to avoid the crash after loading the scenery library. - Yes, it is fixes an issue.
LNM crashes when using MapTiler or MapBox maps with Spherical map projection. Select Mercator if you'd like to use MapTiler or MapBox map themes. - I'm already using Mercator with OpenStreetMap, so workaround is not applicable.
