### ISSUE TITLE
Feature Request: Improve Refresh rate for Online Network

### ISSUE THREAD

**Issue by earthjasonlin** [albar965/littlenavmap#858]
In the most recent release of LNM, the minimum of the refresh rate for online traffic network is 10s a time, but sometimes, as a controller of an online network, the Euroscope software crashes or just doesn't work sometimes because of code: 10061, so we need to use it as our controller's client, why not allowing more frequent refresh rate such as 1s or even less!
Thanks a lot.

**Comment by albar965** [comment]
10 seconds? Do you use an old version? 

Two seconds is currently the minimum in 2.6.17 when using a custom whazzup.txt server. I can change it to allow one second but not less. LNM will skip downloads when using a slow server.
