### ISSUE TITLE
Feature Request: Portable Mode

### ISSUE THREAD

**Issue by earthjasonlin** [albar965/littlenavmap#859]
please give a way to let the program run in portable mode(, for example, create a folder called "portable" in the executable directory, ) , this means the program automatically stores all the configuration files, caches, and the navigation database in the portable folder.
Thanks

**Comment by albar965** [comment]
Makes sense. But cannot add this to the next 2.8. Scheduling for 3.0.

**Comment by earthjasonlin** [comment]
Thanks a lot

**Comment by albar965** [comment]
Fixed with #431. Use a command line parameter which uses a relative path for the settings folder like:
`littlenavmap --settings-path "settings"`. This uses a folder `settings` in the installation path for configuration files and databases.
