### ISSUE TITLE
Measurement Tool - not great circle?

### ISSUE THREAD

**Issue by PaulWalkerUK** [albar965/littlenavmap#860]
I've noticed when using the measurement tool, it almost always gives the bearing as two numbers, eg 257&deg;M &rarr; 259&deg;M. I understand this is the bearing at the start and end of a great circle route between the points. If I'm wanting to use this tool to measure radials from a VOR, I don't think I really want great circle. I've seen something in previous manual versions that seem to indicate we could measure either "great circle" or "rhumb" - it sounds like "rhumb" is more what I'm looking for, but can't seem to see that in LNM. Has this been removed? How should I use this tool for VOR radials, or is there a better way?

**Comment by albar965** [comment]
I removed Rhumb line navigation a long time ago since it's not relevant for aviation.

**Comment by PaulWalkerUK** [comment]
That's fair enough. What's the best way to plot a radial from a VOR?

**Comment by albar965** [comment]
You can right click on a VOR and LNM will start the measurement line (including label) from the navaid. The VOR magnetic declination/calibration which can differ from the declination from surrounding is then used to calculate magnetic course.
Radial is then opposite to the displayed course.

I can add an option for the next version to show the radial too for NDB, VOR and VORTAC.

**Comment by PaulWalkerUK** [comment]
I don't suppose it's a big issue - a couple of degrees here or there over relatively short distances. It just feels a bit odd when you use the measurement tool because you want to see the bearing to somewhere and it gives you "257°M → 259°M", it prompts the question "well which is it?"! (although I understand now these are the starting/ending bearings of the great circle route).

I like the idea of being able to plot specific radials (or even being able to see the _actual_ (rhumb) bearing anywhere), but it's entirely up to you - if you think it isn't necessary then please feel free to close this ticket.

**Comment by albar965** [comment]
> I don't suppose it's a big issue - a couple of degrees here or there over relatively short distances. It just feels a bit odd when you use the measurement tool because you want to see the bearing to somewhere and it gives you "257°M → 259°M", it prompts the question "well which is it?"! (although I understand now these are the starting/ending bearings of the great circle route).
> 
> I like the idea of being able to plot specific radials (or even being able to see the _actual_ (rhumb) bearing anywhere), but it's entirely up to you - if you think it isn't necessary then please feel free to close this ticket.

"Which is it?" The start course at the navaid. And you have to follow the GC line using start and end course to travel along the radial.

I think the best solution is to add an optional thin line parallel to the GC line which shows the constant course track to a VOR, VORDME, VORTAC or NDB. Also add the radial as a label to the line. Will see.

**Comment by Gulliver54** [comment]
I endorse the idea to show the oppositie direction on the radial too if the radial starts from a NDB or VOR.  The inbound course.

**Comment by albar965** [comment]
> I endorse the idea to show the oppositie direction on the radial too if the radial starts from a NDB or VOR. The inbound course.

This is the plan for the next 2.7 alpha.

**Comment by albar965** [comment]
![image](https://user-images.githubusercontent.com/15254956/157079587-85bc186e-dabd-4298-8b3e-427012fa6dda.png)

**Comment by PaulWalkerUK** [comment]
Looks good 👍 
I'm just wondering though... isn't you're screenshot showing the _R090_ radial? I understand that it depends on whether you're going to/coming from as to whether your _heading_ is 090 or 270, but that _radial_ is R090 isn't it?

**Comment by albar965** [comment]
Meh. Stupid me. Should be 090. Right.

**Comment by Gulliver54** [comment]
Radial 090 is ok as it should be because measurements always protrude outbound from VOR.
Reverse radial 270 is inbound. Hope you find a nice spot for the reverse Radial.

**Comment by albar965** [comment]
**First:** R270 is wrong and R090 is right (sort of, see below) for the screenshot above. Radial is radial and has nothing to do with flying direction inbound or outbound.

**Second:** Forget the rhumb line. Really.
The radial extends along a great circle line. I might seem strange that a radio wave changes its course but it makes sense if you look at the geometrical construction of the great circle line.

Following the rhumb line you would deviate from the radial and the CDI would show this deviation on the HSI.

The radial is the start course of the line: 83°M for above shot. To follow the radial you set your CDI on 263° and start flying 278° and arrive at the VOR 263°.

Accuracy goes down for large distances anyway. Not much use beyond 200 NM.

Hope this makes sense.

**Comment by PaulWalkerUK** [comment]
I'm not certain I entirely understand your second point, but that's just a limitation of my knowledge. I'm of course happy for you to do whatever you think best. Thank you for all your work on this great application 🙂

**Comment by Gulliver54** [comment]
As far as I know, a rhumb line is only usable if you fly a along a parallel, for instance the equator or the tropic .. But if you cross a parallel you need the great circle.
