### ISSUE TITLE
multi whazzup.txt or status.txt support

### ISSUE THREAD

**Issue by earthjasonlin** [albar965/littlenavmap#862]
Wish can support fetching 2 or more whazzup.txt or status.txt at the same time and display the aircraft icon in different color.

**Comment by albar965** [comment]
Sorry, but very unlikely to happen due to the big effort. Maintaining the normal online flying stuff with all the different formats, airspaces and issues is already a challenge.

**Comment by earthjasonlin** [comment]
why is it?


---- 回复的原邮件 ----
发件人 Alexander ***@***.***>日期 2022年02月27日 22:20 收件人 ***@***.***>抄送至 ***@***.******@***.***>主题 Re: [albar965/littlenavmap] multi whazzup.txt or status.txt support (Issue #862)
Sorry, but very unlikely to happen due to the big effort. Maintaining the normal online flying stuff with all the different formats, airspaces and issues is already a challenge.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by albar965** [comment]
Will not happen. Reason above.
