### ISSUE TITLE
Request to save aircraft trail with flight plan

### ISSUE THREAD

**Issue by GitPuffy** [albar965/littlenavmap#863]
I found issue #131 (https://github.com/albar965/littlenavmap/issues/131) which references the aircraft trail and flight plans.  I was hoping it would have answered my question directly which is, **is it possible to save a flight plan which includes the aircraft trail after flying the route in the simulator?**

If Little Navmap cannot do this now is this a reasonable and feasible request to add?

Thank you.

**Comment by albar965** [comment]
First: Thank you very much for your donation! You're my first Github sponsor. :1st_place_medal: 

**About trails:** A user aircraft trail is permanently recorded for all flights. This also spans across restarts and relocating the aircraft between flights until you delete it manually. This trail can be saved in menu `File` -> `Export flight plan to other formats` -> `Export flight plan as GPX`. The GPX contains a route element which is a simplified flight plan and the trail with coordinates, flight altitude and a timestamp. The GPX can be imported and viewed in GoogleEarth or other programs.

Another trail is recorded and saved in the logbook and attached to each logbook entry which can also be saved as GPX. Right click on logbook entry and `Files` -> `Saved attached GPX trail as`. 

There is no possibility in LNM to save the trail with the plan (but doable) and you cannot load and view trails except by attaching them to logbook entries.

Let me know if this helps.

Alex

**Comment by GitPuffy** [comment]
> First: Thank you very much for your donation! You're my first Github sponsor. 🥇

You are welcome.  This is a tremendous application and I am enjoying using it.  You will probably be bought out at some time in the future and hopefully making a donation now will stretch out the time before this becomes a commercial app.

> **About trails:** A user aircraft trail is permanently recorded for all flights. This also spans across restarts and relocating the aircraft between flights until you delete it manually. 

I cleared the flight trail before I created this issue/request, it seems I'll need to fly another planned flight this weekend and experiment with the trail.

>This trail can be saved in menu `File` -> `Export flight plan to other formats` -> `Export flight plan as GPX`. The GPX contains a route element which is a simplified flight plan and the trail with coordinates, flight altitude and a timestamp. The GPX can be imported and viewed in GoogleEarth or other programs.

I look forward to trying that out.
 
> Another trail is recorded and saved in the logbook and attached to each logbook entry which can also be saved as GPX. Right click on logbook entry and `Files` -> `Saved attached GPX trail as`.

Interestingly I don't see the trail from the flight I made in my logbook, maybe it is because I deleted the trail.

> There is no possibility in LNM to save the trail with the plan (but doable) and you cannot load and view trails except by attaching them to logbook entries.

I will experiment more with the two scenarios you mentioned before asking for any changes to your program.

> Let me know if this helps.

Thank you very much

**Comment by albar965** [comment]
> You will probably be bought out at some time in the future and hopefully making a donation now will stretch out the time before this becomes a commercial app.

Certainly not. I am a big advocate of open source software. :slightly_smiling_face: 

> Interestingly I don't see the trail from the flight I made in my logbook, maybe it is because I deleted the trail.

You can see the flown trail as a dark blue dashed line when selecting one (not more) logbook entry in the list. See [here](https://www.littlenavmap.org/manuals/littlenavmap/release/2.6/en/LOGBOOK.html) about all this logbook stuff.

GPX is mentioned [here](https://www.littlenavmap.org/manuals/littlenavmap/release/2.6/en/LOGBOOK.html#logbook-files) for the logbook and [here](https://www.littlenavmap.org/manuals/littlenavmap/release/2.6/en/MENUS.html#export-flight-plan-as-gpx) for the general export.

**Comment by GitPuffy** [comment]
I have experimented with the logbook entries and do see the aircraft trail for one of two flights I made with the Little Navmap following the simulator.  I don't know why one has the trail and the other does not.  

For the flight that does have the trail I was able to export as a GPX format file and import into Google Earth.

Thank you though!

**Comment by albar965** [comment]
> I don't know why one has the trail and the other does not.

Trail for logbook entries is recorded between takeoff and touchdown. I can get lost if you restart LNM in between.

**Comment by GitPuffy** [comment]
I am going to close this issue.  With the logbook recording the flight trail no need to make other changes for this.  Thanks for a great application.

**Comment by albar965** [comment]
You're welcome. Glad it's fixed. :slightly_smiling_face:
