### ISSUE TITLE
Airports in LNM are closed, but available in MSFS

### ISSUE THREAD

**Issue by BuffyGC** [albar965/littlenavmap#876]
Hi Alex, thanks for the great conversion yesterday.

here we go with a similar issue, only counter wise.
i.e. LEWQ is marked as closed in LNM, I think, because all runways are closed. But in the airport record it is not marked as closed. The airport is usable in MSFS.

Reference: #820 

Here a list of Airports I found (open in MSFS airport record, closed in LNM). Keine Gewähr ob dies richtig und vollständig ist:)
00XA, 01NK, 04NV, 07MT, 08GA, 0CA3, 0CN1, 0GE2, 0M1, 0OH8, 0R4, 13ME, 17U, 17Z, 1G6, 1I5, 1NY9, 1S3, 1V6, 1XS7, 20R, 21F, 25A, 2C4, 2I2, 2N5, 2TA6, 2TE8, 2V6, 2WN4, 2XS5, 2Y2, 32WA, 34TS, 38AZ, 38J, 3AZ2, 3C8, 3FD1, 3G1, 3N5, 4AZ7, 4MO1, 4OI8, 4TE0, 51FD, 55S, 57K, 57Y, 58S, 5AK6, 5S2, 63CO, 64TE, 68CL, 6G0, 6PA4, 6TA4, 6W6, 6XA4, 7A3, 7NC2, 80E, 81CA, 8Q0, 9IS2, 9L2, AK19, AK39, AZ05, CA19, CA41, CA53, CDH1, CKM6, CL18, CL84, CML2, CNE2, CNE9, CNS8, CYTJ, EDUS, EGCV, EGDC, EGDT, EGIV, EGOY, EGVL, EGWH, EGXH, EICD, EIIB, ENSM, EPKG, ESCK, ESNF, ETHT, ETIE, ETOR, F50, FADC, FAKG, FANE, FASU, FAVR, FAWE, FAWY, FAYL, FCBB, FD48, FL03, FL34, FMRA, FNWK, FQMB, FVGT, FVHA, GA20, HKKW, HKLX, HKNE, HKNT, HKOY, HKPG, HKPR, HKQD, HKQO, HKSW, HUBK, I06, IBO, ID32, ID86, K32, KAGO, KAIY, KARZ, KBYH, KCAI, KCAW, KCCB, KCHG, KELK, KHAX, KISZ, KMCX, KNII, KNRA, KNUN, KNXX, KPTG, KRBL, KSJS, KWRG, L23, L67, LERL, LEWQ, LF63, LFQE, LFQP, LFYK, LGKM, LIDZ, LIEJ, LIER, LIFX, LIIX, LIMP, LIQU, LIUS, LJCE, LKZA, LLNV, LPPO, LQCG, M52, M88, MBSY, MD96, MDPO, ME16, ME41, MM1P, MM52, MM56, MM60, MM76, MM79, MMAC, MMHI, MMIM, MMLE, MMMC, MMSC, MMTG, MO89, MP25, MRJO, MXOC, MYGW, MYXB, N32, N69, N76, NY37,NY94, NZOX, O07, O20, OAFZ, OG39, OMAJ, OMUQ, OOAD, OOSH, OR07, OR10, OR12, OR17, OR19, OR73, RJ04, RPLM, S98, SA42, SADJ, SANI, SATP, SB3E, SBAV, SBKQ, SBKZ, SBLP, SBNM, SBUP, SBWY, SC42, SC80, SCLE, SCMY, SCPC, SCQI, SCTN, SDTB, SIZG, SJCY, SNJB, SNLO, SNNH, SNPX, SNVD, SSCF, SVQO, SVRB, SWCZ, SWNH, SWPY, SWTC, SWUD, TA34, TE27, TX25, UKKT, UNBI, UT27, VAGD, VOHY, W77, WA68, WA76, WALT, WASU, X46, X64, XS63, YLLE, YMYI, YPAM, ZBER

Viele Grüße.
Thomas

**Comment by BuffyGC** [comment]
Hi Alex,

yes, kind of stupid. And a few versions later you add it again, when Asob thinks, that wasn't so good after all. Maybe a (hidden) option would be good.

I'm checking some from the list right now, and haven't found an exception yet. Do you also still need the list for #820? Then I'll add it there.

Thomas

**Comment by albar965** [comment]
> Do you also still need the list for #820?

Nope. I'll do the change and the some spot checks.

**Comment by albar965** [comment]
The result after change albar965/atools@bf91a9994ad15ae4457978a029d5b51b8e06ca36
KODX and LANO are marked as closed despite having open runways.
LEWQ and others marked open despite having all runways closed.
Hope this makes sense. Did not compare against MSFS behavior yet.
