### ISSUE TITLE
LNM 2.7.8 Develop: Waypoints only fill part of the map

### ISSUE THREAD

**Issue by GitPuffy** [albar965/littlenavmap#877]
Using version `2.7.8 develop` I've run into a problem that I do not know how to solve or really explain.

I was turning on and off features displayed on the map, things like airports, VOR stations, ndb stations, and finally waypoints.  I do not know what order or how this happened but waypoints show up on about the bottom 1/3 of my map regardless of whether I have **Show waypoints** turned on or off.  I can move the map around and the bottom 1/3 waypoints will redraw themselves on the map.  

I have quit out of Little Navmap and restarted it and the problem returned immediately.

Here are two screenshots of the situation.
![Screen Shot 2022-04-05 at 10 21 02 PM](https://user-images.githubusercontent.com/16783602/161895578-f3fb43d0-c07c-48c3-b221-05ef1e31c9df.png)
![Screen Shot 2022-04-05 at 10 20 53 PM](https://user-images.githubusercontent.com/16783602/161895597-b659a067-6dac-46c9-9e66-379671f27904.png)
.

I am not sure if this is a bug in 2.7.8 develop or a user error.  Let me know if there is any other information you'd like from me or for me to try to clear this up.

**Comment by albar965** [comment]
Thanks for reporting. Seems an old issue pops up again. I can reproduce this here and will fix for the next alpha.

**Comment by albar965** [comment]
What's happening here: LNM limits the number of shown objects to avoid freezing. This happens too early here. Normally an indication of this overflow is shown too in the status bar but is missing.
