### ISSUE TITLE
IVAO Weather not working anymore

### ISSUE THREAD

**Issue by dfergusson8** [albar965/littlenavmap#879]
Hello,
METAR information from IVAO is not working anymore.
Seems like https://wx.ivao.aero/metar.php is deprecated and has been disabled.

**Comment by albar965** [comment]
Update to 2.6.18. This fixed it.

Maybe you still have the old IVAO URL in options. Hit the reset button to get the right one.
The new IVAO weather URL is `https://api.ivao.aero/v2/airports/all/metar`.

**Comment by Gulliver54** [comment]
Hi Alex,
If I copy the URL in the available box I receive a Authentication message.  
![afbeelding](https://user-images.githubusercontent.com/33782220/163671345-fc990cce-a2cf-4c5e-b5c4-0df440b005bd.png)

**Comment by albar965** [comment]
> If I copy the URL in the available box I receive a Authentication message and nothing happens. V2.7.8

Very sorry, my mistake. This was fixed in the _not yet released_ 2.7.9.develop.

Alex

**Comment by albar965** [comment]
Fixed with #864.

**Comment by Gulliver54** [comment]
Hi Alex,

Great to have IVAO Metar back in the grid.
But it is sad to see that IVAO for unknown reasons to me, seems to block the ATIS from the online controllers.

![afbeelding](https://user-images.githubusercontent.com/33782220/163720620-6ec0d6dd-dbc8-4d3b-9dec-7082a026791e.png)

**Comment by albar965** [comment]
> But it is sad to see that IVAO for unknown reasons to me, seems to block the ATIS from the online controllers.

Have to check where this is stored now and if this is missing.

**Comment by dfergusson8** [comment]
Thank you @albar965, METAR is now fixed with the latest release and it is working again, update itself seem to have corrected the problem.

**Comment by albar965** [comment]
@dfergusson8 You're welcome and thanks for the feedback. :+1:
