### ISSUE TITLE
Version 2.6.18 failed to run: "missing Qt platform plugin"

### ISSUE THREAD

**Issue by etkArduino** [albar965/littlenavmap#881]
Starting to upgrade LNM to version 2.6.18 on a W11-64 bit PC results in the following error message:
    "This application failed to start because no qt platform plugin could be initialized"

The previous versions (like 2.6.17) did not exibit this error.  Possibly after a Windows update?
The solutions presented on the internet are not clear to me or do not work ...
Looks like this version is dependent on some other platform?

Disregard this Issue:   
I tried to download this version again and now it is running OK.  
Comparing the new download with the faulty one:  there were a lot of missing folders.
Sorry about that.

**Comment by albar965** [comment]
This is most likely an incomplete installation (missing files) or permission issues.
Try to download and extract the Zip again into another folder (not `C:\`,  `C:\Programs` or anything else where you do not have full access).
Another reason might be anti-virus blocking files.

**Comment by etkArduino** [comment]
Thanks for your reply.

I can confirm that a re-download did solve the problem.  Somehow the first
download did not receive all the files and folders, to my surprise.
In the meantime I have updated the description of the issue accordingly.

Regards,

Eric

Op ma 25 apr. 2022 14:33 schreef Alexander Barthel ***@***.***

**Comment by albar965** [comment]
Thanks for the feedback. Glad it's fixed.
