### ISSUE TITLE
Version 2.7.9.develop: Unable to download NOAA weather

### ISSUE THREAD

**Issue by GitPuffy** [albar965/littlenavmap#888]
Using Version 2.7.9.develop (revision 14433e8c) it seems LNM no longer has the ability to retrieve NOAA weather.

The following is the error reported.

`Download of weather from "https://tgftp.nws.noaa.gov/data/observations/metar/cycles/00Z.TXT" failed.
Error: Error transferring https://tgftp.nws.noaa.gov/data/observations/metar/cycles/00Z.TXT - server replied: Forbidden (201)
Check weather settings or disable weather downloads.
Suppressing further messages during this session.
`

Have other users run into this issue?  Transient error related to NOAA or possibly a change to the API such that LNM needs to make adjustments on where to retrieve the dataset from?

**Comment by dachande** [comment]
Just had the exact same problem with the current stable release 2.6.18 about half an hour ago, but it's gone now. Might have been a temporary problem at NOAA. When I try to directly access the URL in a browser you posted in your comment (https://tgftp.nws.noaa.gov/data/observations/metar/cycles/00Z.TXT), I get a correct response from NOAA.

**Comment by albar965** [comment]
Probably NOAA outages. Happens from time to time. Currently I see no problems here (10:50 UTC).

NOAA weather service default URL in LNM is `https://tgftp.nws.noaa.gov/data/observations/metar/cycles/%1Z.TXT`
NOAA wind service base URL is `https://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_1p00.pl`
