### ISSUE TITLE
Feature Request: Show distance of selected waypoints

### ISSUE THREAD

**Issue by racer01** [albar965/littlenavmap#892]
I want to measure parts of a flight plan, and it is painstakingly frustrating to add up every leg's distance to find out the exact distance between eg. the 4. and 14. flight plan waypoint. I'm trying to calculate waypoint timing (with speeds varying), and it would be great if lnm would show the distance (or time) of selected waypoints.

Example (not actual distance, just a number):
![image](https://user-images.githubusercontent.com/14020544/173200412-66c80ee0-fc7a-46c6-953e-30ea09712b04.png)

**Comment by albar965** [comment]
Makes sense and I need this too from time to time.
