### ISSUE TITLE
Wrong LOC/GS position on map for LOWI 08

### ISSUE THREAD

**Issue by unhappytroll** [albar965/littlenavmap#896]
Not sure if it should be here, point me in right direction, if you please.
Windows 10 x64. 
LNM 2.7.10.develop (revision 00c1c2f nine) (somehow editor does not want to have last digit in place)
Flight sim is not a matter, map issue.
AIRAC 2206

https://imgur.com/a/GO6Ihjo
As shown on this picture, LOC/GS overlay for Innsbruck (LOWI) is not exactly as it should be for RWY 08.

**Comment by earthjasonlin** [comment]
this should be the problem from Navdata not LNM

**Comment by albar965** [comment]
The position of the LOC is correct. This is used for LOC-W which references OEJ as a related navaid.
It is used to descent through a cloud cover to 5000 ft and then it's circle-to-land.

**Comment by unhappytroll** [comment]
Ok, my stupidity, checked it with Jeppesen, LOC DME West indeed is out there. Closing the issue.
