### ISSUE TITLE
Crash to desktop when trying to select UI font

### ISSUE THREAD

**Issue by devleaks** [albar965/littlenavmap#898]
Mac OS X 10.14.6
LNM 2.6.19
X-Plane 11.55
AIRAC 18.02

Crash to desktop when selecting Preference...->Display and Text->Select Font...
(I have a lot of fonts on that computer...)

[littlenavmap_2022-07-05-100643_New-iMac.crash.zip](https://github.com/albar965/littlenavmap/files/9044583/littlenavmap_2022-07-05-100643_New-iMac.crash.zip)

Issue does not occur on another Mac (MacOS 12.4), with less fonts.

Thank you

Best regards

**Comment by albar965** [comment]
I cannot reproduce this on normal macOS installations. This crash happens deep in the Qt library when enumerating fonts.
Sorry, cannot be fixed.
