### ISSUE TITLE
Little Xpconnect wrongly reports it is misinstalled

### ISSUE THREAD

**Issue by devleaks** [albar965/littlenavmap#899]
MacOS 12.4
X-Plane 11.55
Little Xpconnect 1.0.27

I receive this error in log.txt
```
(...)
Loaded: /Users/pierre/X-Plane 11/Resources/plugins/Little Xpconnect/mac.xpl (ABarthel.LittleXpconnect.Connect).
(...)
*** Little Xpconnect error: Plugin installed in the wrong path: "/Users/pierre/X-Plane 11"
(...)
```
although Little Xpconnect is installed in `Resources/plugins ` and works like a charm.

Thank you.
Pierre

**Comment by albar965** [comment]
Are you sure there is no other Xpconnect `mac.xpl` in the plugins folder?

**Comment by devleaks** [comment]
Yup. I just double checked, no mac.xpl in plugins folder, no hidden file, none.
Before the error appears, plugin loader process reports that Little Xpconnect is loaded from correct path...
P.

**Comment by devleaks** [comment]
OK. Thanks. Very low priority since plugin is working ok.

**Comment by albar965** [comment]
Fixed. Seems X-Plane returns stone-age colon separated path on macOS.
