### ISSUE TITLE
Set aircraft position

### ISSUE THREAD

**Issue by albar965** [albar965/littlenavmap#90]
Allow user to set simulator aircraft position, heading, altitude and speed.
Additionally allow to jump forward to position at the flight plan.

Useful to repeat approaches or jump long distances.

Also allow to move aircraft to gates on airport.

**Comment by Gulliver54** [comment]
Hi Alex,
Is it also possible to change aircraft position everywhere on the map?
And if so, can you display heading to new position during selection?

Regards 
Gradus

**Comment by albar965** [comment]
Hi Gradus,
sure.Doable. But this depends on #327 which is a lot of work.
Alex

**Comment by Gulliver54** [comment]
Hi Alex,
Does this issue comes with an option "set aircraft position" to starting point "loaded flightplan?  

Regards,
Gradus

**Comment by albar965** [comment]
Can do. Setting to like 10 NM ahead of TOD would be also helpful.
Alex

**Comment by albar965** [comment]
Will not happen. Use either simulator internal maps like in X-Plane or third party tools.
