### ISSUE TITLE
Little Navmap crashes after putting an apostrophe in Airport Ident text box in Search window

### ISSUE THREAD

**Issue by Palemka** [albar965/littlenavmap#901]
**OS version:**
Win 10 64 bit

**Repro steps:**
1. Launch Little Navmap version 2.6.19.
2. Open search window (Alt+1 or Window -> Search).
3. Navigate to airport tab.
4. Write an apostrophe ( ' ) in the 'Ident' text field.

**Observed result:**
Little Navmap crashes after putting an apostrophe in Airport Ident text box in Search window.

**Please note:**
Program does not crash after putting apostrophe in any other field in 'Airports' tab, nor when putting an apostrophe into Navaids/Userpoints 'Indent' field.

![crash](https://user-images.githubusercontent.com/47522828/179368376-5ce531b6-a527-436d-90a6-04475cfcfc18.png)

**Attached Log and Configuration files:**
[log.txt](https://github.com/albar965/littlenavmap/files/9126399/log.txt)
[configuration.txt](https://github.com/albar965/littlenavmap/files/9126400/configuration.txt)

**Comment by albar965** [comment]
Thanks. Good find. I can reproduce this with 2.6.19 and the 2.7.10.develop alpha. The apostrophe seems to mess up the SQL queries in the background.
Will fix.
