### ISSUE TITLE
X-Plane cannot import a plan

### ISSUE THREAD

**Issue by RangerGH** [albar965/littlenavmap#902]
Window 10 64 bit
X-Plane 11.55
AIRAC cycle 2207 from Navigraph 2207.

1. I created a flight plan from CYTH to CYYQ by setting CYTH as the departure, CYYQ as the destination.
2.  Added ILS 33 NUDIX to the flight plan for ILS 33 at CYYQ.
3.  For CYTH I added the SID 06 CYTH3 to the flight plan.

The plan is attached in BAD.fms.  If I load this into an FMS (I tried both the FJS 727 and the Airfoilabs KA 350) I get the error shown in BAD.png.  

If I edit the plan and remove The DRCT 0.000 xxxxxx xxxx lines the plan will load fine.

I've never run into this before and I do my planning in LNM, multiexport and use it in the sims.  For BAD.fms I exported it to X-Plane 11 format.

[FMS plans.zip](https://github.com/albar965/littlenavmap/files/9177457/FMS.plans.zip)

**Comment by albar965** [comment]
Done. 

Again: 

**Do not use any of the  `File` -> `Export options` for X-Plane. These are turned off by default for good reason and make only sense in special cases.**

**Comment by RangerGH** [comment]
Okay.  I will check into these settings.  I believe I left them at default.

I use Multiexport when I export so these settings are not needed for any other sims besides X-Plane then.

Thanks for the prompt response.

**Comment by albar965** [comment]
Switch them off an do not use it for **any** simulator. They are useful for some tools which cannot deal with procedures but rarely.

**Comment by RangerGH** [comment]
Done and it now works.  Thank you.

**Comment by albar965** [comment]
You're welcome. :slightly_smiling_face:
