### ISSUE TITLE
Increase tooltip duration

### ISSUE THREAD

**Issue by killerkalamari** [albar965/littlenavmap#903]
- Version: 2.6.19, Revision: 18757514a095b2f158bf203742c94a8ca2d5676c, Archive: LittleNavmap-linux-18.04-2.6.19.tar.gz
- OS: Debian 11 (Bullseye) amd64
- DE: LXDE/Openbox
- GPU: Intel UHD Graphics 630
- [Attachment: ldd information, in case this is a bug](https://github.com/albar965/littlenavmap/files/9177797/ldd-littlenavmap-debian-11.txt)

When I mouse over waypoints, options, etc, I'll get a tooltip (potentially very helpful!). However, the tooltip only lasts for about 1 second then disappears, which is too fast for me to read what was written. Note: I'm not moving the mouse and it still disappears. At first I thought maybe this was due to the map screen refreshing, but it happens in the options dialog as well.

Would it be possible to keep the tooltip showing indefinitely until I move the mouse pointer somewhere else?

Thanks!

**Comment by albar965** [comment]
This was a bug that appeared only when connected to the simulator and was fixed with 8f5a572dcbad2c2195234320e0999ebbb7a1e3bc.

The fix should appear in the next 2.6.20 and 2.7.11.develop.

Closing the issue now. Feel free to reopen if this still happens with the next release.

Alex
