### ISSUE TITLE
Userpoint - Waypoint - Icon Not Showing on Map

### ISSUE THREAD

**Issue by pixelinkmedia** [albar965/littlenavmap#906]
Windows 10 Home
X-Plane 11.55
Little Navmap 2.6.19

Steps
- Add userpoint Waypoint
- After clicking OK button on dialog
- Yellow circle shows but the waypoint icon doesn't display on map at location where waypoint was created.

Shouldn't there be an icon just like all the other userpoint icons?

![image](https://user-images.githubusercontent.com/51757955/182025388-c28245be-031b-4474-a1e5-e676dd4e1bc3.png)

Thanks

**Comment by albar965** [comment]
The icon is probably still disabled in the drop down menu buttonT. You have to enable a userpoint icon category manually after adding.
![grafik](https://user-images.githubusercontent.com/15254956/182025570-b7722afb-59c3-4102-87f5-6cc902f93fab.png)


Next LNM version and 2.7 alpha already enables display automatically after adding.

**Comment by pixelinkmedia** [comment]
Yeah, it was enabled.
However, after I closed LN and reopened it displayed.

**Comment by albar965** [comment]
Strange. Did you add a new icon which was maybe loaded after restart?

**Comment by albar965** [comment]
I see now. A bug in versions 2.6 which is already fixed in the 2.7 alpha versions. I can reproduce it in 2.6 but not in 2.7.

**Comment by pixelinkmedia** [comment]
OKay. Cool. I will update as soon as it is released. Thanks

**Comment by albar965** [comment]
It's already fixed in 2.7.10.develop which enables the category automatically after adding:
https://www.avsim.com/forums/topic/614851-little-navmap-alphadevelopment-2710-released-update-3/
