### ISSUE TITLE
Compilation fails after atools update

### ISSUE THREAD

**Issue by marcoSchr** [albar965/littlenavmap#909]
After the atools commit https://github.com/albar965/atools/commit/d5d870d19bed3eed572e721d4d4c4c7ad823cb75 littlenavmap fails to compile.

# System information
- Arch Linux
- atools master
- littlenavmap master

# Compiler log

I have only copied the errors, and ignored all warnings.
```
../littlenavmap/src/mapgui/mapthemehandler.cpp: In member function ‘QList<QFileInfo> MapThemeHandler::findMapThemes()’:
../littlenavmap/src/mapgui/mapthemehandler.cpp:480:24: error: no matching function for call to ‘checkDir(const QFileInfo&, bool)’
  480 |     if(atools::checkDir(themeDirInfo, true /* warn */))
      |        ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../littlenavmap/src/mapgui/mapthemehandler.cpp:489:29: error: no matching function for call to ‘checkFile(const QFileInfo&, bool)’
  489 |         if(atools::checkFile(themeFile, true /* warn */))
      |            ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by albar965** [comment]
Dependency changes between atools and LNM. I probably forgot to push one of the repos.
I just pushed some changes of both to master. Should be ok again.
Alex

**Comment by marcoSchr** [comment]
Thanks, this fixed the errors, and littlenavmap compiled successfully.
