### ISSUE TITLE
Airports no longer have information on fuel

### ISSUE THREAD

**Issue by sverzijl** [albar965/littlenavmap#918]
Updated to 2.7.11-develop. It requested to update scenery library and now when I look at airports it no longer tells me what fuel is available.

Attempted to load previous versions, including stable 2.6.19, refresh the scenery database and still no mention of fuel.

Opened navmap sqlite database and in table 'airport', column 'has_avgas' and 'has_jet' are all set to 0.

I'm using MSFS2020 (simupdate 10 beta) and Navigraph.

Not sure where the airport fuel available is coming from.

**Comment by albar965** [comment]
Obvously Asobo issue since a few stock airports have fuel like EGAA and KNID. Based on 1.27.18.

Self compiled airport with fuel indicator also shows up ok.

I'd advise to report this to Asobo.

**Comment by tyson-sc** [comment]
I hope I'm not misinterpreting this issue, but Asobo has responded. They are no longer populating some fuel tags in the MSFS BGL files, and they are suggesting the parking fuel data be used.

Source: [https://devsupport.flightsimulator.com/questions/10232/su10-u3-removed-fuel-flags-from-bgl-files.html](url)

**Comment by albar965** [comment]
> I hope I'm not misinterpreting this issue, but Asobo has responded. They are no longer populating some fuel tags in the MSFS BGL files, and they are suggesting the parking fuel data be used.

Plenty of thanks for this hint and the link! This helps a lot. :medal_sports: 

I changed the fuel detection to assign the fuel flags Avgas and Jet A if a fuel pad is available.There is no fuel information on the pad so I only know there is some kind of fuel.

Now there are a lot more fueled airports. :slightly_smiling_face:
