### ISSUE TITLE
Unable to enter password to enable software integration

### ISSUE THREAD

**Issue by Ron1248** [albar965/littlenavmap#921]
![Image 2022-09-05 at 2 27 PM](https://user-images.githubusercontent.com/99447709/188502991-79015af7-6edd-48ce-9850-ad29f408c234.jpg)

**Comment by albar965** [comment]
Don't be confused by the key. This is normal on macOS. 
It does not mean something like "input locked" but that your input is not echoed on the command line.

**Comment by Ron1248** [comment]
Respectfully I am not a moron.  I tried everything possible to enter my password.  It is like trying to enter on a pdf.  You can’t do it.

**Comment by GitPuffy** [comment]
Your password will not display, nothing shows up.  No asterisks, dots, etc..  Enter the password to your Mac, the one that you use to unlock it and then press return / enter.  What does the system say after doing that?

**Comment by Ron1248** [comment]
Here is the issue from my perspective.   The page is loading like a pdf.  In other words it has no linkage.  This could be my problem, although it has never occurred.  My question can you create a workaround for me.?

**Comment by GitPuffy** [comment]
But have you just tried to enter your computer unlock password there?  For me with I see the same thing yet when I type my password and press return the script continues to run.  No password letters, or asterisks, or dots, or anything ever displays as I type my password.  I just do it on faith and then press return and the script continues on.

**Comment by albar965** [comment]
@Ron1248 Try this tool: https://forums.x-plane.org/index.php?/files/file/79828-mac-os-cleanup-quarantine-flags/

**Comment by Ron1248** [comment]
As you can see it cleared all flags with no success.  Here is my perspective…for some reason my computer will not recognize the script.  I have tested everything on my end.  Has no other MacMini user ever asked for help?

**Comment by albar965** [comment]
> As you can see it cleared all flags with no success.

A screenshot? Cannot see anything. Better answer the issue on the Github instead of answering the notification email.

**Comment by albar965** [comment]
Please do not open more issues on the same problem.

**Comment by Ron1248** [comment]
You might have to work a little harder to figure out the problem.  You are a disgrace

**Comment by GitPuffy** [comment]
@Ron1248 Name calling is not the answer here.  A few of us have reached out to help you.  Did you actually try anything I said to try?  

Have you clicked in the terminal window to make it active?
Have you typed in your password that you use to unlock your Mac and press return?  (Yes, we all know nothing is displayed on the screen -- that is how it is for all of us.  Type carefully and press return)
What does the system come back and say after you do that?  Does it give an error or just sit exactly the same?

**Comment by jonaseberle** [comment]
> You might have to work a little harder to figure out the problem. You are a disgrace

@Ron1248 Your behaviour here is extremely disrespectful towards people that are more helpful, more resourceful, more wholesome and smarter than you.
Unfortunately supporting MacOS-users gives me the impression that these special entitled personalities are more common among those.

**Comment by Ron1248** [comment]
Yes I did everything you told me.   Did you listen to me?  I told what the problem was.  Did you try and figure out why your code was not working.  Why do you assume the people you are talking are idiots.

**Comment by GitPuffy** [comment]
Well you did write:

> This has something to do with my Mac OS.
> Grrrrr

A quick look at the main Github page for Little Navmap shows that the project has received:

Stars 878
Watchers 60
Forks 136

My wild guess is there are easily 10 times the amount of "stars" of people using the application without the trouble you are having.  Like you wrote probably something wrong with your macOS installation or customization.

Sorry guy, I chimed in to offer a bit of advice.  You could make an Apple Genius support ticket and go into Apple with your computer and show them what is happening.  They are extremely knowledgeable about their hardware and software.  I am sure sitting at your keyboard they will be able to resolve this issue in 10 minutes or less.

**Comment by Ron1248** [comment]
Thanks that is helpful.  This is something weird.  Appreciate your input

**Comment by albar965** [comment]
Please remain friendly.

> Sorry guy, I chimed in to offer a bit of advice. You could make an Apple Genius support ticket and go into Apple with your computer and show them what is happening. They are extremely knowledgeable about their hardware and software. I am sure sitting at your keyboard they will be able to resolve this issue in 10 minutes or less.

@Ron1248 I think this is the best solution so far. I have no idea what's going on with your computer. The script does work for a lot of people. Otherwise, my mailbox would be stuffed with issues every day.

Here is the exact procedure as described in the manual again:

> You have to remove the quarantine flag from the plugin after downloading and extracting it. Otherwise X-Plane will silently not load the plugin.
> 
> The procedure may be slightly different depending on whether you’re using Big Sur or Catalina.
> 
> * Copy the whole plugin folder Little Xpconnect into the folder plugins in Resources in the X-Plane installation. The complete path should look like .../X-Plane 11/Resources/plugins/Little Xpconnect.
> 
> * Right or Ctrl-Click in the Finder on the included script Prepare Little Xpconnect.command in the folder .../plugins/Little Xpconnect and select Open With and Terminal.
> 
> * You will see a dialog Prepare Little Xpconnect.command cannot be opened because it is from an unidentified developer. Click Ok.
> 
> * Go to System Preferences -> Security and Privacy. You will see a message mentioning the script Prepare Little Xpconnect.command. Click Open Anyway.
> 
> * Next a dialog Are you sure you want to open it? pops up. Click Open.
> 
> The script shows a few explantions and asks for your password which allows it to run a command as an administrator. You can look at the script which is a text file to see what commands are executed.
> 
> The Little Xpconnect installation was successful if you can see it in the X-Plane plugin manager.
> 
> You have to repeat this procedure each time you update Little Xpconnect.

**Comment by Ron1248** [comment]
Thank you all for your help.  I think going to Apple is great.   I am sure it has to do with my computer blocking the script.  I had hoped there was an easy work around.  It is so frustrating because littlenavmap is so cool.  
Thanks again
