### ISSUE TITLE
Custom waypoints don't load in MSFS 2020

### ISSUE THREAD

**Issue by lucasbaraoneves** [albar965/littlenavmap#922]
Hi,

I'm trying to build a custom route using custom waypoints for a REA flying.

All waypoints were created in Little Navmap, saved the flight plan and exported to MSFS 2020.

When loading the saved flight plan in Little Navmap, it loads perfectly, as image bellow:
![image](https://user-images.githubusercontent.com/28148241/188713272-a3f0b190-27a8-4eff-8676-28f10c5802ea.png)
![image](https://user-images.githubusercontent.com/28148241/188713298-7d2e47e4-a5c3-461f-8ce5-b644b9121d34.png)

When loading the exported flight plan in MSFS, the custom waypoints are not loaded and MSFS creates a "crazy" route, as image bellow:

![image](https://user-images.githubusercontent.com/28148241/188713435-90b64e4d-c54c-4173-a786-ca1d2b6bc0bd.png)

In the G1000 system, the flight plan has the waypoints imported, but the route distance is much longer than it should be:
![image](https://user-images.githubusercontent.com/28148241/188713825-3d70954d-3cb0-48a2-8a6a-434a0294308c.png)

It seems like msfs is not recognizing the latitude/longitude registered in the exported flight plan.

My specs:
MSFS 2020 Standard Edition (SU10 Beta);
AMD Ryzen 5 5600x;
16gb RAM;
GPU RTX3060;
SSD 512GB;
Little Navmap version: 2.6.19 (tried with 2.7.11 develop version)

**Comment by albar965** [comment]
This is an MSFS issue when loading flight plans (one of the many). Just checked and the coordinates in the exported PLN file are correct. See attached files (remove `.txt`). You might want to report this to Asobo.

[IFR Araras (SDAA) to Estadual Gastao Madeira (SDUB).pln.txt](https://github.com/albar965/littlenavmap/files/9505115/IFR.Araras.SDAA.to.Estadual.Gastao.Madeira.SDUB.pln.txt)
[IFR Araras (SDAA) to Ubatuba (SDUB) NO COORDS.lnmpln.txt](https://github.com/albar965/littlenavmap/files/9505126/IFR.Araras.SDAA.to.Ubatuba.SDUB.NO.COORDS.lnmpln.txt)
