### ISSUE TITLE
Little Xpconnect support for native arm64 X-Plane 12 on M1 Mac (Apple Silicon)

### ISSUE THREAD

**Issue by ollie** [albar965/littlenavmap#923]
Hello!

X-Plane 12 now runs on M1 Macs (Apple Silicon) natively in arm64, whereas x86_64 X-Plane 11 is run automatically through Rosetta that translates code into arm on-the-fly (ha). Is it possible to create a Xpconnect universal build that can be run in both modes? (Or separate versions?)

The error in the log manifests with: `(mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))`
My system: `macOS Monterey 12.5.1 (chip Apple M1 Pro/Apple Silicon)`

I don't understand this domain so I asked someone knowledgeable and was given this reply, copied verbatim:

> It's ARM code plus Intel code bundled in one file. For developers, the process is explained here: https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary
One critical aspect for X-Plane plugin developers is that all libraries used also need to be provided as universal libraries. That's something that can slow down developers if they rely on many external libs.
>
> The most critical one for X-Plane is the XPLM library provided by Laminar. As we speak only members of the Alpha test program have access to an early build of the XPLM lib. But that should change soon, will become available here https://developer.x-plane.com/sdk/plugin-sdk-downloads/ as SDK 4.0.0.

If you need any more info, happy to help!

**Comment by albar965** [comment]
Working on it but this will take a while

This is plenty of work. Have no M1 mac and cross compiling to arm64 does not work with the currently used Qt 5.15. Need to update to Qt 6 which is not supported by Marble since it uses some modules which are gone in 6.

And thank you for the links.

**Comment by ollie** [comment]
In the mean time I found a workaround: You can still run XP12 via Rosetta (here's how https://www.macworld.com/article/338843/how-to-force-a-native-m1-mac-app-to-run-as-an-intel-app-instead.html) and Xpconnect works fine.

**Comment by albar965** [comment]
Thanks again! This will be helpful for other users too.

**Comment by albar965** [comment]
For devs volunteering to compile this:

There is no need to recompile the whole LNM and Marble for this. The only required projects are atools (only a part of it, the other parts can be excluded) and Xpconnect.
I can help if somebody needs instructions for Xpconnect.
One problem is that this requires Qt 6 but atools and Xpconnect are currently compiled with Qt 5 which might need some changes.

**Comment by albar965** [comment]
Managed to get a Xpconnect as universal binary compiling on BigSur. Tested on Intel macOS X-Plane and seems to work so far.

**Comment by wyperion** [comment]
Tested on MacStudio M1 Max, it's work ! Thank you !!

**Comment by albar965** [comment]
> Tested on MacStudio M1 Max, it's work ! Thank you !!

Thanks a lot! Good to know.

**Comment by karlvr** [comment]
I don't have Rosetta 2 installed on my M1 Max. I cannot open LittleNavmap-macOS-2.8.1.beta as the binary `Little Navmap.app/Contents/MacOS/littlenavmap` is only compiled for x86_64.

**Comment by albar965** [comment]
> I don't have Rosetta 2 installed on my M1 Max. I cannot open LittleNavmap-macOS-2.8.1.beta as the binary `Little Navmap.app/Contents/MacOS/littlenavmap` is only compiled for x86_64.

I'm sorry, but compiling the whole program for M1 would require using a new updated Qt library which is a bit effort.
For now please to use Rosetta to run LNM. The Intel LNM can connect to the M1 XP plugin without issues.

Alex
