### ISSUE TITLE
X-Plane 11 add-on airports ignored during db loading

### ISSUE THREAD

**Issue by Skarafaz** [albar965/littlenavmap#927]
Little Navmap v2.8.0-beta
Windows 10
X-Plane latest version

Hi! Latest beta release is not reading add-on airports inside my Custom Scenery directory; I've tried real directories, simlinks and junctions but only gloabal airports are recognised. Am I missing something? Thanks.

**Comment by albar965** [comment]
Confirmed. Thank you for reporting!
