### ISSUE TITLE
Holding patterns not displayed via web server?

### ISSUE THREAD

**Issue by PaulWalkerUK** [albar965/littlenavmap#934]
Holding patterns don't seem to be displayed via the webserver. I can see other features OK (traffic patterns etc), but any holding patterns I add on LNM never seem to show up on the web page (version 2.6.19)

**Comment by albar965** [comment]
Seems to be fixed in 2.8.0.beta with 9a5d3f60bc99cdc9ecdf2e0a19345d95ff13031f .
I forgot copy the holdings in an internal structure to the web display.

Feel free to reopen if this still appears in 2.8.
