### ISSUE TITLE
Can this be Fixed?

### ISSUE THREAD

**Issue by Gelowims** [albar965/littlenavmap#936]
Hi there, I am using MSFS2020 and all well until i installed the latest beta version. Now when i update the database i get the following report from the program, which i never got on any of the previous versions. Can this be fixed?
Found 15 warnings in 15 scenery entries when loading the scenery database
Some files or scenery directories could not be read properly due to encrypted airport data or other issues.
Scenery Title: OneStore
Encrypted add-on "asobo-airport-eddf-frankfurt" found. Add-on might not show up correctly.
Scenery Title: OneStore
Encrypted add-on "asobo-airport-egll-heathrow" found. Add-on might not show up correctly.
Scenery Title: OneStore
Encrypted add-on "asobo-airport-eham-amsterdam" found. Add-on might not show up correctly.
Scenery Title: OneStore
Encrypted add-on "asobo-airport-fact-cape-town" found. Add-on might not show up correctly.
Scenery Title: OneStore
Encrypted add-on "asobo-airport-heca-cairo" found. Add-on might not show up correctly.
Scenery Title: OneStore
Encrypted add-on "asobo-airport-kden-denver" found. Add-on might not show up correctly.
Scenery Title: OneStore
Encrypted add-on "asobo-airport-kord-chicago-ohare" found. Add-on might not show up correctly.
Scenery Title: OneStore
Encrypted add-on "asobo-airport-ksfo-sanfrancisco" found. Add-on might not show up correctly.
Scenery Title: OneStore
Encrypted add-on "asobo-airport-lemd-adolfo-suarez" found. Add-on might not show up correctly.
Scenery Title: OneStore
Encrypted add-on "asobo-airport-omdb-dubai-intl" found. Add-on might not show up correctly.
Scenery Title: OneStore
Encrypted add-on "flightbeam-kden" found. Add-on might not show up correctly.
Scenery Title: OneStore
Encrypted add-on "fsdreamteam-airport-ksdf-louisville" found. Add-on might not show up correctly.
Scenery Title: OneStore
Encrypted add-on "lvfr-kmsy" found. Add-on might not show up correctly.
Scenery Title: OneStore
Encrypted add-on "msfscenerybuilders-kpie" found. Add-on might not show up correctly.
Scenery Title: OneStore
Encrypted add-on "msfscenerybuilders-ktlh" found. Add-on might not show up correctly.

Where can i look for the log file?. Many thanks for a great program.

Gelomare
Windows 11 Pro
MSFS2020

**Comment by albar965** [comment]
These are just warnings and cannot be fixed.

See FAQ:
https://albar965.github.io/littlenavmap-faq.html#no-airport-msfs

Alex

**Comment by Gelowims** [comment]
Thank You. Will do both of your suggestions. I I love your software and use it often.
  
Gelomare
  

  

  

  
  
  
  
  
>

**Comment by albar965** [comment]
I hope Asobo will provide an interface to read the encrypted airports in the future. Have to see.
Closing for now.

And thank you for the kind words!

Alex
