### ISSUE TITLE
[Feature request] Reduce density of wind barbs for small zoom levels

### ISSUE THREAD

**Issue by jonaseberle** [albar965/littlenavmap#940]
Thank you for LittleNavmap. I find it incredible how you implemented NOAA wind data! I like to see winds always because it gives me a good picture of the weather systems.

I would like to suggest a visual improvement to the wind barbs display:

(v2.8.0-beta)

On small zoom levels, wind barbs can clutter the map (on a world scale it is not usable):
![image](https://user-images.githubusercontent.com/1678001/195048187-4edfa4c1-9dd0-4c78-84ee-754a5759da2e.png)
(Detail Level: Normal)

I would say this is about the maximum useful density:
![image](https://user-images.githubusercontent.com/1678001/195048756-fb33fb5c-8995-492f-8d34-82667d4d7b09.png)

Is it possible to thin them out at smaller zoom levels or generally when they are too close to each other?

Notice that in spherical projection the meridians are getting very close close to the poles:
![image](https://user-images.githubusercontent.com/1678001/195049522-30b77a6f-cea0-434b-9da8-a5d5ef5a30ba.png)
Maybe filtering out unnecessary longitudes could also be done for high/low latitudes?
EDIT: The reason is different, but the effect is the same in Mercator projection.

I might try to do a pull request but I can't promise if I find the time.
EDITEDIT: I guess here would be the right place 
https://github.com/albar965/littlenavmap/blob/02ea17a837bbb5a29a047b7927e4f459dfcaa516/src/mappainter/mappainterwind.cpp#L63-L79

**Comment by albar965** [comment]
Makes sense. Could be done by dropping symbols if the grid cell size is below a certain screen size in pixels.
Will consider this with one of the next updates.

**Comment by jonaseberle** [comment]
Thank you! I just updated to 2.8.7 :)

**Comment by albar965** [comment]
You're welcome. 

Und eine frohe Weihnachten! :gift:

**Comment by jonaseberle** [comment]
Thank you. The same to you! And some relaxing days.
What you have achieved for the community is absolutely amazing!
