### ISSUE TITLE
Loading from MSFS2020 scenery library after SU 10 cause an error

### ISSUE THREAD

**Issue by FR13ndSDP** [albar965/littlenavmap#941]
As "<Content>" entries are no longer used by MSFS starting with Sim Update 10, If I replace my old `Content.xml` file with a file only has `Priority` entry, I got:

"Caught exception

Error reading "C:/Users/USERNAME/AppData/Local/Packages/Microsoft.FlightSimulator_8wekyb3d8bbwe/LocalCache/Content.xml" on line 6 column 13: Premature end of document."

**Comment by albar965** [comment]
Known issue. See FAQ: https://albar965.github.io/littlenavmap-faq.html#msfs-scenery-library-content-xml
You can update to the LNM 2.8.0.beta which is adapted to the new content.xml or simply rename / delete the file.

**Comment by FR13ndSDP** [comment]
Ok thanks a lot
