### ISSUE TITLE
FlightPlan Creation from Simbrief creates a VFR FP

### ISSUE THREAD

**Issue by cowreth** [albar965/littlenavmap#943]
Hiii :)

A small one.
When you follow the path "File > Open FP From Simbrief" and end on clicking the "Create Flight Plan" button, a VFR Flight Plan (as seen in the dropdown) is created. Which is rarely the case if one is using Simbrief ;)

Cheers
K.

(PS : I love the fact you've thought about that "copy link rather than opening in the browser" button for the FP submission _to_ simbrief ;))

**Comment by albar965** [comment]
Shortest bug lifetime ever. :slightly_smiling_face:

**Comment by cowreth** [comment]
Efficiency as its best.

Cheers, mate. Great work, as always.
