### ISSUE TITLE
Stange issue on lattest release first one I have ever had issue with  Cant open app windows 11 asks for store

### ISSUE THREAD

**Issue by davidbuckleyni** [albar965/littlenavmap#945]
Stange issue on lattest release first one I have ever had issue with 

![image](https://user-images.githubusercontent.com/5619229/201117424-9a575f3e-cc49-43b2-a61b-25ef3e7123c3.png)

When I click on the link I made in task bar or the exe I get the above dialog any ideas? I get my release from here

https://github.com/albar965/littlenavmap/releases

**Comment by albar965** [comment]
What file did you double click precisely to start LNM? `littlenavmap.exe.simconnect` maybe?
Or does it happen when you try to connect to MSFS (which version, maybe SU11 beta)?

**Comment by davidbuckleyni** [comment]
No I Downloiad it from here https://github.com/albar965/littlenavmap/releases/tag/v2.6.19 and just the exe am a software developer myself not typical user

**Comment by davidbuckleyni** [comment]
File is C:\Users\david\Downloads\LittleNavmap-win-2.6.19 (4).zip

**Comment by davidbuckleyni** [comment]
https://screenrec.com/share/PYQO203vAW

**Comment by davidbuckleyni** [comment]
Specs

Device name	DavidDesktop
Processor	Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz   3.70 GHz
Installed RAM	32.0 GB (31.9 GB usable)
Device ID	BFC994A6-1ACC-4147-86EB-915D676F53D8
Product ID	00330-81475-98701-AA779
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display


Edition	Windows 11 Pro
Version	22H2
Installed on	‎15/‎10/‎2022
OS build	22623.885
Experience	Windows Feature Experience Pack 1000.22637.1000.0

**Comment by albar965** [comment]
Sorry, no idea what can cause this. Looks all correct what you do in the screenrec. 
Anti-virus, file permission issues other Windows 11 security measures? Only apps from the store allowed to run?

**Comment by u-an-i** [comment]
some ideas:

- did you extract the zip or opened from inside the zipped folder (file) in Explorer?
- did you try clicking "No" and see if it launches?
- did you disable Windows Smart Screen Filter (Windows Defender security against downloaded apps)? I receive a WSSF warning.
- try creating a shortcut to the exe and double click the shortcut
- try associating exe files with Explorer (Warning! This should be the default afair. Many years ago an Archiver application once reassigned exe files (Windows 7 times or so) to nothing and I couldn't launch them anymore, I think I solved it by reassociating them with Explorer or I reinstalled Windows :(

**Comment by u-an-i** [comment]
also https://thegeekpage.com/youll-need-a-new-app-to-open-this-exe-file/

**Comment by u-an-i** [comment]
also try the beta itself next to the last main release you already downloaded.

**Comment by davidbuckleyni** [comment]
Tried both this has only happened since this version been using little nav map for years

**Comment by albar965** [comment]
Last user who had this issue changed a security setting in Windows. Unfortunately I cannot find the solution.
Sometjing like "allow only apps from app store".

**Comment by davidbuckleyni** [comment]
This is already off which is so strange lol

![image](https://user-images.githubusercontent.com/5619229/201491816-2bcfed94-c021-4bad-8b03-26fcb451af9e.png)

@albar965

**Comment by albar965** [comment]
> This is already off which is so strange lol

Thanks for the information. Maybe I can find what's causing this but I'm totally at a loss now. :slightly_frowning_face:

**Comment by davidbuckleyni** [comment]
For me the issue is the exe was marked as blocked @albar965  even though in edge I told it to keep the zip and extract the zip some how the exe was blocked from running ? am not to sure what does that as default @albar965

**Comment by davidbuckleyni** [comment]
Habing done a bit of research it seems that windows apps that our not digitally signed will automatically be locked I hope this helps u its security mesure i guess if u look at digitall singing ur exe should solve issue @albar965

**Comment by davidbuckleyni** [comment]
This seems to only happen in windows 11

**Comment by albar965** [comment]
There is no absolute requirement to run only signed apps on Windows. Otherwise, my mailbox would flow over from complaints from Windows 11 users.

It does work for others. No idea what's wrong in your case, sorry.
