### ISSUE TITLE
I've loaded a plan from LittleNAVMAP to MSFS2020 and it's implemented strangely.

### ISSUE THREAD

**Issue by rockybear67** [albar965/littlenavmap#946]
1. https://albar965.gitbooks.io/little-navmap-user-manual/content/en/APPENDIX.html#troubleshoot
[The website could not enter because it gave a 404 error]

2. OS: Windows 11, Build 22621.819

3. Flight Simulator Version: MSFS2020, Ver. 1.29.28.0

5. Did you attach related files?
    no. I get a 404 error when trying to access a related site. [https://albar965.gitbooks.io/little-navmap-user-manual/content/en/FILES.html]

6. There is no site that works normally. If there is a way to extract the log file, please let me know and I will attach it.

![0031](https://user-images.githubusercontent.com/7418669/201469713-b94fc7de-c235-401f-a53c-111710f5fd56.jpg)

![0029](https://user-images.githubusercontent.com/7418669/201469721-65259a0e-7f8c-47b1-9030-1a8e7866302e.jpg)

**Comment by albar965** [comment]
I abandoned Gitbooks years ago already. Where did you get this link from?

Here is the main page: https://albar965.github.io/index.html
User manual for current stable 2.6; https://www.littlenavmap.org/manuals/littlenavmap/release/2.6/en/
User manual work in progress for the 2.8 betas: https://www.littlenavmap.org/manuals/littlenavmap/release/2.8/en/

Here is information about MSFS flight plan loading issues: https://www.littlenavmap.org/manuals/littlenavmap/release/2.8/en/
Sorry, I cannot fix this. This is a simulator issue.

**Comment by rockybear67** [comment]
> I abandoned Gitbooks years ago already. Where did you get this link from?
> 
> Here is the main page: https://albar965.github.io/index.html User manual for current stable 2.6; https://www.littlenavmap.org/manuals/littlenavmap/release/2.6/en/ User manual work in progress for the 2.8 betas: https://www.littlenavmap.org/manuals/littlenavmap/release/2.8/en/
> 
> Here is information about MSFS flight plan loading issues: https://www.littlenavmap.org/manuals/littlenavmap/release/2.8/en/ Sorry, I cannot fix this. This is a simulator issue.

Before I write here on the Github Issue, you have noted the precautions.  The link you posted is registered there. I read the precautions and wrote on the Issue.
![0035](https://user-images.githubusercontent.com/7418669/201478628-527ef01a-a89b-495e-9fc7-3371aa054b3a.jpg)

**Comment by albar965** [comment]
What file is this in the screenshot? Please post a link.
Probably in an older release.

Anyway, you've seen the notes about flight plan loading issues in MSFS?

**Comment by rockybear67** [comment]
> What file is this in the screenshot? Please post a link. Probably in an older release.
> 
> Anyway, you've seen the notes about flight plan loading issues in MSFS?

This is not a file. These are the settings you set yourself. Please make a new post on your github as New Issue and it will come out like a screenshot.

+When applying the flight
![Honeycam 2022-11-13 00-50-48](https://user-images.githubusercontent.com/7418669/201482503-5bfd2a4b-da45-433e-bb28-ab78f568c140.gif)
 plan prepared by Littlenavmap to MSFS2020, no error message appeared.

**Comment by albar965** [comment]
> This is not a file. These are the settings you set yourself. Please make a new post on your github as New Issue and it will come out like a screenshot.

I don't understand an thing. Please make yourself clear. And don't send screenshots of Github. This does not make sense.

Here is your problem from the FAQ again:

> - **Loading a flight plan containing user defined points (coordinates) results in some positions of the plan placed at the North Pole.** Note this was fixed with a Navigraph update AIRAC Cycle 2209 rev.2.

This is not an LNM issue. I had numerous reports about this and verified coordinates and flight plans over and over. All coming from LNM is correct. Please report this to Asobo.Maybe they will fix it one day.

**Comment by rockybear67** [comment]
> > 이것은 파일이 아닙니다. 사용자가 직접 설정한 설정입니다. github에 New Issue로 새 게시물을 작성하면 스크린샷과 같이 나옵니다.
> 
> 나는 아무것도 이해하지 못한다. 자신을 명확하게하십시오. 그리고 Github의 스크린샷을 보내지 마세요. 이것은 말이 되지 않습니다.
> 
> 다음은 FAQ의 문제입니다.
> 
> > * **사용자 정의 지점(좌표)이 포함된 비행 계획을 로드하면 계획의 일부 위치가 북극에 배치됩니다. **이것은 Navigraph 업데이트 AIRAC Cycle 2209 rev.2로 수정되었습니다.
> 
> 이것은 LNM 문제가 아닙니다. 나는 이것에 대한 수많은 보고를 받았고 계속해서 좌표와 비행 계획을 확인했습니다. LNM에서 오는 모든 것이 정확합니다. 이것을 Asobo에 보고하십시오.아마 그들은 언젠가 그것을 고칠 것입니다.

I also don't understand what you're talking about too... Don't get excited. I'm here to solve problems, not to cause any problems. I didn't know you hate posting pictures on Github and My main language is not English, I didn't understand the question of what file it was. so my comprehension may be lacking.

Anyway, I have confirmed that it is not a problem with the program, so I think the problem has been solved in the end. We will contact ASOBO.

Thank you and Have a good one

**Comment by rockybear67** [comment]
Additionally, you seem to be wondering where I got that link from in the first place. All of these are automatically filled in with descriptions when click New Issue on Github. You set it up yourself and you have to figure it out... It may close this ticket. thank you.

**Comment by albar965** [comment]
> Anyway, I have confirmed that it is not a problem with the program, so I think the problem has been solved in the end. We will contact ASOBO.

Thank you! Reporting helps a lot.
And thanks for the hint with the new ticket template. The issue with the broken link is there.

**Comment by albar965** [comment]
Closing.
