### ISSUE TITLE
MSFS 2020 Sim update 11 broke LNM

### ISSUE THREAD

**Issue by MiGManFSM** [albar965/littlenavmap#948]
As per the title.
I have been told "The localization file is moved to another place, So LNM couldn't find the entry of "AIRPORT_ICAO.Name" in the translation table."

FYI

**Comment by MiGManFSM** [comment]
Thanks, sorry I didn't find the earlier mention of the problem.

**Comment by albar965** [comment]
No problem. See the Avsim forum. There are some discussions going on about the MSFS release and LNM:
https://www.avsim.com/forums/forum/780-little-navmap-little-navconnect-little-logbook-support-forum/
Alex
