### ISSUE TITLE
Possible typo in flight plan export dialog

### ISSUE THREAD

**Issue by ChrisXPP** [albar965/littlenavmap#949]
Hi @albar965 ,

first of all, thank you very much for your continued work on LittleNavmap! The latest beta 2.8.2 works like a charm for me... 👍 

I maybe found a small typo in the flight plan export dialog (at least in the German translation)... there it says "Exportiere Flugplan als X-Plane FMS 11...". I think this should read "Exportiere Flugplan als X-Plane **11/12** FMS..." to make clearer this flight plan format can be used in both simulator platforms (?) - unless LR decides to change the FPL format for XP12.

![typo](https://user-images.githubusercontent.com/74152765/202842922-8f4a56db-d047-43eb-b696-1a1b1577c8db.png)

Greetz,

Christoph

**Comment by albar965** [comment]
It's actually not a type since the format is called FMS 11. It did not change from XP 11 to XP 12.
But I'll rename it anyway since it's confusing. I agree.
