### ISSUE TITLE
2.8.2 doesnt read and display XP12 real weather.

### ISSUE THREAD

**Issue by Marci353** [albar965/littlenavmap#950]
Good day,

2.8.2 doesnt read and display XP12 real weather. Everything have been set correctly.

What do I do wrong?

Thank you

**Comment by albar965** [comment]
Sorry, need more information as indicated in the message which you see when creating the issue.

Do you get an error message?
Or are reports old?
Are reports missing?
Does this affect only METAR or winds aloft?
What OS?

**Comment by Marci353** [comment]
Oh, sorry for the insufficient datas and thanks for the quick reply.

So: Win 10, latest XP12 (setting real weather), LittleXPconnect 1.0.30., Little Navmap 2.8.2.beta, setting weather and wind source as flight simulator.


Absolutely no info under the weather tab in Little Navmap. I attach picture:

![image](https://user-images.githubusercontent.com/102797982/202920895-4479f7a9-f30e-4250-9772-189a1377f856.png)

**Comment by albar965** [comment]
Thank you. Will check.

**Comment by Marci353** [comment]
Thank you.

Here is my real weather folder:

![image](https://user-images.githubusercontent.com/102797982/202921444-1a06fe30-2544-4dd1-8adf-b7807b20b8c7.png)

**Comment by albar965** [comment]
I see the issue. They changed the filename for the METAR files. My last version uses `METAR-2022-9-6-21.00-ZULU.txt`.
The wind files did not change as far as I can see. 
Do the winds aloft work? I.e. can you see wind barbs?

**Comment by Marci353** [comment]
Then that is why even Pilot2ATC cannot read weather data!!!

Yes, the wind barbs are there.

**Comment by albar965** [comment]
Thank you a lot! :+1: 

I'm currently not at my flying computer. That's why I asked. Will fix for the next release.

**Comment by Marci353** [comment]
And when I rename it back to your filename format, LittleNavmap weather works from the sim. So that is the issue for sure!

**Comment by albar965** [comment]
Yup. I'll make the reading procedure more tolerant. Allow `ZULU` or not.

**Comment by Marci353** [comment]
Great! Waiting for it! Thank you!

**Comment by albar965** [comment]
@Marci353 Thank you very much for your donation!

**Comment by Marci353** [comment]
It is my pleasure!

By the way, I saw you added a commit. Does it mean you are ready with the fix?

**Comment by albar965** [comment]
Slowly. :slightly_smiling_face:  Not tested yet.

**Comment by Marci353** [comment]
Dont want to hurry you, but approx. when will you fix it?

**Comment by albar965** [comment]
It's fixed. Just need to test, fix other issues, prepare release and whatnot. 
I'll release when all is working as expected.

A few days probably until next.
