### ISSUE TITLE
Current Performance not working, weather shows "XP 11 weather"

### ISSUE THREAD

**Issue by Jehudale** [albar965/littlenavmap#953]
OS: Windows 10 64bit
LNM: 2.8.2 beta
Sim: X-Plane 12, Plane: Toliss A321

The tab "Current Performance" always shows "Example Performancve Profile - C 172 - XP11" no matter if sim connected or not, no matter if performance is restartet multiple times. BUT the tab "Progress" under "Simulator Aircraft" shows the right aircraft.

The weather tab shows "XP 11 weather" with METAR date (old in this example) even if XP 12 with fresh downloaded weather is connected.

See screenshot.

Cross check with X-Plane 11 and older version of LittleXPCOnnect: Same
![LNM Beta](https://user-images.githubusercontent.com/119054312/203990975-c1f5fd8f-59ff-4d34-8586-840fefa69d2c.jpg)

**Comment by albar965** [comment]
> The tab "Current Performance" always shows "Example Performancve Profile - C 172 - XP11" no matter if sim connected or not, no matter if performance is restartet multiple times. BUT the tab "Progress" under "Simulator Aircraft" shows the right aircraft.

Already fixed for the next version. The example text appeared in several places.

> The weather tab shows "XP 11 weather" with METAR date (old in this example) even if XP 12 with fresh downloaded weather is connected.

This depends on the selection in the menu `Scenery Library`. LNM will access XP11 weather if connected to XP12 but selected XP11 scenery library. I know this is not very intuitive but I have no other solution for now.

LNM has an issue with XP12 weather files which were renamed during the beta phase. Already fixed for the next LNM beta.

**Comment by albar965** [comment]
Reading weather files was fixed with 2.8.4.beta
