### ISSUE TITLE
22-04-2.8.2Beta won't launch in Debian 

### ISSUE THREAD

**Issue by EdmundStoner** [albar965/littlenavmap#954]
Thank you for Littlenavmap, I regularly use it.
But, when I installed the 22-04-2.8.2Beta and it wouldn't run
My OS is Debian GNU/Linux 11 (bullseye) and the kernel is 5.10.0-19-amd64 
Starting it from a terminal :
     5800X:~/Games/X-Plane 11/Little Navmap$ ./littlenavmap
     ./littlenavmap: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./littlenavmap)
     ./littlenavmap: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./littlenavmap)
    ./littlenavmap: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./littlenavmap)
I have all of the latest updates applied to my system

**Comment by albar965** [comment]
Try [Linux (64 bit, based on Ubuntu 20.04) - LittleNavmap-linux-20.04-2.8.2.beta.tar.gz](https://github.com/albar965/littlenavmap/releases/download/v2.8.2.beta/LittleNavmap-linux-20.04-2.8.2.beta.tar.gz).

**Comment by EdmundStoner** [comment]
Thanks worked well
