### ISSUE TITLE
Different QNH in tabs and XP 12

### ISSUE THREAD

**Issue by Jehudale** [albar965/littlenavmap#956]
OS: Windows
Sim: XP 12 B14

Just started Beta 3 to try it out and found different QNH information. NOAA information according to LNM is 2 hours old but fits current information in the internet, so it seems accurate. The airport tab shows a different to the current and the progress tab also shows a different on (that one should match with the sim as it did in the past). 
![NLM Wetter](https://user-images.githubusercontent.com/119054312/204303588-6eb99f07-bcde-4a4e-a893-0dea669fa81d.jpg)

**Comment by albar965** [comment]
X-Plane has some delay compared to NOAA. The delayed weather is an X-Plane 12 issue which is discussed in the x-org forums.

Check out https://albar965.github.io/release/2022/11/28/littlenavmap-beta-284-released.html, BTW

**Comment by Jehudale** [comment]
Danke für die Rückmeldung. Der QNH ist aber immer noch abweichend, auch wenn ich den Flieger länger da stehen lasse und warte.

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows

Von: Alexander ***@***.***>
Gesendet: Montag, 28. November 2022 15:58
An: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Betreff: Re: [albar965/littlenavmap] Different QNH in tabs and XP 12 (Issue #956)


X-Plane has some delay compared to NOAA. The delayed weather is an X-Plane 12 issue which is discussed in the x-org forums.

Check out https://albar965.github.io/release/2022/11/28/littlenavmap-beta-284-released.html<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Falbar965.github.io%2Frelease%2F2022%2F11%2F28%2Flittlenavmap-beta-284-released.html&data=05%7C01%7C%7C16981f7198ff4c02020b08dad150faf5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638052442975361070%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mFJDESLoXD01794jMMnGiYUUjRLaXFaCmvqifMZ8Qso%3D&reserved=0>, BTW

**Comment by Jehudale** [comment]
Ich meine das aktuelle Wetter in dem Progress-Tab. Da wird aktuell (ich lasse das einfach im Hintergrund weiter laufen um zu sehen, was sich ändert) unter Fortschritt ein QNH von 1017/3002 angezeigt, gehe ich auf die Minimap im Sim wird mir 2999 angezeigt. Diese Werte stimmten bisher immer überein, wenn man am Flugplatz stand.

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows

Von: Alexander ***@***.***>
Gesendet: Montag, 28. November 2022 16:23
An: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Betreff: Re: [albar965/littlenavmap] Different QNH in tabs and XP 12 (Issue #956)


Das Datum ist auschlaggebend für die aktualität des METAR:

KELN 281505Z AUTO 00000KT 10SM FEW006 SCT020 M04/M06 A2973 RMK AO2 T10391061

Wenn das nicht übereinstimmt, dann weichen auch die QNH-Werte ab. X-Plane Wetter war schon immer älter als NOAA.

**Comment by albar965** [comment]
> Ich meine das aktuelle Wetter in dem Progress-Tab. Da wird aktuell (ich lasse das einfach im Hintergrund weiter laufen um zu sehen, was sich ändert) unter Fortschritt ein QNH von 1017/3002 angezeigt, gehe ich auf die Minimap im Sim wird mir 2999 angezeigt. Diese Werte stimmten bisher immer überein, wenn man am Flugplatz stand.

Im Tab `Progress` werden die tatsächlichen Werte an der Flugzeugposition angeben. Die werden direkt aus dem Simulator gelesen und von LNM unverarbeitet angezeigt. Da ist kein Fehler drin. Diese Werte sind dann auch vom Simulator zwischen Stationen interpoliert und können vom METAR in der Nähe abweichen. Von den NOAA-Daten sowieso.
