### ISSUE TITLE
Beta 4: Filename for export as fms

### ISSUE THREAD

**Issue by Jehudale** [albar965/littlenavmap#958]
OS: Windows
Version: B4

Wenn now exporting a file plan in fms format the naming convention is "IFR Wien Schwechat (LOWW) to Brussels National (EBBR)" for a flight from LOWW to EBBR, not "LOWW-EBBR.fms" as it has been in the past.

**Comment by albar965** [comment]
The suggested name depends on the settings in [Multiexport Options Dialog](https://www.littlenavmap.org/manuals/littlenavmap/release/2.8/en/ROUTEEXPORTALL.html#multiexport-options-dialog) when using `Export Flight Plan as FMS for X-Plane 11 and 12 ...`  from the file menu. The default pattern is `DEPARTIDENT-DESTIDENT.fms`.
I know this i not very intuitive but I have no other solution for now.

**Comment by Jehudale** [comment]
Damit klappt es, das hatte ich unter XP11 nie geändert .) Wahrscheinlich ist kein Defaultwert dafür vorhanden gewesen.

„I know this i not very intuitive but I have no other solution for now.“ Keine falsche Scham. Ich bin nur nicht drauf gekommen, da nach zu sehen, da dass explizit Mulitexport-Einstellungen heisst. Wahrscheinlich wäre ich bei „Export-Einstellungen“ selber da rein gegangen. Ich finde das alles in allem gut gelöst, also keine falsche Bescheidenheit 😊

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows

Von: Alexander ***@***.***>
Gesendet: Montag, 28. November 2022 16:34
An: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Betreff: Re: [albar965/littlenavmap] Beta 4: Filename for export as fms (Issue #958)


The suggested name depends on the settings in Multiexport Options Dialog<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.littlenavmap.org%2Fmanuals%2Flittlenavmap%2Frelease%2F2.8%2Fen%2FROUTEEXPORTALL.html%23multiexport-options-dialog&data=05%7C01%7C%7C1d269fed66f14f9d3ac708dad15602c2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638052464580468118%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=dttCQgU1HjHEaMeZmahVzE6k1Z23ATkgHLfxqYBNtEY%3D&reserved=0> when using Export Flight Plan as FMS for X-Plane 11 and 12 ... from the file menu. The default pattern is DEPARTIDENT-DESTIDENT.fms.
I know this i not very intuitive but I have no other solution for now.

**Comment by albar965** [comment]
Prima. Eventuell wurde beim Update ein falscher Wert aus älteren Installation gelesen. LNM versucht immer bei einen Update Einstellungen anzupassen, was aber manchmal auch schiefgeht.
Ich mache hier mal zu. :slightly_smiling_face:
