### ISSUE TITLE
2.8.4 doesnt read and display XP12 real weather - again!

### ISSUE THREAD

**Issue by Marci353** [albar965/littlenavmap#960]
Hi Alex,

the issue is there - again.

Could you check it pls?

**Comment by Marci353** [comment]
It is RC2 now what I use. Here you are the log file. Pilot2ATC for example works (reads weather data).
[Log.zip](https://github.com/albar965/littlenavmap/files/10153496/Log.zip)

**Comment by Marci353** [comment]
Wrong log.zip was uploaded sorry! I hope you didnt work with it. Here is the good one:

It is RC2 now what I use. Here you are the log file. Pilot2ATC for example works (reads weather data).

**Comment by Marci353** [comment]
[Log.zip](https://github.com/albar965/littlenavmap/files/10153752/Log.zip)

**Comment by Marci353** [comment]
Did you receive the good log file?

**Comment by albar965** [comment]
I see no issues here with the latest XP. Make sure that you have selected XP12 in the scenery library menu and that the right weather sources are selected in the menu `Weather`.

Also use the latest LNM beta: https://albar965.github.io/release/2022/11/28/littlenavmap-beta-284-released.html

If all fails send me or attach the **LNM log** (not the Log.txt) which you can get from LNM menu `Tools`.

Also describe the issue better: Does it show old weather? Does it fail to update? Or is not weather loaded at all?

**Comment by albar965** [comment]
Sorry, just seen you use 2.8.4 which is the latest.

**Comment by Marci353** [comment]
I see this in my log.txt:

[Little Xpconnect 1.0.31]: Dataref 'sim/weather/temperature_ambient_c' has been replaced. Please use the new name.
[Little Xpconnect 1.0.31]: Dataref 'sim/weather/temperature_le_c' has been replaced. Please use the new name.
[Little Xpconnect 1.0.31]: Dataref 'sim/weather/visibility_reported_m' has been replaced. Please use the new name.
[Little Xpconnect 1.0.31]: Dataref 'sim/weather/rain_percent' has been replaced. Please use the new name.
[2022-12-05T11:59:33.410 INFO] Little Xpconnect: Plugin id 5 installed in path "C:\X-Plane 12 RC2\Resources\plugins\Little Xpconnect\64\win.xpl" ("C:\X-Plane 12 RC2\Resources\plugins\Little Xpconnect\64\win.xpl"), app path "C:/X-Plane 12 RC2/X-Plane.exe"
[2022-12-05T11:59:33.410 INFO] Little Xpconnect: Plugin path "C:/X-Plane 12 RC2/Resources/plugins/Little Xpconnect/64" is ok

XPR 11:59:33 plugin enableFound stats plugin: 3
WARNING: two datarefs in datarefs.txt have the same name: sim/weather/aircraft/wind_direction_degt.  Please remove the duplicate datare from datarefs.txt.

**Comment by Marci353** [comment]
What does it say to you?

**Comment by albar965** [comment]
> [Little Xpconnect 1.0.31]: Dataref 'sim/weather/temperature_ambient_c' has been replaced. Please use the new name.
> [Little Xpconnect 1.0.31]: Dataref 'sim/weather/temperature_le_c' has been replaced. Please use the new name.
> [Little Xpconnect 1.0.31]: Dataref 'sim/weather/visibility_reported_m' has been replaced. Please use the new name.
> [Little Xpconnect 1.0.31]: Dataref 'sim/weather/rain_percent' has been replaced. Please use the new name.

Ahh. I see. I fixed this already for the next update. But LNM should show weather anyway.

**Comment by Marci353** [comment]
![image](https://user-images.githubusercontent.com/102797982/205629797-c3faf8aa-40be-40e2-a742-036dacdbb9e4.png)

**Comment by Marci353** [comment]
I would send you the LNM log if I could find it.

**Comment by Marci353** [comment]
You mean this?

abarthel-little_navmap.log

**Comment by albar965** [comment]
> You mean this?
> 
> abarthel-little_navmap.log

Yes.

**Comment by albar965** [comment]
Open it in a text editor from LNM menu `Tools` -> `Files and Directories`.

**Comment by Marci353** [comment]
[abarthel-little_navmap.zip](https://github.com/albar965/littlenavmap/files/10153870/abarthel-little_navmap.zip)

Here you are.

**Comment by albar965** [comment]
Thanks for the log file.

I see `Base path not valid "C:/X-Plane 12/"` in the log. Did you move your XP installation folder?
Open the load scenery library dialog in LNM and click `Reset Paths`. This is the XP 12 place LNM uses to search for weather information too.

Also check in options on page `Weather Files` if the path to XP 12 weather files is empty.

**Comment by albar965** [comment]
No problem and not a stupid issue for sure. 

Looks like I have to add an error message for this case (moved simulator) since this can always happen. 
LNM should not silently stop reading weather.

Alex

**Comment by Marci353** [comment]
Good idea!

**Comment by Marci353** [comment]
Could you please still delete it?

I am not proud of it, I should have known this.

Thank you for deleting.

**Comment by albar965** [comment]
Will do but again: No problem. LNM really has to show an error message in this case.
