### ISSUE TITLE
Typo in options dialog 

### ISSUE THREAD

**Issue by Emma-Peel** [albar965/littlenavmap#965]
- Little Navmap Version 2.8.7
- Windows 11 22H2
- Navigraph AIRAC Cycle 2212 rev.1
- MSFS Version 1.29.30.0

In the options dialog, tab "Startup and Updates", "Updates" pane, appear two ampersands within the control caption. It seems to be a language independent problem, maybe misconfigured keyboard shortcuts.

![grafik](https://user-images.githubusercontent.com/91339262/209319889-5efdfbc3-0841-4c86-aaaf-cdb32020917f.png)

![grafik](https://user-images.githubusercontent.com/91339262/209320053-b792fc2c-8593-4c7b-ac25-66bf757cd6c1.png)

**Comment by albar965** [comment]
Thanks. There is a connect lost between the label and the drop down selection box. Will fix for the next release.
