### ISSUE TITLE
"Show only Add-on Airports" filter does not work like expected

### ISSUE THREAD

**Issue by Emma-Peel** [albar965/littlenavmap#966]
- Little Navmap Version 2.8.7
- Windows 11 22H2
- Navigraph AIRAC Cycle 2212 rev.1
- P3Dv5 5.3.17

With Little Navmap Version 2.8.7 and the new airport filter toolbar drop down, I experienced the following behaviour:

1. Reset all airport filter: All airports are shown
2. Select the "Add-on" filter: All airports, regardless if they are add-ons or not, are still displayed. (expected: only add-on airports remain visible)
3. Select "Hard surface" filter: Hard surface airports disappear, except those are add-ons.

I think the intendend use case was the ability to filter to add-on only airports independendly from other runway properties like surface or length.

**Comment by albar965** [comment]
The idea of the add-on filter is to really force the display of add-ons bypassing all filters.

See here: https://www.littlenavmap.org/manuals/littlenavmap/release/2.8/en/MENUS.html#add-on-add-on

**Comment by Emma-Peel** [comment]
Thanks for the clarification. I have to admit I used this a lot without being aware of the original intention. 
Well, may be you can take this as a feature suggestion for a future release: In previous LNM versions I used this mainly as a "show me only add-ons" filter by selecting "add-ons" and deselecting the three runway types:
![grafik](https://user-images.githubusercontent.com/91339262/209332165-a0bc2710-5412-4003-97cf-37b3c10895df.png)
This was very convenient to achive with a maximum of 4 clicks since all filters has been next to another in the toolbar. 
With the new drop down menu and the additional filters in 2.8.7 it can affort up to 18 clicks to achive the same result. By the way, at least in my color scheme it is not possible to distinguish selected and unselected filters:

![grafik](https://user-images.githubusercontent.com/91339262/209333494-ea54e99b-63a1-4f48-ac6b-9034ea44ae5d.png)

Maybe setting all desired filters in a pop-up dialog with remains visible until settings are completed would result in a better user experience.

But it is really only a suggestion - the tool overall is great and I'm willing to invest the extra clicks if needed.

**Comment by albar965** [comment]
No need for 18 clicks and pop up dialog. Tear off the menu into a window:

![Tear Off](https://www.littlenavmap.org/manuals/littlenavmap/release/2.8/en/_images/tearoff.jpg)

See here fore more UI stuff https://www.littlenavmap.org/manuals/littlenavmap/release/2.8/en/INTRO.html#tear-off-dropdown-menus

I'll have a look if `None`/`All` buttons make sense in this menu. The color scheme looks strange as well. I see a contrast on Windows here:
![grafik](https://user-images.githubusercontent.com/15254956/209339476-f230cbb9-1222-4f5d-ba0c-4564d32ff4b2.png)

You can try to use another style like Fusion.

**Comment by Emma-Peel** [comment]
Sorry, it seemed I went too fast through the release notes. I just wondered about the dotted line but did not have any clue it is the solution. 

I never carred about styles in LNM so far and have to add that my client was running in "windowsvista" setting. Switching to any of the other styles solves the above display issues. I would like to let you decide if that is worth further investigation, I am fine with using the Fusion style. 

Thanks again for your quick and helpful response.

**Comment by albar965** [comment]
You're welcome. I suppose I can close the issue. 
Wish you Happy Holidays and all the best for the New Year! :christmas_tree:
