### ISSUE TITLE
Linux Mint 20.3 Una error: /littlenavmap: /home/me/bin/Little Navmap/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./littlenavmap)

### ISSUE THREAD

**Issue by 3DSpotters** [albar965/littlenavmap#968]
**Thank your to contributing to _Little Navmap_.**

**Please take a minute and read the instructions below to help me to avoid unnecessary work and additional communication overhead when reporting a bug or requesting new features.**

All issues for _atools_, _Little Navconnect_, _Little Xpconnect_ are collected in this repository since ownership is often not clear.

Note that almost all _Little Navmap_ dialogs allow to copy formatted text. Simply click and drag the mouse in the dialog to mark the text. Use `Ctrl+C` or context menu to copy to the clipboard. Make screenshots only if relevant for the issue like drawing errors.

Please note that this project is released with a [Contributor Code of Conduct][code-of-conduct]. By participating in this project you agree to abide by its terms.

**Please read before writing an issue**

## If you'd like to report an error:

* Try the steps in the [troubleshoot](https://www.littlenavmap.org/manuals/littlenavmap/release/2.6/en/APPENDIX.html#troubleshoot) section of the manual if these solve the problem.
* Check the [list of open issues](https://github.com/albar965/littlenavmap/issues) if you one was already reported. Use the search function.
* Include your OS and version in detail like: `Windows 10 64 bit`, `macOS 10.11` or `Ubuntu Linux 17.10 64 bit`.
* Flight simulator and version like: `Prepar3D v4.1`, `FSX SE`, `X-Plane 11.05` or `X-Plane 11.10.rc2`
* AIRAC cycle and navdata source if applicable: `FSX Stock`, `Navigraph Cycle 1713`, `FSX fsAerodata cycle 1707` or `X-Plane stock data cycle 1611`.
* Attach any related files if copyright and size permits: Flight plan files, FSX/P3D BGL files, or X-Plane apt.dat files. For freeware scenery a link is sufficient.
* Attach the log file and if needed the configuration file. See [here](https://www.littlenavmap.org/manuals/littlenavmap/release/2.6/en/FILES.html) for information about file locations.
* Provide all steps to reproduce the error like: Start program with empty database and load flight plan.

## If you'd like propose a new feature:

* Check the list of issues [here](https://github.com/albar965/littlenavmap/issues) and use the search function to check if
  your proposal is already covered.
* Provide a clear description and attach screenshots, file examples or documentation links that help me to understand and implement the feature.

**Delete this text _after reading_ before posting the issue.**

[code-of-conduct]: https://github.com/albar965/littlenavmap/blob/master/.github/CODE_OF_CONDUCT.md

**Comment by 3DSpotters** [comment]
Hi,

I use: Linux Mint 20.3 Una

With the latest version v2.8.7 of LNM I get error:
...
$  ./littlenavmap
./littlenavmap: /home/me/bin/Little Navmap/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./littlenavmap)
./littlenavmap: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./littlenavmap)
./littlenavmap: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./littlenavmap)

**Comment by albar965** [comment]
> Hi,
> 
> I use: Linux Mint 20.3 Una
> 
> With the latest version v2.8.7 of LNM I get error: ... $ ./littlenavmap ./littlenavmap: /home/me/bin/Little Navmap/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./littlenavmap) ./littlenavmap: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./littlenavmap) ./littlenavmap: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./littlenavmap)

Try the build from Ubuntu 20.04: https://github.com/albar965/littlenavmap/releases/download/v2.8.7/LittleNavmap-linux-20.04-2.8.7.tar.gz

**Comment by jonaseberle** [comment]
@3DSpotters try the binary built with Ubuntu 20.04 from https://github.com/albar965/littlenavmap/releases/tag/v2.8.7

**Comment by 3DSpotters** [comment]
HJi Jonas

"try the binary built with Ubuntu 20.04 from https://github.com/albar965/littlenavmap/releases/tag/v2.8.7"
this is the exact version I try to run ...

**Comment by 3DSpotters** [comment]
The proof 8-) :

$ ... ~/bin/Little Navmap $ cat ./version.txt
2.8.7

**Comment by 3DSpotters** [comment]
In my Linux Mint 20.3 Una (based on Ubuntu 20.04) I have:

$ strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_3.4.26
GLIBCXX_3.4.27
GLIBCXX_3.4.28
GLIBCXX_DEBUG_MESSAGE_LENGTH

**Comment by jonaseberle** [comment]
There are two builds for Linux for version 2.8.7. I suppose you have used the one built with Ubuntu **22**.04. Your older glibc will be more happy with the one built for 20.04.

**Comment by 3DSpotters** [comment]
RIGTH!

My bad...too many "2" :)
This version is working now!
Than you!

**Comment by albar965** [comment]
I suppose this can be closed. :slightly_smiling_face: 

Happy Holidays! :gift:

**Comment by 3DSpotters** [comment]
YSE, do close. Happy Holidays !
