### ISSUE TITLE
macOS: Application is not signed

### ISSUE THREAD

**Issue by p-linnane** [albar965/littlenavmap#969]
Hello. I am a maintainer for [Homebrew](brew.sh). When bumping Little Navmap to the latest version, we noticed the application is not signed.  This causes issues running on Apple silicon, which is almost all Macs released in the last 2 years. I just wanted to see if there was a plan to `codesign` the application moving forward.

**Comment by albar965** [comment]
The application itself still needs Rosetta to run on Apple Silicon architecture. I need to port LNM to Qt 6 before the whole application can be compiled into a universal binary. And I expect plenty of issues and side effects with Qt 6. 

The Xpconnect plugin is a different thing which already supports Arm but is not signed.
I'm not much a friend of code signing and even less for paying for it.

Will see what can be done for a future release.
