### ISSUE TITLE
Use color profile for aircraft trail

### ISSUE THREAD

**Issue by bilkaPek** [albar965/littlenavmap#97]
Add a color elevation profile instead of point for plane

**Comment by albar965** [comment]
Hi Sam,
can you give me more details about this. A screen shot for example.
Send me an e-mail (find it in my profile). It better to communicate than issues. :-)

**Comment by bilkaPek** [comment]
Hello Alexander
I just send you information by email

**Comment by albar965** [comment]
![capture4](https://cloud.githubusercontent.com/assets/15254956/22217387/230a62c6-e1a3-11e6-8050-76fda0eb9d24.PNG)
![capture1](https://cloud.githubusercontent.com/assets/15254956/22217388/230bb7c0-e1a3-11e6-9309-ca49e7a147f6.PNG)
