### ISSUE TITLE
Altitude Issue

### ISSUE THREAD

**Issue by gabocasy** [albar965/littlenavmap#971]
Hello Alex!
After updating, there was a problem:
The simulator aircraft altitude display does not match the MSFS 2020 altitude, e.g.: In the simulator I fly at an altitude of 8000 feet, LittleNavmap shows 7650 feet. All aircraft types have the same problem, 350-1000 feet difference. Navigraph data synchronized, MSFS scenery synchronized... In which setting should I look for the solution?
Thanks for the answer!
Gabor

**Comment by albar965** [comment]
This is probably only a settings issue. See here in this thread if it helps:
https://www.avsim.com/forums/topic/628561-altitude-differs-from-msfs/
