### ISSUE TITLE
LNM crashing

### ISSUE THREAD

**Issue by MvonderTann** [albar965/littlenavmap#973]
### Discussed in https://github.com/albar965/littlenavmap/discussions/972

<div type='discussions-op-text'>

<sup>Originally posted by **MvonderTann** December 29, 2022</sup>
Has anybody encountered this? Approaching Sint Maarten (TNCM), and just before I touch down the program crashes:

![image](https://user-images.githubusercontent.com/86071411/210018836-8a3d8e43-f65f-437f-804c-f4cb096494f8.png)

Wanted to check here first before posting a bug....

Thanks ,and Happy New Year  to everyone :-)</div>

**Comment by albar965** [comment]
Thanks for the report. Will fix for the next update.

The question is: How did you get boats from online traffic? Were you connected to VATSIM or IVAO when it crashed?
Can you send me the log from the crash?

**Comment by MvonderTann** [comment]
[abarthel-little_navmap.log](https://github.com/albar965/littlenavmap/files/10324965/abarthel-little_navmap.log)

I have VATSIM Online Traffic activated. When I tried to replicate it I also noticed that when zoomed out it was fine, but as soon as I zoomed in where the boats became visible (just off the coast of TNCM) LNM crashed. 

Here is the log :-) Thanks for looking into this and trying to get it fixed, and Happy New Year!

**Comment by MvonderTann** [comment]
Perhaps this helps too (renamed from ini to txt so I can upload)

[little_navmap.txt](https://github.com/albar965/littlenavmap/files/10324992/little_navmap.txt)

**Comment by albar965** [comment]
Thank you very much for the files. No idea why LNM thinks out online boats but I'll make it at least more robust.
Wish you all the best for the New Year too!
Alex

**Comment by albar965** [comment]
Should be fixed. Will show a white aircraft with a question mark if an aircraft type is unknown and no icon is available.
