### ISSUE TITLE
littlexpconnect: Messes up colors

### ISSUE THREAD

**Issue by maxhille** [albar965/littlenavmap#983]
The LittleXPConnect seems to mess up the colors in my sim, see attached screenshots. The reddish one is with the Plugin installed, the proper/white-ish one without the plugin. This is 100% reproducible for me.

I get that XP12 support might just be accidental at the moment and it might aswell be a bug in the sim. Since I have done some plugin dev myself already I might take a shot at it if I find the time (no promises).

OS: Ubuntu 22.10
NVIDIA-Driver: 525.78.01 (ppa)
X-Plane: 12.01b1

![CirrusSF50 - 2023-01-10 13 22 49](https://user-images.githubusercontent.com/693447/211551477-46391b3c-ed0f-4003-9daa-aa64f0c2337a.png)
![CirrusSF50 - 2023-01-10 13 24 25](https://user-images.githubusercontent.com/693447/211551483-d5a5d8c8-3905-486d-9edf-61215363e92a.png)

**Comment by albar965** [comment]
Known issue but I have absolutely no idea how to fix this. I already reduced dependencies (shared libraries) to a minimum but it did not help.

What Xpconnect version do you use?

**Comment by albar965** [comment]
> `1.0.33` which came bundled with LNM `22.04-2.8.7`.

Ok. This is the latest.

> Intuition says we modify a dataref somewhere, otherwise we should not be able to modify the sims state at all - unless it is an XP bug of course.

Nope. For sure not. My internal code even does not allow this. I'd rather suspect that XP does not like my internal multithreading (all safe according to LR specs and not accessing datarefs from other threads than main loop).

You can try to disable `Load AI Aircraft Information` or `Fetch AI` in the LNM Xpconnect plugin menu which reduces file accesses.

**Comment by maxhille** [comment]
@albar965 I investigated a bit today. It seems like just creating a QCoreApplication instance leads to this behaviour. I created a very stripped down version of LXP to demonstrate this: https://github.com/maxhille/littlexpconnect . Maybe we can approach LR with this.

Is this a Ubuntu/Linux issue only?
Since which XP version does this happen?

**Comment by albar965** [comment]
Thank your for demo. The issue appears only on Linux and only with X-Plane 12. 

No idea for removing QCoreApplication. This will affect a lot of program parts like logging, signals, threads and whatnot. I'll have a look if I can simplify this more.

**Comment by albar965** [comment]
Have to see if I can run this without QCoreApplication.

**Comment by maxhille** [comment]
QCoreApplication docs make it pretty clear that you cannot have multiple instances in one Process and so it makes sense that stuff breaks this way.

Do you think it makes sense to talk to LR about this? Are you in their 3rd party dev Slack by any chance?

**Comment by albar965** [comment]
> QCoreApplication docs make it pretty clear that you cannot have multiple instances in one Process and so it makes sense that stuff breaks this way.

Then why does this happen with only one plugin installed? Who is the other Qt user then? LR certainly not.
Why does it only happen on Linux?
Why only with XP12 and not with 11?

I'll try to get rid of the application instance but I'm not sure if this is doable. Not using Qt is no option since I have to support multiple OS. Have to see.

**Comment by maxhille** [comment]
> Then why does this happen with only one plugin installed? Who is the other Qt user then? LR certainly not.

Maybe XP uses QT? I don't know.

> Why does it only happen on Linux?
> Why only with XP12 and not with 11?

The behaviour for multiple instances of QCoreApplication is undefined.

**Comment by albar965** [comment]
> Maybe XP uses QT? I don't know.

For sure not. Never seen it mentioned. See no library references.

> The behaviour for multiple instances of QCoreApplication is undefined.

You have a source?

**Comment by maxhille** [comment]
`QCoreApplication::instance();` does return <null>, so I guess we are not competing with another QT instance here.

So for the deeper reason part, I am out of ideas. Maybe @bsupnik can give us a hint?

> I'll try to get rid of the application instance but I'm not sure if this is doable. Not using Qt is no option since I have to support multiple OS. Have to see.

What part of QT does the plugin need?

**Comment by maxhille** [comment]
@albar965 Ok I think I found the culprit.

I found another plugin which uses QT (ExtPlane) and they have this interesting line and comment at https://github.com/vranki/ExtPlane/blob/master/extplane-plugin/xplaneplugin.cpp#L54

Tested and verified that this does the trick. I guess behind the scenes something like "string to float" or similar got messed up by QT changing the process locale.

**Comment by albar965** [comment]
> Tested and verified that this does the trick. I guess behind the scenes something like "string to float" or similar got messed up by QT changing the process locale.

Terrific. :+1: 

That absolutely makes sense. It can mess up number conversion. I also ran into this already.

I'll merge, cherry pick into `release/1.0` and attach the builds here for testing.

Thanks a lot!

Alex

**Comment by albar965** [comment]
This new version 1.0.35 includes your fix:
[Little Xpconnect-22.04-1.0.35.tar.gz](https://github.com/albar965/littlenavmap/files/10572640/Little.Xpconnect-22.04-1.0.35.tar.gz)
Let me know if this is working.

**Comment by maxhille** [comment]
Corfirming your build works.

**Comment by albar965** [comment]
This is the offender:

https://codebrowser.dev/qt5/qtbase/src/corelib/kernel/qcoreapplication.cpp.html#_ZN23QCoreApplicationPrivate10initLocaleEv

**Comment by albar965** [comment]
Hotfix in Avsim forum: https://www.avsim.com/forums/topic/630237-hotfix-for-issues-with-little-xpconnect-x-plane-12-on-linux/

I also attached the modified builds to the 2.8.8 release: https://github.com/albar965/littlenavmap/releases/tag/v2.8.8

Thanks all for the help and big thank you to Max Hille for the fix!
