### ISSUE TITLE
Libraries GLIBCXX_3.4.29, GLIBC_2.32 and GLIBC_2.34 not found when installing in Debian 11

### ISSUE THREAD

**Issue by alexgberm** [albar965/littlenavmap#984]
I am trying to install LittleNavmap-linux 22.04-2.8.7 following the installation instructions in the user manual.
I get the errors:

"/littlenavmap: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./littlenavmap)
./littlenavmap: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./littlenavmap)
./littlenavmap: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./littlenavmap)"

I have tried "sudo apt install libxcb-xinerama0 libxcb-icccm4" as indicated in the user manual faqs for linux start. However, Debian says I have the latest versions of the libraries already installed.

In Ubuntu I have no problems installing this version of LittleNavmap but I would prefer to use the program in Debian.
I would appreciate any help on this issue. Log file attached.

Thanks.

[start_log.txt](https://github.com/albar965/littlenavmap/files/10413109/start_log.txt)

**Comment by albar965** [comment]
Try the other build based on Ubuntu 20.04:
https://github.com/albar965/littlenavmap/releases/download/v2.8.7/LittleNavmap-linux-20.04-2.8.7.tar.gz

Alex

**Comment by alexgberm** [comment]
Thanks for your reply. The version you suggested worked straightaway.
Problem solved.

**Comment by albar965** [comment]
You're welcome. :slightly_smiling_face: 
I suppose the issue can be closed.

**Comment by alexgberm** [comment]
Hi,
Yes. I did not know how to close It.
Thanks very much for your support.
Best regards
Alejandro Gómez
