### ISSUE TITLE
littlenavmap does not run in Debian

### ISSUE THREAD

**Issue by wellthatwaseasy** [albar965/littlenavmap#986]
missing library errors are shown(below) when running in 
Debian 11 (bullseye) 64-bit
Kernel Linux 5.10.0-20-amd64 x86_64
Mate 1.24.1

Output from Terminal:

mike:~/Games/X-Plane 11/Little Navmap$ ./littlenavmap
./littlenavmap: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./littlenavmap)
./littlenavmap: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./littlenavmap)
./littlenavmap: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./littlenavmap)

**Comment by albar965** [comment]
See #984 . You have to use the Ubuntu 20.04 build:
https://github.com/albar965/littlenavmap/releases/download/v2.8.7/LittleNavmap-linux-20.04-2.8.7.tar.gz
