### ISSUE TITLE
additional map sources

### ISSUE THREAD

**Issue by anonymous555** [albar965/littlenavmap#994]
The package of additional map sources is amazing.  Could you please include it by default!!!

https://forum.mistymoorings.com/index.php?topic=4272.msg36956#msg36956

It makes looking at airways much easier seeing low and high, and it's great having the option to overlay the symbology and fonts from traditional sectionals/vfr maps.

Relevant:
https://github.com/albar965/littlenavmap/issues/278

**Comment by albar965** [comment]
Source is https://www.avsim.com/forums/topic/627225-new-maps-for-lnm-updated/

I added only maps to LNM as default which are really free to use and do not cause license issues. Therefore I'd like to keep these out.
But you are free to install and use them.
