### ISSUE TITLE
Double click on airport no longer brings up procedures

### ISSUE THREAD

**Issue by tillbcrazy** [albar965/littlenavmap#996]
Windows 11
Littlenavmap 2.8.8

In the right pane you used to be able to have the procedures tab selected and when you double click on an airport to select it, the procedures for that airport would show. This is no longer working. Now, I have to right click on  an airport and select show procedures.

**Comment by albar965** [comment]
Check this setting. It has to be enabled:
![image](https://user-images.githubusercontent.com/15254956/217797688-fbcecde1-d739-469d-b4f4-70a05ccc66b5.png)

**Comment by tillbcrazy** [comment]
Thank you! Sorry to bother you. I did not know it was a simple setting.

**Comment by albar965** [comment]
No problem. I think this can be closed.

**Comment by tillbcrazy** [comment]
Sure can. Thank you again!
