### ISSUE TITLE
Opentopomap zoomed in display is "blocky"

### ISSUE THREAD

**Issue by Gunpilot399** [albar965/littlenavmap#997]
![LNM prob](https://user-images.githubusercontent.com/125111402/218242310-83e49e74-ab6b-4b42-81e6-685b10151dd7.jpg)
Running latest version 2.8.8 on Windows 11 desktop with 4080 graphics card for MSFS2020.....all map themes are showing detail when I zoom in except for Opentopomap theme.........when I zoom right in on map, some tiles are detailed while others are "blocky/pixelated"...see attached screen shot

**Comment by albar965** [comment]
Also answered in #980 :

> I still have this blocky prob when I zoom in for detail...running 2.8.8 on Windows 11

What does LNM menu -> `Help` -> `About Little Navmap` say about OpenSSL? 

The libraries `libcrypto-1_1-x64.dll` and `libssl-1_1-x64.dll` are included in the download. Are these quarantined by anti-virus or blocked by Windows for any reason?

**Comment by albar965** [comment]
Also check if LNM can access the internet at all.

Futhermore: I cannot fix OpenTopoMap since it is not my service and slow at times. Seems there are currently issues. Use another map theme until they are back.

**Comment by albar965** [comment]
Closing. Feel free to reopen if it appears again.
